### ISSUE TITLE
PeerTube says the browser is incompatible when cookies are disabled

### ISSUE THREAD

**Issue by jish** [Chocobozzz/PeerTube#2808] opened 2020-05-30 10:53 UTC
**What happened?**

I received a message that "We are sorry but it seems that PeerTube is not compatible with your web browser."

<img width="1340" alt="Screen Shot 2020-05-30 at 3 45 31 AM" src="https://user-images.githubusercontent.com/1817/83326354-3af8d900-a228-11ea-8241-da2e68b1bb68.png">

**What do you expect to happen instead?**

To see a PeerTube website

**Steps to reproduce:**

1. Open Firefox

2. Disable cookies

3. Navigate to https://peertube.touhoppai.moe/accounts/shichimi/video-channels

**Additional information**
* PeerTube version or URL: https://peertube.touhoppai.moe/accounts/shichimi/video-channels
* Browser name/version: Firefox 76.0.1 (64-bit)
* NodeJS version:

* Link to browser console log if useful:

```
TypeError: setting getter-only property "sessionStorage"
main-es2015.2b5955fffe6b361be4d8.js:1:1164715
Request to access cookie or storage on “<URL>” was blocked because we are blocking all storage access requests. 2
Request to access cookie or storage on “https://peertube.touhoppai.moe/accounts/shichimi/video-channels” was blocked because we are blocking all storage access requests.

Request to access cookie or storage on “https://peertube.touhoppai.moe/accounts/shichimi/video-channels” was blocked because we are blocking all storage access requests.
```

* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by JohnXLivingston** [comment] 2020-05-30 14:15
This is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/2757 , already fixed.

**Closed** 2020-06-02 14:19 UTC
Labels: Type: Duplicate :loop:
