### ISSUE TITLE
Captcha

### ISSUE THREAD

**Issue by stemy2** [Chocobozzz/PeerTube#1946] opened 2019-06-26 12:35 UTC
Hello,

Many instance maintainers are complaining of the amount of spam content, notably fake copyrighted contents, because there's no captcha system to prevent it. It's surprising that it's not implemented because this is primordial.

**Comment by Zig-03** [comment] 2019-06-26 14:07
What good libre captchas are out there?

**Comment by JohnXLivingston** [comment] 2019-06-27 09:40
Waiting for this feature, you can use this tips to block registration based on countries:
https://framacolibri.org/t/tips-block-registrations-based-on-country-to-avoid-spam/5288

On my instance, most of spam came from Indonesia or Malaysia.

**Comment by Chocobozzz** [comment] 2019-07-01 08:06
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/1721

**Comment by Serkan-devel** [comment] 2019-07-01 13:57
It would be better to have an issue open for captchas that aren't recaptcha

**Comment by JohnXLivingston** [comment] 2019-07-01 17:02
I agree, this is not the same issue as #1721. There are some captcha libraries that don't need third party services.

**Comment by Nutomic** [comment] 2019-07-15 14:26
Here is a thread about this topic with a lot of different options:

https://mastodon.at/@switchingsocial/102445246710877910

**Comment by JohnXLivingston** [comment] 2019-07-15 16:13
> Here is a thread about this topic with a lot of different options:
> 
> https://mastodon.at/@switchingsocial/102445246710877910

I found this interesting link on your thread: https://kevv.net/you-probably-dont-need-recaptcha/

**Comment by rigelk** [comment] 2019-11-25 10:18
> Here is a thread about this topic with a lot of different options:
> 
> [mastodon.at/@switchingsocial/102445246710877910](https://mastodon.at/@switchingsocial/102445246710877910)

The thread being unavailable, I suppose this content is now available at switchingsocial's new site: https://switching.software/ethical-alternatives-to-google-recaptcha/

**Closed** 2019-11-26 18:26 UTC
Labels: Component: PeerTube Plugin :package:, Type: Enhancement :sparkles:

**Comment by DontUseGithub** [comment] 2020-01-17 09:06
FYI https://github.com/produck/svg-captcha - nodejs captcha generator

**Comment by JohnXLivingston** [comment] 2020-01-17 15:35
> FYI https://github.com/produck/svg-captcha - nodejs captcha generator

I'm on it. I will implement this one as a plugin for Peertube 2.1.

**Comment by stemy2** [comment] 2020-05-23 09:42
I'm currently using the hCaptcha plugin. It is marketed as privacy friendly, but i'm not sure if it is right since the privacy policy is barely comprehensive. Furthermore, it's not listed on the [swiso's list](https://switching.software/replace/google-recaptcha/).

**Comment by Findus23** [comment] 2020-05-24 09:37
@stemy2 I am not sure if hCaptcha is in any way more privacy friendly than reCAPTCHA (apart from "it is not Google")

https://github.com/matomo-org/matomo/issues/13905#issuecomment-605627370
