### ISSUE TITLE
Own videos not shown in user channel with various privacy settings

### ISSUE THREAD

**Issue by agru** [Chocobozzz/PeerTube#6778] opened 2024-12-19 22:37 UTC
### Describe the current behavior

If a user, that is logged in, uploads videos, puts them in a channel, and uses one of the privacy settings

- Private,
- Scheduled, or
- Password protected

and then takes a look to the channel, the correct number of videos in the channel are displayed, but videos with one of this privacy settings are hidden. So the user is not able to see completely which videos are in his / her own channel.

### Steps to reproduce

1. Upload a video and place it in a channel
2. Set the privacy setting of the video to "Private", "Scheduled" or "Password protected"
3. Go to the channel where the video is placed. The video is not listed, although it belongs to the user. Channel management is therefore difficult

### Describe the expected behavior

All videos that belong to a user, independent from the video privacy settings, should be displayed to the logged in user while visiting one of the own channels.

### Additional information

* PeerTube instance:
  * URL: https://pt01.lehrerfortbildung-bw.de
  * Version: 7.0.0
  * NodeJS version: v20.18.1
  * Ffmpeg version: 5.1.6
 * Browser name, version and platforms on which you could reproduce the bug: Firefox 133.0.3 on Linux

**Comment by Chocobozzz** [comment] 2024-12-20 06:05
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/5539

**Closed by Chocobozzz** 2024-12-20 06:05 UTC
