### ISSUE TITLE
Add link to video in "Unknown infoHash" error log message

### ISSUE THREAD

**Issue by ilfarpro** [Chocobozzz/PeerTube#6515] opened 2024-07-28 11:06 UTC
### Describe the problem to be solved

Sometimes for some unknown reason I get "Unknown infoHash" warning on some videos. I mean cases when it's not related for browser cache. 

If I reupload videos causing this warning few times It may get correct infoHash. Problem is how to find this videos, because no information given in logs.

```
warn[28.07.2024, 15:09:55] Warning in tracker.
{
  "err": {
    "stack": "Error: Unknown infoHash 58a350c22c5c086d9645d07cf0130e26ff0055c8 requested by ip 178.205.xx.xx\n    at Server.filter [as _filter] (file:///app/dist/core/controllers/tracker.js:50:16)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
    "message": "Unknown infoHash 58a350c22c5c086d9645d07cf0130e26ff0055c8 requested by ip 178.205.xx.xx"
  }
}
``` 

### Describe the solution you would like

Please, let's improve logging, so it will tell in which video page was discovered this issue.

**Comment by Chocobozzz** [comment] 2024-07-31 11:48
Hi,

Unfortunately we don't have the video context in this filter.
The root cause of your issue should be fixed by https://github.com/Chocobozzz/PeerTube/issues/6516
But as a side note, you can also disable the infohash filter by setting `tracker.private: false` in the config: https://github.com/Chocobozzz/PeerTube/blob/develop/config/default.yaml#L366

**Closed by Chocobozzz** 2024-07-31 11:48 UTC
