### ISSUE TITLE
Connection impossible with email

### ISSUE THREAD

**Issue by bristow** [Chocobozzz/PeerTube#1916] opened 2019-06-19 08:11 UTC
**What happened?**

It seems that in version 1.3.1, you can no longer connect with an email with capital letters.
If, as an administrator, I modify this email and put it in lowercase, then we can use this email again to connect.
No problem with the ID of these accounts

**What do you expect to happen instead?**

In a previous version of PT, we could connect with an email with capital letters

**Additional information**
* PeerTube version or URL: 1.3.1
* Browser name/version: Firefox
* NodeJS version: ?

**Comment by NassimBounouas** [comment] 2019-06-19 11:48
Hi,

I have been able to reproduce this bug. I'll investigate to suggest a fix.

**Comment by NassimBounouas** [comment] 2019-06-19 13:38
On the client side, the email is converted to lower case before sending the request [(implemented there)](https://github.com/Chocobozzz/PeerTube/commit/c1521ca3d757bee91f7dfbb15b3717162bf4997d).

On the server side, sequelize-typescript is used as ORM to query the postgresql database. There I need a confirmation (maybe from @Chocobozzz ?). As I understood, the API request is received by [this function](https://github.com/Chocobozzz/PeerTube/blob/develop/server/controllers/api/users/index.ts#L158). And from there, the token generation is handled by oauth2-server [(there)](https://github.com/Chocobozzz/PeerTube/blob/develop/server/middlewares/oauth.ts#L76). The credentials verification is based on the user retrieve [there](https://github.com/Chocobozzz/PeerTube/blob/develop/server/lib/oauth-model.ts#L75).

So I guess that the problem is coming from [this query](https://github.com/Chocobozzz/PeerTube/blob/develop/server/models/account/user.ts#L402), the lowercase email sent by the client is tested against the saved email without converting it to lowercase so the query is case sensitive.

My first suggestion is to modify the sequelize query [like this](https://github.com/NassimBounouas/PeerTube/commit/4f68f648a41464b9fa3221c8b3fa9ec7b67465f2).

I tested it locally and it seems to solve the problem but I'm really not sure. If @rigelk or @Chocobozzz can review my suggestion before I make a PR, It would be kind.

Thank you

**Comment by Chocobozzz** [comment] 2019-06-19 14:02
Unfortunately emails are (in theory) case sensitive. So I think you should revert my commit, and use `iLike` for the username on the server.

**Comment by NassimBounouas** [comment] 2019-06-19 14:29
Yes, you are right according [the RFC 5321](https://tools.ietf.org/html/rfc5321#section-2.3.11) only the domain part should be considered as case insensitive. I'll revert your commit and use the `iLike` operator only on the username.

**Comment by NassimBounouas** [comment] 2019-06-19 14:41
I forgot to reference this issue on the [revert commit](https://github.com/NassimBounouas/PeerTube/commit/9bfd6d7eedd76bf0390332bd96ecd51934c44996). I tested locally this new version and, as expected, now the login is username case insensitive and email sensitive. I'll create a PR and modify it according your feedback.

Thank you

**Comment by NassimBounouas** [comment] 2019-07-02 11:07
This issue has been solved and merged with the PR #1917 . I guess it should be closed.

**Closed** 2019-07-02 16:39 UTC
Labels: Type: Bug :bug:

**Comment by kontrollanten** [comment] 2021-01-25 16:31
> Yes, you are right according the [RFC 5321](https://tools.ietf.org/html/rfc5321#section-2.3.11) only the domain part should be considered as case insensitive. I'll revert your commit and use the `iLike` operator only on the username.

I'd suggest that we make emails case insensitive again. We've a lot of old users and they have the ability to mix upper and lower case when writing their email address. What's the drawback with making it case insensitive? That theoretically there can be two different mailboxes that has Joe@example.com and joe@example.com? StackOverflow and a lot of other big sites has the email case insensitive so maybe it's safe for us too?
