### ISSUE TITLE
Redundant m3u8 files

### ISSUE THREAD

**Issue by double-u-a** [Chocobozzz/PeerTube#5316] opened 2022-10-01 13:16 UTC
### Describe the problem to be solved

If a peertube is mirroring a video, it still has to query the origin peertube node for the m3u8 playlist in order to play. This means when the origin node is down, the redundant node fails.

### Describe the solution you would like

If the redundant node mirrored the m3u8 file as well, it would theoretically be able to operate even if the origin node is temporarily down.

**Comment by Chocobozzz** [comment] 2023-03-08 14:02
Duplicate of https://github.com/Chocobozzz/PeerTube/issues/3431

**Closed by Chocobozzz** 2023-03-08 14:02 UTC
Labels: Type: Feature Request :sparkles:, Component: Redundancy
