### ISSUE TITLE
Add <link> to make RSS feeds auto-discoverable

### ISSUE THREAD

**Issue by kevincox** [Chocobozzz/PeerTube#4585] opened 2021-11-30 13:41 UTC
**Describe the problem to be solved**

PeerTube supports RSS feeds which is fantastic but they are hard to find. You need to click "Subscribe" and know that there will be an RSS link presented or find the RSS link on the channel page. Instead it would be great if the RSS feed could be auto-discovered.

**Describe the solution you would like:**

PeerTube channel pages (and ideally video pages as well) should have a `<link rel="alternate" type="application/atom+xml" title="ExampleChannel" href="https://peertube.example/feeds/videos.atom?videoChannelId=1234" />` element in the HTML. This will allow browsers and browser addons to automatically identify that a feed is available as well as allowing feed-readers to allow subscribing by just pasting the channel/video page rather than forcing the user to find the feed URL themselves.

Alternatively or additionally a  `Link:` header can be used.

**Describe alternatives you have considered**

Stay with the RSS links. This allows custom UX and can surface these feeds for users who don't have user-agent support however it means that automation can not be applied. Most importantly the two options are not mutually exclusive.

**Comment by Chocobozzz** [comment] 2021-12-01 12:54
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/541

**Closed by Chocobozzz** 2021-12-01 12:54 UTC
