### ISSUE TITLE
No reminder to change ownership  

### ISSUE THREAD

**Issue by SenTraveler** [Chocobozzz/PeerTube#4511] opened 2021-11-02 02:23 UTC
When I transferred the video to other people, the recipient did not receive the reminder.

**Comment by Chocobozzz** [comment] 2021-11-02 08:33
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/3639

**Closed by Chocobozzz** 2021-11-02 08:33 UTC
