### ISSUE TITLE
change language button defaults to home page from current page

### ISSUE THREAD

**Issue by test2a** [Chocobozzz/PeerTube#2993] opened 2020-07-21 15:27 UTC
**What happened?**
https://peertube2.cpy.re/videos/watch/9c9de5e8-0a1e-484a-b099-e80766180a6d
I am on this video. I click on change interface language to any language. i am thrown to home page, away from the current page i was on. Now i have to click back or search for the video to reach it
**What do you expect to happen instead?**
interface language should refresh the page and should stay on the current page
**Steps to reproduce:**

1. open https://peertube2.cpy.re/videos/watch/9c9de5e8-0a1e-484a-b099-e80766180a6d

2. click on change interface

3. select any language

4. you are thrown to https://peertube2.cpy.re/es-ES instead of the above link

**Additional information**
* PeerTube version or URL: peertube2.cpy.re
* Browser name/version: firefox 78.0.2 (64-bit) ubuntu
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment] 2020-07-22 06:53
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/1466

**Closed by Chocobozzz** 2020-07-22 06:53 UTC
