### ISSUE TITLE
Unable to download my own private video while logged in

### ISSUE THREAD

**Issue by Vertux** [Chocobozzz/PeerTube#2261] opened 2019-11-17 12:03 UTC
**What happened?**
If I try to download a video, which is labeled as "private" and "download allowed" (Herunterladen erlauben) is checked,

![Bildschirmfoto 2019-11-17 um 12 58 20](https://user-images.githubusercontent.com/10457918/69007136-2dd66580-093a-11ea-9203-f1ac2ec3240f.png)

 while I am logged in as user (owner of the file) the following error pops up in the browser:

![Bildschirmfoto 2019-11-17 um 12 49 07](https://user-images.githubusercontent.com/10457918/69007099-8eb16e00-0939-11ea-9cd2-b246de4ebfe9.png)

**What do you expect to happen instead?**
I expected, that the download would start.

**Steps to reproduce:**

1. Upload a video as "private" and "download allowed" checked.

2. Login and try to download the video.

**Additional information**
* PeerTube version or URL: v2.0
* Browser name/version: Firefox 70.0.1 MacOS

**Comment by Chocobozzz** [comment] 2019-11-18 08:50
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/1975

**Closed by Chocobozzz** 2019-11-18 08:50 UTC
Labels: Type: Duplicate :loop:
