### ISSUE TITLE
Tripled transcoding

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#5110] opened 2022-07-08 05:35 UTC
### Describe the current behavior

An user uploaded a video yesterday, 1080px resolution. It ran transcoding for all resolutions three times, except for the upload resolution which only was transcoded once. Only after the first batch of transcodes it was running the move-to-object-storage job, which lead to the video to be broken for the users. A summary of all the jobs, which all was successful according to the states (timestamps are for processed on-finished on):

First batch:
- optimize, 13:11-13:12
- 1080, 15:40-16:18 (Error: Missing lock for job 174 finished)
- audio, 13:49-13:49
- 480, 13:49-14:05
- 360, 14:05-14:19
- 720, 14:19-14:41
- 240, 14:41-14:52
- move-to-object-storage 14:53-14:54

Second batch:
- audio, 16:17-16:20
- 480, 16:39-16:58 (Error: Missing lock for job 182 finished)
- 360, det 16:58-17:13
- 720, 17:34-17:56 (Error: Missing lock for job 184 finished)
- 240, 17:58-18:09

Third batch:
- audio, 18:15-18:16
- 480, 18:32-18:48 (Error: Missing lock for job 189 finished)
- 360, 18:48-19:00
- 720, 19:01-19:22
- 240, 19:33-19:44 (Error: Missing lock for job 192 finished)

In parentheses is the message that's shown under the JSON data in the job. I've seen this message for other jobs, even though they seems to haven't broke the video. I couldn't find any errors in other logs.

Since we've versioned enabled in our bucket we can see that our master.m3u8 and segments-sha256.json has been updated at the following timestamps:

- 14:53:38
- 15:28:50
- 16:16:06
- 16:18:54
- 16:37:46
- 16:56:23
- 17:11:25
- 17:33:49
- 17:55:59
- 18:08:27
- 18:15:25
- 18:31:25
- 18:47:27
- 19:00:18
- 19:22:10
- 19:32:54
- 19:44:02

But neither master och segments-sha256 has been renamed, which I guess It should've done?

### Additional information

* PeerTube instance:
  * Version: 4.2.2
  * NodeJS version: v16.15.1
  * Ffmpeg version: 5.0.1-1+20.04.sav1

**Comment by kontrollanten** [comment] 2022-07-08 10:21
Here's the full information about the jobs:

```
[
  {
    "id": "173",
    "state": "completed",
    "type": "video-transcoding",
    "data": {
      "type": "optimize-to-webtorrent",
      "videoUUID": "0723eff8-e93e-4567-b645-17db0437878f"
    },
    "progress": 100,
    "priority": 138,
    "error": null,
    "createdAt": "2022-07-07T11:11:47.726Z",
    "finishedOn": "2022-07-07T11:12:42.573Z",
    "processedOn": "2022-07-07T11:11:47.730Z"
  },
  {
    "id": "174",
    "state": "completed",
    "type": "video-transcoding",
    "data": {
      "type": "new-resolution-to-hls",
      "autoDeleteWebTorrentIfNeeded": true,
      "videoUUID": "0723eff8-e93e-4567-b645-17db0437878f",
      "resolution": 1080,
      "isPortraitMode": false,
      "copyCodecs": false,
      "isMaxQuality": true,
      "hasAudio": true
    },
    "progress": 100,
    "priority": 138,
    "error": "Error: Missing lock for job 174 finished\n    at Object.finishedErrors (/var/www/peertube/versions/peertube-v4.2.2/node_modules/bull/lib/scripts.js:219:16)\n    at /var/www/peertube/versions/peertube-v4.2.2/node_modules/bull/lib/scripts.js:206:23\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
    "createdAt": "2022-07-07T11:12:42.567Z",
    "finishedOn": "2022-07-07T14:17:47.944Z",
    "processedOn": "2022-07-07T13:40:19.669Z"
  },
  {
    "id": "175",
    "state": "completed",
    "type": "video-transcoding",
    "data": {
      "type": "new-resolution-to-hls",
      "videoUUID": "0723eff8-e93e-4567-b645-17db0437878f",
      "resolution": 0,
      "isPortraitMode": false,
      "hasAudio": true,
      "copyCodecs": false,
      "isMaxQuality": false,
      "autoDeleteWebTorrentIfNeeded": true,
      "isNewVideo": true
    },
    "progress": 100,
    "priority": 138,
    "error": null,
    "createdAt": "2022-07-07T11:48:46.706Z",
    "finishedOn": "2022-07-07T11:49:13.055Z",
    "processedOn": "2022-07-07T11:48:51.781Z"
  },
  {
    "id": "176",
    "state": "completed",
    "type": "video-transcoding",
    "data": {
      "type": "new-resolution-to-hls",
      "videoUUID": "0723eff8-e93e-4567-b645-17db0437878f",
      "resolution": 480,
      "isPortraitMode": false,
      "hasAudio": true,
      "copyCodecs": false,
      "isMaxQuality": false,
      "autoDeleteWebTorrentIfNeeded": true,
      "isNewVideo": true
    },
    "progress": 100,
    "priority": 138,
    "error": null,
    "createdAt": "2022-07-07T11:48:46.715Z",
    "finishedOn": "2022-07-07T12:05:46.476Z",
    "processedOn": "2022-07-07T11:49:13.055Z"
  },
  {
    "id": "177",
    "state": "completed",
    "type": "video-transcoding",
    "data": {
      "type": "new-resolution-to-hls",
      "videoUUID": "0723eff8-e93e-4567-b645-17db0437878f",
      "resolution": 360,
      "isPortraitMode": false,
      "hasAudio": true,
      "copyCodecs": false,
      "isMaxQuality": false,
      "autoDeleteWebTorrentIfNeeded": true,
      "isNewVideo": true
    },
    "progress": 100,
    "priority": 138,
    "error": null,
    "createdAt": "2022-07-07T11:48:46.726Z",
    "finishedOn": "2022-07-07T12:19:07.187Z",
    "processedOn": "2022-07-07T12:05:46.476Z"
  },
  {
    "id": "178",
    "state": "completed",
    "type": "video-transcoding",
    "data": {
      "type": "new-resolution-to-hls",
      "videoUUID": "0723eff8-e93e-4567-b645-17db0437878f",
      "resolution": 720,
      "isPortraitMode": false,
      "hasAudio": true,
      "copyCodecs": false,
      "isMaxQuality": false,
      "autoDeleteWebTorrentIfNeeded": true,
      "isNewVideo": true
    },
    "progress": 100,
    "priority": 138,
    "error": null,
    "createdAt": "2022-07-07T11:48:46.733Z",
    "finishedOn": "2022-07-07T12:41:18.556Z",
    "processedOn": "2022-07-07T12:19:07.187Z"
  },
  {
    "id": "179",
    "state": "completed",
    "type": "video-transcoding",
    "data": {
      "type": "new-resolution-to-hls",
      "videoUUID": "0723eff8-e93e-4567-b645-17db0437878f",
      "resolution": 240,
      "isPortraitMode": false,
      "hasAudio": true,
      "copyCodecs": false,
      "isMaxQuality": false,
      "autoDeleteWebTorrentIfNeeded": true,
      "isNewVideo": true
    },
    "progress": 100,
    "priority": 138,
    "error": null,
    "createdAt": "2022-07-07T11:48:46.747Z",
    "finishedOn": "2022-07-07T12:52:50.322Z",
    "processedOn": "2022-07-07T12:41:18.556Z"
  },
  {
    "id": "181",
    "state": "completed",
    "type": "video-transcoding",
    "data": {
      "type": "new-resolution-to-hls",
      "videoUUID": "0723eff8-e93e-4567-b645-17db0437878f",
      "resolution": 0,
      "isPortraitMode": false,
      "hasAudio": true,
      "copyCodecs": false,
      "isMaxQuality": false,
      "autoDeleteWebTorrentIfNeeded": true,
      "isNewVideo": true
    },
    "progress": 100,
    "priority": 139,
    "error": null,
    "createdAt": "2022-07-07T13:30:04.875Z",
    "finishedOn": "2022-07-07T14:20:26.705Z",
    "processedOn": "2022-07-07T14:17:47.944Z"
  },
  {
    "id": "182",
    "state": "completed",
    "type": "video-transcoding",
    "data": {
      "type": "new-resolution-to-hls",
      "videoUUID": "0723eff8-e93e-4567-b645-17db0437878f",
      "resolution": 480,
      "isPortraitMode": false,
      "hasAudio": true,
      "copyCodecs": false,
      "isMaxQuality": false,
      "autoDeleteWebTorrentIfNeeded": true,
      "isNewVideo": true
    },
    "progress": 100,
    "priority": 139,
    "error": "Error: Missing lock for job 182 finished\n    at Object.finishedErrors (/var/www/peertube/versions/peertube-v4.2.2/node_modules/bull/lib/scripts.js:219:16)\n    at /var/www/peertube/versions/peertube-v4.2.2/node_modules/bull/lib/scripts.js:206:23\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
    "createdAt": "2022-07-07T13:30:04.888Z",
    "finishedOn": "2022-07-07T14:57:34.199Z",
    "processedOn": "2022-07-07T14:38:59.195Z"
  },
  {
    "id": "183",
    "state": "completed",
    "type": "video-transcoding",
    "data": {
      "type": "new-resolution-to-hls",
      "videoUUID": "0723eff8-e93e-4567-b645-17db0437878f",
      "resolution": 360,
      "isPortraitMode": false,
      "hasAudio": true,
      "copyCodecs": false,
      "isMaxQuality": false,
      "autoDeleteWebTorrentIfNeeded": true,
      "isNewVideo": true
    },
    "progress": 100,
    "priority": 139,
    "error": null,
    "createdAt": "2022-07-07T13:30:04.911Z",
    "finishedOn": "2022-07-07T15:12:28.999Z",
    "processedOn": "2022-07-07T14:57:34.199Z"
  },
  {
    "id": "184",
    "state": "completed",
    "type": "video-transcoding",
    "data": {
      "type": "new-resolution-to-hls",
      "videoUUID": "0723eff8-e93e-4567-b645-17db0437878f",
      "resolution": 720,
      "isPortraitMode": false,
      "hasAudio": true,
      "copyCodecs": false,
      "isMaxQuality": false,
      "autoDeleteWebTorrentIfNeeded": true,
      "isNewVideo": true
    },
    "progress": 100,
    "priority": 139,
    "error": "Error: Missing lock for job 184 finished\n    at Object.finishedErrors (/var/www/peertube/versions/peertube-v4.2.2/node_modules/bull/lib/scripts.js:219:16)\n    at /var/www/peertube/versions/peertube-v4.2.2/node_modules/bull/lib/scripts.js:206:23\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
    "createdAt": "2022-07-07T13:30:04.924Z",
    "finishedOn": "2022-07-07T15:56:23.264Z",
    "processedOn": "2022-07-07T15:34:16.216Z"
  },
  {
    "id": "185",
    "state": "completed",
    "type": "video-transcoding",
    "data": {
      "type": "new-resolution-to-hls",
      "videoUUID": "0723eff8-e93e-4567-b645-17db0437878f",
      "resolution": 240,
      "isPortraitMode": false,
      "hasAudio": true,
      "copyCodecs": false,
      "isMaxQuality": false,
      "autoDeleteWebTorrentIfNeeded": true,
      "isNewVideo": true
    },
    "progress": 100,
    "priority": 139,
    "error": null,
    "createdAt": "2022-07-07T13:30:04.932Z",
    "finishedOn": "2022-07-07T16:08:43.804Z",
    "processedOn": "2022-07-07T15:57:40.676Z"
  },
  {
    "id": "188",
    "state": "completed",
    "type": "video-transcoding",
    "data": {
      "type": "new-resolution-to-hls",
      "videoUUID": "0723eff8-e93e-4567-b645-17db0437878f",
      "resolution": 0,
      "isPortraitMode": false,
      "hasAudio": true,
      "copyCodecs": false,
      "isMaxQuality": false,
      "autoDeleteWebTorrentIfNeeded": true,
      "isNewVideo": true
    },
    "progress": 100,
    "priority": 140,
    "error": null,
    "createdAt": "2022-07-07T14:17:47.860Z",
    "finishedOn": "2022-07-07T16:15:43.064Z",
    "processedOn": "2022-07-07T16:15:10.785Z"
  },
  {
    "id": "189",
    "state": "completed",
    "type": "video-transcoding",
    "data": {
      "type": "new-resolution-to-hls",
      "videoUUID": "0723eff8-e93e-4567-b645-17db0437878f",
      "resolution": 480,
      "isPortraitMode": false,
      "hasAudio": true,
      "copyCodecs": false,
      "isMaxQuality": false,
      "autoDeleteWebTorrentIfNeeded": true,
      "isNewVideo": true
    },
    "progress": 100,
    "priority": 140,
    "error": "Error: Missing lock for job 189 finished\n    at Object.finishedErrors (/var/www/peertube/versions/peertube-v4.2.2/node_modules/bull/lib/scripts.js:219:16)\n    at /var/www/peertube/versions/peertube-v4.2.2/node_modules/bull/lib/scripts.js:206:23\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
    "createdAt": "2022-07-07T14:17:47.870Z",
    "finishedOn": "2022-07-07T16:47:43.474Z",
    "processedOn": "2022-07-07T16:31:47.862Z"
  },
  {
    "id": "190",
    "state": "completed",
    "type": "video-transcoding",
    "data": {
      "type": "new-resolution-to-hls",
      "videoUUID": "0723eff8-e93e-4567-b645-17db0437878f",
      "resolution": 360,
      "isPortraitMode": false,
      "hasAudio": true,
      "copyCodecs": false,
      "isMaxQuality": false,
      "autoDeleteWebTorrentIfNeeded": true,
      "isNewVideo": true
    },
    "progress": 100,
    "priority": 140,
    "error": null,
    "createdAt": "2022-07-07T14:17:47.877Z",
    "finishedOn": "2022-07-07T17:00:36.338Z",
    "processedOn": "2022-07-07T16:47:43.474Z"
  },
  {
    "id": "191",
    "state": "completed",
    "type": "video-transcoding",
    "data": {
      "type": "new-resolution-to-hls",
      "videoUUID": "0723eff8-e93e-4567-b645-17db0437878f",
      "resolution": 720,
      "isPortraitMode": false,
      "hasAudio": true,
      "copyCodecs": false,
      "isMaxQuality": false,
      "autoDeleteWebTorrentIfNeeded": true,
      "isNewVideo": true
    },
    "progress": 100,
    "priority": 140,
    "error": null,
    "createdAt": "2022-07-07T14:17:47.887Z",
    "finishedOn": "2022-07-07T17:22:26.485Z",
    "processedOn": "2022-07-07T17:00:36.338Z"
  },
  {
    "id": "192",
    "state": "completed",
    "type": "video-transcoding",
    "data": {
      "type": "new-resolution-to-hls",
      "videoUUID": "0723eff8-e93e-4567-b645-17db0437878f",
      "resolution": 240,
      "isPortraitMode": false,
      "hasAudio": true,
      "copyCodecs": false,
      "isMaxQuality": false,
      "autoDeleteWebTorrentIfNeeded": true,
      "isNewVideo": true
    },
    "progress": 100,
    "priority": 140,
    "error": "Error: Missing lock for job 192 finished\n    at Object.finishedErrors (/var/www/peertube/versions/peertube-v4.2.2/node_modules/bull/lib/scripts.js:219:16)\n    at /var/www/peertube/versions/peertube-v4.2.2/node_modules/bull/lib/scripts.js:206:23\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
    "createdAt": "2022-07-07T14:17:47.912Z",
    "finishedOn": "2022-07-07T17:44:20.576Z",
    "processedOn": "2022-07-07T17:33:15.055Z"
  }
]
```

**Comment by Chocobozzz** [comment] 2022-07-12 12:35
Did you have high CPU usage between `2022-07-07T13:40:19.669Z` and `2022-07-07T14:17:47.944Z`? (or during other failed job)

**Comment by kontrollanten** [comment] 2022-07-14 06:38
I'm sorry but I can't see if that where the case. May the high CPU usage be the cause of the tripled jobs?

**Comment by Chocobozzz** [comment] 2022-07-14 07:29
Yes, I think the root cause is `Missing lock for job` error. It means that Bull did not manage to extend the lock key when the job was processed. It can happens when the node event loop has too much work, so Bull doesn't have the opportunity do reassign the lock.

**Comment by kontrollanten** [comment] 2022-07-14 07:40
Okay. We've a separate server where redis is running, is it that server that needs more CPU? Is it possible to mark the job as failed if `Missing lock for job` is thrown?

**Comment by Chocobozzz** [comment] 2022-07-15 11:55
>  is it that server that needs more CPU

No, it's the peertube one. But it should not happen. We need to find what happened on peertube side to understand why the event loop was so busy.

**Comment by Chocobozzz** [comment] 2022-07-22 09:25
Do you know what happened to redis at 20h35?

**Comment by Chocobozzz** [comment] 2022-09-09 06:10
> This is still happening for ~30% of our videos.

With what peertube version? 4.2.2? Because the next one should fix this issue (hopefully)

**Comment by Chocobozzz** [comment] 2022-09-16 08:24
Okay then closing this issue. Please comment if it happens again with 4.3

**Closed by Chocobozzz** 2022-09-16 08:24 UTC
Labels: Status: To Reproduce, Component: Transcoding
