### ISSUE TITLE
MaxListenersExceededWarning crash on YunoHost installation

### ISSUE THREAD

**Issue by boistordu** [Chocobozzz/PeerTube#4023] opened 2021-04-29 18:54 UTC
**Describe the current behavior**
https://github.com/YunoHost-Apps/peertube_ynh/issues/229

**Steps to reproduce:**

nothing specific

**Describe the expected behavior**

Well there should not be this kind of message if it's built with the right node modules? 

**Additional information**

Sorry if I don't put all the informations in this bug report, but if I have it, since it's a pretty straightforward installation through yunohost and that I didn't change a lot of things besides the transcoding threads number and things like that, many people should have it in their journalctl 

Plus I'm trying to debug a lot of things here which are causing by peertube apparently on my setup, so can't really put you all the specifics.
But to know what's this peertube installation is made of just look at: https://github.com/YunoHost-Apps/peertube_ynh and you should have all the information about nodejs etc. 

tell me if you need something more specific :)
* PeerTube instance:
  * URL: 
  * version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment] 2021-05-05 09:14
Hello,

Please paste server logs leading to the crash

**Comment by boistordu** [comment] 2021-05-05 23:12
Here is the start of this :

https://github.com/YunoHost-Apps/peertube_ynh/issues/229

What else do you need ? If you point to me the exact situation to the information you need then I can bring it to you

**Comment by Chocobozzz** [comment] 2021-05-06 06:45
I would need server logs above the lines you paste on yunohost repo. Also, did you reproduce your issue since laste week?

**Comment by boistordu** [comment] 2021-05-06 13:07
It's the case at each reboot. 
It was a copy paste from the start of the service, not the installation nor the use of it in any way. 
Does peertube has its own log ?

**Comment by boistordu** [comment] 2021-05-13 02:59
Well I don't know sir. The only thing I know is that there seems some inconsistencies in the code that impeach peertube to process to release in time of shutdown the folder it has under its grip. So I did go à bit deeper and look at the logs and there is when I found it the error/warning in the logs. So I wanted to make it public that's all

**Comment by Chocobozzz** [comment] 2021-05-26 13:46
Closing, feel free to comment if you notice another crash.

**Closed by Chocobozzz** 2021-05-26 13:46 UTC
Labels: Status: Waiting for answer
