### ISSUE TITLE
Player size during auto play

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#4656] opened 2021-12-20 06:31 UTC
Peertube version: 4.0.0

**Describe the problem to be solved**
When the next video in the playlist is turned on, the full screen is reset.

1. I launch the first video in the playlist and watch it to the end in full screen.
2. The second video in the order in the playlist starts automatically. The full screen is reset.

**Describe the solution you would like:**
If automatic playback of the next video is enabled when viewing a playlist, then the size of the player must remain the same. If it was expanded to full screen, then the next video should also remain expanded to full screen.

**Comment by Chocobozzz** [comment] 2021-12-22 09:32
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/3159

**Closed by Chocobozzz** 2021-12-22 09:32 UTC
