### ISSUE TITLE
Support different encoders based on resolution

### ISSUE THREAD

**Issue by SimplyCorbett** [Chocobozzz/PeerTube#4258] opened 2021-07-18 23:38 UTC
I've looked to see if this was already created and didn't find anything.

It would be nice to have different encoding profiles (the plugin) based on video resolution.

Example: VP9 could be enabled for 480p and 720p and then H264 could be used on 1080p-1440p.

This could also be used for live streaming.

**Comment by SimplyCorbett** [comment] 2021-11-26 18:49
Any progress on this? Would be nice to use preset 8 on SVT-AV1 within 360p-720p and preset 5-6 on 1080p+. Preset 8 is super fast but there is a noticeable loss of detail on higher resolutions.

**Comment by Chocobozzz** [comment] 2022-08-02 12:45
It seems this issue is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/3994

**Closed by Chocobozzz** 2022-08-02 12:45 UTC
Labels: Type: Enhancement :sparkles:, Component: Transcoding, Component: PeerTube Plugin :package:
