### ISSUE TITLE
title needs localization on Peertube version 3.3.0 menu

### ISSUE THREAD

**Issue by rnek0** [Chocobozzz/PeerTube#4274] opened 2021-07-24 21:40 UTC
https://github.com/Chocobozzz/PeerTube/blob/c1936140b9b61f44f53d05c7ef55cb5701a3f4e7/client/src/app/core/menu/menu.service.ts#L104

![_in_my_library](https://user-images.githubusercontent.com/52655832/126881595-d7f4b212-12d4-4f6d-95eb-fba0ff2190fe.png)

**Comment by Chocobozzz** [comment] 2021-07-26 06:46
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/4261

**Closed by Chocobozzz** 2021-07-26 06:46 UTC

**Comment by rnek0** [comment] 2021-07-26 07:48
I see the changes on the development branch for line 104 now :)  
If we want to do a code review on the github site. Is this the branch to look in?

After upgrading to the latest version and seeing this, I wanted to find out where this was happening. I went to see if the translations were good on weblate, but I didn't take the right branch.

**Comment by Chocobozzz** [comment] 2021-07-26 08:04
> If we want to do a code review on the github site. Is this the branch to look in?

Yes it is.
