### ISSUE TITLE
Handle webm videos without duration in container/stream

### ISSUE THREAD

**Issue by zanhesl** [Chocobozzz/PeerTube#4092] opened 2021-05-13 13:20 UTC
Hello everyone, for some reason I am unable to upload [this](https://www.dropbox.com/s/vlcujzkl5f7rpbj/Muse%20-%20Uprising%20%5BOfficial%20Video%5D.webm?dl=0) video to any peertube instance (my local one, my public ones and random instance I've gotten from global list - https://pony.tube/).

It is in the .webm format and plays normally on my local pc.

Have you any ideas, why this file creates such an error? I want to avoid getting in such kind of problems in the future, so I want to define, why this error happens.

Thanks for your attention.

**Comment by Chocobozzz** [comment] 2021-05-14 07:36
Hello,

The video is not available

**Comment by zanhesl** [comment] 2021-05-14 09:23
Sorry, this is new link - https://www.dropbox.com/s/9860j2nerin3gbq/Muse%20-%20Uprising%20%5BOfficial%20Video%5D.webm?dl=0

Seems to be just a usual video. I've found another one in webm format, that produces such an error. However, I've never witnessed mp4 file producing such an error

**Comment by zanhesl** [comment] 2021-05-19 13:02
So it seems that some .webm files could cause errors for some reason. Maybe one had better use ither formats for uploading videos

**Comment by Chocobozzz** [comment] 2021-05-25 08:33
The issue is that ffprobe can't find the duration in the webm file. I think we can try to improve this, using an "unknown" value for the duration for example.

**Comment by zanhesl** [comment] 2021-05-25 08:34
Thanks for finding that out, hope you'll be able to fix this.

**Comment by Chocobozzz** [comment] 2024-08-06 11:50
Closing this issue, it seems we can correctly upload webm videos without duration metadata if PeerTube transcoding is enabled :)

**Closed by Chocobozzz** 2024-08-06 11:50 UTC
Labels: Type: Feature Request :sparkles:
