### ISSUE TITLE
Poor loading on mobile

### ISSUE THREAD

**Issue by Halfwren** [Chocobozzz/PeerTube#2952] opened 2020-07-13 01:07 UTC
Hello there, I am new to peertube so I apologize in advance for any n00bery.

I'm developing a website designed primary for use on mobile, and this site includes links to videos that are hosted off-site (I was originally just going to link to youtube videos, but I would rather expose people to something more decentralized if possible).

In my test (in browser on iphone), the link leads to the video on peertube just fine, but whether or not the video loads in any kind of timely manner is incredibly inconsistent. It usually stays a black screen and only pulls up even a short video maybe 1 in 15 or 20 loads. This is the case from multiple browsers (and in any case I want consistency from as many mobile browsers as possible, naturally). As you can imagine, this would make most people abandon the site before learning enough to put up with this level of issue.

Is this inconsistency on mobile a noted problem with peertube, or with WebRTC in general? Is this problem something that is instance-specific (and if so, I would love if someone could break down what tweaks might make a peertube instance work more consistently on mobile).

Thank you in advance for any help!

**Comment by rigelk** [comment] 2020-07-13 14:26
Hi @Halfwren, we cannot debug without video URL where you noticed the issue. Could you provide examples?

**Comment by Chocobozzz** [comment] 2020-07-20 06:35
If the peertube instance uses the webtorrent player, enabling HLS could help

**Comment by Halfwren** [comment] 2020-07-28 17:38
@rigelk Sorry about the delay here, the mobile version of this link is one that never seemed to load on mobile with any consistency https://peertube.fidonet.io/videos/watch/f895d4b0-2292-4b4c-845c-7975b2ea3e0c

**Comment by rigelk** [comment] 2020-07-28 17:40
What mobile and browser version have you tested this on?

**Comment by Halfwren** [comment] 2020-07-28 18:21
iPhone 10, safari and firefox. It isn't my instance, by the way. If you're not encountering the same issue, I don't want to waste too much of your time on this, as it seems I should be able to set something up...on looking further it seems the problem might be entirely on my end

**Comment by Chocobozzz** [comment] 2020-07-31 09:53
@Halfwren Sorry but I could not reproduce the issue using browser stack. Maybe related to your network? Closing this issue, don't hesitate to comment if you find something new.

**Closed by Chocobozzz** 2020-07-31 09:53 UTC
Labels: Status: Waiting answer
