### ISSUE TITLE
When I upload a video, download and comments are unticked by me. However, once video is uploaded, download and comments are ON in video settings

### ISSUE THREAD

**Issue by antistress** [Chocobozzz/PeerTube#5090] opened 2022-06-30 13:12 UTC
### Describe the current behavior

Settings regarding **not** allowing comments nor download are not taken into account at the time the video is uploaded.
I have to set it again after the video is uploaded.

I'm using Peertube within apps.education.fr (not the beta one, the final one)

Thanks

**Comment by Chocobozzz** [comment] 2022-07-01 06:56
Hi,

I'm sorry but I can't reproduce. Could you paste the PeerTube instance URL?

**Comment by antistress** [comment] 2022-07-01 20:35
Hi,

https://tube-arts-lettres-sciences-humaines.apps.education.fr/my-library/videos

I already noticed that problem 1,5 year ago with peertube within https://apps-versailles.beta.education.fr and it's still there with peertube within apps.education.fr this week.

Thanks

**Comment by antistress** [comment] 2022-07-02 16:04
Actually it happens when I "upload" a video **by copying/pasting an url**
The bug doesn't occur when I upload a local file
Thanks

**Comment by Chocobozzz** [comment] 2022-07-04 09:33
Thanks! It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/0146f3516ec458d7eaba3ede2addb23005bd4a28

**Closed by Chocobozzz** 2022-07-04 09:33 UTC
Labels: Type: Bug :bug:, UI, Component: Import

**Comment by antistress** [comment] 2022-07-04 16:08
Thanks Chocobozzz :)
