### ISSUE TITLE
Watch video together

### ISSUE THREAD

**Issue by FirePowi** [Chocobozzz/PeerTube#1770] opened 2019-04-11 17:29 UTC
I know we can't (for now at least) add Live in peertube but… We can add "Première" as youtube do… And more… We can have something like a "Watch together" where the video watched is synchronized between viewers with a direct chat (as in youtube).
A "Watch together" may be initialized by the content creator or by anyone else.
A notification is sent to the subscribers of the "Watch together"'s launcher.

EDIT : (@fredsif)
> Also, being able to use a playlist with this option would be great.

Pro :
- Peertube work via torrent. And peertube can handle a massive one-video watching.

**Comment by fredsif** [comment] 2019-04-13 12:37
So much this.
Also, being able to use a playlist with this option would be great.

That's what https://cytu.be/ does, but they don't work with Peertube, only media providers such as Youtube/Vimeo/Etc

**Comment by buoyantair** [comment] 2019-04-13 12:51
I love this idea. This is I think one of the features I always wanted Youtube to have. To be able to watch together with groups of people and talk about stuff together. Watching a movie and actually talking about it a There is in fact a whole website dedicated to enabling this for youtube at https://www.watch2gether.com/

This is really pretty cool and I think really pushes the whole "community centric humane software" goal too.

**Comment by rigelk** [comment] 2019-12-19 01:32
This is actually similar/borderline duplicate of #357, which will track the issue from now on.

**Closed by rigelk** 2019-12-19 01:32 UTC
Labels: Type: Enhancement :sparkles:
