### ISSUE TITLE
Bulk import from YouTube

### ISSUE THREAD

**Issue by TILvids** [Chocobozzz/PeerTube#3054] opened 2020-08-09 20:19 UTC
I'm working with a bunch of creators on my [TILvids](https://tilvids.com) instance, and they are looking to pull in a number of their videos from YouTube. They would like the ability to bulk-import from URL at one time, and then go back and change description/metadata information later if they desire.

**Comment by Chocobozzz** [comment] 2020-08-10 06:39
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/1438

**Closed by Chocobozzz** 2020-08-10 06:39 UTC
