### ISSUE TITLE
Different number of subscribers and videos for the same account across different instances

### ISSUE THREAD

**Issue by ghost** [Chocobozzz/PeerTube#1942] opened 2019-06-23 18:46 UTC
This issue is basically like https://github.com/Chocobozzz/PeerTube/issues/1887 but instead of comments, we have different numbers of subscribers and videos.

- video.ploud.fr/**accounts/savjee**@peertube.social/video-channels **-** (PeerTube v1.3.0) 33 subs and 1 video

- peertube.social/**accounts/savjee**/videos **-** (PeerTube v1.3.1) 38 subs and 5 videos

- video.taboulisme.com/**accounts/savjee**@peertube.social/videos **-** (PeerTube v1.3.0) 33 subs (earlier I saw 16 subs) and 1 video

**Comment by Aluriak** [comment] 2019-06-23 19:18
I see 33 subs on the third one.

**Comment by Zig-03** [comment] 2019-06-23 19:28
> I see 33 subs on the third one.

I do now too. Weird. But it was 16. 

And how many videos do you see on the third one?

**Comment by Jorropo** [comment] 2019-06-24 00:22
I've allready got this error but like all of these kind (For all I know) waiting fix it, its maybe due a cache error ?

**Comment by Aluriak** [comment] 2019-06-26 08:28
> And how many videos do you see on the third one?

One, as you said.

> its maybe due a cache error ?

Probably something like that.

**Comment by Zig-03** [comment] 2019-07-02 13:17
@Chocobozzz Do you see 5 videos on this link https://video.ploud.fr/accounts/savjee@peertube.social/video-channels? Because that's how many videos should be there, but instead I see only one. I don't understand why you labeled this issue "To Reproduce", do you see different things? @Aluriak seems to see things as I see them, so that's 2 people.

**Comment by Chocobozzz** [comment] 2019-07-02 17:04
Reproduce labels means that I need to find a way to **reproduce** (and understand) the bug. It does not mean that I don't see it :)

**Comment by Chocobozzz** [comment] 2020-02-04 09:09
Should be fixed in the current develop (peertube 2.2)

**Closed by Chocobozzz** 2020-02-04 09:09 UTC
Labels: Status: To Reproduce
