### ISSUE TITLE
Incorrectly displayed the counter of the number of responses

### ISSUE THREAD

**Issue by Izorkin** [Chocobozzz/PeerTube#4133] opened 2021-05-29 18:16 UTC
**Describe the current behavior**
Wrote an answer under the comment. After that, I corrected the message 3 times. As a result, instead of one answer, 4 is written.
```
View 4 replies from ...
```

* PeerTube instance:
  * version: 3.2.0
  * NodeJS version: 14.16.1
  * Ffmpeg version: 4.3.2

**Comment by hjarvard** [comment] 2021-05-31 09:18
I'm experiencing the same issue. Also, there is an error message in the console:
```
TypeError: this.form is undefined
    patchTextValue video-comment-add.component.ts:198
    ngOnChanges video-comment-add.component.ts:78
```

**Comment by Chocobozzz** [comment] 2021-06-08 08:41
I fixed the error in the console in https://github.com/Chocobozzz/PeerTube/commit/5982ffc4b5c926ea51f5bb3ca48f0f2f8f5bd621

However I could not reproduce your issue. Could you paste your comment URLs?

**Comment by Izorkin** [comment] 2021-06-08 10:41
> Could you paste your comment URLs?

https://stream.elven.pw/videos/watch/c1ab5ed8-36e7-4070-a415-588dccf2218f

**Comment by Chocobozzz** [comment] 2021-06-08 11:52
Thanks, I could reproduce. Then it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/99cb53fd5af3a13886e87c6aa224d777acee9fac

**Closed by Chocobozzz** 2021-06-08 11:52 UTC
Labels: Component: Comments, Status: Waiting for answer, Type: Bug :bug:
