### ISSUE TITLE
Server keeping unwanted high video resolutions

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#2643] opened 2020-04-16 10:55 UTC
**What happened?**
I uploaded a video in 1080p, in an acceptable format (that can be published instantly). My server is configure to only use resolution below 720p, HLS and non HLS. 
After transcoding jobs, the video is still available in 1080p (HLS and non HLS).

**What do you expect to happen instead?**
I thought that by settings transcoding resolutions below 720p, I will not have any 1080p video and so save some space and resources.
Is this a wanted behavior? To keep original resolution if the file is acceptable, even if its resolution is higher than the configuration?

**Steps to reproduce:**

1. Download a 1080p video from peertube (so it is already in an acceptable format)

2. Upload it on an instance that is configured to only use <= 720p resolution

3. Waiting for transcode jobs to finish

4. The video is available in 1080p, and was duplicated in the hls folder.

**Additional information**
* PeerTube version or URL: 2.1.1 (https://videos.globenet.org)

**Comment by Chocobozzz** [comment] 2020-04-16 12:09
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/1030

**Closed by Chocobozzz** 2020-04-16 12:09 UTC

**Comment by JohnXLivingston** [comment] 2020-04-16 12:23
Oops, didn't see this one.
