### ISSUE TITLE
Adding Turkish Language Pack to Peertube interface

### ISSUE THREAD

**Issue by samsunatakum** [Chocobozzz/PeerTube#6293] opened 2024-03-26 11:34 UTC
### Describe the problem

     Hello @Chocobozzz, we have completed the translation of the Turkish language package from "https://weblate.framasoft.org/translate/peertube".

1-Can we use the Turkish language package in the offline instance we are currently using? (Can we add the package to the system offline?)

2- If the above is not possible, can you add the Turkish language package to the peertube installation file? So that we can install a new instance.

thanks..

***Our Peertube example works offline.***

### Additional information

* PeerTube instance URL:
* PeerTube version:
* NodeJS version:
* Ffmpeg version:
* Redis version:
* PostgreSQL version:

**Comment by Chocobozzz** [comment] 2024-03-26 15:14
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/6289

**Closed by Chocobozzz** 2024-03-26 15:14 UTC
