### ISSUE TITLE
Square video format is stretched in thumbnail

### ISSUE THREAD

**Issue by klorydryk** [Chocobozzz/PeerTube#3272] opened 2020-11-08 13:59 UTC
v2.4.0

1. Import square format video like this one https://twitter.com/konbininews/status/1325030485651824641
2. Let the automatic thumbnail to be generated by peertube.
3. In the video list, the thumbnail of this video is stretched.

![Capture d’écran_2020-11-08_15-40-45](https://user-images.githubusercontent.com/1232047/98468017-df6c4780-21d8-11eb-9c8f-6dc793770036.png)

**Comment by Chocobozzz** [comment] 2020-11-08 18:14
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/3027

**Closed by Chocobozzz** 2020-11-08 18:14 UTC
