### ISSUE TITLE
Allow non technical users to mirror their YouTube videos on PeerTube

### ISSUE THREAD

**Issue by theRAGEhero** [Chocobozzz/PeerTube#5048] opened 2022-06-13 12:07 UTC
Hello everyone, 
Thank you for PeerTube, I hope my idea can contribute to make it better.

**Allow non technical users to mirror their YouTube videos on PeerTube**

**Normal users or also youtubers would love to mirror their videos on PeerTube, this would give more sense to PeerTube instances, with more fresh content.

I love PeerTube but is in some way hard to tell to people to not use YouTube since most of the content is there. 
**

**I see two possible solutions:

- Integrate the possibility to automate the import of YouTube videos on every instance.
A sort of option like: “Connect your YouTube account that you would like to mirror” that check every day if there are new videos.

- Offer a standalone software that do that, like there is alredy for the search engine. You connect on import.domain.com, you put your instance name like tube.example.org and your user and password (or maybe, even better, some API).
 ** 

Thank you.

**Comment by Sobsz** [comment] 2022-06-13 13:12
[This plugin](https://zeteo.me/gitea/Outils-PeerTube/peertube-plugin-auto-import-ytb) might interest you, though it's admittedly not the most user-friendly.

**Comment by Chocobozzz** [comment] 2022-06-14 07:14
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/754

**Closed by Chocobozzz** 2022-06-14 07:14 UTC

**Comment by theRAGEhero** [comment] 2022-06-15 12:03
> [This plugin](https://zeteo.me/gitea/Outils-PeerTube/peertube-plugin-auto-import-ytb) might interest you, though it's admittedly not the most user-friendly (and it requires admin involvement to set the channels being mirrored).

Thank you, I'll try it!

> Thanks for reporting this issue, but this is a duplicate of #754

Oh, I didn't see. Thank you.
