### ISSUE TITLE
See transcoding status for a video

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#4732] opened 2022-01-20 07:38 UTC
**Describe the problem to be solved**
If there's an issue with uploading a video it would be great for an admin to be able to easily trace the error. It would also be great for an admin to be able to see how long time it takes for a video to get transcoded.

**Describe the solution you would like:**
Possibility to filter transcoding jobs for a certain video.

**Describe alternatives you have considered**  
* A search filter on /admin/system/jobs to be able to get all jobs related to a specific video and/or channel.
* List all jobs related to a video in /admin/videos/list

**Comment by Chocobozzz** [comment] 2022-01-20 13:15
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/4320 and https://github.com/Chocobozzz/PeerTube/issues/799

**Closed by Chocobozzz** 2022-01-20 13:15 UTC
Labels: Type: Duplicate :loop:
