### ISSUE TITLE
Enable option to set videos uploaded to be 'pending' before going live

### ISSUE THREAD

**Issue by hellomotow** [Chocobozzz/PeerTube#740] opened 2018-06-28 00:23 UTC
Another feature I would like to see is an option to set new uploads to pending, needing to be approved by an admin before going live.

**Comment by Chocobozzz** [comment] 2018-06-28 12:42
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/138

**Closed by Chocobozzz** 2018-06-28 12:42 UTC
