### ISSUE TITLE
Downloaded video length not displaying correctly on Windows and Android

### ISSUE THREAD

**Issue by ianrbuck** [Chocobozzz/PeerTube#6353] opened 2024-04-24 01:29 UTC
### Describe the current behavior

If you download a video (whether via the download button on the PeerTube webpage or a podcast player downloading via the RSS feed) and play it on a Windows or Android device, the media player will misinterpret the length of the video and will not be able to properly display the scrub bar. This issue does not seem to appear on macOS. I have observed this happening on almost all videos I download from many different instances. Different media players display the length differently (Pocket Casts shows 4 or 5 seconds for most videos, Windows Media Player greys out the scrub bar and does not display a video length) but none of them seem to be correct.

### Steps to reproduce

1. On a Windows computer, click on the download button on [this video](https://urbanists.video/w/ckn5uQoo6exxfxHfyViXZB) webpage.
2. Open the video file in Windows Media Player.
3. Observe the scrub bar greyed out and no video length displayed.

### Describe the expected behavior

The video length should be 20 seconds, and the scrub bar should steadily progress from the start of the video to the end.

### Additional information

* PeerTube instance: Urbanists.video (behavior observed on many other instances as well)
  * URL: https://urbanists.video/w/ckn5uQoo6exxfxHfyViXZB
  * Version: 6.0.4
  * NodeJS version: 
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug: Windows, Android; all browsers
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment] 2024-04-24 04:56
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/4130

**Closed by Chocobozzz** 2024-04-24 04:56 UTC
