### ISSUE TITLE
Peertube link on player sends to a 404 error (on custom home page).

### ISSUE THREAD

**Issue by rnek0** [Chocobozzz/PeerTube#4291] opened 2021-07-30 11:58 UTC
**Describe the current behavior**
Maybe the "player" needs to check if it has been integrated into this home page?
I get a 404 error here https://ptb.lunarviews.net/home when I click on the Peertube link in the player, so I have to put a button to link to another instance.
Is this a bug?
**Steps to reproduce:**

1. go to https://ptb.lunarviews.net/home and click on the Peertube player
2.
3.

**Describe the expected behavior**
The link on the player should send to another instance. In this case [here](https://peer.hostux.social/videos/watch/d39d6b94-f320-4694-9d3d-ed9b8cb6d538)
**Additional information**

* PeerTube instance:
  * URL: https://ptb.lunarviews.net/
  * version: 3.3.0
  * NodeJS version:  v14.16.1
  * Ffmpeg version: 4.1.6-1~deb10u1+rpt2

* Browser name, version and platforms on which you could reproduce the bug:
 - [Firefox](https://www.mozilla.org/en-US/firefox/90.0.2/releasenotes/?utm_campaign=about-dialog&utm_medium=firefox-desktop&utm_source=firefox-browser)
 - [Chromium](Version 92.0.4515.107 (Build officiel) Arch Linux (64 bits))
 - **I think in all browsers**
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment] 2021-07-30 12:04
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/4289

**Closed by Chocobozzz** 2021-07-30 12:04 UTC
