### ISSUE TITLE
URL shortener

### ISSUE THREAD

**Issue by McFlat** [Chocobozzz/PeerTube#2882] opened 2020-06-17 22:13 UTC
Need a way to shorten urls and be able to share them. 

Something like this https://github.com/muhsin-k/URL-Shortner only using the current framework in place (postgres, express and angular)

Would be great to share a url with either a random short code or a label such as

/u/We4fV9
/u/a-short-url

which redirects to any valid url on that site, such as a video url or a channel url etc. can be restricted to shorten only urls from the instance. and when sharing a generated short url will be displayed to share instead of a long video url with a hash, should also not allow duplicate urls to generate a hash but allow duplicates if different label perhaps that will redirect to that video url

**Comment by Chocobozzz** [comment] 2020-06-18 07:05
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/534

**Closed by Chocobozzz** 2020-06-18 07:05 UTC
Labels: Type: Duplicate :loop:
