### ISSUE TITLE
Playlist selection popup appears outside of viewport

### ISSUE THREAD

**Issue by e8johan** [Chocobozzz/PeerTube#2151] opened 2019-10-01 08:48 UTC
**What happened?**

When adding videos to a playlist using the "..." symbol below items in a list of videos, e.g. a channel, the initial popup (where you choose to add to playlist) appears in a position adapted to the current viewport, but the popup letting you select an actual playlist appears relative to the "..." symbol, which means that it might appear under the viewport.

**What do you expect to happen instead?**

The playlist selection popup should appear in a position so that it is visible in the viewport.

**Steps to reproduce:**

1. Find a channel with enough videos to overflow the current viewport.

2. Click the "..." of a video close to the bottom of the viewport and select to add to a playlist.

3. The popup with a list of playlists appear partially outside the viewport.

**Additional information**
* PeerTube version or URL: 1.3.1, https://conf.tube
* Browser name/version: Firefox 69.0 64-bit on Windows
* NodeJS version: no idea

* Link to browser console log if useful: n/a
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/): n/a

**Comment by Chocobozzz** [comment] 2019-12-02 13:45
Blocked by https://github.com/ng-bootstrap/ng-bootstrap/issues/3495

**Comment by Chocobozzz** [comment] 2022-06-16 12:59
Closing as I can't reproduce anymore with the latest ng-bootstrap upgrade.

**Closed by Chocobozzz** 2022-06-16 12:59 UTC
Labels: Status: Blocked :hand:, Type: Bug :bug:, UI
