### ISSUE TITLE
Updating a video thumbnail does not change the updated time 

### ISSUE THREAD

**Issue by rscmbbng** [Chocobozzz/PeerTube#4501] opened 2021-10-26 08:45 UTC
**Describe the current behavior**
When video metadata is edited, the `updated_at` value returned through the API changes accordingly. However, when a video thumbnail is changed this does not update the `updated_at` value.

**Steps to reproduce:**

1. Publish a video and [query it via the api](https://docs.joinpeertube.org/api-rest-reference.html#tag/Video). Take note of the `updated_at` value.
2. Edit the video metadata by changing the description. Notice `updated_at` value returned by the api has changed.
3. Edit the video metadata by changing the thumbnail. Notice `updated_at` value returned by the api has *not* changed.

**Describe the expected behavior**
Changing the thumbnail is to be considered as updating the video metadata which should be reflected in the `updated_at` time stamp. Systems relying on `updated_at` to update for example a local version of the thumbnail do not work now. 

* PeerTube instance:
  * version: 3.3
  * NodeJS version:
  * Ffmpeg version:

**Comment by Poslovitch** [comment] 2021-11-10 08:05
Could it be the cause of #4442 ?

**Comment by Chocobozzz** [comment] 2021-11-10 14:17
Fixed by https://github.com/Chocobozzz/PeerTube/commit/5cf027bdc46f1bf214c4cf26eee17ebda228004f

**Closed by Chocobozzz** 2021-11-10 14:17 UTC
Labels: Type: Bug :bug:
