### ISSUE TITLE
Cancelled videos should cancel transcoding jobs

### ISSUE THREAD

**Issue by Kinuseka** [Chocobozzz/PeerTube#5492] opened 2022-12-30 06:40 UTC
### Describe the current behavior

Whenever a video was still trancoding and was cancelled midway by the user the transcoding job associated with it should also be halted. 

This is beneficial in a way:
1. This prevents duplicated transcoding (when the user reuploads the same video back)
2. Does not waste CPU resource
3. Does not clog up the job process transcoding on a cancelled video

This feature pretty significant on large videos where transcoding jobs take so much time.

### Steps to reproduce

1. Find an instance
2. Upload/import a video
3. While in the middle of transcoding cancel it

### Describe the expected behavior

Cancelled videos should cancel transcode jobs

### Additional information

* PeerTube instance:
  * URL: https://vid.kinuseka.us/
  * Version: 5.0.0
  * NodeJS version: 16.19.0
  * Ffmpeg version: 4.4.2-0ubuntu0.22.04.1

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment] 2022-12-30 07:20
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/5279

**Closed by Chocobozzz** 2022-12-30 07:20 UTC
