### ISSUE TITLE
Cant edit private Playlist

### ISSUE THREAD

**Issue by 6543** [Chocobozzz/PeerTube#1833] opened 2019-05-22 09:35 UTC
Version: 1.3.0-rc.2

Error Message: "Cannot get this private video playlist."
url: <Instance>/my-account/video-playlists/update/29d4597c-14b0-4e22-8364-f0ee1a6d7007

PS: public one works fine!

**Comment by Chocobozzz** [comment] 2019-05-24 09:43
I'm sorry but I can't reproduce. Please explain the step to reproduce this bug. Is it your playlist?

**Comment by stom79** [comment] 2019-05-26 11:09
I got errors 403 when I want to watch a video at the root of my play-lists. If I add them into a play-list that I created, the list is empty for the same purpose.

`{"error":"Cannot get this private video playlist."}`

It seems related to the private status of my play-lists

**Comment by 6543** [comment] 2019-05-26 11:32
@Chocobozzz I'll try to send you a detailed report

**Comment by Chocobozzz** [comment] 2019-05-28 07:51
I was finally able to reproduce it!

Thanks @6543 & @stom79, it should be fixed in https://github.com/Chocobozzz/PeerTube/commit/964298de4e112df0e126aad755c6b077442a2821

**Closed by Chocobozzz** 2019-05-28 07:51 UTC
Labels: Type: Bug :bug:

**Comment by 6543** [comment] 2019-05-28 08:00
@Chocobozzz thanks, you are so fast!! :)
