### ISSUE TITLE
Account channels don't work

### ISSUE THREAD

**Issue by yassinphilip** [Chocobozzz/PeerTube#556] opened 2018-05-10 19:22 UTC
I created a channel, then in the upload page, selected this channel, then clicked "Select the file to upload" yet [my video has been published on my "default channel"](https://peertube.nsa.ovh/videos/watch/8ff4f4f7-1991-46b3-a707-175aa27a12cf) and in [the "Update" page](https://peertube.nsa.ovh/videos/edit/8ff4f4f7-1991-46b3-a707-175aa27a12cf), the "Channel" menu is grayed out, so I cant put my video in the proper channel.

**Comment by Chocobozzz** [comment] 2018-05-11 08:47
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/349

**Closed by Chocobozzz** 2018-05-11 08:47 UTC
