### ISSUE TITLE
Move PIP button or make it unclickable

### ISSUE THREAD

**Issue by SimplyCorbett** [Chocobozzz/PeerTube#4551] opened 2021-11-20 02:23 UTC
**Describe the current behavior**

Opening the resolution menu and clicking 1080p sometimes opens PIP mode instead. Clicks go straight through the menu and click on the PIP button.

![button](https://user-images.githubusercontent.com/7935624/142711235-c8ad2df5-977e-4bf2-989a-9a405c946218.png)

**Describe the expected behavior**

Clicks don't go through the menu

**Additional information**

* PeerTube instance:
  * URL: private
  * version: GIT
  * NodeJS version: 16.10
  * Ffmpeg version: 4.4.1
  * Latest firefox/linux with ublock

**Comment by Chocobozzz** [comment] 2021-11-23 13:18
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/3275

**Closed by Chocobozzz** 2021-11-23 13:18 UTC
