### ISSUE TITLE
Import with URL feature (and API) imports 720p version of 1080p YouTube video vs 1080p like it did before

### ISSUE THREAD

**Issue by sunknudsen** [Chocobozzz/PeerTube#4241] opened 2021-07-08 14:29 UTC
**Describe the current behavior**

I updated my [instance](https://peertube.sunknudsen.com/) to `3.2.1` and now importing videos from YouTube (using “Import with URL” feature or API) imports 720P version of 1080P YouTube video vs 1080P like it did before.

**Steps to reproduce:**

1. Import 1080P YouTube video using “Import with URL” feature or API

**Describe the expected behavior**

Before update, “Import with URL” feature or API imported 1080P YouTube videos as 1080P.

Running `youtube-dl --format "bestvideo[ext=mp4][height<=1080]+bestaudio[ext=m4a]/best[ext=mp4]/best" "https://www.youtube.com/watch?v=GJ31v-7g4Qo"` downloads 1080P version as expected so issue appears to be at the PeerTube-level.

**Additional information**

* PeerTube instance:
  * URL: https://peertube.sunknudsen.com/
  * version: `3.2.1`
  * NodeJS version: `v12.20.2`
  * Ffmpeg version: `4.1.6-1~deb10u1`

**Comment by rigelk** [comment] 2021-07-08 14:35
hi @sunknudsen,

You are not describing the expected behaviour of PeerTube, which filters out not only extensions but codecs too: https://github.com/Chocobozzz/PeerTube/blob/develop/server/helpers/youtube-dl.ts#L120-L127

**Comment by sunknudsen** [comment] 2021-07-08 14:40
@rigelk Why close issues that fast? I am investing a ridiculous amount of extra time supporting (and advocating for) PeerTube as a Google alternative. The process is overwhelming but I still feel proud to support decentralization initiatives. That said, being shutdown like this makes me want to stop fighting. You comment didn’t help... something has changed since I last published. Now imports are 720P vs 1080P. That isn’t expected behaviour right? I understand you guys must be overwhelmed by all outstanding issues. That said expedited project management like this pushes us away. 😔

**Comment by rigelk** [comment] 2021-07-08 15:11
In its current state the issue is not a feature request, but a bug report. A bug report fundamentally consists of an observed/expected behaviour, and a context. If either is untrue, the issue is invalid, hence my closing the issue by pointing out this is not the expected behaviour in PeerTube at the moment.

I can leave the issue open if you want to change the current behaviour of PeerTube, but in that case you must be specific about what you want and edit the issue to reflect the desired changes, or open a feature request following its template.

In your issue, you are pointing out an undesired behaviour of PeerTube for you, stating that a 720p video source is not what the detected optimal source should be, using as an exemple of normal behaviour youtube-dl filters in your command line that are _not_ the ones used by PeerTube when importing a video, hence the different results (_aka_ expected behaviour). Where did you find your command line? It should look more like the code pointed above, or `youtube-dl --format "bestvideo[vcodec^=avc1]height=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=1080]+bestaudio/bestvideo[vcodec^=avc1][height<=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/best" "https://www.youtube.com/watch?v=GJ31v-7g4Qo"`.

PeerTube seeks to import the best quality available, with some constraints. Recently (3.1 and above) we added codec filters since per #3499 HDR videos used in vp9.2 and av1 videos result in a shifted color space. Usually this color space change starts with 1080p sources, hence the 720p selected import.

Is the previous version of PeerTube you ran anterior to 3.1-rc1? That might explain the difference of results. I also assume you enabled 1080p as a target transcoding resolution in your instance settings.

**Comment by sunknudsen** [comment] 2021-07-08 15:21
@rigelk Thanks for allocating time to this issue.

In the context of publishing to PeerTube, I’m just a content creator.

I believe content creators should not be aware of this technical stuff. That said, I am also a developer.

As a content creator, before updating to `3.2.1`, importing videos from YouTube imported 1080P content which looked great (at least on macOS) and streamed fine.

Why is 720P version chosen after update? This is a significant drop in quality for viewers.

Btw, I believe my content is not transcoded given selected config.

Thanks for helping out!

![Screen Shot 2021-07-08 at 11 19 18 AM](https://user-images.githubusercontent.com/2117655/124948073-e796b400-dfff-11eb-9c14-18308f7db6bb.png)

**Comment by rigelk** [comment] 2021-07-08 15:31
> Btw, I believe my content is not transcoded given selected config.

Indeed it is not! Thanks for that precision, as that changes my answer:

In your case PeerTube has no indication of which source height to look for as a reflection of the maximal quality of the source, and uses a default cap of 720p: https://github.com/Chocobozzz/PeerTube/blob/develop/server/helpers/youtube-dl.ts#L117

Why do we cap our resolutions? YouTube and other import sources have sometimes high resolutions that might strain the CPU, or be unfit for regular streaming. We thus need to cap our downloaded resolution.

In your case, you apparently want that default to be 1080p, which requires to enable the 1080p transcoding target with the current PeerTube version.

**Comment by sunknudsen** [comment] 2021-07-08 15:43
> Indeed it is not! Thanks for that precision, as that changes my answer:

As you mentioned, context is helpful. Sorry I didn’t mention all of this earlier.

> In your case PeerTube has no indication of which source height to look for as a reflection of the maximal quality of the source, and uses a default cap of 720p: https://github.com/Chocobozzz/PeerTube/blob/develop/server/helpers/youtube-dl.ts#L117

👍

> Why do we cap our resolutions? YouTube and other import sources have sometimes high resolutions that might strain the CPU, or be unfit for regular streaming. We thus need to cap our downloaded resolution.

As usual, great engineering decision. 🙌

> In your case, you apparently want that default to be 1080p, which requires to enable the 1080p transcoding target with the current PeerTube version.

Oh, I guess that is what has changed! I didn’t change config before or after update so I was puzzled.

If I select 1080P, will this trigger transcoding of already transcoded content (which would likely impact video quality)?

Again, thanks for helping out!

**Comment by rigelk** [comment] 2021-07-08 15:48
> If I select 1080P, will this trigger transcoding of already transcoded content (which would likely impact video quality)?

No, thus far all transcoding settings apply only to future videos. The import should be done again or the file/a resolution added via https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/tools.md#create-import-video-file-jobjs

**Comment by sunknudsen** [comment] 2021-07-08 16:04
@rigelk Sorry, I realize my question was not precise enough.

I meant, when importing future videos from YouTube which have already been transcoded by YouTube, will PeerTube transcode them again (once I enable 1080P in config)?

That would result in double transcoding which would likely impact video quality.

**Comment by rigelk** [comment] 2021-07-08 16:17
> I meant, when importing future videos from YouTube which have already been transcoded by YouTube, will PeerTube transcode them again (once I enable 1080P in config)?

In general, the source is not transcoded if it matches the proper codecs, bitrates, etc. In all likelyhood it will not get transcoded.

**Comment by sunknudsen** [comment] 2021-07-08 17:42
> In general, the source is not transcoded if it matches the proper codecs, bitrates, etc. In all likelyhood it will not get transcoded.

Sounds promising! I selected 1080P and ran a test.

Import is currently stuck at “The video is being imported, it will be available when the import is finished.”.

```console
$ ps ax | grep youtube-dl
31432 ?        S      0:05 python /var/www/peertube/versions/peertube-v3.2.1/node_modules/youtube-dl/bin/youtube-dl -f bestvideo[vcodec^=avc1][height=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=1080]+bestaudio/bestvideo[vcodec^=avc1][height<=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/best -o /var/www/peertube/storage/tmp/7a0ee9895603fa55471e37c6f3beb29aad97a00a28fa7dd2798ef4310bf7ac46-import http://www.youtube.com/watch?v=GJ31v-7g4Qo
```

**Comment by sunknudsen** [comment] 2021-07-08 17:46
> In general, the source is not transcoded if it matches the proper codecs, bitrates, etc. In all likelyhood it will not get transcoded.

Sounds promising! I enabled “1080p” in “Resolutions to generate per enabled format” and imported video from YouTube.

Import has been stuck at “The video is being imported, it will be available when the import is finished.” for a while (much longer than usual).

```console
$ ps ax | grep youtube-dl
31432 ?        S      0:05 python /var/www/peertube/versions/peertube-v3.2.1/node_modules/youtube-dl/bin/youtube-dl -f bestvideo[vcodec^=avc1][height=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=1080]+bestaudio/bestvideo[vcodec^=avc1][height<=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/best -o /var/www/peertube/storage/tmp/7a0ee9895603fa55471e37c6f3beb29aad97a00a28fa7dd2798ef4310bf7ac46-import http://www.youtube.com/watch?v=GJ31v-7g4Qo
```

Would you happen to know what I am doing wrong?

Thanks again for helping out!

**Comment by rigelk** [comment] 2021-07-08 20:56
> Would you happen to know what I am doing wrong?

IMHO you are not doing anything wrong. How has the situation developed?

**Comment by sunknudsen** [comment] 2021-07-08 21:03
@rigelk I ran `sudo kill 31432` and re-imported video.

Import worked… but then, I enabled `240p`, `360p`, `480p` and `720p` resolutions (a few viewers are watching the privacy guides from countries with low bandwidth connections).

I deleted video and tried import again to trigger transcoding and, this time, ffmpeg hung again.

Had to kill process multiple times (likely because of one subprocess per resolution).

**Comment by Chocobozzz** [comment] 2021-12-03 14:09
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/3987

**Closed by Chocobozzz** 2021-12-03 14:09 UTC
Labels: Type: Discussion :thought_balloon:, Component: Import

**Comment by mj-saunders** [comment] 2021-12-06 20:27
Looking at `getYoutubeDLVideoFormat` in `helpers/youtube-dl/youtube-dl-cli.js`, am I right in saying that if no resolutions are set in the `VOD Transcoding` web ui config, that the max resolution is in fact 720p, and not the maximum resolution available?

According the the `VOD` config page, `The original file resolution will be the default target if no option is selected.`

Also, even when setting e.g. `1080p` explicitly in the webui config `720p` was the max resolution that got downloaded in my test. I can confirm that changing the hardcoded `720` value in `getYoutubeDLVideoFormat` to `1080` helped, but obviously this is not a real solution.

I would have thought that setting in the config would have been enough to bypass the `720` cap, but apparently not. I don't quite understand why.
