### ISSUE TITLE
SEO improvements

### ISSUE THREAD

**Issue by Zig-03** [Chocobozzz/PeerTube#1080] opened 2018-09-17 15:12 UTC
_SEO - Search Engine Optimization_

The thing is that almost none of the instances/video titles/content is discoverable by SEs (Search Engines). 
For example, there is an instance called **peertube.social**, and let's say we need to find a channel called "chriswere" so if we search for:
["chriswere peertube social"](https://duckduckgo.com/?q=chriswere+peertube+social) - we get no results. 

Let's be more exact and add 2 more keywords from [this](https://peertube.social/videos/watch/13ce5139-06f5-4c4b-9289-426d588d2836) video of ()chriswere:
["chriswere peertube social Chromium BSU"](https://duckduckgo.com/?q=chriswere+peertube+social+Chromium+BSU) - zero results.

To fix this (at least for now), this article should do: https://backlinko.com/on-page-seo (this is a general purpose article, not everything applies to peertube, but most of it I'd say)

**Comment by rigelk** [comment] 2018-09-17 18:26
We're essentially missing custom video urls, if I get the gist of this page.

**Comment by Zig-03** [comment] 2018-09-17 19:58
@rigelk a ctr+u on a video page reveals that there are no header like H1, H2, H3. So there could be more missing steps.

Also this file is weird to me https://peertube.social/robots.txt
I don't know how crawlers interpret this:

> User-agent: *
> **Disallow: ' '**

After Disallow it's usually a link or a path or nothing https://moz.com/learn/seo/robotstxt 

So perhaps bots aren't even allowed to enter and crawl these website?

**Comment by rigelk** [comment] 2018-09-22 10:59
I have changed the html tag of the video title to `<h1>` on the video view, and attributes of miniatures now include the title in the `alt` attribute.

**Comment by Chocobozzz** [comment] 2018-09-25 08:54
I'm reopening, because we still have SEO issues. For example, we need to index only local videos/accounts/video channels. 

Moreover, google does not index our videos because "Google chose different canonical than user".

**Comment by BO41** [comment] 2018-11-13 11:32
non video pages are missing opengraph/twitter tags and a canonical URL.
and not found urls are **not** returning a `404` status code

**Comment by BO41** [comment] 2018-11-13 15:35
a nice thing to add would be another opengraph tag
>`video:tag` - string array - Tag words associated with this movie.

**Comment by Zig-03** [comment] 2018-12-02 20:10
We need H tags as well. <H1> for the each video title and <H2> for each video description. 

BTW right now comments aren't displayed when viewing the page source, was this intended to be like this?

**Comment by fflorent** [comment] 2019-01-27 13:35
I can confirm that's an issue for video makers who want to be present to Peertube (mostly because Youtube ). SEO will lower the barrier for those who don't see the advantages of Peertube (yet).

**Comment by Chocobozzz** [comment] 2019-05-31 13:36
PeerTube should be properly indexed now. Closing this issue.

If you notice bugs, or ways to improve peertube SEO please create another issue.

**Closed by Chocobozzz** 2019-05-31 13:36 UTC
Labels: Priority: Medium, Status: In Progress :soon:, Type: Enhancement :sparkles:

**Comment by k09i71** [comment] 2020-05-20 08:37
SEO is still very bad. I was thinking that we might need to use `rel=canonical`. 

> The idea is simple: if you have several similar versions of the same content, you pick one “canonical” version and point the search engines at it. This solves the duplicate content problem where search engines don’t know which version of the content to show in their results.

https://yoast.com/rel-canonical/

> Cross-domain canonical URLs
> Perhaps you have the same piece of content on several domains. There are sites or blogs that republish articles from other websites on their own, as they feel the content is relevant for their users. In the past, we had websites republishing articles from Yoast.com as well (with express permission), but if you had looked at the HTML of every one of those articles you’d found a rel=canonical link pointing right back to our original article. This means all the links pointing to their version of the article count towards the ranking of our canonical version. They get to use our content to please their audience, and we get a clear benefit from it too. Everybody wins.

In our case, each video is indexed by the many instances that are available and I believe this confuses search engines. Search engines don't know who should have the most "priority".

So how should we do this? If instance A has a certain video, then all the other instances that have that video on their instance should add a `rel=canonical` which will point to the video hosted on instance A.


I'm not a master in SEO, but this seems right for our use case.

**Comment by Chocobozzz** [comment] 2020-05-20 08:39
@k09i71 It's already the case:

```
curl https://peertube.cpy.re/videos/watch/04af977f-4201-4697-be67-a8d8cae6fa7a

...
<link rel="canonical" href="https://peertube2.cpy.re/videos/watch/04af977f-4201-4697-be67-a8d8cae6fa7a" />
...
```

**Comment by k09i71** [comment] 2020-05-20 09:01
@Chocobozzz sorry by bad.

After taking another look at it, I can see that you don't have any h1 and h2 (which are critical) in the html version of the page. As someone has pointed this above and this is how Vimeo is doing it as well:
- H1 for the video title
- H2 for description
- H3 for channel name and account name
- H4 or `<p>` for the section which includes this info:

> Privacy Public
> Origin instance video.latavernedejohnjohn.fr
> Originally published 25 February 2018
> etc..
- and `<p>` for everything else, including comments (if you wanna index them)

Check this video's page source out https://vimeo.com/88385603 and you'll see that their html source is much richer than our pages.

**Comment by Chocobozzz** [comment] 2020-05-20 09:27
We have a SPA so yes, you won't see HTML using curl. Google bot should interpret JS and correctly render the page. We already use `h1` for video title and inject the video title and description in the meta tags of the HTML page.

I'm not sure to understand what do you mean with *SEO is still very bad.*.

**Comment by creasysee** [comment] 2022-08-19 10:36
> curl https://peertube.cpy.re/videos/watch/04af977f-4201-4697-be67-a8d8cae6fa7a

Hi, all!
I found that Peertube instance has two (more?) pages for each video:
 - like https://peertube.cpy.re/videos/watch/04af977f-4201-4697-be67-a8d8cae6fa7a
 - like https://peertube.cpy.re/w/1zywKcr1ChzL7R9rG6yCnq
But only the second link displayed in search results, trending, discover, etc... pages, not the first.

So, why the rel=canonical meta tag point to the first link?

I understand, now is all correct, duplicates has identical canonical meta, it's ok, the question only is why the first link, not second?

**Comment by creasysee** [comment] 2022-08-19 11:02
> I found that Peertube instance has two (more?) pages for each video:

I found the third link:
https://peertube.cpy.re/videos/embed/04af977f-4201-4697-be67-a8d8cae6fa7a

And this page doesn't have canonical rel link.

**Comment by Chocobozzz** [comment] 2022-09-07 14:33
Hello,

For historical reason we use the first URL (`videos/watch`) as canonical URL/ActivityPub ID but in the web interface we prefer shorter URLs. It's the reason why the SPA changes the first URL to the second one.

I'll add the canonical tag in embed too.
