### ISSUE TITLE
Allow uploads to be resumed

### ISSUE THREAD

**Issue by conferences-gesticulees** [Chocobozzz/PeerTube#324] opened 2018-03-06 09:32 UTC
Uploading videos take hours with most connections available today. Waiting for hours to get nothing because the connection breaks for a couple minutes, the server gets restarted, or a power failure at 5am is highly frustrating.

Users should be able to resume their uploads. Ideally, it should be possible to resume a partial upload. At the very least, it should be possible to complete the publishing process after an upload is done. For example if an error happens during the processing stage, users should not have to upload the whole video again.

A checksum of the bytes already uploaded could be compared to ensure the local file has not been modified in the meantime.

Partial uploads should not be kept on the server indefinitely. I guess keeping them for 10 days would be long enough.

**Comment by MayeulC** [comment] 2018-03-21 12:36
How about uploading the video with webtorrent as well (with the current way as a fallback)? It could even open up some interesting functionalities down the road, like allowing the video to be watched before it's completely transferred, and maybe helping pave the road to livestreaming :)

**Comment by rigelk** [comment] 2018-03-21 22:05
@MayeulC actually uploading the video with WebTorrent would mean uploading the video with a WebRTC data channel to the server and using BitTorrent in it to declare (creating a torrent) and then transfer the file. WebRTC acts as a mere transport layer for a BitTorrent session whose goal is to share a file. The first problem is the fact that torrents are immutable: it prevents livestreaming (see issue #151). In our case the file is a video, but what prevents a client from declaring a torrent for other file types? The server should be able to check the file conforms to what a video is, thus downloading the video in its entirety anyway before forwarding the declared torrent. So I'm afraid using WebTorrent for the upload wouldn't bring anything, except added complexity.

**Comment by JigmeDatse** [comment] 2018-06-01 06:55
@rigelk I've been thinking about this feature.  The underlying .torrent could potentially be uploaded, but to do so would require the local generation of the .torrent file.  Now I'm not sure if this is a possibility or not with how things are currently designed.  

From my understanding the only way that would allow that, without someone manually creating the torrent locally than uploading it (and seeding it) would be to try to do it with JavaScript in the browser.  

I don't know if that is a feasible way to do things or not either.  But if there were the option of using the torrent protocol to upload, that could allow for the creation of clusters.  Without that, I think the issues I've had with being able to watch videos will probably continue, as I suspect that the limited numbers of peers is a significant factor.  

It is also possible that the peers that do exist for a given video with performance issues are behind a "too slow connection."

**Comment by Chocobozzz** [comment] 2018-06-01 07:04
>  Without that, I think the issues I've had with being able to watch videos will probably continue, as I suspect that the limited numbers of peers is a significant factor.

Please if you have playback problems on peertube create an issue so we can investigate.

**Comment by rigelk** [comment] 2018-06-01 07:06
We should not mix up things in this issue. Correct me if I'm wrong, but there are two options considered so far:

1. keep it simple by improving the actual HTTP upload mechanism. Resumable file uploads are not something out of the ordinary, and there seem to be quite a few libraries out there: https://github.com/23/resumable.js/ , https://tus.io/ − and even integrations like https://uppy.io/
2. go a step further, with a client (in the browser or out of it) creating a torrent and seeding it.

Frankly, I think 1. is way more realistic, since 2. complexifies things a lot.

**Comment by JigmeDatse** [comment] 2018-06-01 18:58
There is a third option:

3. allow the uploading of a seeded torrent file.  

I don't know the code base at all, so whether that is an option that ends up as "even more complex" or "less complex" I have no idea.  The more I'm seeing the community, and the development team, the more I'm leaning toward staying with YouTube and Vimeo...

**Comment by rigelk** [comment] 2018-06-01 19:14
@JigmeDatse Don't misunderstand me. I'm merely trying to give hints as to  whether or not this is easy, not refusing any option, just so that we can prioritize ways to solve the problem best. Whichever the solution, if you want to get to know the codebase to implement it yourself, we'll be more than willing to help. I don't think you'll ever be given that much by YouTube's.

**Comment by JigmeDatse** [comment] 2018-06-01 21:11
I don't believe I am misunderstanding you.  It's not merely comments to me, but I have seen repeatedly comments of "we don't want to do this."  You're quite right that I'd never be given the right to "rewrite" YouTube, and call it YouTube, but I also wouldn't see bickering between a developer and users ever with YouTube or Vimeo.  

Perhaps the problem isn't so much that you *disagree* with people, but that you present roadblocks with no indication of any effort on your (or any other dev member) interest in helping to find them.  To *you* that may be "merely trying to give hints," to most people who aren't already involved, this is *probably* a strong indication of "we won't do this, unless you are willing and able to do it yourself."  

Which to me means "please feel free to fork, because you're going to basically be doing that anyway."

**Comment by JigmeDatse** [comment] 2018-06-01 21:13
I think you've made my decision for me.  Thanks for the effort to be "more than willing to help." as you've helped enormously.  I'm going to go back to seeing about MediaGoblin where "more than willing to help" was *never* mentioned, they just proved it by saying, "oh yeah, that's something to fix..." and they went ahead and fixed it.  If it *was* something which required more than that they *did* work to do that.  I don't have the time or energy to try to work with your team...

**Comment by Booteille** [comment] 2018-11-10 22:49
Maybe we should continue to discuss about how to fix this issue.
I really think we should have the ability to resume upload and in the first instance make it work simple so we can then take our time to think about a more sophisticated way to do that.

**Comment by filmaidykai** [comment] 2019-03-22 23:17
Or maybe is possible to upload file straight to folder without web browser with ftp client  like filezila?

**Comment by xcffl** [comment] 2019-07-09 12:03
I would like to help with introducing resumable.js and implement this.

**Comment by rigelk** [comment] 2020-01-11 10:27
@xcffl if you are still around, I've come down to https://github.com/kukhariev/ngx-uploadx to the client part of the upload process, and https://github.com/kukhariev/node-uploadx for the server part receiving the chunks. I'll be giving it a stab in the next weeks if all is well, to see if that stack is statisfying. You can have a try at it too if you want :slightly_smiling_face:

**Comment by xcffl** [comment] 2020-01-11 11:34
> @xcffl if you are still around, I've come down to https://github.com/kukhariev/ngx-uploadx to the client part of the upload process, and https://github.com/kukhariev/node-uploadx for the server part receiving the chunks. I'll be giving it a stab in the next weeks if all is well, to see if that stack is statisfying. You can have a try at it too if you want 🙂

Great to hear that! That's definitely helpful.

I've realized that PeerTube is not exactly suitable for my use case, so I might not continue to contribute here.

**Comment by xcffl** [comment] 2020-03-01 07:13
OK, I'm coming back to this again. If there is anything I can help I may have a look.

**Comment by Salmon-Bard** [comment] 2020-07-07 10:36
I have used resume.js with a node angular project and it was easy to add to main project with webpack. here is the approach I used
https://morioh.com/p/8f10c2038aca

I may give it a try integrating with Peertype uploader. 
@rigelk Is there still interest in adding this feature?? I do not waist time if not planned to be mainlined???

**Comment by rigelk** [comment] 2020-07-07 10:41
@Salmon-Bard there is still interest in this feature, although I would suggest you use the above module.

**Comment by Salmon-Bard** [comment] 2020-07-07 10:54
> @xcffl if you are still around, I've come down to https://github.com/kukhariev/ngx-uploadx to the client part of the upload process, and https://github.com/kukhariev/node-uploadx for the server part receiving the chunks. I'll be giving it a stab in the next weeks if all is well, to see if that stack is statisfying. You can have a try at it too if you want

There is something confusing as your referring to both client and server parts with the same link  !!!

**Comment by rigelk** [comment] 2020-07-07 11:06
> There is something confusing as your referring to both client and server parts with the same link !!!

`ngx-uploadx` != `node-uploadx`

> looks much simpler to implement

How so? Its server implementation example is shallow at best.

**Comment by Salmon-Bard** [comment] 2020-07-07 11:51
Thanks for the clarification. 

I th 

> How so? Its server implementation example is shallow at best.

By shallow you mean less features and hooks to work with. But maybe we do not want to alert the current Peertube server side processes handling files and only want to work on uploading client resume events with same events triggers and hooks.

I'm looking for a simple solution that will not require rewrting most of the current code around uploading and storage handling.
In all cases I will take a deeper look into **ngx-upload** and do some testing.

**Comment by ldexterldesign** [comment] 2020-08-02 02:06
Also, an error notification detailing why the upload failed would be better than throwing the user back to [the upload view/state]. Unfortunately, I'm currently on a 3MB connection and spent the past evening trying to upload a ~400MB file. I must have attempted it 10-20 times and now I'm giving up. I'm still not sure why it keeps failing 🤷‍♂️.

Sincerely

[the upload view/state]:
<img width="1904" alt="Screenshot 2020-08-02 at 03 01 17" src="https://user-images.githubusercontent.com/1715809/89113737-a8192c80-d46c-11ea-9644-383555285722.png">

**Comment by techied** [comment] 2020-08-24 23:00
> We should not mix up things in this issue. Correct me if I'm wrong, but there are two options considered so far:
> 
> 1. keep it simple by improving the actual HTTP upload mechanism. Resumable file uploads are not something out of the ordinary, and there seem to be quite a few libraries out there: https://github.com/23/resumable.js/ , https://tus.io/ − and even integrations like https://uppy.io/
> 2. go a step further, with a client (in the browser or out of it) creating a torrent and seeding it.
> 
> Frankly, I think 1. is way more realistic, since 2. complexifies things a lot.

I've played around with both Uppy and Tus and there's quite a lot you can do with them (Uppy in particular could be used to add support for sources like Google Drive, Dropbox, Onedrive, etc. which currently requires a publicly accessible URL for link import, though that's another discussion).

More importantly, chunked uploading with Tus also has the added benefit that uploads work behind more restrictive proxies like Cloudflare which has a max request size of 100MB on the free plan. More than 200MB, you're looking at enterprise pricing.

**Comment by MayeulC** [comment] 2020-08-24 23:27
Well, this *might* come as a by-product of livestreaming, depending on how it is to be implemented, to reference my first comment ^^"

**Comment by jeena** [comment] 2020-11-22 03:52
I think at least a error message in the UI when a video upload failed would be a good first step. I was confused for hours about it because the UI just goes back to the "Please choose a file" state and then I thought I accidentally closed the tab (uploading takes about one hour and I keep using my browser). But when I looked in the browser console there are error messages about it. The wifi seems really flaky here at the hotel so it happens often that I need to reupload a video 5 or 7 times before it really appears on my instance. This means a full day of trying to upload a 20 minutes video over and over manually.

![error](https://user-images.githubusercontent.com/151764/99893294-806efe00-2cc1-11eb-922f-8042f8f6c220.png)

**Comment by rigelk** [comment] 2020-12-03 14:07
@ldexterldesign @jeena I added a way for us to display helpful (hopefully) messages and a retry button while not throwing users out of their upload form, in #3347.

**Comment by pravi** [comment] 2021-01-26 17:30
Another option could be allowing the torrent upload to use the peertube tracker for uploads as well. I tried adding the tracker of the instance to my torrent client but it gave an error no such hash or something. So if the torrent upload option guides the user to add the tracker to the torrent and once the torrent file is uploaded, the peertube bit torrent tracker should list the torrent. When I tried to upload a torrent I just created, the server would never see my seed and my client showed no peers.

**Comment by pravi** [comment] 2021-01-26 17:52
I think the idea used in https://github.com/subins2000/WebDrop could be a good fit here.

**Comment by MayeulC** [comment] 2021-01-26 21:06
@pravi, couldn't you manually add your peertube server as a pair with your torrent client?

You could also try to add some open trackers to your torrent before importing it.

**Comment by subins2000** [comment] 2021-01-27 18:25
@pravi @MayeulC  It seems adding the peertube WebTorrent tracker to the torrent doesn't help. It gives a 403 Forbidden. `wss://peertube.debian.social/tracker/socket` is one of those I tried. Test it out in this [web torrent client](https://btorrent.xyz/)

Testing on the debian Social PeerTube instance, the torrent upload doesn't work for 1 seed only torrents. I tried combo of many trackers too. But this seems to need a new issue on its own. From looking through the code I understand WebTorrent itself is used for the ImportVideoFromTorrent plugin, yet it doesn't work so well, all my attempts reached at `Webtorrent download timeout.`

**Comment by rigelk** [comment] 2021-01-27 18:46
@subins2000 it's on purpose, otherwise anyone could use any PeerTube instance as a tracker for any kind of torrent.

**Comment by subins2000** [comment] 2021-01-27 19:23
@rigelk Yes, public WebTorrent trackers [can be used for general purpose WebRTC apps](https://github.com/subins2000/p2pt) too apart from torrenting, there are many usecases!

**Closed** 2021-05-10 09:13 UTC
Labels: Status: In Progress :soon:, Type: Enhancement :sparkles:

**Comment by rigelk** [comment] 2021-05-10 12:19
The feature will appear in the next release, and is already documented at https://docs.joinpeertube.org/api-rest-reference.html#tag/Video-Upload; we're looking forward to your feedback on the implementation in the upcoming release candidate!
