### ISSUE TITLE
Add Option [View subscribers] 

### ISSUE THREAD

**Issue by AnonymousWebHacker** [Chocobozzz/PeerTube#4374] opened 2021-09-04 01:34 UTC
I do not think it is an option available in yotube, but in Peertube it would be very good to have it.

It would be great to be able to see the subscribers of each of our channels and not only see reports in the notifications

**Comment by Chocobozzz** [comment] 2021-09-06 06:03
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/2023

**Closed by Chocobozzz** 2021-09-06 06:03 UTC
