### ISSUE TITLE
Studio Feature: Publish customized video as New Video 

### ISSUE THREAD

**Issue by smilekison** [Chocobozzz/PeerTube#5162] opened 2022-08-01 06:42 UTC
### Describe the problem to be solved

When using studio feature on PeerTube, I can cut the video to have new start and new end time. Thus, customizing the video to have shorter length. This is an important feature. But, When I save the video, it overwrites the existing video with customized video length. 
**Request:** Able to upload customized video as new video.
**Problem:** There are times when i want to have both long version and short version of same video. But, it is more work to upload the video separately and updating one video to have short length. 

### Describe the solution you would like

I think inside Studio setting, 
We have two buttons:
**Run Video edition:** Publishes the current video with new customized changes.
**Publish as New Video:** New video will be published with all existing metadata with new changed setting.

![image](https://user-images.githubusercontent.com/24309222/182087982-b5d2b1d9-131b-495f-8134-a00e01029186.png)

**Comment by Chocobozzz** [comment] 2022-08-01 08:23
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/5107

**Closed by Chocobozzz** 2022-08-01 08:23 UTC
