### ISSUE TITLE
Multiple audio tracks

### ISSUE THREAD

**Issue by DavidLibeau** [Chocobozzz/PeerTube#1342] opened 2018-10-23 12:33 UTC
For acessibility purpose (audio description) and internationalization (multi language video), I think it would be cool to add several audio tracks to a video.

**Comment by Chocobozzz** [comment] 2018-12-13 14:54
Thanks for the issue but it is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/1342

**Closed by Chocobozzz** 2018-12-13 14:54 UTC
Labels: Type: Duplicate :loop:, Type: Enhancement :sparkles:
