### ISSUE TITLE
Live Stream with object storage

### ISSUE THREAD

**Issue by stevespaw** [Chocobozzz/PeerTube#5658] opened 2023-02-28 15:04 UTC
### Describe the current behavior

I have Peertube 5.01 working pretty well (very large files still do not move)  with object storage (s3). But now livestreams do not work. What am I missing? is there a new setting in the YAML file? (setting object storage to false causes "LiveStream" to work properly)
I am sure I have missed something. Can anyone give me a direction to look?

Thanks!

### Steps to reproduce

1. object storage  = "true" - Livestreams do not display - no error in logs etc. and remote encoders show no error.
2. object storage  = "false" Livestreams display but are not using object storage or CDN.
3. This worked in version 4

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment] 2023-03-01 09:29
Hello,

Please paste the livestream URL so we can reproduce

**Comment by stevespaw** [comment] 2023-03-01 13:42
https://video3.shadow-technologies.com/w/1dvf64voab9hLry7c39BHZ
No ffmpeg errors, If I just change object storage=false. This stream pops up just fine. 
![image](https://user-images.githubusercontent.com/11045430/222155495-427a0675-eac1-4af4-a6c4-12f24f37ec0d.png)

**Comment by Chocobozzz** [comment] 2023-03-01 14:08
I would need you to stream in the live :)

**Comment by stevespaw** [comment] 2023-03-01 14:56
I am streaming it! That was a live screen grab from the encoder. It is going 24/7 right now for testing. I will repeat - if I just change object storage setting to false and restart PeerTube. This stream pop right in, now changes to anything else.

**Comment by Chocobozzz** [comment] 2023-03-01 15:01
Oup's sorry I did not understand. I thought the live stream did not work because of a network error or something like that on client side.

Then please stop your livestream, wait a few minutes and stream again. Wait again ~30 seconds and paste or send me PeerTube server logs

**Comment by stevespaw** [comment] 2023-03-01 15:40
This is the section of starting and stopping the stream - no errors on the encoder, It thinks the stream is fine.

Mar 01 09:37:00 [video3.shadow-technologies.com:443] 2023-03-01 15:37:00.486 info: 172.124.0.0 - - [01/Mar/2023:15:37:00 +0000] "POST /api/v1/metrics/playback HTTP/1.1" 204 - "https://video3.shadow-technologies.com/w/mFkzdpvD8Ws1gkaD7g4Nmv" "Chrome"
Mar 01 09:37:10 [video3.shadow-technologies.com:443] 2023-03-01 15:37:10.048 info: 172.18.0.1 - - [01/Mar/2023:15:37:10 +0000] "GET / HTTP/1.1" 200 17208 "-" "Mozilla (CloudronHealth)"
Mar 01 09:37:10 12:M 01 Mar 2023 15:37:10.069 * 10 changes in 300 seconds. Saving...
Mar 01 09:37:10 12:M 01 Mar 2023 15:37:10.071 * Background saving started by pid 555
Mar 01 09:37:10 555:C 01 Mar 2023 15:37:10.115 * DB saved on disk
Mar 01 09:37:10 555:C 01 Mar 2023 15:37:10.117 * RDB: 0 MB of memory used by copy-on-write
Mar 01 09:37:10 12:M 01 Mar 2023 15:37:10.171 * Background saving terminated with success
Mar 01 09:37:11 [video3.shadow-technologies.com:443] 2023-03-01 15:37:11.022 info: Cleanup TMP live files from filesystem of /app/data/storage/streaming-playlists/hls/01bef261-f73f-447a-864e-ab10f03ef52f.
Mar 01 09:37:12 [video3.shadow-technologies.com:443] 2023-03-01 15:37:12.474 info: rtmp://127.0.0.1:1935/live/72b6b295-95b6-4954-914b-6fd29984deee probing took 1438 ms (bitrate: 4500000, fps: 30, resolution: 1080)
Mar 01 09:37:12 [video3.shadow-technologies.com:443] 2023-03-01 15:37:12.479 info: Will mux/transcode live video of original resolution 1080. {
Mar 01 09:37:12 "allResolutions": [
Mar 01 09:37:12 1080
Mar 01 09:37:12 ]
Mar 01 09:37:12 }
Mar 01 09:37:12 [video3.shadow-technologies.com:443] 2023-03-01 15:37:12.496 error: Cannot handle sessions. {
Mar 01 09:37:12 "err": {
Mar 01 09:37:12 "stack": "TypeError: Cannot read properties of null (reading 'replace')\n at replaceByBaseUrl (/app/code/server/dist/server/lib/object-storage/urls.js:40:20)\n at getHLSPublicFileUrl (/app/code/server/dist/server/lib/object-storage/urls.js:22:12)\n at VideoStreamingPlaylistModel.getMasterPlaylistObjectStorageUrl (/app/code/server/dist/server/models/video/video-streaming-playlist.js:129:57)\n at VideoStreamingPlaylistModel.getMasterPlaylistUrl (/app/code/server/dist/server/models/video/video-streaming-playlist.js:119:29)\n at VideoStreamingPlaylistModel.assignP2PMediaLoaderInfoHashes (/app/code/server/dist/server/models/video/video-streaming-playlist.js:113:40)\n at LiveManager.<anonymous> (/app/code/server/dist/server/lib/live/live-manager.js:351:22)\n at Generator.next (<anonymous>)\n at fulfilled (/app/code/server/node_modules/tslib/tslib.js:115:62)\n at runMicrotasks (<anonymous>)\n at processTicksAndRejections (node:internal/process/task_queues:96:5)",
Mar 01 09:37:12 "message": "Cannot read properties of null (reading 'replace')"
Mar 01 09:37:12 }
Mar 01 09:37:12 }

**Comment by stevespaw** [comment] 2023-03-01 16:10
Also just to add, I have tried with live transcoding on and off - no difference.

**Comment by Chocobozzz** [comment] 2023-03-02 07:34
Thanks! Then it's the same issue as https://github.com/Chocobozzz/PeerTube/issues/5559#issuecomment-1406153403

It is fixed in 5.1 (in RC at the moment)

**Closed by Chocobozzz** 2023-03-02 07:34 UTC
Labels: Status: Waiting for answer

**Comment by stevespaw** [comment] 2023-06-23 21:49
@Chocobozzz  This still does not work... :-(

**Comment by Chocobozzz** [comment] 2023-06-26 09:50
@stevespaw Can you explain what is not working and provide a live stream example please?

**Comment by stevespaw** [comment] 2023-06-29 21:31
Here is the current error when "object storage" is enabled. When the stream starts It goes "live" in the player with just the spinner and then it will error. The "published" video replay works just fine.
<img width="985" alt="image" src="https://github.com/Chocobozzz/PeerTube/assets/11045430/a5d9835a-f1c3-4f9b-a169-51e6fab5b911">

**Comment by stevespaw** [comment] 2023-06-29 21:33
`warn[6/29/2023, 4:30:02 PM] Client log: HLS.js error: networkError - fatal: false - fragLoadError
{
  "tags": [
    "client"
  ],
  "username": "shadow",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.43",
  "url": "https://video3.shadow-technologies.com/w/jJjNGoqXc5RXXuvmVnf2HC"
}
error[6/29/2023, 4:30:02 PM] Client log: Segment https://cdn3.shadow-technologies.com/streaming-playlists/hls/97ad52c2-7a51-4925-99ab-f6e5aed2f4b2/master.m3u8+V0+5 error.
{
  "tags": [
    "client"
  ],
  "username": "shadow",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.43",
  "stackTrace": "Hashes does not correspond for segment 0-000005.ts/(expected: 60dfffc4a4420f795e8dfcbf7925eff7df4980145825762d1836f3390e05e03a instead of b9355fcb3810f88d950ffec2a31506dac7171ab2708549a4fa71d8034d69092c)\nError: Hashes does not correspond for segment 0-000005.ts/(expected: 60dfffc4a4420f795e8dfcbf7925eff7df4980145825762d1836f3390e05e03a instead of b9355fcb3810f88d950ffec2a31506dac7171ab2708549a4fa71d8034d69092c)\n    at Object.<anonymous> (https://video3.shadow-technologies.com/client/en-US/2293.8591ea1f48e76966.js:1:155786)\n    at Generator.next (<anonymous>)\n    at e (https://video3.shadow-technologies.com/client/en-US/main.18895fd6dd4b2857.js:3:689431)\n    at c (https://video3.shadow-technologies.com/client/en-US/main.18895fd6dd4b2857.js:3:689633)\n    at i.invoke (https://video3.shadow-technologies.com/client/en-US/polyfills.737628ee7146c22a.js:1:68824)\n    at lt.run (https://video3.shadow-technologies.com/client/en-US/polyfills.737628ee7146c22a.js:1:64112)\n    at https://video3.shadow-technologies.com/client/en-US/polyfills.737628ee7146c22a.js:1:79108\n    at i.invokeTask (https://video3.shadow-technologies.com/client/en-US/polyfills.737628ee7146c22a.js:1:69444)\n    at lt.runTask (https://video3.shadow-technologies.com/client/en-US/polyfills.737628ee7146c22a.js:1:64752)\n    at H (https://video3.shadow-technologies.com/client/en-US/polyfills.737628ee7146c22a.js:1:71489)",
  "url": "https://video3.shadow-technologies.com/w/jJjNGoqXc5RXXuvmVnf2HC"`

**Comment by stevespaw** [comment] 2023-06-29 21:35
Again if I disable object storage - the live stream works as expected, but is not connected to the CDN, of course. = bad

**Comment by Chocobozzz** [comment] 2023-06-30 06:30
I would need to test a livestream myself: can you run a permanent live stream so I can debug it?

**Comment by stevespaw** [comment] 2023-06-30 15:33
Sure:
this one is set for replay: https://video3.shadow-technologies.com/w/jJjNGoqXc5RXXuvmVnf2HC
rtmp://video3.shadow-technologies.com:1935/live
4090aaa4-4815-4de1-8b17-9b74c0fbcb11
This is not recording: https://video3.shadow-technologies.com/w/4DGi6rQPRKF8cB5epCYDFZ
rtmp://video3.shadow-technologies.com:1935/live
8bc9e230-b4ca-43c5-bb5e-4891eaf75c5e

I am happy to set up a channel for you also on this instance for any testing.

Thanks

**Comment by stevespaw** [comment] 2023-07-12 16:54
@Chocobozzz  Thanks for looking at this, but the issue is still real. Our setup is s3 Object storage that is cached by the CDN. I did have a "PermaCache" setting enabled which pushed all s3 content to the CDN. After I disabled that (I was just testing that) the short replay of old video went away on the "Live". Now I have nothing but the swirling ring and eventually an HLS error when it goes live. But of course, the replay of the live, that I never saw, plays back perfect after the move to s3. _This is the real question/issue._ During "Live" the video only exists on the local instance, so it is disconnected from the CDN which is only looking at the s3 and the Player is still directed at s3. Somehow during "Live" the CDN and thus the (player still using the CDN address) need to be directed at the Local instance. Unless I am missing something......  This seems like a defect. It seems that there needs to be a way for the CDN to look at the local instance during live ??? Or to send the Live video to s3 during live...

**Comment by stevespaw** [comment] 2023-07-19 19:58
@Chocobozzz You led me down the correct path, My CDN was caching the endpoint URL, not the bucket URL. This worked fine for VOD, but not "live". The CDN could not find the live segments. (Which made me think that they were not there) After fixing that and adjusting the TTL I have success with live and CDN.
Thank you for your work and help on this!
