### ISSUE TITLE
Add a public Overview of a Playlist that doesn't automatically go to a video

### ISSUE THREAD

**Issue by 0lhi** [Chocobozzz/PeerTube#4881] opened 2022-03-26 20:25 UTC
**Describe the problem to be solved**

When linking a Playlist, it automatically sends you to it's first video:

https://video.ploud.fr/w/p/47zMgz44kevvDxHsRU87XT

This makes it inconvenient to get an overview of the videos that are available within the Playlist.

**Describe the solution you would like:**

Add a public link that's similar to the /my-library/video-playlists overview:

![Playlist](https://user-images.githubusercontent.com/74732674/160255704-26cf50da-90c1-41b7-9c6d-1edf84cf5af3.png)

**Comment by Chocobozzz** [comment] 2022-03-27 06:46
Spyro :smiling_face_with_three_hearts:

But it's a duplicate of https://github.com/Chocobozzz/PeerTube/issues/2672 :)

**Closed by Chocobozzz** 2022-03-27 06:46 UTC
