### ISSUE TITLE
About/Instance Statistics are not readable when using Dark theme

### ISSUE THREAD

**Issue by grondinm** [Chocobozzz/PeerTube#2244] opened 2019-11-14 12:48 UTC
Just upgraded my instance to v2. Looking great so far. Only issue is simply the stats are not readable when using the dark theme.

https://pixelfed.social/p/mgrondin/100574420690669568

Thank you

**Comment by Chocobozzz** [comment] 2019-11-14 13:11
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/2237

**Closed by Chocobozzz** 2019-11-14 13:11 UTC

**Comment by grondinm** [comment] 2019-11-15 01:33
Of course this was already reported and fixed. My apologies for not looking at the fixed issues before submitting. Thank you for all your work.
