### ISSUE TITLE
Links pointing to the local instance don't work when clicked

### ISSUE THREAD

**Issue by hylianux** [Chocobozzz/PeerTube#2520] opened 2020-02-26 15:57 UTC
**What happened?**

One can post links in the description and in the comment section of any video.  The problem is if that link points to a location on the same instance, the link will not work when clicked.

Links leading to *outside* locations work just fine.

Also worth noting - while in the edit screen of a video, the preview text containing the link to the local instance works if clicked... it only seems to stop working on the video page itself.

**What do you expect to happen instead?**

Clicking a link should make your browser redirect to wherever that link points to.

**Steps to reproduce:**

(General)
1. Edit a video's description, and add a link that points to any location within that local instance.
2. Add a link to the description that points to any outside location (I used duckduckgo.com)
3. Add a comment on the video with a link that points to any location within that local instance.
4. Add another comment on the video with a link that points to any outside location.
5. Click the links, and take note of which ones actually result in redirection.

(Full path)
1. Edit a video's description, and add a link that points to any location within that local instance.  Make sure that link is a full path to any video, playlist, or even the home page.
2. Add a comment on the video with a the same link(s).
3. Click the links in the preview page, and take note that they work.
4. Click update, and try to use the links on the video's display page, and take note that now they do not.

(Relative path)
1. Edit a video's description, and add a link that points to any location within that local instance.  Make sure that link is a relative path to any video, playlist, or even the home page.  Use markdown syntax `[Link Text](/path/to/stuff)`.
2. Click the links in the preview page, and take note that they work.
3. Click update, and try to use the links on the video's display page, and take note that now they do not.

(Easiest test)
1. Edit a video's description, and add this markdown: `[Test Link](/)`.  It's a relative path link leading to that instance's root/homepage.
2. Click the "preview text" version of the link to verify that it works.
3. Save the changes, and click the link on the video display page, and take note that now it does not work.

**Current workaround**

It's not ideal, but the only way these links work is if you right-click them and click "open".  Left-clicking will not work unless it points to an outside location.

**Additional information**

* PeerTube version or URL:2.1.0
* Browser name/version: All browsers
* NodeJS version:

* Link to browser console log if useful: **note**: No errors appear in the dev console.
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/): **note**: No errors appear in the server logs either.

**Comment by pprw** [comment] 2020-04-27 09:57
I noticed that too. Why it is not a bug?

**Comment by rigelk** [comment] 2020-04-27 10:37
@pprw because this is default behavior for the markdown library we use and not something we introduced.

**Comment by pprw** [comment] 2020-04-27 11:01
@rigelk Ok thanks for the explanation. 

Not being able to link to a another video of the same instance (or channel, or playlist, ...) is pretty annoying...

**Comment by hylianux** [comment] 2020-04-27 15:46
@rigelk if that is indeed true, then why do the links in the preview of the rendered markdown text work when you're editing it, but not on the main page?  What's different on the edit/update page vs the video page itself?

**Comment by Chocobozzz** [comment] 2020-05-06 12:21
Thanks for the issue. Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/d4eea028016092b36d9177616c9e6bb96df9abee

**Closed by Chocobozzz** 2020-05-06 12:21 UTC
Labels: Type: Bug :bug:, UI

**Comment by pprw** [comment] 2020-05-06 12:53
Thanks!
