### ISSUE TITLE
Can't install Peertube 6.2 on FreeBSD arm64

### ISSUE THREAD

**Issue by src386** [Chocobozzz/PeerTube#6502] opened 2024-07-22 20:57 UTC
### Describe the problem

Yeah I'm that guy with the most exotic setup ever that no one else hass.
Peertube worked fine until 6.2 as it fails at the `yarn install` step.
Command:
```
HOME=/data/peertube yarn install --production --pure-lockfile
```
Errors (most steps ommited):
```
[ 97%] Building CXX object CMakeFiles/node_datachannel.dir/src/web-socket-server-wrapper.cpp.o
[ 97%] Building CXX object CMakeFiles/node_datachannel.dir/src/main.cpp.o
[100%] Linking CXX shared library Release/node_datachannel.node
c++: warning: argument unused during compilation: '-static-libgcc' [-Wunused-command-line-argument]
c++: warning: argument unused during compilation: '-static-libstdc++' [-Wunused-command-line-argument]
ld: error: relocation R_AARCH64_ABS64 cannot be used against local symbol; recompile with -fPIC
>>> defined in /usr/lib/libcrypto.a(comp_err.o)
>>> referenced by comp_err.c
>>>               comp_err.o:(COMP_str_reasons) in archive /usr/lib/libcrypto.a

ld: error: relocation R_AARCH64_ABS64 cannot be used against local symbol; recompile with -fPIC
>>> defined in /usr/lib/libcrypto.a(comp_err.o)
>>> referenced by comp_err.c
>>>               comp_err.o:(COMP_str_reasons) in archive /usr/lib/libcrypto.a

ld: error: relocation R_AARCH64_ABS64 cannot be used against local symbol; recompile with -fPIC
>>> defined in /usr/lib/libcrypto.a(comp_err.o)
>>> referenced by comp_err.c
>>>               comp_err.o:(COMP_str_reasons) in archive /usr/lib/libcrypto.a

ld: error: relocation R_AARCH64_ADR_PREL_PG_HI21 cannot be used against symbol 'ASN1_OBJECT_free'; recompile with -fPIC
>>> defined in /usr/lib/libcrypto.a(a_object.o)
>>> referenced by x_x509a.c:149 (/usr/src/crypto/openssl/crypto/x509/x_x509a.c:149)
>>>               x_x509a.o:(X509_trust_clear) in archive /usr/lib/libcrypto.a

ld: error: relocation R_AARCH64_ADD_ABS_LO12_NC cannot be used against symbol 'ASN1_OBJECT_free'; recompile with -fPIC
>>> defined in /usr/lib/libcrypto.a(a_object.o)
>>> referenced by x_x509a.c:149 (/usr/src/crypto/openssl/crypto/x509/x_x509a.c:149)
>>>               x_x509a.o:(X509_trust_clear) in archive /usr/lib/libcrypto.a

ld: error: relocation R_AARCH64_ADR_PREL_PG_HI21 cannot be used against symbol 'ASN1_OBJECT_free'; recompile with -fPIC
>>> defined in /usr/lib/libcrypto.a(a_object.o)
>>> referenced by x_x509a.c:157 (/usr/src/crypto/openssl/crypto/x509/x_x509a.c:157)
>>>               x_x509a.o:(X509_reject_clear) in archive /usr/lib/libcrypto.a

ld: error: relocation R_AARCH64_ADD_ABS_LO12_NC cannot be used against symbol 'ASN1_OBJECT_free'; recompile with -fPIC
>>> defined in /usr/lib/libcrypto.a(a_object.o)
>>> referenced by x_x509a.c:157 (/usr/src/crypto/openssl/crypto/x509/x_x509a.c:157)
>>>               x_x509a.o:(X509_reject_clear) in archive /usr/lib/libcrypto.a

ld: error: relocation R_AARCH64_ABS64 cannot be used against local symbol; recompile with -fPIC
>>> defined in /usr/lib/libcrypto.a(x_x509a.o)
>>> referenced by x_x509a.c
>>>               x_x509a.o:(X509_CERT_AUX_it.local_it) in archive /usr/lib/libcrypto.a

ld: error: relocation R_AARCH64_ABS64 cannot be used against local symbol; recompile with -fPIC
>>> defined in /usr/lib/libcrypto.a(x_x509a.o)
>>> referenced by x_x509a.c
>>>               x_x509a.o:(X509_CERT_AUX_it.local_it) in archive /usr/lib/libcrypto.a

ld: error: relocation R_AARCH64_ABS64 cannot be used against local symbol; recompile with -fPIC
>>> defined in /usr/lib/libcrypto.a(x_x509a.o)
>>> referenced by x_x509a.c
>>>               x_x509a.o:(X509_CERT_AUX_seq_tt) in archive /usr/lib/libcrypto.a

ld: error: relocation R_AARCH64_ABS64 cannot be used against symbol 'ASN1_OBJECT_it'; recompile with -fPIC
>>> defined in /usr/lib/libcrypto.a(tasn_typ.o)
>>> referenced by x_x509a.c
>>>               x_x509a.o:(X509_CERT_AUX_seq_tt) in archive /usr/lib/libcrypto.a

ld: error: relocation R_AARCH64_ABS64 cannot be used against local symbol; recompile with -fPIC
>>> defined in /usr/lib/libcrypto.a(x_x509a.o)
>>> referenced by x_x509a.c
>>>               x_x509a.o:(X509_CERT_AUX_seq_tt) in archive /usr/lib/libcrypto.a

ld: error: relocation R_AARCH64_ABS64 cannot be used against symbol 'ASN1_OBJECT_it'; recompile with -fPIC
>>> defined in /usr/lib/libcrypto.a(tasn_typ.o)
>>> referenced by x_x509a.c
>>>               x_x509a.o:(X509_CERT_AUX_seq_tt) in archive /usr/lib/libcrypto.a

ld: error: relocation R_AARCH64_ABS64 cannot be used against local symbol; recompile with -fPIC
>>> defined in /usr/lib/libcrypto.a(x_x509a.o)
>>> referenced by x_x509a.c
>>>               x_x509a.o:(X509_CERT_AUX_seq_tt) in archive /usr/lib/libcrypto.a

ld: error: relocation R_AARCH64_ABS64 cannot be used against symbol 'ASN1_UTF8STRING_it'; recompile with -fPIC
>>> defined in /usr/lib/libcrypto.a(tasn_typ.o)
>>> referenced by x_x509a.c
>>>               x_x509a.o:(X509_CERT_AUX_seq_tt) in archive /usr/lib/libcrypto.a

ld: error: relocation R_AARCH64_ABS64 cannot be used against local symbol; recompile with -fPIC
>>> defined in /usr/lib/libcrypto.a(x_x509a.o)
>>> referenced by x_x509a.c
>>>               x_x509a.o:(X509_CERT_AUX_seq_tt) in archive /usr/lib/libcrypto.a

ld: error: relocation R_AARCH64_ABS64 cannot be used against symbol 'ASN1_OCTET_STRING_it'; recompile with -fPIC
>>> defined in /usr/lib/libcrypto.a(tasn_typ.o)
>>> referenced by x_x509a.c
>>>               x_x509a.o:(X509_CERT_AUX_seq_tt) in archive /usr/lib/libcrypto.a

ld: error: relocation R_AARCH64_ABS64 cannot be used against local symbol; recompile with -fPIC
>>> defined in /usr/lib/libcrypto.a(x_x509a.o)
>>> referenced by x_x509a.c
>>>               x_x509a.o:(X509_CERT_AUX_seq_tt) in archive /usr/lib/libcrypto.a

ld: error: relocation R_AARCH64_ABS64 cannot be used against symbol 'X509_ALGOR_it'; recompile with -fPIC
>>> defined in /usr/lib/libcrypto.a(x_algor.o)
>>> referenced by x_x509a.c
>>>               x_x509a.o:(X509_CERT_AUX_seq_tt) in archive /usr/lib/libcrypto.a

ld: error: relocation R_AARCH64_ABS64 cannot be used against local symbol; recompile with -fPIC
>>> defined in /usr/lib/libcrypto.a(x_val.o)
>>> referenced by x_val.c
>>>               x_val.o:(X509_VAL_it.local_it) in archive /usr/lib/libcrypto.a

ld: error: too many errors emitted, stopping now (use --error-limit=0 to see all errors)
c++: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [CMakeFiles/node_datachannel.dir/build.make:279: Release/node_datachannel.node] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:372: CMakeFiles/node_datachannel.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
ERR! OMG Process terminated: 2
prebuild ERR! build Error: Failed to build cmake with exit code 1
prebuild ERR! build     at ChildProcess.<anonymous> (/data/peertube/versions/peertube-v6.2.0/node_modules/node-datachannel/node_modules/prebuild/cma
```

Looks like it fails trying to build the dependency of a dependency.
Any help would be appreciated because Arm64/Aarch64 is a cheap way to have plenty of CPU cores and memory, which is useful for ffmpeg :)

### Additional information

* PeerTube version: 6.2
* NodeJS version: 21.7.3
* Ffmpeg version: 6.1
* Redis version: 7.2.4
* PostgreSQL version: 16.2
* Operating system: FreeBSD 14.1-RELEASE

**Comment by Chocobozzz** [comment] 2024-07-23 06:24
Hi,

Unfortunately it is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/6486

**Closed by Chocobozzz** 2024-07-23 06:24 UTC

**Comment by ltning** [comment] 2024-07-30 18:09
I'm getting this on FreeBSD 14.1-amd64 as well (not just arm64). Is this really the same issue as #6486 - which pertains to Alpine Linux?
Sorry for poking a dead horse here. :)
