### ISSUE TITLE
Newly added instance's videos should have their true publishing date

### ISSUE THREAD

**Issue by DavidLibeau** [Chocobozzz/PeerTube#594] opened 2018-05-28 01:02 UTC
* **PeerTube version or URL:** beta.6

* **What is the expected behaviour?**

Newly added instance's videos should have their true publishing date.

* **What do you see instead?**

When we follow a new instance, PeerTube seems to add all the videos of this instance to ours. The videos are added to Recently added and Trending tab. But, the videos should not have publishing time of "1 second", "2 minutes"… but the date when they were published on the host instance.

**Comment by Chocobozzz** [comment] 2018-05-28 06:48
I can't reproduce. Where do you see this date? And what was the instance you added?

**Comment by DavidLibeau** [comment] 2018-05-28 12:15
You can see it live here : https://videonaute.fr/videos/recently-added
You can see that all the videos are published "11h ago", but in fact, 11h hour ago I add the instance "thinkerview", and the videos were published days ago.

**Comment by Chocobozzz** [comment] 2018-05-28 16:57
Thanks, it should be fixed: https://github.com/Chocobozzz/PeerTube/commit/53a613171e5d3e2d31c04d85ed883dd9a37cf1fb

**Closed by Chocobozzz** 2018-05-28 16:57 UTC
Labels: Type: Bug
