### ISSUE TITLE
Problem playing videos with HLS

### ISSUE THREAD

**Issue by manalejandro** [Chocobozzz/PeerTube#3181] opened 2020-09-27 22:43 UTC
**What happened?**
Problem playing videos with HLS

**Steps to reproduce:**

1. We are using official docker image chocobozzz/peertube:develop-buster

2. We have next error with HLS player ![peertube-error](https://user-images.githubusercontent.com/8077120/94377590-5d8df680-0123-11eb-8aed-3ea0ba7f5a01.png)

**Additional information**
* PeerTube version or URL: [peertube.hatthieves.es](https://peertube.hatthieves.es)
* Browser name/version: Firefox Quantum 68.12.0esr (64-bit)
* NodeJS version: Native official image

**Comment by eggercomputerchaos** [comment] 2020-10-23 22:08
same issue here after upgrade to v2.4.0

following the logs during installation:
root@XXXXXXX:/var/www/peertube/versions/peertube-v2.4.0# sudo -H -u peertube yarn install --production --pure-lockfile
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
warning Resolution field "http-signature@1.3.4" is incompatible with requested version "http-signature@~1.2.0"
warning Resolution field "oauth2-server@3.1.0-beta.1" is incompatible with requested version "oauth2-server@3.0.0"
[3/5] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > @typescript-eslint/eslint-plugin@3.10.0" has unmet peer dependency "@typescript-eslint/parser@^3.0.0".
warning " > marked-man@0.7.0" has incorrect peer dependency "marked@^0.7.0".
[5/5] Building fresh packages...
$ test -n "$NOCLIENT" || (cd client && yarn install --pure-lockfile)
yarn install v1.21.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > file-loader@6.0.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > raw-loader@4.0.1" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > @ngx-i18nsupport/tooling@8.0.3" has incorrect peer dependency "@angular/common@^8.0.0".
warning " > @ngx-i18nsupport/tooling@8.0.3" has incorrect peer dependency "@angular/core@^8.0.0".
warning " > @ngx-loading-bar/http-client@5.1.0" has incorrect peer dependency "tslib@^1.10.0".
warning " > @ngx-loading-bar/router@5.1.0" has incorrect peer dependency "tslib@^1.10.0".
warning " > @ngx-meta/core@9.0.0" has incorrect peer dependency "@angular/core@>=9.0.0 <10.0.0".
warning " > @ngx-meta/core@9.0.0" has incorrect peer dependency "@angular/platform-browser@>=9.0.0 <10.0.0".
warning " > @ngx-meta/core@9.0.0" has incorrect peer dependency "@angular/platform-browser-dynamic@>=9.0.0 <10.0.0".
warning " > @ngx-meta/core@9.0.0" has incorrect peer dependency "@angular/router@>=9.0.0 <10.0.0".
warning " > @ngx-meta/core@9.0.0" has incorrect peer dependency "tslib@^1.10.0".
warning " > angular2-hotkeys@2.2.0" has incorrect peer dependency "@angular/core@^5.2.0 || ^6.0.0 || ^7.0.0 || ^8.0.0 || ^9.0.0".
warning " > angular2-hotkeys@2.2.0" has incorrect peer dependency "tslib@^1.10.0".
warning " > bootstrap@4.5.2" has unmet peer dependency "jquery@1.9.1 - 3".
warning " > bootstrap@4.5.2" has unmet peer dependency "popper.js@^1.16.1".
warning " > css-loader@3.6.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > extract-text-webpack-plugin@4.0.0-beta.0" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
warning " > html-loader@1.2.1" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > html-webpack-plugin@4.3.0" has unmet peer dependency "webpack@>=4.0.0 < 6.0.0".
warning " > linkifyjs@2.1.9" has unmet peer dependency "jquery@>= 1.11.0".
warning " > linkifyjs@2.1.9" has unmet peer dependency "react@>= 0.14.0".
warning " > linkifyjs@2.1.9" has unmet peer dependency "react-dom@>= 0.14.0".
warning " > primeng@9.1.3" has incorrect peer dependency "@angular/core@^7.0.0 || ^8.0.0 || ^9.0.0".
warning " > primeng@9.1.3" has incorrect peer dependency "@angular/common@^7.0.0 || ^8.0.0 || ^9.0.0".
warning " > primeng@9.1.3" has incorrect peer dependency "@angular/forms@^7.0.0 || ^8.0.0 || ^9.0.0".
warning " > sass-loader@8.0.2" has unmet peer dependency "webpack@^4.36.0 || ^5.0.0".
warning "sass-resources-loader > @babel/cli@7.10.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "sass-resources-loader > babel-eslint@10.1.0" has unmet peer dependency "eslint@>= 4.12.1".
warning " > terser-webpack-plugin@3.1.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "tslint-config-standard > tslint-eslint-rules@5.4.0" has incorrect peer dependency "tslint@^5.0.0".
warning " > webpack-cli@3.3.12" has unmet peer dependency "webpack@4.x.x".
[4/4] Building fresh packages...
$ npm rebuild node-sass
Done in 14.30s.
Done in 58.70s.

running on debian buster

so I downgraded to v2.3.0 and it works again
may be someone has an idea what the cause doesn't playing videos in version v2.4.0

greetings from nothern germany and stay healthy

**Comment by Chocobozzz** [comment] 2020-10-26 07:58
@manalejandro  Sorry for the late answer. Could you paste the URL of a video that does not work?

@eggercomputerchaos Did you restart peertube after the upgrade? If yes, try with a another web browser. If it still does not work, please create a dedicated issue.

**Comment by manalejandro** [comment] 2020-10-29 00:12
Yes, sorry too, it happens with all local videos of our instance https://peertube.hatthieves.es

https://peertube.hatthieves.es/videos/watch/5b7c07b9-5f30-4d64-b896-712a7964576b

**Comment by Chocobozzz** [comment] 2020-10-29 08:05
@manalejandro What is your ffmpeg version?

**Comment by manalejandro** [comment] 2020-10-30 00:13
# docker run -ti --rm chocobozzz/peertube:production-buster ffmpeg -version
ffmpeg version 4.1.6-1~deb10u1 Copyright (c) 2000-2020 the FFmpeg developers

**Comment by Chocobozzz** [comment] 2020-10-30 07:22
Please check your logs and your transcoding jobs in the admin to see if there are errors

**Comment by manalejandro** [comment] 2020-10-30 15:28
I have transcoded all local videos with hls without errors again, i think it is the web player? :thinking:

**Comment by rigelk** [comment] 2020-11-06 16:55
@manalejandro have you encountered errors again?

**Comment by manalejandro** [comment] 2020-11-06 18:49
Yes it happens again with latest videos https://peertube.hatthieves.es/videos/watch/8f2d5197-ad3e-4216-8d19-4028e088b48d

using image: chocobozzz/peertube:develop-buster
$ sudo -u peertube NODE_CONFIG_DIR=/config NODE_ENV=production npm run create-transcoding-job -- --generate-hls -v 8f2d5197-ad3e-4216-8d19-4028e088b48d

/usr/bin/ffmpeg -i /app/storage/videos/8f2d5197-ad3e-4216-8d19-4028e088b48d-576.mp4 -y -acodec aac -vcodec libx264 -r 25 -filter:v scale=w=trunc(oh*a/2)*2:h=576 -f mp4 -level 3.1 -b_strategy 1 -bf 16 -pix_fmt yuv420p -map_metadata -1 -movflags faststart -maxrate 2613333.3333333335 -bufsize 5226666.666666667 -g 50 -hls_time 4 -hls_list_size 0 -hls_playlist_type vod -hls_segment_filename /app/storage/streaming-playlists/hls/8f2d5197-ad3e-4216-8d19-4028e088b48d/8f2d5197-ad3e-4216-8d19-4028e088b48d-576-fragmented.mp4 -hls_segment_type fmp4 -f hls -hls_flags single_file -threads 1 /app/storage/streaming-playlists/hls/8f2d5197-ad3e-4216-8d19-4028e088b48d/576.m3u8

Completed ok but doesn't work :disappointed:

**Comment by Chocobozzz** [comment] 2020-11-07 12:41
Do you have a reverse proxy in front of docker? Because it's seems the server does not respect the byte range request

**Comment by manalejandro** [comment] 2020-11-07 13:33
Yes we have a cached proxy :cry: now have compiled nginx `--with-http_slice_module` and doing next config in vhost works as you can see in our instance :+1: 
```
     slice 1m;
     proxy_cache_key $host$uri$is_args$args$slice_range;
     proxy_set_header Range $slice_range;
```

Thanks a lot @Chocobozzz :smiley:

**Comment by rigelk** [comment] 2020-11-07 13:51
@manalejandro for reference, could you provide more details about your setup (how the cache proxy relates to the nginx holding the configuration, and where you put the above config)?

**Closed by rigelk** 2020-11-07 13:51 UTC

**Comment by manalejandro** [comment] 2020-11-07 14:06
Sure, have a default nginx server based in the docker server [docker-nginx-http3](https://github.com/nwtgck/docker-nginx-http3) with support HTTP/3 and IPv6, we add next global cache config in all vhost
```
# cat nginx/conf.d/proxy.conf
        proxy_cache_path /etc/nginx/cache levels=1:2 keys_zone=my_cache:10m max_size=10g inactive=60m use_temp_path=off;
        proxy_cache my_cache;
        proxy_cache_revalidate on;
        proxy_cache_min_uses 3;
        proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
        proxy_cache_background_update on;
        proxy_cache_lock on;
```
with the latest config we can watch videos again, thanks
