### ISSUE TITLE
`LocalVideoViewerWatchSectionModel.watchStart cannot be null` when processing viewer stats

### ISSUE THREAD

**Issue by thib92** [Chocobozzz/PeerTube#6112] opened 2023-12-13 21:34 UTC
### Describe the current behavior

I just deployed a PeerTube instance, and uploaded a few videos on it. Playback works fine. However, the `videos-views-stats` task fails, and it is reported as `delayed`.
In the server logs, I found the following stacktrace which seems to be the source of the problem:

```
SequelizeValidationError: notNull Violation: LocalVideoViewerWatchSectionModel.watchStart cannot be null
    at InstanceValidator._validate (/app/node_modules/sequelize/lib/instance-validator.js:50:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async InstanceValidator._validateAndRunHooks (/app/node_modules/sequelize/lib/instance-validator.js:60:7)
    at async InstanceValidator.validate (/app/node_modules/sequelize/lib/instance-validator.js:54:12)
    at async LocalVideoViewerWatchSectionModel.save (/app/node_modules/sequelize/lib/model.js:2426:7)
    at async LocalVideoViewerWatchSectionModel.create (/app/node_modules/sequelize/lib/model.js:1362:12)
    at async LocalVideoViewerWatchSectionModel.bulkCreateSections (file:///app/dist/core/models/view/local-video-viewer-watch-section.js:9:27)
    at async VideoViewerStats.saveViewerStats (file:///app/dist/core/lib/views/shared/video-viewer-stats.js:118:36)
    at async file:///app/dist/core/lib/views/shared/video-viewer-stats.js:90:44
    at async /app/node_modules/sequelize/lib/sequelize.js:507:18
    at async VideoViewerStats.processViewerStats (file:///app/dist/core/lib/views/shared/video-viewer-stats.js:86:21)
```

I've tried to trace where that `null` value comes from, but got a bit stuck. This is what I have so far:

1. When you are watching a video, the front-end calls the `api/v1/videos/<video-id>/views` endpoint defined [here](https://github.com/Chocobozzz/PeerTube/blob/1aab639928a5f06260a8e2b3095f59e14fe7ebb1/server/core/controllers/api/videos/view.ts#L34)
2. The controller calls the Video Views Manager's `processLocalView` method defined [here](https://github.com/Chocobozzz/PeerTube/blob/develop/server/core/lib/views/video-views-manager.ts#L43)
3. This calls the `addLocalViewer` method from the VideoViewerStats class defined [here](https://github.com/Chocobozzz/PeerTube/blob/develop/server/core/lib/views/shared/video-viewer-stats.ts#L45)
4. This calls `this.updateLocalViewerStats(...)` which has quite a lot of logic. It's possible that the issue is in this method. It's defined [here](https://github.com/Chocobozzz/PeerTube/blob/develop/server/core/lib/views/shared/video-viewer-stats.ts#L68)
5. This method then stores its output in the local cache + Redis cache in here: `this.setLocalVideoViewer(...)`
6. When this class is intanciated, it sents an interval to run `this.processViewerStats()`: https://github.com/Chocobozzz/PeerTube/blob/develop/server/core/lib/views/shared/video-viewer-stats.ts#L40
7. This calls `this.getLocalVideoViewerByKey()`, which gets the data from the cache of step 5: https://github.com/Chocobozzz/PeerTube/blob/develop/server/core/lib/views/shared/video-viewer-stats.ts#L141
8. It then tries to save inside the model: https://github.com/Chocobozzz/PeerTube/blob/develop/server/core/lib/views/shared/video-viewer-stats.ts#L153
And this is where we have the column constraint issue

From this, my guess is that maybe the front-end sometimes calls the views endpoint with no `currentTime`. Or when `currentTime` is `0`, it's mis-cast as `null`

In my Redis cluster, I found a `local-video-viewer-stats` object with the following:

```json
{
    "firstUpdated": 1702340233129,
    "lastUpdated": 1702340357208,
    "watchSections": [
        {
            "start": 0,
            "end": 0
        },
        {
            "start": 6,
            "end": 11
        },
        {
            "start": 0,
            "end": 0
        },
        {
            "start": 8,
            "end": 28
        },
        {
            "start": null,
            "end": 0
        }
    ],
    "watchTime": 25,
    "country": null,
    "videoId": 8
}
```

Because the `watchSections` are what are being inserted in the database, the last element with `"start": null` seems to be the culprit.

### Steps to reproduce

1. Deploy a PeerTube instance
2. Upload a video
3. View the video
4. Go to the administration panel, and notice the `delayed` jobs.

### Describe the expected behavior

The job should work, and views counts should be incremented on videos.

### Additional information

* PeerTube instance:
  * URL: https://up1.upcast.work/
  * Version: Latest
  * NodeJS version: Packaged in the Dockerfile
  * Ffmpeg version: Packaged in the Dockerfile

* Browser name, version and platforms on which you could reproduce the bug: Google Chrome, latest. Deployed on Kubernetes with the Docker distribution.

Note: I re-created the Nginx configuration using Nginx Ingress Controller on Kubernetes, I didn't use the `docker-compose` setup.

**Comment by Chocobozzz** [comment] 2023-12-14 10:12
Thanks for your detailed report! I was able to understand the root cause of the issue.

Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/63c4a02ce0fca3d5efa07e0444d1bed4fec69eaa

**Closed by Chocobozzz** 2023-12-14 10:12 UTC
Labels: Type: Bug :bug:
