### ISSUE TITLE
Login form goes to the home page, not the initially requested page

### ISSUE THREAD

**Issue by henke37** [Chocobozzz/PeerTube#475] opened 2018-04-05 12:57 UTC
When visiting a page I am asked to login, so far so good. But when I press the login button in the login form I'm redirected to the homepage, not the page I was trying to access in the first place.

* **PeerTube version or URL:** https://peertube.nsa.ovh/videos/recently-added
* **Browser name/version:** Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0 SeaMonkey/2.49.1
* **NodeJS version:** N/A

* **What is the expected behaviour?** Visit the page I tried accessing in the first place
* **What do you see instead?** The home page

**Comment by Chocobozzz** [comment] 2018-04-05 13:02
Duplicate of https://github.com/Chocobozzz/PeerTube/issues/294

**Closed by Chocobozzz** 2018-04-05 13:02 UTC
