### ISSUE TITLE
Playlists don't autoplay for guest users (i.e. users who aren't logged in)

### ISSUE THREAD

**Issue by hylianux** [Chocobozzz/PeerTube#2519] opened 2020-02-26 15:40 UTC
**What happened?**

When watching a playlist, peertube respects the "playlist autoplay" setting for any user logged in.

But if you're not logged in, peertube ignores the "playlist autoplay" setting, and just refuses to autoplay to the next video in the playlist.

**What do you expect to happen instead?**

A playlist should respect the autoplay setting whether a user is logged in or not.

**Steps to reproduce:**

1. Log in
2. Open a playlist
3. Click the autoplay button in the playlist on the right side of the screen.
4. Watch video in playlist to the end (or skip to the end)
5. Verify that the behavior of autoplay matches the state of the autoplay button.
6. Log out
7. Open same playlist
8. Watch video in playlist to the end (or skip to the end).
9. Verify whether the autoplay setting is acknowledged or not.

**Additional information**

* PeerTube version or URL: 2.1.0
* Browser name/version: Vivaldi (Chromium), Firefox, and Google Chrome
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by rigelk** [comment] 2020-03-20 09:37
@hylianux Could you provide a playlist example? I couldn't reproduce on my end.

**Comment by hylianux** [comment] 2020-03-28 04:45
Hey, sorry, somehow missed the followup.  

I can provide a link, sure.  https://video.hylianux.com/videos/watch/playlist/74f7536e-c0ca-4b6f-9985-ae3bcfab2ab0?videoId=52dafdd0-f2ae-433b-a816-42385a21a62b&resume=true

**Comment by hylianux** [comment] 2020-03-28 07:39
Also tried updating to 2.1.1 and the issue persists.

**Comment by Chocobozzz** [comment] 2020-04-08 07:43
Thanks @hylianux, should be fixed in https://github.com/Chocobozzz/PeerTube/commit/9870329f6946f5fbbec9860652cee6fb12fdc2aa

**Closed by Chocobozzz** 2020-04-08 07:43 UTC
Labels: Component: Playlist, Type: Bug :bug:
