### ISSUE TITLE
Can't read the text in the forms, with Firefox dark theme, because the text is white on white.

### ISSUE THREAD

**Issue by ParleurA** [Chocobozzz/PeerTube#1023] opened 2018-09-06 22:29 UTC
* **PeerTube version or URL: 1.0.0-beta11**
* **Browser name/version: Firefox 62.0/Linux**

* **What is the expected behaviour?**
Just see the text in the forms!

* **What do you see instead?**
White on white text.

Basically, all the problem is in the subject.

When I want to fill any form, using Firefox with a dark theme, the text in the forms is white on white, and so, its imposibble to read it, unless highlighting it.

It's *very* annoying.

**Comment by rigelk** [comment] 2018-09-06 22:41
isn't it caused by your browser theme? I don't see how we can act on this.

**Comment by ParleurA** [comment] 2018-09-06 23:09
Partially, for sure. However, I didn't have the problem with the same browser theme and the previous version of Peertube.

**Comment by Chocobozzz** [comment] 2018-09-07 07:01
What is your theme so we can reproduce?

**Comment by ParleurA** [comment] 2018-09-07 07:08
Firefox uses default system theme, which is Adwaita-dark.

**Comment by rigelk** [comment] 2018-09-08 16:17
In the meantime there is always https://github.com/DmitriK/darkContrast

**Comment by ParleurA** [comment] 2018-09-09 08:35
Thank you very much for the tip with the firefox plugin ; it'll help for a couple of others website with the same problem. :)

**Comment by rigelk** [comment] 2018-09-09 13:00
You're welcome!

The problem should be fixed in https://github.com/Chocobozzz/PeerTube/commit/20c3a59e2c81bb00be943ccc51efe175c08eaa4e.

**Closed by rigelk** 2018-09-09 13:00 UTC
Labels: Type: Bug :bug:
