### ISSUE TITLE
Mull browser for Android not in incognito considered "incompatible" on TILVids.com

### ISSUE THREAD

**Issue by nehemiagurl** [Chocobozzz/PeerTube#6249] opened 2024-02-26 05:57 UTC
### Describe the current behavior

[Mull browser](https://gitlab.com/divested-mobile/mull-fenix) is a privacy fork of Firefox for Android. it's latest version, 122.1.0, was released on February 11th, two weeks ago.
Recently (although it is important to note, not immediately after the browser update but a few days later), I started getting an "incompatible browser" screen on TILVids.com when browsing in normal (i.e. not incognito) mode. Notably I don't get such an error on other instances running v6.0.3, such as neat.tube, and when browsing to TILvids in incognito mode from the same browser with the same addons.
This never happened to me before and is entirely new behaviour.
For completion's sake I'll say I have the uBlock Origin and Privacy Badger addons, though both block nothing and disabling them doesn't help.

### Steps to reproduce

1. open a non-incognito tab in the Mull browser
2. go to TILVids.com
3. an "incompatible browser" screen is popped

### Describe the expected behavior

one can browse normally, like other instances or incognito

### Additional information

* PeerTube instance: TILVids
  * URL: https://tilvids.com
  * Version: 5.2.1
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug: Mull browser (non-incognito mode)
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment] 2024-02-26 08:27
Hi,

I think the issue is fixed on peertube >= v6. Tilvids should upgrade :)

**Closed by Chocobozzz** 2024-02-26 08:27 UTC
