### ISSUE TITLE
cannot find a centralized search function & "other videos" are often irrelevant

### ISSUE THREAD

**Issue by gloschtla** [Chocobozzz/PeerTube#2847] opened 2020-06-08 18:20 UTC
How can I search for all videos on all peertube instances?
Is there any instance, which follows all instances?

EDIT: This issue will be fixed in the year 2020 - thx to @ballsystemlord who [initiated it.](https://github.com/Chocobozzz/PeerTube/issues/824)

**Comment by rigelk** [comment] 2020-06-08 19:43
As mentioned, duplicate of #824.

**Closed** 2020-06-08 19:43 UTC
Labels: Type: Duplicate :loop:
