### ISSUE TITLE
problems playing redundancies

### ISSUE THREAD

**Issue by guffymarinovich** [Chocobozzz/PeerTube#6359] opened 2024-04-26 19:22 UTC
### Describe the current behavior

There are 3 instances with all redundancies enabled. The videos are distributed on the servers, everything is OK. Physically, the videos are there and they are played. But when the connection with one of the instances is lost, the video stops running on the others where it is downloaded

### Steps to reproduce

1. installed and configured 3 instances enabled redundancies on all Strategy recently-added
2. everything works, videos are played until the connection with one of the instances is lost
3. "level":"error","message":"Client log: HLS.js error: networkError - fatal: true - manifestLoadError",

### Additional information

* PeerTube instance:
  * URL:
  * Version:6.0.4
  * NodeJS version: v18.20.2
  * Ffmpeg version: 4.4.2-0ubuntu0.22.04.1

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by guffymarinovich** [comment] 2024-04-26 19:22
time settings are the same on 3 instances

**Comment by guffymarinovich** [comment] 2024-04-27 05:00
Why can’t the instance itself play video that it downloaded from other instances? When remote instances are not available

**Comment by Chocobozzz** [comment] 2024-04-29 06:10
Hi,

Can you provide a video link so I reproduce?

**Comment by guffymarinovich** [comment] 2024-04-29 14:29
logs

**Comment by Chocobozzz** [comment] 2024-05-16 08:51
Hi,

> https://zone-video.online/w/3cMVb58mCJuQKGx8dZJxk2

Unfortunately the video link doesn't work anymore

**Comment by guffymarinovich** [comment] 2024-05-16 09:05
I can't wait that long until you decide to check

**Comment by SimplyCorbett** [comment] 2024-05-29 01:11
> I can't wait that long until you decide to check
> 
> how about you, eblan

Why not? Is the video copyright?

**Comment by Chocobozzz** [comment] 2024-05-29 13:43
> I can't wait that long until you decide to check

I'm sorry the free support offered by Framasoft is not fast enough for you, but we have to deal with our own time constraints.

Closing as we were unable to reproduce.

**Closed by Chocobozzz** 2024-05-29 13:43 UTC
Labels: Status: Waiting for answer
