### ISSUE TITLE
Unable to upload subtitle : Cannot read property id of undefined

### ISSUE THREAD

**Issue by GreenBlood** [Chocobozzz/PeerTube#1533] opened 2019-01-04 23:52 UTC
**What happened?**
I was trying to upload a subtitle (srt) file to a video. The video is in english and the file in french.
When I try to add it, nothing happens and the brower logs shows `ERROR TypeError: Cannot read property 'id' of undefined` which completely breaks the navigation until I reload the page

**What do you expect to happen instead?**
Being able to upload the subtitle file and continue navigation

**Steps to reproduce:**

1. Go on a video, and click "Update"

2. In the captions tab, click "Add another caption"

3. Choose the language, browse to the srt file, and click "Add this caption"

4. The browser logs now says the error mentionned above (i've joined the stacktrace to the issue in Additionnal informations) and no caption file is added

5. Every subsequent click on any link on the page now throws the same error until I reload the page

**Additional information**
* PeerTube version or URL: 1.1.0
* Browser name/version: Chrome/ChromeOS 71, tested on Firefox 64 on my mobile device. I can't have the browser logs here but behaviour is the same.
* NodeJS version: Latest LTS : 10.15.0

* Link to browser console log if useful:
[peertube_browser_stacktrace.log](https://github.com/Chocobozzz/PeerTube/files/2728881/peertube_browser_stacktrace.log)
The "main.js" file is from https://[peertube URL]/client/en_US/main.5d6ceb8684e2878ff758.js
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):
I don't think they are relevant as the error seems client-side but I'll gladly send some if needed.

Regards,
_Green_

**Comment by Folatt** [comment] 2019-01-06 09:58
I have the same problem on Falkon.

**Comment by Chocobozzz** [comment] 2019-01-07 07:56
Thanks for the issue @GreenBlood, but it's a duplicate of https://github.com/Chocobozzz/PeerTube/issues/1501 (that have been fixed on develop).

**Closed by Chocobozzz** 2019-01-07 07:56 UTC
