### ISSUE TITLE
Don't resume video the last five seconds

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#5651] opened 2023-02-25 07:44 UTC
### Describe the current behavior

When watching a video til the end it will be resumed even if it's just a few seconds left.

Related:
https://github.com/Chocobozzz/PeerTube/issues/3866
https://github.com/Chocobozzz/PeerTube/issues/660

### Steps to reproduce

1. Visit https://peertube.cpy.re/w/sWxgbBUu1ScQkHqz831Qqi
2. Go to 1.13 in the video
3. Watch til the end
4. Reload the page

### Describe the expected behavior

The video should be restarted from the beginning.

It seems that this is caused by PT only storing playback position each five seconds. [When deciding](https://github.com/kontrollanten/PeerTube/blob/1a99dc647fd407f443238d10f9a721c8d887074f/client/src/app/%2Bvideos/%2Bvideo-watch/video-watch.component.ts#L581-L582) where to start to play [this value](https://github.com/Chocobozzz/PeerTube/blob/59a643aa5cf6775d27dfcc147b19c4537292d53c/client/src/assets/player/shared/peertube/peertube-plugin.ts#L31) should be taken into account:

```
if (video.duration - startTime <= USER_VIEW_VIDEO_INTERVAL) startTime = 0
```

### Additional information

* PeerTube instance:
  * URL: https://peertube.cpy.re/w/sWxgbBUu1ScQkHqz831Qqi
  * Version: 5.0.1

**Comment by Chocobozzz** [comment] 2023-02-25 15:27
Hi,

The bug is on the server side where it doesn't accept the last timestamp sent, that is above the video duration (`81` vs `80`).

Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/6de076222aca7005371e01768171efdc62ed8018

**Closed by Chocobozzz** 2023-02-25 15:27 UTC
Labels: Type: Bug :bug:, UI

**Comment by Chocobozzz** [comment] 2023-02-27 08:03
Yes it should, you can try to reproduce on https://peertube2.cpy.re/w/sWxgbBUu1ScQkHqz831Qqi since the fix is already deployed

**Comment by Chocobozzz** [comment] 2023-03-01 10:36
Sorry about that, it should also be fixed for anonymous users in https://github.com/Chocobozzz/PeerTube/commit/626b76dcf5df3d27628cd90053630cbbbbcccff0
