### ISSUE TITLE
Firefox 131 reported as "Incompatible browser"

### ISSUE THREAD

**Issue by nhoizey** [Chocobozzz/PeerTube#6664] opened 2024-10-09 07:28 UTC
### Describe the current behavior

PeerTube says Firefox 131 is incompatible

### Steps to reproduce

1. navigate to https://media.fsfe.org/w/j1c6LQVZ8qnCLLwpXMuw3M
2. see the message "Incompatible browser, We are sorry but it seems that PeerTube is not compatible with your web browser. Please try with the latest version of Mozilla Firefox."

![CleanShot 2024-10-09 at 09 21 47@2x](https://github.com/user-attachments/assets/3775ce43-0edf-4ac5-b5af-bff6bcf3802b)

### Describe the expected behavior

PeerTube should not consider Firefox 131 as incompatible

### Additional information

* PeerTube instance: https://media.fsfe.org/about/instance
  * URL: https://media.fsfe.org/w/j1c6LQVZ8qnCLLwpXMuw3M
  * Version: 6.3.2
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug: Firefox 131.0 (aarch64) on a MacBook Air M2 with macOS 15.0
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment] 2024-10-09 07:35
Please paste web browser console logs

**Comment by nhoizey** [comment] 2024-10-09 10:24
```
Ouverture de https://media.fsfe.org/w/j1c6LQVZ8qnCLLwpXMuw3M
GET
https://media.fsfe.org/w/j1c6LQVZ8qnCLLwpXMuw3M
[HTTP/1.1 200 OK 98ms]

La mise en page a été forcée avant le chargement complet de la page. Si les feuilles de style ne sont pas encore chargées, cela peut provoquer un flash de contenu non stylisé. markup.js:250:53
GET
https://media.fsfe.org/client/en-US/chunk-UG7XBKEN.js
[HTTP/1.1 200 OK 134ms]

GET
https://media.fsfe.org/client/en-US/chunk-CFH4UIWR.js
[HTTP/1.1 200 OK 195ms]

GET
https://media.fsfe.org/client/en-US/chunk-L6IFYWM5.js
[HTTP/1.1 200 OK 188ms]

GET
https://media.fsfe.org/client/en-US/chunk-GOQXWQS6.js
[HTTP/1.1 200 OK 159ms]

GET
https://media.fsfe.org/client/en-US/chunk-ZIGFMZH6.js
[HTTP/1.1 200 OK 191ms]

GET
https://media.fsfe.org/client/en-US/chunk-TE466U42.js
[HTTP/1.1 200 OK 174ms]

GET
https://media.fsfe.org/client/en-US/chunk-CSVAFG3P.js
[HTTP/1.1 200 OK 218ms]

GET
https://media.fsfe.org/client/en-US/chunk-2LHPOVYD.js
[HTTP/1.1 200 OK 189ms]

GET
https://media.fsfe.org/client/en-US/chunk-A3C2VH6R.js
[HTTP/1.1 200 OK 203ms]

GET
https://media.fsfe.org/client/en-US/chunk-ZTIZI5SX.js
[HTTP/1.1 200 OK 204ms]

GET
https://media.fsfe.org/client/en-US/polyfills-MMKWWPQO.js
[HTTP/1.1 200 OK 341ms]

GET
https://media.fsfe.org/client/en-US/main-VSF4UGOE.js
[HTTP/1.1 200 OK 343ms]

GET
https://media.fsfe.org/client/en-US/styles-6MDVCK3R.css
[HTTP/1.1 200 OK 308ms]

GET
https://media.fsfe.org/client/en-US/media/SourceSans3VF-Roman.ttf-DPX3LM3Z.woff2
[HTTP/1.1 200 OK 383ms]

Uncaught Error: Permission denied to access property "script"
    <anonymous> <anonymous code>:16
<anonymous code>:16:9
GET
https://media.fsfe.org/client/en-US/chunk-Z5PSBMEZ.js
[HTTP/1.1 200 OK 75ms]

GET
https://media.fsfe.org/client/en-US/chunk-B6QLNCNA.js
[HTTP/1.1 200 OK 80ms]

GET
https://media.fsfe.org/client/en-US/chunk-RSGGMXGL.js
[HTTP/1.1 200 OK 173ms]

GET
https://media.fsfe.org/client/en-US/chunk-2KNEJYIL.js
[HTTP/1.1 200 OK 68ms]

GET
https://media.fsfe.org/client/en-US/chunk-2ZEOHFIQ.js
[HTTP/1.1 200 OK 41ms]

GET
https://media.fsfe.org/client/en-US/chunk-RWOC7QRQ.js
[HTTP/1.1 200 OK 55ms]

GET
https://media.fsfe.org/client/en-US/chunk-QL266V7J.js
[HTTP/1.1 200 OK 45ms]

GET
https://media.fsfe.org/client/en-US/chunk-KVZYEW32.js
[HTTP/1.1 200 OK 38ms]

GET
https://media.fsfe.org/client/en-US/chunk-MH3XEBHQ.js
[HTTP/1.1 200 OK 41ms]

GET
https://media.fsfe.org/client/en-US/chunk-FSLABYG5.js
[HTTP/1.1 200 OK 47ms]

GET
https://media.fsfe.org/client/en-US/chunk-DFTYF6DS.js
[HTTP/1.1 200 OK 55ms]

GET
https://media.fsfe.org/client/en-US/chunk-OK6PRY3X.js
[HTTP/1.1 200 OK 51ms]

GET
https://media.fsfe.org/client/en-US/chunk-NSYAOYHN.js
[HTTP/1.1 200 OK 57ms]

GET
https://media.fsfe.org/client/en-US/chunk-HQCR3YFH.js
[HTTP/1.1 200 OK 76ms]

GET
https://media.fsfe.org/client/en-US/chunk-OJTIM34Y.js
[HTTP/1.1 200 OK 52ms]

GET
https://media.fsfe.org/client/en-US/chunk-CRXDMSEA.js
[HTTP/1.1 200 OK 76ms]

GET
https://media.fsfe.org/client/en-US/chunk-RUMG2SUW.js
[HTTP/1.1 200 OK 37ms]

GET
https://media.fsfe.org/client/en-US/chunk-D343PUHB.js
[HTTP/1.1 200 OK 29ms]

GET
https://media.fsfe.org/client/en-US/chunk-XJAOKYNP.js
[HTTP/1.1 200 OK 29ms]

GET
https://media.fsfe.org/client/en-US/chunk-VIZZ6AN2.js
[HTTP/1.1 200 OK 27ms]

GET
https://media.fsfe.org/client/en-US/chunk-5BDE4WMB.js
[HTTP/1.1 200 OK 28ms]

GET
https://media.fsfe.org/client/en-US/chunk-CZFXMGOD.js
[HTTP/1.1 200 OK 27ms]

GET
https://media.fsfe.org/client/en-US/chunk-GDWYPZIP.js
[HTTP/1.1 200 OK 32ms]

GET
https://media.fsfe.org/client/en-US/chunk-YWFFSKOS.js
[HTTP/1.1 200 OK 27ms]

GET
https://media.fsfe.org/client/en-US/chunk-TUURZOBH.js
[HTTP/1.1 200 OK 49ms]

GET
https://media.fsfe.org/client/en-US/chunk-B2XT645N.js
[HTTP/1.1 200 OK 55ms]

GET
https://media.fsfe.org/client/en-US/chunk-KBLCI2W2.js
[HTTP/1.1 200 OK 51ms]

GET
https://media.fsfe.org/client/en-US/chunk-YE75BIQU.js
[HTTP/1.1 200 OK 50ms]

GET
https://media.fsfe.org/client/en-US/chunk-4TKANZEM.js
[HTTP/1.1 200 OK 78ms]

GET
https://media.fsfe.org/client/en-US/chunk-FHAM4LWJ.js
[HTTP/1.1 200 OK 78ms]

GET
https://media.fsfe.org/client/en-US/chunk-7I3DZ4SZ.js
[HTTP/1.1 200 OK 77ms]

GET
https://media.fsfe.org/client/en-US/chunk-JE2MBW7Q.js
[HTTP/1.1 200 OK 59ms]

GET
https://media.fsfe.org/client/en-US/media/SourceSans3VF-Roman.ttf-DPX3LM3Z.woff2
[HTTP/1.1 200 OK 90ms]

Injecting 0 themes. logger.ts:24:17
Enabling default theme. logger.ts:24:17
XHRGET
https://media.fsfe.org/api/v1/oauth-clients/local
[HTTP/1.1 200 OK 155ms]

XHRGET
https://media.fsfe.org/api/v1/videos/languages
[HTTP/1.1 200 OK 133ms]

XHRGET
https://media.fsfe.org/api/v1/config/
[HTTP/1.1 200 OK 131ms]

GET
https://media.fsfe.org/client/en-US/chunk-ZKAJQEQP.js
[HTTP/1.1 200 OK 183ms]

GET
https://media.fsfe.org/client/assets/images/logo.svg?89b2e470aa21490d9a0887921d9f3393fbe28ea7
[HTTP/1.1 200 OK 124ms]

GET
https://media.fsfe.org/client/en-US/media/menu-7FLSGCBJ.svg
[HTTP/1.1 200 OK 103ms]

GET
https://media.fsfe.org/client/assets/images/favicon.png?662068d774dec571b2d275769897eb0617a2ad91
[HTTP/1.1 200 OK 36ms]

GET
https://media.fsfe.org/client/assets/images/icons/icon-192x192.png
[HTTP/1.1 200 OK 36ms]

GET
https://media.fsfe.org/client/en-US/chunk-S6J4MSVS.js
[HTTP/1.1 200 OK 40ms]

Client credentials loaded. logger.ts:24:17
GET
https://media.fsfe.org/client/en-US/chunk-EOGGNZUT.js
[HTTP/1.1 200 OK 38ms]

GET
https://media.fsfe.org/client/en-US/chunk-5NE4JAFC.js
[HTTP/1.1 200 OK 26ms]

GET
https://media.fsfe.org/client/en-US/chunk-CZNH56XH.js
[HTTP/1.1 200 OK 27ms]

GET
https://media.fsfe.org/client/en-US/chunk-4NVJRMZI.js
[HTTP/1.1 200 OK 35ms]

GET
https://media.fsfe.org/client/en-US/chunk-XDTYH7PD.js
[HTTP/1.1 200 OK 26ms]

GET
https://media.fsfe.org/client/en-US/chunk-4ML4ZKXO.js
[HTTP/1.1 200 OK 43ms]

GET
https://media.fsfe.org/client/en-US/chunk-QBYV6TEX.js
[HTTP/1.1 200 OK 44ms]

GET
https://media.fsfe.org/client/en-US/chunk-4NUW5VIE.js
[HTTP/1.1 200 OK 45ms]

GET
https://media.fsfe.org/client/en-US/chunk-5LZ54M7A.js
[HTTP/1.1 200 OK 53ms]

GET
https://media.fsfe.org/client/en-US/chunk-3QWOH7ME.js
[HTTP/1.1 200 OK 52ms]

GET
https://media.fsfe.org/client/en-US/chunk-XPJNM72U.js
[HTTP/1.1 200 OK 51ms]

GET
https://media.fsfe.org/client/en-US/chunk-RZOQ7LPR.js
[HTTP/1.1 200 OK 72ms]

GET
https://media.fsfe.org/client/en-US/chunk-EZD2NQ5K.js
[HTTP/1.1 200 OK 69ms]

GET
https://media.fsfe.org/client/en-US/chunk-TSF2IMOF.js
[HTTP/1.1 200 OK 82ms]

GET
https://media.fsfe.org/client/en-US/chunk-FAJ7GM2S.js
[HTTP/1.1 200 OK 78ms]

GET
https://media.fsfe.org/client/en-US/chunk-7OADMNOM.js
[HTTP/1.1 200 OK 72ms]

GET
https://media.fsfe.org/client/en-US/chunk-RDRWV2RN.js
[HTTP/1.1 200 OK 82ms]

GET
https://media.fsfe.org/client/en-US/chunk-JZRE6ZZ2.js
[HTTP/1.1 200 OK 101ms]

GET
https://media.fsfe.org/client/en-US/chunk-PCTNPR6N.js
[HTTP/1.1 200 OK 101ms]

GET
https://media.fsfe.org/client/en-US/chunk-JMNUQ4A3.js
[HTTP/1.1 200 OK 98ms]

GET
https://media.fsfe.org/client/en-US/chunk-YVPWIWN5.js
[HTTP/1.1 200 OK 127ms]

GET
https://media.fsfe.org/client/en-US/chunk-XDNYQVZS.js
[HTTP/1.1 200 OK 109ms]

GET
https://media.fsfe.org/client/en-US/chunk-KJEIOT2H.js
[HTTP/1.1 200 OK 109ms]

GET
https://media.fsfe.org/client/en-US/chunk-LMN474DE.js
[HTTP/1.1 200 OK 104ms]

GET
https://media.fsfe.org/client/en-US/chunk-VPTMOHL3.js
[HTTP/1.1 200 OK 136ms]

GET
https://media.fsfe.org/client/en-US/chunk-QV4RHWBU.js
[HTTP/1.1 200 OK 130ms]

GET
https://media.fsfe.org/client/en-US/chunk-Y5KRQYTF.js
[HTTP/1.1 200 OK 130ms]

GET
https://media.fsfe.org/client/en-US/chunk-42EEQ72G.js
[HTTP/1.1 200 OK 130ms]

Medium parser loaded app.js:2:9
XHRGET
https://media.fsfe.org/api/v1/videos/j1c6LQVZ8qnCLLwpXMuw3M/captions
[HTTP/1.1 200 OK 191ms]

XHRGET
https://media.fsfe.org/api/v1/videos/j1c6LQVZ8qnCLLwpXMuw3M
[HTTP/1.1 200 OK 218ms]

XHRGET
https://media.fsfe.org/api/v1/videos/j1c6LQVZ8qnCLLwpXMuw3M/storyboards
[HTTP/1.1 200 OK 205ms]

XHRGET
https://media.fsfe.org/api/v1/videos/j1c6LQVZ8qnCLLwpXMuw3M/chapters
[HTTP/1.1 200 OK 195ms]

GET
https://media.fsfe.org/client/en-US/chunk-MOFJ5UZ7.js
[HTTP/1.1 200 OK 30ms]

XHRGET
https://media.fsfe.org/api/v1/search/videos?start=0&count=7&skipCount=true&nsfw=false&tagsOneOf=ada&tagsOneOf=ada & zangemann&tagsOneOf=children&tagsOneOf=free software&tagsOneOf=software freedom&sort=-publishedAt&searchTarget=local
[HTTP/1.1 200 OK 69ms]

XHRGET
https://media.fsfe.org/api/v1/videos/91cb5612-09b7-45a8-82d1-1a921d38df29/comment-threads?start=0&count=10&sort=-createdAt
[HTTP/1.1 200 OK 42ms]

GET
https://media.fsfe.org/client/assets/images/default-avatar-account-48x48.png
[HTTP/1.1 200 OK 27ms]

GET
https://media.fsfe.org/lazy-static/avatars/ac167baf-c78f-461d-8264-34aa699ebdc7.jpg
[HTTP/1.1 200 OK 37ms]

GET
https://media.fsfe.org/lazy-static/storyboards/26ec73d8-7c27-49ab-b365-0aee4aebf7de.jpg
[HTTP/1.1 200 OK 353ms]

XHRGET
https://media.fsfe.org/static/streaming-playlists/hls/91cb5612-09b7-45a8-82d1-1a921d38df29/eb7889cf-17d3-44e0-aa53-eba17412d466-master.m3u8
[HTTP/1.1 200 OK 27ms]

GET
https://media.fsfe.org/client/en-US/media/tick-white-DB6RWDOS.svg
[HTTP/1.1 200 OK 28ms]

La lecture automatique n’est autorisée que lorsqu’elle a été approuvée par l’utilisateur, que le site est activé par l’utilisateur, ou que le média est muet. core.js:19401:26
GET
https://media.fsfe.org/client/en-US/chunk-AEQ243LR.js
[HTTP/1.1 200 OK 27ms]

GET
https://media.fsfe.org/client/en-US/media/big-play-button-EKJZWIDB.svg
[HTTP/1.1 200 OK 27ms]

GET
https://media.fsfe.org/lazy-static/previews/5e4d8101-46f2-4758-a2ce-2a5c63144a54.jpg
[HTTP/1.1 200 OK 34ms]

GET
https://media.fsfe.org/lazy-static/thumbnails/13318823-b248-4990-8695-cfe6a4d1874a.jpg
[HTTP/1.1 200 OK 35ms]

GET
https://media.fsfe.org/lazy-static/thumbnails/cd912717-0069-43dc-b41e-9a3ec4fe539f.jpg
[HTTP/1.1 200 OK 34ms]

GET
https://media.fsfe.org/client/en-US/chunk-EX4MJSN5.js
[HTTP/1.1 200 OK 53ms]

GET
https://media.fsfe.org/client/en-US/chunk-6ERW756X.js
[HTTP/1.1 200 OK 36ms]

GET
https://media.fsfe.org/lazy-static/avatars/8c564d2a-89ca-4a02-83b2-576873f5b02e.png
[HTTP/1.1 200 OK 87ms]

GET
https://media.fsfe.org/client/en-US/chunk-TDURFM6W.js
[HTTP/1.1 200 OK 34ms]

XHRPOST
https://media.fsfe.org/api/v1/videos/91cb5612-09b7-45a8-82d1-1a921d38df29/views
[HTTP/1.1 204 No Content 168ms]

Jeu de règles ignoré suite à un mauvais sélecteur. content.css:2:9
Propriété « -moz-border-radius » inconnue.  Déclaration abandonnée. content.css:2:850
Erreur d’analyse de la valeur pour « min-height ».  Déclaration abandonnée. content.css:30:201
Erreur d’analyse de la valeur pour « min-height ».  Déclaration abandonnée. content.css:31:199
Erreur d’analyse de la valeur pour « letter-spacing ».  Déclaration abandonnée. content.css:48:439
Erreur d’analyse de la valeur pour « transition ».  Déclaration abandonnée. content.css:48:845
Erreur d’analyse de la valeur pour « letter-spacing ».  Déclaration abandonnée. content.css:49:100
Erreur d’analyse de la valeur pour « margin ».  Déclaration abandonnée. content.css:52:2216
Erreur d’analyse de la valeur pour « margin-inline-end ».  Déclaration abandonnée. content.css:90:1007
Erreur d’analyse de la valeur pour « margin ».  Déclaration abandonnée. content.css:93:2147
Erreur d’analyse de la valeur pour « -webkit-text-size-adjust ».  Déclaration abandonnée. en-US:1:4743
GET
https://media.fsfe.org/client/assets/images/logo.svg?89b2e470aa21490d9a0887921d9f3393fbe28ea7
[HTTP/1.1 200 OK 0ms]

Pseudo-classe ou pseudo-élément « -ms-reveal » inconnu.  Jeu de règles ignoré suite à un mauvais sélecteur. primeng.css:502:21
Erreur d’analyse de la valeur pour « -webkit-text-size-adjust ».  Déclaration abandonnée. _reboot.scss:58:2
Pseudo-classe ou pseudo-élément « -moz-focus-outer » inconnu.  Jeu de règles ignoré suite à un mauvais sélecteur. _form-range.scss:23:2
Jeu de règles ignoré suite à un mauvais sélecteur. _form-range.scss:38:4
Pseudo-classe ou pseudo-élément « ng-deep » inconnu.  Jeu de règles ignoré suite à un mauvais sélecteur. _mixins.scss:61:2
Pseudo-classe ou pseudo-élément « ng-deep » inconnu.  Jeu de règles ignoré suite à un mauvais sélecteur. _mixins.scss:61:2
Propriété « -moz-border-radius » inconnue.  Déclaration abandonnée. primeng-custom.scss:226:2
Propriété « -moz-border-radius » inconnue.  Déclaration abandonnée. primeng-custom.scss:279:2
Erreur d’analyse de la valeur pour « z-index ».  Déclaration abandonnée. z-index.scss:58:4
Erreur d’analyse de la valeur pour « z-index ».  Déclaration abandonnée. z-index.scss:62:4
Erreur d’analyse de la valeur pour « z-index ».  Déclaration abandonnée. z-index.scss:66:4
Pseudo-classe ou pseudo-élément « ng-deep » inconnu.  Jeu de règles ignoré suite à un mauvais sélecteur. _mixins.scss:61:2
Pseudo-classe ou pseudo-élément « ng-deep » inconnu.  Jeu de règles ignoré suite à un mauvais sélecteur. _mixins.scss:61:2
Pseudo-classe ou pseudo-élément « ng-deep » inconnu.  Jeu de règles ignoré suite à un mauvais sélecteur. _mixins.scss:61:2
Pseudo-classe ou pseudo-élément « ng-deep » inconnu.  Jeu de règles ignoré suite à un mauvais sélecteur. _mixins.scss:61:2
Pseudo-classe ou pseudo-élément « ng-deep » inconnu.  Jeu de règles ignoré suite à un mauvais sélecteur. _mixins.scss:61:2
Pseudo-classe ou pseudo-élément « ng-deep » inconnu.  Jeu de règles ignoré suite à un mauvais sélecteur. _mixins.scss:61:2
Erreur d’analyse de la valeur pour « outline ».  Déclaration abandonnée. _menu.scss:33:4
Valeur non valide trouvée pour la fonctionnalité de média. en-US:1:510
Pseudo-classe ou pseudo-élément « -webkit-full-screen » inconnu.  Jeu de règles ignoré suite à un mauvais sélecteur. en-US:1:14076
Valeur non valide trouvée pour la fonctionnalité de média. en-US:1:7030
Valeur non valide trouvée pour la fonctionnalité de média. en-US:1:1038
Valeur non valide trouvée pour la fonctionnalité de média. en-US:1:603
Valeur non valide trouvée pour la fonctionnalité de média. en-US:1:541
Valeur non valide trouvée pour la fonctionnalité de média. en-US:1:1140
Valeur non valide trouvée pour la fonctionnalité de média. en-US:1:603
GET
https://media.fsfe.org/client/en-US/media/big-play-button-EKJZWIDB.svg
[HTTP/1.1 200 OK 0ms]

GET
https://media.fsfe.org/client/en-US/media/menu-7FLSGCBJ.svg
[HTTP/1.1 200 OK 0ms]

GET
https://media.fsfe.org/client/en-US/media/SourceSans3VF-Roman.ttf-DPX3LM3Z.woff2
[HTTP/1.1 200 OK 159ms]

GET
https://media.fsfe.org/client/en-US/media/SourceSans3VF-Roman.ttf-DPX3LM3Z.woff2
[HTTP/1.1 200 OK 170ms]
```

**Comment by Chocobozzz** [comment] 2024-10-21 13:46
Do you still have the issue? I can't reproduce :thinking:

**Comment by nhoizey** [comment] 2024-11-12 09:28
@Chocobozzz I still have the issue, using Firefox 132.0.1

**Comment by Chocobozzz** [comment] 2024-11-12 09:39
In the console, only log "Errors". Then click on the link of the message

```

Uncaught Error: Permission denied to access property "script"
    <anonymous> <anonymous code>:16
<anonymous code>:16:9
```

So we can see where it comes from

**Comment by nhoizey** [comment] 2024-11-12 14:05
Is this enough to understand where it comes from?

![CleanShot 2024-11-12 at 15 04 33@2x](https://github.com/user-attachments/assets/ae9aece4-842d-4192-9c87-e851ec84c40e)

**Comment by Chocobozzz** [comment] 2024-11-12 14:13
Not sure where this script comes from :thinking:  Can you try with firefox extensions disabled?

**Comment by Chocobozzz** [comment] 2024-11-29 08:56
Ping @nhoizey

**Comment by Chocobozzz** [comment] 2024-12-18 16:00
Thanks @ftoral 

Then I'm closing this issue.

**Closed by Chocobozzz** 2024-12-18 16:00 UTC
Labels: Status: Waiting for answer
