### ISSUE TITLE
Hash/Tag plugin

### ISSUE THREAD

**Issue by 01123581321345589144233** [Chocobozzz/PeerTube#5179] opened 2022-08-07 15:14 UTC
### Describe the problem to be solved

A hashtag list on the startpage or the /videos/recently-added page with the most used hashtags
so i can also edit the hashtag list for add new hashtags they are used in the video description.

### Describe the solution you would like

i do no how but there are alot of people here they can do this.
I have now this solution: https://tv1.gomntu.space/search?search=docu&searchTarget=local with a html link
like this #docu for Documentation on my start page

**Comment by Chocobozzz** [comment] 2022-08-08 06:29
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/4798

**Closed by Chocobozzz** 2022-08-08 06:29 UTC
