### ISSUE TITLE
DJ-ing/Livestreaming of Pre-existing Content

### ISSUE THREAD

**Issue by illeatmyhat** [Chocobozzz/PeerTube#2818] opened 2020-06-01 00:10 UTC
Related to #2806 
### Concept:
A livestreamer should be able to create a playlist of existing videos on Peertube.
From this playlist, the livestreamer will determine what videos are being played, and can seek to specific times, acting as a "DJ" of sorts for their viewers.
Video content is not duplicated or processed in any way. The only information being distributed from channel to viewer is video IDs and timecodes.

An active demonstration of this concept for centralized video streaming services can be found in the CyTube project ([website](http://cytu.be/)/[github](https://github.com/calzoneman/sync)).

### Use Cases:
- Decentralized "Movie Nights", "Viewing Parties"
- "Radio Stations"
- Equivalent to Youtube's "Premiere" feature
### Possible Implementation:
Dependencies:
- a lot of UI work
- pubsub for synchronizing timecodes and playlist content

If I'm understanding the system correctly, the plugin system cannot add or change UI components beyond CSS, so the feature cannot be implemented as a plugin.

**Comment by Chocobozzz** [comment] 2020-06-04 12:44
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/357

**Closed by Chocobozzz** 2020-06-04 12:44 UTC
