### ISSUE TITLE
No Audio only resolution in Player

### ISSUE THREAD

**Issue by test2a** [Chocobozzz/PeerTube#3663] opened 2021-01-29 16:57 UTC
**Describe the current behavior**
https://peertube2.cpy.re/videos/watch/07a78392-c981-42af-a7fa-46e23e593716

this video. it plays just fine but i see the quality selector shows resolutions including 1080p, 720p, 480p, 360p, 240p but no audio only.
checking its download, there is infact a "0p" version which downloads to a 0p mp4
**Steps to reproduce:**

1. https://peertube2.cpy.re/videos/watch/07a78392-c981-42af-a7fa-46e23e593716
2. check resolution in video player
3. check resolution in downloads

**Describe the expected behavior**
0p should also show in video player
**Additional information**

![Screenshot_20210129_222212](https://user-images.githubusercontent.com/39449563/106304125-f921a600-6280-11eb-8576-dfae820ebaa6.png)
![Screenshot_20210129_222259](https://user-images.githubusercontent.com/39449563/106304134-fcb52d00-6280-11eb-8c88-bb96c7ed4622.png)

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by kontrollanten** [comment] 2021-01-29 17:51
Hi, this is a duplicate of #3281

**Comment by test2a** [comment] 2021-01-29 18:14
Should I close this one or?

**Closed** 2021-01-29 18:30 UTC
Labels: Type: Duplicate :loop:
