### ISSUE TITLE
Transcoding job marked as completed upon failure

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#3596] opened 2021-01-14 11:08 UTC
**Describe the current behavior**
When a transcoding job [returns stderr upon end](https://www.npmjs.com/package/fluent-ffmpeg#end-processing-finished) it won't be respected and the job will be marked as completed.

https://github.com/Chocobozzz/PeerTube/blob/5ec8a71f8471bbbd6b8e77bae2550cc28930f9ab/server/helpers/ffmpeg-utils.ts#L623-L627

**Steps to reproduce:**

1. Start a transcoding job.
2. Stop PeerTube before the job ends.
3. Start PeerTube.
4. The job is marked as completed but the video won't work.

**Describe the expected behavior**
Mark the job as failed.

* PeerTube instance:
  * version: 3.0.1
  * NodeJS version:
  * Ffmpeg version: 4.2.4

**Comment by Chocobozzz** [comment] 2021-01-14 12:39
Hi,

ffmpeg log data on `stderr` so it doesn't mean the command failed

**Comment by kontrollanten** [comment] 2021-01-14 12:53
Aha. Then it's hard to determine whether it failed or not. In my case it also had an error in `stderr`.

**Comment by Chocobozzz** [comment] 2021-01-14 13:06
What was this error? The job should fail if ffmpeg returns an error status code

**Comment by kontrollanten** [comment] 2021-01-14 15:43
```
ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
libavutil      56. 31.100 / 56. 31.100
libavcodec     58. 54.100 / 58. 54.100
libavformat    58. 29.100 / 58. 29.100
libavdevice    58.  8.100 / 58.  8.100
libavfilter     7. 57.100 /  7. 57.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  5.100 /  5.  5.100
libswresample   3.  5.100 /  3.  5.100
libpostproc    55.  5.100 / 55.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/var/www/peertube/storage/streaming-playlists/hls/d8d1cc73-f2fe-4a06-adc0-80ba85da0905/d8d1cc73-f2fe-4a06-adc0-80ba85da0905-480-fragmented.mp4':
Metadata:
  major_brand     : iso5
  minor_version   : 512
  compatible_brands: iso6mp41
  encoder         : Lavf58.29.100
Duration: 00:36:29.76, start: 0.000000, bitrate: 255 kb/s
  Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 253 kb/s (default)
  Metadata:
    handler_name    : SoundHandler

Codec AVOption g (set the group of picture (GOP) size) specified for output file #0 (/var/www/peertube/storage/streaming-playlists/hls/d8d1cc73-f2fe-4a06-adc0-80ba85da0905/720.m3u8) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
Codec AVOption level (Specify level) specified for output file #0 (/var/www/peertube/storage/streaming-playlists/hls/d8d1cc73-f2fe-4a06-adc0-80ba85da0905/720.m3u8) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.

[hls @ 0x55674d8ce480] Opening '/var/www/peertube/storage/streaming-playlists/hls/d8d1cc73-f2fe-4a06-adc0-80ba85da0905/d8d1cc73-f2fe-4a06-adc0-80ba85da0905-720-fragmented.mp4' for writing
Output #0, hls, to '/var/www/peertube/storage/streaming-playlists/hls/d8d1cc73-f2fe-4a06-adc0-80ba85da0905/720.m3u8':
Metadata:
  encoder         : Lavf58.29.100
  Stream #0:0: Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 253 kb/s (default)
Stream mapping:
Stream #0:0 -> #0:0 (copy)
Press [q] to stop, [?] for help
size=N/A time=00:22:48.02 bitrate=N/A speed=2.73e+03x    
size=N/A time=00:36:29.73 bitrate=N/A speed= 750x    
video:0kB audio:67728kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
```

More specific I'm thinking of `Codec AVOption g (set the group of picture (GOP) size) specified for output file #0 (/var/www/peertube/storage/streaming-playlists/hls/d8d1cc73-f2fe-4a06-adc0-80ba85da0905/720.m3u8) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.`. But maybe that's not an error?

**Comment by Chocobozzz** [comment] 2021-01-15 09:23
Your input file seems wrong, there is no video stream :thinking: 

What are your VOD transcoding options? And how did you upload this file? Is it a FLAC upload?

**Comment by kontrollanten** [comment] 2021-01-15 09:38
I imported it from Vimeo. I did the following

1) Import video from Vimeo
1) Wait until import job is done and transcoding starts
1) Restart PeerTube

**Comment by rigelk** [comment] 2021-01-16 13:48
@kontrollanten could you answer https://github.com/Chocobozzz/PeerTube/issues/3596#issuecomment-760776563 ?

**Comment by kontrollanten** [comment] 2021-01-16 16:43
HLS
* Audio only
* 240p
* 360p
* 480p
* 720p

How do I know if it's FLAC? This is the video source https://www.youtube.com/watch?v=QYR5LCDfnP4

**Comment by kontrollanten** [comment] 2021-01-18 11:12
Yes, I can reproduce it. It seems that it only gets broken if I restart during the 1080p transcoding job though.

**Scenario A - I restart PeerTube during the `type: optimize` transcoding job.**
The video works when I play it after all the jobs are done.

**Scenario B - I restart PeerTube during 1080p transcoding job (the job next after type: optimize).** 
Only audio plays and when I try to switch quality in the player there's only "Audio only" as an option. When I look at the transcoding jobs they're marked as completed, but they've only been running for 10-25 seconds each (which looks short to me).

**Scenario C - I restart PeerTube during 480p transcoding job (the job next after 0 and 1080p).** 
The video works when I play it after all the jobs are done.

**Comment by Chocobozzz** [comment] 2021-01-20 15:16
Thanks, I was able to reproduce. The issue:
 * The job generating the first HLS file is stalled because peertube was restarted while the job was running
 * Bull (queue manager) processes other transcoding jobs, and finally process the stalled job
 * Since the first job generates the highest resolution file, other jobs are broken because this highest resolution file is needed

Blocked by https://github.com/OptimalBits/bull/issues/1925

Workaround: only generate job after the first one was done (ie generate 480p when 720p is done, 360p when 480p is done etc)

**Comment by kontrollanten** [comment] 2021-01-21 13:51
Thanks for your research. Actually my point with this issue was to mark failed jobs (not only this case) as failed to make it possible to monitor if the published videos works as expected.

**Comment by Chocobozzz** [comment] 2021-01-21 13:56
Failed transcoding jobs should be marked as such. But your case is particular because ffmpeg did not consider it has failed.

**Closed** 2021-01-25 13:38 UTC
Labels: Component: Transcoding, Status: Blocked :hand:, Type: Bug :bug:
