### ISSUE TITLE
resume uploads

### ISSUE THREAD

**Issue by 6543** [Chocobozzz/PeerTube#1568] opened 2019-01-24 23:11 UTC
It would be nice if the uploader notice if there was already a try to upload a video witch has the same hash and can use the parts wich are already on the server to go streat to the breaking point.

But of course the unfinished uploads should be only temporarly ...

what do you think about?

**Comment by bootlicker** [comment] 2019-01-24 23:16
I agree, i would like this feature

**Comment by rigelk** [comment] 2019-01-25 03:31
This is a duplicate of #324

**Closed** 2019-01-25 03:31 UTC
