### ISSUE TITLE
"This video is already being transcoded" but the video doesn't seem to be transcoding (even after admin importing)

### ISSUE THREAD

**Issue by JacksonChen666** [Chocobozzz/PeerTube#5863] opened 2023-06-29 19:43 UTC
### Describe the current behavior

After importing a video that now has 0 HLS stream files (I have a copy, but peertube thinks it has no copy right now because I have deleted them in peertube) on an HLS instance with remote runners, it doesn't seem to transcode. I tried to get it to transcode, but that didn't seem to work either.

Nothing new in runner jobs.

```
Job: 5
Type: video-file-import
Processed on 6/29/23, 9:29:10.200 PM
Finished on 6/29/23, 9:29:32.178 PM

{
  "videoUUID": "2de91863-448d-4121-9e4f-7a2084359a0d",
  "filePath": "/var/www/exploding entities plugin showcase.mp4"
}
```

### Steps to reproduce

1. Have remote runners setup
2. Only have HLS enabled
3. Use create-import-video-file-job.js on a video
4. Go to `/admin/videos/list` on instance
5. Click "Run HLS transcoding" on the imported video
6. Get error "This video is already being transcoded"

### Describe the expected behavior

After importing through the CLI tools, the file should start to be transcoded.

### Additional information

* PeerTube instance: videos.jacksonchen666.com
  * URL: (What do you want? The video? It doesn't work of course because the HLS files are gone from peertube)
  * Version: 5.2.0
  * NodeJS version: v16.18.1
  * Ffmpeg version: 6.0

* Browser name, version and platforms on which you could reproduce the bug: LibreWolf 114.0.1-2 macOS 13.4.1
* Link to browser console log if relevant: See below
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): See below

<details><summary>Browser console log</summary>

```
21:33:43.919 XHRPOST
https://videos.jacksonchen666.com/api/v1/videos/280589/transcoding
[HTTP/2 409 Conflict 105ms]

21:33:44.030 Backend returned code 409, errorMessage is: This video is already being transcoded main.18895fd6dd4b2857.js:3:572887
21:33:44.033 Error: This video is already being transcoded main.18895fd6dd4b2857.js:3:572887
```

</details>

<details><summary>Server logs</summary>

```
Jun 29 21:33:44 laptop-server peertube[675602]: [videos.jacksonchen666.com:443] 2023-06-29 21:33:44.094 info: 84.236.0.0 - - [29/Jun/2023:19:33:44 +0000] "POST /api/v1/server/logs/client HTTP/1.0" 204 - "https://videos.jacksonchen666.com/admin/videos/list?search=isLive:false%20isLocal:true%20exploding" "Firefox"
Jun 29 21:33:44 laptop-server peertube[675602]: [videos.jacksonchen666.com:443] 2023-06-29 21:33:44.099 error: Client log: Error: This video is already being transcoded {
Jun 29 21:33:44 laptop-server peertube[675602]:   "username": "jacksonchen666",
Jun 29 21:33:44 laptop-server peertube[675602]:   "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/114.0",
Jun 29 21:33:44 laptop-server peertube[675602]:   "url": "https://videos.jacksonchen666.com/admin/videos/list?search=isLive:false%20isLocal:true%20exploding"
Jun 29 21:33:44 laptop-server peertube[675602]: }
Jun 29 21:33:44 laptop-server peertube[675602]: [videos.jacksonchen666.com:443] 2023-06-29 21:33:44.101 info: 84.236.0.0 - - [29/Jun/2023:19:33:44 +0000] "POST /api/v1/server/logs/client HTTP/1.0" 204 - "https://videos.jacksonchen666.com/admin/videos/list?search=isLive:false%20isLocal:true%20exploding" "Firefox"
```

</details>

**Comment by Chocobozzz** [comment] 2023-07-03 08:40
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/5355

**Comment by Chocobozzz** [comment] 2023-07-12 08:37
Hi,

The `create-import-video-file` script should be used to replace a specific resolution. So we don't want to run again transcoding.

To replace all resolutions with a new version of the video, see https://github.com/Chocobozzz/PeerTube/issues/1845

**Closed by Chocobozzz** 2023-07-12 08:37 UTC
Labels: Status: To Reproduce
