### ISSUE TITLE
S3 (or similar) external cloud storage support [Feature request]

### ISSUE THREAD

**Issue by Shleeble** [Chocobozzz/PeerTube#1784] opened 2019-04-24 16:43 UTC
Basic: My Mastodon Instance use S3 to storage all data "offsite".. this has a number of benefits
1) If my server dies, as long as the database is backed up, I can rebuild the server and continue from there quickly.
2) Cloud provider can handle disk/storage and IO.. Backups are generally covered and safe. AWS S3 for example is cached globally via their CDN blah blah blah blah blah

So please allow me to follow this pattern. :)

Advanced: Uploading a video to S3 could allow us to use Lamdba to trigger transcoding to different formats on demand in the cloud instead of locally....

**Comment by Shleeble** [comment] 2019-04-24 17:52
notes for the advanced idea:
https://dev.to/hmschreck/building-a-super-cheap-transcoder-using-aws-lambda-1j76
https://intoli.com/blog/transcoding-on-aws-lambda/
https://news.ycombinator.com/item?id=16976238

**Comment by Chocobozzz** [comment] 2019-04-25 06:57
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/147

**Closed by Chocobozzz** 2019-04-25 06:57 UTC
