### ISSUE TITLE
It is not possible to add large files to the server

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#5998] opened 2023-10-10 09:31 UTC
### Describe the current behavior

I thought that the error was only in the latest versions of the nightly builds, but when I installed release 5.2.1 on the test server, the error was repeated. In previous versions, everything worked fine, I could add a file up to 12G in size, this is the default limitation in the Nginx configuration file.

Now a 1.6G file is being added to the server without errors.

But if I add a 2.5G file or more, then an error appears

![Снимок экрана 2023-10-10 121938](https://github.com/Chocobozzz/PeerTube/assets/11453567/eb67685f-c18a-40e6-adcc-538ecc3a1516)
![Снимок экрана 2023-10-10 122125](https://github.com/Chocobozzz/PeerTube/assets/11453567/97676409-4448-408a-a184-7c6693485068)
![Снимок экрана 2023-10-10 122205](https://github.com/Chocobozzz/PeerTube/assets/11453567/47e23d29-8130-4505-ab38-e659e27901ff)

There are no errors in the peertube.error.log file.

### Steps to reproduce

1. Upload a file with a size of 2.5G or more
2. Wait for the download to finish and get an error

### Additional information

* PeerTube instance:
  * URL: https://video.ustim.ru
  * Version: 5.2.1 (5.2.1-nightly-2023-10-10)
  * NodeJS version: v18.17.1
  * Ffmpeg version: 5.1.3-1

* Browser name, version and platforms on which you could reproduce the bug: yandex (chrome)

**Comment by Alterak** [comment] 2023-10-10 10:52
probably a problem with some files .MKV, because I was able to add a .MP4 (2.2G) file and a file .MOV (4.2G) and other files .MKV (1.3G)

**Comment by Chocobozzz** [comment] 2023-10-11 06:38
Hi,

Can you send me by email a link to download your MKV so I can reproduce?

**Comment by Alterak** [comment] 2023-10-11 07:34
> Hi,
> 
> Can you send me by email a link to download your MKV so I can reproduce?

I have sent you a link to the email address that you have in your GitHub profile.

**Comment by Chocobozzz** [comment] 2023-10-12 13:36
Thanks! I think it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/58fda6d416d896c3cf09d6ca608a7461172ffc7b

Please try tomorrow with the latest nightly build and comment if it doesn't resolve the bug on your side (I'm not 100% sure because the error in your log is not the same as mine on my local computer).

**Closed by Chocobozzz** 2023-10-12 13:36 UTC
Labels: Type: Bug :bug:, Component: Upload

**Comment by Alterak** [comment] 2023-10-13 05:18
> Thanks! I think it should be fixed by [58fda6d](https://github.com/Chocobozzz/PeerTube/commit/58fda6d416d896c3cf09d6ca608a7461172ffc7b)
> 
> Please try tomorrow with the latest nightly build and comment if it doesn't resolve the bug on your side (I'm not 100% sure because the error in your log is not the same as mine on my local computer).

Hi, I have updated my instance to version **5.2.1-nightly-2023-10-13** . Now everything has become great! You're cool! Thanks!

**Comment by Alterak** [comment] 2023-10-13 05:29
> Thanks! I think it should be fixed by [58fda6d](https://github.com/Chocobozzz/PeerTube/commit/58fda6d416d896c3cf09d6ca608a7461172ffc7b)
> 
> Please try tomorrow with the latest nightly build and comment if it doesn't resolve the bug on your side (I'm not 100% sure because the error in your log is not the same as mine on my local computer).

Только теперь автоматически появились Заголовки -).

![Снимок экрана 2023-10-13 082220](https://github.com/Chocobozzz/PeerTube/assets/11453567/cf2970ba-17d3-48a1-ab49-ee893e236363)

И полоска проигрывания видео разделилась на 2 части, хотя заголовков 12 штук

![image](https://github.com/Chocobozzz/PeerTube/assets/11453567/f43733e1-9256-4f31-8349-7729c845f4f8)

**Comment by Chocobozzz** [comment] 2023-10-13 06:47
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/81a51d4bb1ff5f657f605acca67926c9f2436235
