### ISSUE TITLE
Local storage filled during API upload.

### ISSUE THREAD

**Issue by stevespaw** [Chocobozzz/PeerTube#6019] opened 2023-10-31 14:32 UTC
### Describe the current behavior

We also have crashed the server with a large number of imports via API, Local storage filled before transcode and move to object storage. A GUI setting for a number to hold would be huge benefit for us. We are looking to migrate some people from Vimeo and BrightCove, but we have to do it by hand in batches because of this.

Some method of putting more that "x" in a queue.

The same issue can happen with a large channel sync..

Thanks!

### Steps to reproduce

1. Upload a large list of videos via API script
2. Watch the local video storage climb
3. Too many = Crash

### Additional information

* PeerTube instance:

  * Version: 5.2.1

**Comment by Chocobozzz** [comment] 2023-11-02 08:28
Hi,

Thanks for the issue I know understand your message on the forum. Putting "on hold" every upload/import etc seems difficult (to develop but also in UX perspective). I guess transcoding is the root cause of the bottleneck no?

**Comment by Chocobozzz** [comment] 2023-11-07 07:42
Closing in favour of https://github.com/Chocobozzz/PeerTube/issues/6024

**Closed by Chocobozzz** 2023-11-07 07:42 UTC
Labels: Status: Waiting for answer
