### ISSUE TITLE
Send mail to all verified users

### ISSUE THREAD

**Issue by M-Stenzel** [Chocobozzz/PeerTube#4877] opened 2022-03-24 13:15 UTC
Hi team,

periodically I need to send an email to all the mail verified users of the instance, for example when there is a scheduled downtime or when there are some other issues that need to be communicated.

How can I extract all of the mail addresses of the instance (from all the users who verified their mail address) in order to give this information?
Of course I do not want to send any mails to users who are not verified, nor do I want to send mail to users who closed their account.

TIA,

Martin.

**Comment by Alterak** [comment] 2022-03-28 05:41
> Hi team,
> 
> periodically I need to send an email to all the mail verified users of the instance, for example when there is a scheduled downtime or when there are some other issues that need to be communicated.
> 
> How can I extract all of the mail addresses of the instance (from all the users who verified their mail address) in order to give this information? Of course I do not want to send any mails to users who are not verified, nor do I want to send mail to users who closed their account.
> 
> TIA,
> 
> Martin.

I would also like to send mail to users. It would be nice to add this feature to Pertube.

**Comment by Chocobozzz** [comment] 2022-04-08 12:02
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/3805

**Closed by Chocobozzz** 2022-04-08 12:02 UTC
Labels: Type: Question
