### ISSUE TITLE
Click Event is passed through to PIP button from settings

### ISSUE THREAD

**Issue by Mastercuber** [Chocobozzz/PeerTube#4329] opened 2021-08-17 19:18 UTC
**Describe the current behavior**
When I view a video and want to change the quality, but the PIP button is exactly behind the quality I want to choose, then the PIP button action is triggered. The resolution stays the same.

The same applies to all other actions in the settings menu like subtitle selection. 

**Steps to reproduce:**

1. view a video with at least 3 different resolutions
2. click on settings 
3. click on quality
4. when hovering the video with the cursor the little PIP button appears behind one resolution or the "back" button
5. when clicking the resolution, or the back button, hiding the PIP Button, then the click event is passed through to the PIP button and not fired on the settings menu

**Describe the expected behavior**
When the settings menu is open the click event should not be triggering the PIP button action.

**Additional information**
I tested this bug on 2 different instances.

* PeerTube instance:
  * URL: 
  * version: both 3.3.0
  * NodeJS version:
  * Ffmpeg version:

I tested this on 2 Browsers. First is Firefox 91.0 on Ubuntu 20.04.2 LTS and the second one is Chrome Version 86.0.4240.183

This issue only appeared with Firefox. Chrome didn't show the PIP button on videos for me.

**Comment by Chocobozzz** [comment] 2021-08-18 07:16
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/3275

**Closed by Chocobozzz** 2021-08-18 07:16 UTC

**Comment by Mastercuber** [comment] 2021-08-18 19:48
I think I need to improve my "search before opening an issue" skill :laughing: :thinking:
