### ISSUE TITLE
IPv6 Release Download

### ISSUE THREAD

**Issue by oxzi** [Chocobozzz/PeerTube#4277] opened 2021-07-26 15:14 UTC
**Describe the problem**
The releases are only hosted on GitHub, which lacks support for IPv6.
Thus, on IPv6-only machines one has to take detours to install PeerTube.

However, your website, joinpeertube.org, supports the current version of the Internet Protocol.\I would love to see an IPv6-enabled mirror of the downloads.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
host -t AAAA github.com
github.com has no AAAA record
```

**Comment by scanlime** [comment] 2021-07-27 20:22
Does PeerTube support IPv6-only machines? I would expect federation, imports, and email to be a problem as well if you're turning off support for the most widely used protocol.

**Comment by oxzi** [comment] 2021-08-01 18:11
@scanlime: Thanks for your concerns. I am currently deploying PeerTube to an IPv6-only environment and so far, it mostly works. There are some issues which we are addressing.

However, there is no reason to lock someone out due to concerns about a twenty year old protocol.

**Comment by scanlime** [comment] 2021-08-01 20:45
pretty ageist discriminating against IPv4 like that 😅
do you also remove old tech like cookies and JPEG and HTTPS?

**Comment by oxzi** [comment] 2021-08-01 21:25
It should be known that IPv4 addresses are becoming scarce. Otherwise, there is even a [massive Wikipedia article on this topic](https://en.wikipedia.org/wiki/IPv4_address_exhaustion).
As such, I would ask you to stop derailing or trolling here.

**Comment by scanlime** [comment] 2021-08-01 21:29
not trying to derail just aiming for some honesty here. It's obvious why supporting IPv6 would be good, but supporting the removal of IPv4 is a different request, and if you want to achieve some notion of purity on your setup that's a very different goal to aim for than achieving compatibility with all widely used standards.

**Comment by ROBERT-MCDOWELL** [comment] 2021-08-01 22:43
@scanlime
the problem is not all DC offers ipv6 to dedicated servers... on the other hand, it started to be some huge speculation on ipv4 market as most of them are taken by DCs around the world who they are themselves renting them from the IANA.

**Comment by mxmehl** [comment] 2021-08-05 10:42
> It's obvious why supporting IPv6 would be good, but supporting the removal of IPv4 is a different request, and if you want to achieve some notion of purity on your setup that's a very different goal to aim for than achieving compatibility with all widely used standards.

@oxzi does not intend to "remove" IPv4, but support IPv6, a well-known, well-standardised and modern internet protocol.

Currently, people and organisations who do not have (enough) IPv4 addresses to run services like peertube are left in the dark here. This should be fixed, ideally by github, but subsequently also by everyone offering releases on github.

**Comment by Chocobozzz** [comment] 2021-12-16 13:36
Done in https://github.com/Chocobozzz/PeerTube/commit/c501f44119c8e63a2519e12085dc4fca4e874f3f

**Closed by Chocobozzz** 2021-12-16 13:36 UTC
Labels: Type: Maintenance :construction_worker_woman:, Type: Enhancement :sparkles:

**Comment by vincib** [comment] 2025-06-07 20:56
Sorry to reopen it, but 7.2.0 is currently not available there, 

I don't need it there, but this may hide some other bugs...

**Comment by Chocobozzz** [comment] 2025-06-10 06:37
Thanks! It should be fixed
