### ISSUE TITLE
Resume upload transcoding in case of server crash or reboot

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#5157] opened 2022-07-31 16:18 UTC
### Describe the problem to be solved

Tested a reboot while the server was transcoding resulted in a fatal disruption.

### Describe the solution you would like

Find a way to restart or resume the transcoding from the original file after crash or reboot.

**Comment by Chocobozzz** [comment] 2022-08-01 08:16
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/5078

**Closed by Chocobozzz** 2022-08-01 08:16 UTC
