### ISSUE TITLE
RSA PRIVATE KEY not found from openssl output

### ISSUE THREAD

**Issue by mycloudmatrix** [Chocobozzz/PeerTube#5144] opened 2022-07-24 13:25 UTC
### Describe the current behavior

Users receiving the following error when creating a channel in peertube instance:

"RSA PRIVATE KEY not found from openssl output..."

User is created.

### Steps to reproduce

1. Create account at https://peertube.noiz.ie.
2. Error presents in browser, but user still creates.

Output from /var/log/nginx/peertube.error.log:
2022/07/24 21:21:18 [crit] 11241#11241: *4951 SSL_do_handshake() failed (SSL: error:0A000126:SSL routines::unexpected eof while reading) while SSL handshaking, client: 185.***.***.43, server: 0.0.0.0:443
2022/07/24 21:21:18 [crit] 11241#11241: *4953 SSL_do_handshake() failed (SSL: error:0A00006C:SSL routines::bad key share) while SSL handshaking, client: 185.***.***.43, server: 0.0.0.0:443

### Describe the expected behavior

User to be created without error.

### Additional information

* PeerTube instance:
  * URL: https://peertube.noiz.ie/
  * Version: Latest as of July 24th 2022
  * NodeJS version: v16.16.0
  * Ffmpeg version: 4.4.2-0ubuntu0.22.04.1

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): Included above

**Comment by Chocobozzz** [comment] 2022-07-25 07:53
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/4901

**Closed by Chocobozzz** 2022-07-25 07:53 UTC
