### ISSUE TITLE
Subtitles: full text under the video

### ISSUE THREAD

**Issue by tdelmas** [Chocobozzz/PeerTube#4035] opened 2021-05-02 21:44 UTC
**Describe the problem to be solved**

Quickly find information in a video and go to the timestamp where it is

**Describe the solution you would like:**

Under the video, after the description, a toggle block, closed by default (click on "subtitles" to see what should happen):
<details open>
 <summary>Subtitles</summary>
00:01 Hello folks !

10:45 About PeerTube...
</details>

---
So text could be search using CTRL+F in your browser (or even found by a search engine), and to go the specific section on the video, you just had to click on the timestamp or the sentence, as they would be links to the corresponding timestamp on the video.

If multiple languages are available, a dropdown should be displayed in the beginning.

Ideally, an anchor would be available to link to a specific sentence, for example `#subtitles>10:45`

**Comment by Chocobozzz** [comment] 2021-05-03 06:54
Thanks for reporting this issue, but this is a duplicate of s

**Closed by Chocobozzz** 2021-05-03 06:54 UTC

**Comment by tdelmas** [comment] 2021-05-03 09:43
Yes, thank you @Chocobozzz and sorry to have miss that issue!
