### ISSUE TITLE
Transcoding

### ISSUE THREAD

**Issue by filmaidykai** [Chocobozzz/PeerTube#1378] opened 2018-11-06 16:15 UTC
Hey guys Im usings peertube 1.0.0 so just wanna ask I make enable just 480p for transcoding 
 but if resolution is bigger so after transcoding system shows 480p and 720p or sometimes 480p and 1080p like on this video 
http://hostyour.tv/videos/watch/5d6f0528-a366-4c3f-95c1-e10e984179f2 so possible to make just 480p?

**Comment by Nutomic** [comment] 2018-11-06 16:19
This is a duplicate of #1030.

**Closed** 2018-11-06 16:49 UTC
Labels: Type: Duplicate :loop:
