### ISSUE TITLE
recreate removed account optional

### ISSUE THREAD

**Issue by 01123581321345589144233** [Chocobozzz/PeerTube#5054] opened 2022-06-15 14:16 UTC
### Describe the problem to be solved

I have a account with a specific name, and this is beeing remove. but i will recreate this account with the same name also channel name, but it doesnt work.
error:
Another actor (account/channel) with this name on this instance already exists or has already existed.

how can i optional enable this ? so i can recreate this name

### Describe the solution you would like

solution: make a extra option in the admin pannel so only admin can recreate old usernames and channel names.
this can makes in the user creation page.

**Comment by Chocobozzz** [comment] 2022-06-16 06:17
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/3269

**Closed by Chocobozzz** 2022-06-16 06:17 UTC
