### ISSUE TITLE
TypeError: Expected a string but received a null

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#5822] opened 2023-06-06 20:04 UTC
### Describe the current behavior

We see a lot of `TypeError: Expected a string but received a null` errors in our logs. I can't find any way to reproduce them though. Maybe just clarify the error message to give some hints on which URL causing the issue?

```
{
	"err": "TypeError: Expected a string but received a null
    at assertString (/var/www/peertube/versions/peertube-v5.1.0/node_modules/validator/lib/util/assertString.js:17:11)
    at Object.isInt (/var/www/peertube/versions/peertube-v5.1.0/node_modules/validator/lib/isInt.js:16:29)
    at Function.<anonymous> (/var/www/peertube/versions/peertube-v5.1.0/dist/server/lib/client-html.js:44:38)
    at Generator.next (<anonymous>)
    at /var/www/peertube/versions/peertube-v5.1.0/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/var/www/peertube/versions/peertube-v5.1.0/node_modules/tslib/tslib.js:163:16)
    at Function.getWatchHTMLPage (/var/www/peertube/versions/peertube-v5.1.0/dist/server/lib/client-html.js:42:24)
    at /var/www/peertube/versions/peertube-v5.1.0/dist/server/controllers/client.js:101:53
    at Generator.next (<anonymous>)
    at /var/www/peertube/versions/peertube-v5.1.0/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/var/www/peertube/versions/peertube-v5.1.0/node_modules/tslib/tslib.js:163:16)
    at generateWatchHtmlPage (/var/www/peertube/versions/peertube-v5.1.0/dist/server/controllers/client.js:96:20)
    at /var/www/peertube/versions/peertube-v5.1.0/dist/server/middlewares/async.js:21:32
    at Layer.handle [as handle_request] (/var/www/peertube/versions/peertube-v5.1.0/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/www/peertube/versions/peertube-v5.1.0/node_modules/express/lib/router/index.js:328:13)
    at /var/www/peertube/versions/peertube-v5.1.0/node_modules/express/lib/router/index.js:286:9
    at param (/var/www/peertube/versions/peertube-v5.1.0/node_modules/express/lib/router/index.js:365:14)
    at param (/var/www/peertube/versions/peertube-v5.1.0/node_modules/express/lib/router/index.js:376:14)
    at param (/var/www/peertube/versions/peertube-v5.1.0/node_modules/express/lib/router/index.js:376:14)
    at Function.process_params (/var/www/peertube/versions/peertube-v5.1.0/node_modules/express/lib/router/index.js:421:3)
    at next (/var/www/peertube/versions/peertube-v5.1.0/node_modules/express/lib/router/index.js:280:10)
    at Function.handle (/var/www/peertube/versions/peertube-v5.1.0/node_modules/express/lib/router/index.js:175:3)
    at router (/var/www/peertube/versions/peertube-v5.1.0/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/var/www/peertube/versions/peertube-v5.1.0/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/www/peertube/versions/peertube-v5.1.0/node_modules/express/lib/router/index.js:328:13)
    at /var/www/peertube/versions/peertube-v5.1.0/node_modules/express/lib/router/index.js:286:9",
	"level": "error",
	"message": "Error in controller.",
	"label": "",
	"timestamp": "2023-05-29T07:43:11.670Z"
}
```

### Additional information

* PeerTube instance:
  * Version: 5.1.0

**Comment by Chocobozzz** [comment] 2023-06-07 06:15
Please paste the HTTP request path of this error

**Comment by Chocobozzz** [comment] 2023-07-12 07:24
@EricGuic Do you have the HTTP path of the request that led to this error, since you had the same issue in https://github.com/Chocobozzz/PeerTube/issues/5842?

**Comment by EricGuic** [comment] 2023-07-21 13:14
Hi Chocobozzz, sorry but I don't see the error in the last week log. (I should wait for the return of my colleague to see older entries).

**Comment by Chocobozzz** [comment] 2023-07-26 08:50
Okay, then the root cause of this issue should be fixed by https://github.com/Chocobozzz/PeerTube/commit/69e3f2049f01a9aa78b81889ac040a10f925e590

**Closed by Chocobozzz** 2023-07-26 08:50 UTC
Labels: Status: Waiting for answer
