### ISSUE TITLE
Uploader fails with ".MOV" extensions (SequelizeValidationError)

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#4193] opened 2021-06-17 06:59 UTC
**Describe the current behavior**

This is via a user who was uploading on iOS successfully before the 3.2.1 update, and now they consistently hit failures. They sent me enough info to narrow down the issue in the server-side logs today, and it looks like after many successfully uploaded chunks, the server finally returns a 500 and logs this traceback:

```
SequelizeValidationError: Validation error: \".MOV\" is not a valid extname.\n
    at InstanceValidator._validate (/var/www/peertube/versions/peertube-v3.2.1/node_modules/sequelize/lib/instance-validator.js:78:13)\n
    at runMicrotasks (<anonymous>)\n
    at processTicksAndRejections (node:internal/process/task_queues:94:5)\n    at async InstanceValidator._validateAndRunHooks (/var/www/peertube/versions/peertube-v3.2.1/node_modules/sequelize/lib/instance-validator.js:111:7)\n
    at async InstanceValidator.validate (/var/www/peertube/versions/peertube-v3.2.1/node_modules/sequelize/lib/instance-validator.js:93:12)\n
    at async VideoFileModel.save (/var/www/peertube/versions/peertube-v3.2.1/node_modules/sequelize/lib/model.js:3877:7)
```

After that, I verified that the issue is indeed related to the filename only, and it's browser-independent. The steps below work in firefox.

**Steps to reproduce:**

1.  Upload "test.mov", works successfully
2. Upload "test.MOV", uploader reports an internal server error

**Describe the expected behavior**

No regression from previous release

**Additional information**

* PeerTube instance:
  * URL: diode.zone
  * version: 3.2.1
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug: Any? (tested on safari & firefox)
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by SMJ** [comment] 2021-06-20 01:37
Seeing this as well when editing videos in iMovie on the iPhone and attempting to upload the result to a peertube 3.2.1 instance.  Default extension from IOS iMovie is .MOV.  There are possibly other cases as well which are probably handled in fluent-ffmpeg/lib/utils.js

**Comment by AnonymousWebHacker** [comment] 2021-06-23 22:29
Checked, the same thing happens to me

**Comment by Chocobozzz** [comment] 2021-06-24 08:57
Duplicate of https://github.com/Chocobozzz/PeerTube/issues/4152

**Closed by Chocobozzz** 2021-06-24 08:57 UTC
