### ISSUE TITLE
Optionally changing support info for an entire channel

### ISSUE THREAD

**Issue by XenonFiber** [Chocobozzz/PeerTube#1319] opened 2018-10-20 17:23 UTC
Adding up to date links and info to every video in a channel can be tedious. Having this as a choice would make it easier.

**Comment by Chocobozzz** [comment] 2018-10-22 07:56
Hello,

Thanks for the issue but I think it's a duplicate of https://github.com/Chocobozzz/PeerTube/issues/827

**Closed** 2018-11-16 14:46 UTC
Labels: Type: Duplicate :loop:
