### ISSUE TITLE
Uploading music cuts the file short

### ISSUE THREAD

**Issue by Midek** [Chocobozzz/PeerTube#2153] opened 2019-10-01 18:11 UTC
**What happened?**
When uploading sound files (mp3, flac) the file seems to be transcoded incorrectly, and the output file is shorter than original file.
On the videos list it does show the proper time, but after playing it its short.
Reuploading the file results in different length.
**What do you expect to happen instead?**
Music file should have the same length as the original.
**Steps to reproduce:**

1. Upload mp3 or flac file.

2. Listen to the resulting video

**Additional information**
* PeerTube version or URL: 
v1.4.1
https://tube.midov.pl/
* Browser name/version:
Chromium 77
Firefox 69
* NodeJS version:
v10.16.3
* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):
https://cloud.midov.pl/s/FCBEqC9XziEYBPk

**Comment by rigelk** [comment] 2019-10-06 17:16
@Midek could you please provide us with the incriminated audio file source, so that we can replicate the bug?

**Comment by Midek** [comment] 2019-10-06 17:54
It seems to happen with pretty much any mp3 or flac file i try.
Here are example mp3 and flac files that i tried recently:
https://cloud.midov.pl/s/F2CPfrFzjYERezT
Im also attaching a cover files for them, since it would not let me upload otherwise.

**Comment by Steffo99** [comment] 2019-10-16 22:41
I have the same issue on my instance...

It happens only on 50% of the uploads, though.

If you need help in reproducing the issue please tell me what to do :)

**Comment by Steffo99** [comment] 2019-10-17 09:31
I've been told from some users of my instance that the bug doesn't manifest if you wait a minute or two before pressing the publish button on the upload page. 

Perhaps the problem is not with the transcoding...?

**Comment by Midek** [comment] 2019-10-17 09:51
I can confirm, i have uploaded 3min18s file and waited for some time before pressing publish - now the video has lenght of 3 minutes and 20 seconds (longer than the music file)
Then i have uploaded 9min26s flac file, waited for ffmpeg process on the server to finish, and pressed publish - resulting video is 9min27s.
In both cases on the videos list in peertube it shows proper values, ie 3min18s for the first one and 9min26s for the second one.

**Comment by Chocobozzz** [comment] 2019-10-18 11:49
Thanks @Midek & @Steffo99, I managed to reproduce this issue. Should be fixed in https://github.com/Chocobozzz/PeerTube/commit/eba06469b70ffd722532881e40574d2a38a2a19b

See the ffmpeg bug tracker for the video that is longer than the audio: https://trac.ffmpeg.org/ticket/5456

**Closed by Chocobozzz** 2019-10-18 11:49 UTC
Labels: Component: Transcoding, Type: Bug :bug:
