### ISSUE TITLE
Playlists - Shuffle

### ISSUE THREAD

**Issue by spirillen** [Chocobozzz/PeerTube#6347] opened 2024-04-23 03:10 UTC
### Describe the problem to be solved

Not a problem... just a wish :smile: 

### Describe the solution you would like

When you have a playlist full of music, it could be very nice if you could shuffle it, both as a listener and a playlists maintainer (builder, owner)

We already have the `Stop autoplay nest` & `Loop playlist video`

**Comment by Chocobozzz** [comment] 2024-04-23 06:08
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/3148

**Closed by Chocobozzz** 2024-04-23 06:08 UTC
