### ISSUE TITLE
Extend PeerTube storage

### ISSUE THREAD

**Issue by Dremor** [Chocobozzz/PeerTube#1426] opened 2018-11-22 19:39 UTC
Hi,

I tried today Peertube (on https://peertube.fr ), and I have a suggestion.
As people may want to upload a lot of videos, they will soon enough get to the point that they hit the upload limit of the instance. As not everyone can create their own instance, we need a way to easily increase storage space. 
One of these way would be to make it possible to directly buy space from the instance owner, but this would increase burden on the instance administrator. Thus, I think we should add a way for the user to add storage themselves.

After some research I think we should start with WebDAV, as storage provider are quite widely available (Owncloud / Nextcloud, etc.), or even setup your own WebDAV server.

The idea would be to connect a Peertube account to a WebDAV server, by providing basic info (server URL, logins, maybe folder name), and then create a dedicated folder for storing the videos.

**Comment by Nutomic** [comment] 2018-11-22 20:15
Duplicate of #147.

Also I don't think this makes a lot of sense, because storage is really the smallest part of server cost. What's really expensive is CPU (for transcoding) and bandwidth.

**Comment by rigelk** [comment] 2018-11-22 21:38
It's not really a duplicate of #147 tough, because this issue is centered on user bringing their storage, whereas #147 is broader and seems to focus more on admin setup of external storage and it's integration with PeerTube.

**Comment by Chocobozzz** [comment] 2018-12-13 14:52
> One of these way would be to make it possible to directly buy space from the instance owner, but this would increase burden on the instance administrator. Thus, I think we should add a way for the user to add storage themselves.

I think they should run their own PeerTube instance instead.

**Closed by Chocobozzz** 2018-12-13 14:52 UTC
Labels: Type: Discussion :thought_balloon:

**Comment by Dremor** [comment] 2019-02-20 15:04
Not everyone have the technical knowledge how to do it, it would be easier for a content author to just configure a external storage provider than create his own instance.
