### ISSUE TITLE
Playing video on iPad doesn’t work

### ISSUE THREAD

**Issue by imc67** [Chocobozzz/PeerTube#2997] opened 2020-07-23 09:57 UTC
**What happened?**
Playing a video on an iPad in Safari (latest versions) in standard “desktop” view the video keeps spinning and not playing. When switching to “mobile” view it does work, also on iPhone.

**What do you expect to happen instead?**
Playing the video

**Steps to reproduce:**

1. Open Safari on iPad 

2. Go to URL of PeerTube 

3. If not in “desktop” view then switch to “desktop” view

4. Play the video

**Additional information**
* PeerTube version or URL: 2.3.0.
* Browser name/version: Safari on iPad, iOS 13.6
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment] 2020-07-23 14:08
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/2941

**Closed by Chocobozzz** 2020-07-23 14:08 UTC
