### ISSUE TITLE
Remove leading and trailing newlines and whitespace from translation markup

### ISSUE THREAD

**Issue by gunchleoc** [Chocobozzz/PeerTube#1793] opened 2019-05-01 07:37 UTC
Usually, when I translate `Cancel`, my translation memory will fill it out for me and I only have to confirm. When I translate it here, I get no hits at all from my translation memory, because the source string is `\n        Cancel        \n` with varying amounts of whitespace. So, I have to retranslate the same thing again and again... There are a lot of strings like that in `angle.po` and it would be great if they could be cleaned up.

**Comment by Chocobozzz** [comment] 2019-05-13 12:20
Blocked by https://github.com/angular/angular/issues/13114

**Comment by Chocobozzz** [comment] 2019-11-28 14:45
Is it still an issue with weblate?

**Comment by gunchleoc** [comment] 2019-11-28 17:31
I can't find "Cancel" anywhere on https://hosted.weblate.org/projects/peertube/android/gd/ so I have no easy way of confirming.

**Comment by Chocobozzz** [comment] 2019-11-29 07:54
The weblate peertube page is https://weblate.framasoft.org/projects/peertube/angular/

**Comment by gunchleoc** [comment] 2019-12-01 15:23
Thanks! The link in the original announcement when to somewhere else, so I tried looking for it myself. I was already wondering why there was only an Android app up there.

The issue seems to be gone now.

**Comment by gunchleoc** [comment] 2019-12-01 15:38
I spoke too soon, I am seeing lots of

    <newline>          Your video <placeholder> has been published<newline>

which should optimally be

    Your video <placeholder> has been published

I don't know how many already existing translations will break though if we fix this. Moving to Weblate has been a great help already.

I am currently translating the file off the original from GitHub because all untranslated segments have a copy of the English source strings in them.

**Comment by gunchleoc** [comment] 2019-12-03 08:39
I have taken a screenshot of an example off the original XLIFF from GitHub - the only difference between these 2 strings is superfluous whitespace.

![angular_example](https://user-images.githubusercontent.com/4095570/70033878-3f5d7580-15a8-11ea-9d70-0410d42a2159.png)

**Comment by Chocobozzz** [comment] 2020-08-25 13:37
Closing this issue: I can't reproduce anymore with this string: https://weblate.framasoft.org/translate/peertube/angular/fr_FR/?q=do+not+list&sort_by=-priority%2Cposition&offset=4

**Closed by Chocobozzz** 2020-08-25 13:37 UTC
Labels: Component: i18n :abcd:, Status: Blocked :hand:, Type: Bug :bug:
