### ISSUE TITLE
Implementation of global links like Matrix.to and others.

### ISSUE THREAD

**Issue by ivnvitx** [Chocobozzz/PeerTube#2911] opened 2020-06-28 14:30 UTC
Let's go straight to the point. Maybe this is already in the works? Please tell me if so. 

Do you know about [Matrix](https://matrix.org/)? It's a federated instant messaging protocol. It works fantastically. Just like PeerTube. But there is a massive difference when sharing links for certain chatrooms. **They can be shared with a common link**, no matter the matrix instance in use.

This is done with [**matrix.to**](https://matrix.to/). Go check it out! It is explained right there. Such a simple, beautiful idea. For any chatroom, you can generate a link that starts with `matrix.to/whatever`, and everybody knows what is the protocol used, and they can configure [**matrix.to**](https://matrix.to) to **directly redirect to your platform of choice**. 

This basically would destroy the **absolute boring experience** of having to copy a PeerTube link from other instance, open your instance of preference, paste it on the search bar and then being able to watch the video through your own account, with all your themes, the availability of the like, comment and follow features. All that is now done with the click of a button. 

All this hassle erased by a simple **peertube.central** kind of link, exactly parallel to [matrix.to](https://matrix.to), where you can configure your instance of choice for redirection. So any time someone shares the peertube.central link, it automatically takes you to your app or website of preference for watching that content. 

Other federated platforms, such as LBRY, a direct "competitor" also have this idea implemented.

With this system, you **avoid using browser extensions**, which are a half-baked solution, hard to mantain for all the different platforms, sometimes not even supported, and they make browsing a slower experience while also increasing [browser fingerprint](https://www.privacytools.io/browsers/#fingerprint).

I already [talked about this](https://github.com/Chocobozzz/PeerTube/issues/2851), but maybe I didn't express it right, so let's move the discussion here. I hope that now it is clear how important it is that we get a feature like this to really make PeerTube a thing for the general public.

**Comment by Chocobozzz** [comment] 2020-06-29 06:57
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/1540

**Closed by Chocobozzz** 2020-06-29 06:57 UTC
