### ISSUE TITLE
Video transcoding is left in an unclean state when ffmpeg is killed by OOM killer

### ISSUE THREAD

**Issue by lapin-b** [Chocobozzz/PeerTube#4031] opened 2021-05-01 14:06 UTC
**Describe the current behavior**

The transcoding queue works as expected, initiating a transcoding job whenever somebody uploads a video.

If the LXC container ever comes short of avaliable memory, the OOM killer springs into action and terminates processes (can be ffmpeg) to free up memory space. PeerTube handles this case and marks the job as failed with the following information:

```text
Job: XYZ
Type: video-transcoding
Processed on Apr 18, 2021, 9:32:34 PM
Finished on Apr 18, 2021, 9:32:38 PM
```
```json
{
  "type": "optimize-to-webtorrent",
  "videoUUID": "<video UUID>",
  "isNewVideo": true
}
```
```text
Error: ffmpeg was killed with signal SIGKILL
    at ChildProcess.<anonymous> (/var/www/peertube/versions/peertube-v3.1.0/node_modules/fluent-ffmpeg/lib/processor.js:180:22)
    at ChildProcess.emit (events.js:314:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
```

However, the killing of ffmpeg leaves the video in an unclean state where:

- The sound has been transcoded but there is no video;
- The video is unplayable and the notice still persists.

**Steps to reproduce:**

1. Have a container with low memory available condition, either have just enough memory to run PeerTube or have enough memory to run PeerTube but the container is somehow is close to memory exhaustion
2. Send a video to the instance
3. Transcoding is queued and begins processing
4. The OOM killer kills ffmpeg (could be simulated with terminating ffmpeg with SIGKILL ?)
5. The video is left in an unclean state

**Describe the expected behavior**

One expected behavior is that Peertube will, somehow requeue the job and try again or pick where it left off. The server can retry the transcode job a few times before having an admin queue the transcode job manually.

Possibilities can be discussed.

**Additional information**

* PeerTube instance:
  * URL: peertube.ch
  * version: 3.1.0
  * NodeJS version: 12.21.0
  * Ffmpeg version: 4.1.6-1~deb10u1

* Browser name, version and platforms on which you could reproduce the bug: *not relevant; not a client issue*
* Link to browser console log if relevant: *not relevant; not a client issue*
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): *see above for the failed transcoding job description*

**Comment by Chocobozzz** [comment] 2021-05-03 06:47
Hi,

It's weird because we transcode videos in the `tmp` directory (according to your peertube conf) so if the ffmpeg process fails, it should not overwrite the input file resulting in a broken transcoded file.

**Comment by Chocobozzz** [comment] 2021-06-01 08:23
Closing since the unclean state could not be reproduced. Feel free to comment if you manage to reproduce :)

**Closed by Chocobozzz** 2021-06-01 08:23 UTC
Labels: Component: Transcoding, Status: To Reproduce, Status: Waiting for answer
