### ISSUE TITLE
Backblaze: Unsupported value for canned acl 'private'

### ISSUE THREAD

**Issue by verymilan** [Chocobozzz/PeerTube#5499] opened 2022-12-31 11:57 UTC
### Describe the current behavior

Seemingly random videos fail to make it to the configured S3 compatible storage. It is already listed as using object storage but also gets the label about failing. 
![SCR-20221231-hvt](https://user-images.githubusercontent.com/10698140/210135890-b8a58696-bcbc-487b-bed7-15a01dd4af7a.png)

Peertube would still try to playback from local storage (where we get a 404) when using the default resolution. 

The error log contains:
```
        "Code": "InvalidArgument",
        "message": "Unsupported value for canned acl 'private'",
        "$response": {
            "statusCode": 400,
            "headers": {
                "x-amz-request-id": "b57cd473dc545b89",
                "x-amz-id-2": "aZDo5SWG8YkFiQWG4MMxm8WLIYQI3g2au",
                "cache-control": "max-age=0, no-cache, no-store",
                "content-type": "application/xml",
                "content-length": "172",
                "date": "Sat, 31 Dec 2022 10:42:22 GMT",
                "connection": "close"
            },
```

Most of the time, affected videos are actually public, i don't understand why it is trying to use a private acl.

### Steps to reproduce

unknown

### Additional information

* PeerTube instance:
  * URL: https://tube.tchncs.de
  * Version: 5.0.0
  * NodeJS version: v16.19.0
  * Ffmpeg version: 4.3.5-0+deb11u1

**Comment by Kinuseka** [comment] 2022-12-31 13:46
Backblaze does not support object level ACL. This is also why I raised issue #5497 
to use Bucket Policies instead due to limited support of ACL in various Object Storage providers.

**Comment by verymilan** [comment] 2022-12-31 16:22
Okey, but this does not explain why not all videos are affected – and the user confirmed that nothing was different about their video settings to previous videos that worked. 
In fact, they have reuploaded their video which then worked just fine. 🤯

**Comment by Chocobozzz** [comment] 2023-01-03 07:59
Duplicate of https://github.com/Chocobozzz/PeerTube/issues/5497

See  https://github.com/Chocobozzz/PeerTube/issues/5479 for a workaround

**Closed by Chocobozzz** 2023-01-03 07:59 UTC
