### ISSUE TITLE
API Modify video details?

### ISSUE THREAD

**Issue by hellomotow** [Chocobozzz/PeerTube#1427] opened 2018-11-24 00:16 UTC
Is there an easy way to modify all videos for certain things such as disabling comments, setting a language, set a category, set video as being mature.

**Comment by BO41** [comment] 2018-11-24 10:38
this may be a duplicate of #827

**Comment by Chocobozzz** [comment] 2018-11-26 08:12
Or you can use a script: https://docs.joinpeertube.org/api.html#tag/Video/paths/~1videos~1{id}/put

**Closed by Chocobozzz** 2018-11-26 08:12 UTC
