### ISSUE TITLE
Regenerating HLS files produces ultra low quality videos

### ISSUE THREAD

**Issue by maeries** [Chocobozzz/PeerTube#2788] opened 2020-05-26 09:47 UTC
**What happened?**
I lost the folder with the HLS files in it and regenerated them using `NODE_ENV=production npm run create-transcoding-job -- --generate-hls -v <VIDEO ID>` (which was discussed in #2783) These Videos are now ultra low bitrate. There are only a hand full of different colors, often just grayscale, the pixel are huge and the frame rate is about 10 fps. Sometimes the screen is just all grey for half a second. The strange thing is that the files on the hard drive are fine, it's just peertube playing them in such a bad quality

Also, the player only offers 1080p as a quality, but that's in the list twice. I enabled transcodung to every quality in the settings.

**What do you expect to happen instead?**
Being able to play the videos at every quality setting and seeing the video with an appropriated image quality

**Steps to reproduce:**

1. Activate HLS and I guess transcodung in the settings

2. upload some videos

3. delete the HLS folder

4. run `NODE_ENV=production npm run create-transcoding-job -- --generate-hls -v <VIDEO ID>` (im using Docker, otherwise the command would be a little different)

5. Wait until it's finished and play the respective video

**Additional information**
* PeerTube version or URL: 2.1.1
* Browser name/version: Firefox 76
* NodeJS version: v10.19.0
* Running as Docker container on ubuntu 18.04

* The Terminal doesn't show any errors or warnings when playing a video

**Comment by Chocobozzz** [comment] 2020-05-26 09:49
Hello,

I think it's a duplicate of https://github.com/Chocobozzz/PeerTube/issues/2709 that will be fixed in 2.2

**Comment by maeries** [comment] 2020-05-26 10:03
damn, forgot to google the issue first, might have found it then. Feel free to delete this issue

**Closed** 2020-05-26 10:11 UTC
