### ISSUE TITLE
Video is not the main content of the page

### ISSUE THREAD

**Issue by aflamrip** [Chocobozzz/PeerTube#6283] opened 2024-03-21 21:19 UTC
### Describe the current behavior

When the results of the site appear in the search engine, they do not appear in the results of Google videos, they appear as links and not a video, and an error appears in the webmasters stating that the video is not the main content of the page and is a supplementary content.
![Video-page-indexing1](https://github.com/Chocobozzz/PeerTube/assets/112701602/54178e89-0798-4ab3-a888-13979c6f4cac)
![Video-page-indexing2](https://github.com/Chocobozzz/PeerTube/assets/112701602/f3a8be69-d3f8-4f33-b49b-54a46a9be89f)

### Steps to reproduce

1.Add videos to the instance
2.Add the instance to Google Webmasters
3.Waiting for the results to appear in the search engine

### Describe the expected behavior

Most search results should appear like this without problems for webmasters
![site-pcbu-nl-Google-Search1](https://github.com/Chocobozzz/PeerTube/assets/112701602/c996163f-b2f6-4ca2-be40-7c0fb88d59df)
But all links, for example, appear like this
![site-pcbu-nl-Google-Search2](https://github.com/Chocobozzz/PeerTube/assets/112701602/5c03cce3-af05-490f-9127-a63e493e8e3a)

### Additional information

* PeerTube instance:
  * URL:
  * Version:6.0.3
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by kontrollanten** [comment] 2024-03-22 09:12
Hi! This looks like a duplicate of https://github.com/Chocobozzz/PeerTube/issues/6210

**Closed** 2024-03-25 09:03 UTC
