### ISSUE TITLE
html and line returns in administrators and durability section

### ISSUE THREAD

**Issue by stemy2** [Chocobozzz/PeerTube#3463] opened 2020-12-12 23:31 UTC
**Describe the problem to be solved**
On the "administrators and durability" section, html code and CRLF are not interpreted. It makes the presentation very ugly: URL are not clickable, no possibility to use icons like liberapay, text on the same lines when it shouldn't. Strangely, the sections situed above are actually able to do so.

**Describe the solution you would like:**
Correct the lack of code interpretation.

**Comment by Chocobozzz** [comment] 2020-12-14 14:48
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/3368

**Closed by Chocobozzz** 2020-12-14 14:48 UTC
