### ISSUE TITLE
wrong ratio thumbnail for panorama video - ratio 2.39

### ISSUE THREAD

**Issue by tomtoom1978** [Chocobozzz/PeerTube#4017] opened 2021-04-25 16:07 UTC
When I upload a video with a ratio **2,39:1** from 4K resolution 4096 × 1716
The automatic generated thumbnail is still 1,78:1 (16/9). The preview is not so nice.
_____
Other things about: name of the resolution for 2,39 ratio.
**peertube resolutions menu show this for viewers :**
- **1716p** _for 4096 x 1716_
- **858p** _for 2048 x 858_
- **720p** _for 1728 x 720_

Do you think something like this is more friendly for people.
(because it's real 4K and 2K, and not 2160p)
- **4K**
- **2K**
- **720p**

Thanks

**Comment by Chocobozzz** [comment] 2021-04-26 09:51
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/3027

**Closed by Chocobozzz** 2021-04-26 09:51 UTC
Labels: Template not filled
