### ISSUE TITLE
Video quota and data on disk

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#3037] opened 2020-08-05 12:19 UTC
In the admin panel, in the Users section, the uploaded video quota for each user is displayed.
For example, as an administrator, 13GB is displayed for me, but in fact, I have a lot more loaded, about 100GB. Why is the information displayed incorrectly? Perhaps only public videos are counted?

Peertube ver 2.3.0

**Comment by test2a** [comment] 2020-08-05 18:52
can you share screnshots?

**Comment by Alterak** [comment] 2020-08-05 19:17
https://peervideo.ru
screenshot, just don't understand how he can help you
![123](https://user-images.githubusercontent.com/11453567/89454353-422ced80-d769-11ea-99a2-9f2ef900524f.PNG)
there is nothing interesting and necessary in the logs either ... The same problem was in the previous version of peertube.

**Comment by test2a** [comment] 2020-08-05 20:50
@alterak what does 13/hero... mean? I dont understand Russian. Does it mean 13 per day or 13 per month or something else? 
If that is the case, you could have easily uploaded say 8 gb in 12 days.

**Comment by rigelk** [comment] 2020-08-05 21:23
@test2a here it means "unlimited", so user have no limit to what they can upload.

**Comment by Alterak** [comment] 2020-08-06 05:01
> here it means "unlimited", so users have no limit to what they can upload.

Really. 13GB / Unlimited.
Also my other account is Alterak. There it is 1GB / Unlimited - This is also not valid data!
It is displayed incorrectly for all users.

**Comment by Chocobozzz** [comment] 2020-08-12 07:06
As said on every places where you set the user quota, it does not reflect data stored on disk because it does not take into account transcoding. We could add a message or calculate the actual amount of data stored.

**Comment by Chocobozzz** [comment] 2020-08-14 14:27
In fact this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/1888

**Closed by Chocobozzz** 2020-08-14 14:27 UTC
Labels: Type: Enhancement :sparkles:
