### ISSUE TITLE
Split audio and video tracks and merge in browser

### ISSUE THREAD

**Issue by mulx** [Chocobozzz/PeerTube#1448] opened 2018-12-03 16:08 UTC
This is an enhancement proposal.
During transcode from a source video:
- create multiple video tracks with different resolution without audio.
- create a few less audio tracks (let say two quality).
- keep only the best quality file with audio & video.
Then, during playback, we fetch audio and video track and read them simultaneously. 

This way we can have a video with a very "low" resolution suitable for small screen or limited bandwith but keeping audio at high bit-rate/quality and at the same time saving a bit space on the server.

And a torrent file still point the best quality (original?) file for offline watching.

**Comment by rigelk** [comment] 2018-12-03 17:00
Note that this complexifies the situation for offline downloaders, which might want to have access to the file directly at different resolutions and not just the best one. It's definitely a question of interoperability too.

**Comment by Poslovitch** [comment] 2018-12-03 17:12
The idea seems hard to implement, although it's actually quite good. Maybe should you just allow the offline downloaders to get the best quality available?

**Comment by Chocobozzz** [comment] 2018-12-13 14:55
Thanks for the issue but it is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/1342

**Closed by Chocobozzz** 2018-12-13 14:55 UTC
Labels: Component: Transcoding, Type: Discussion :thought_balloon:
