### ISSUE TITLE
Video being transcoded to 2160p despite resolution being unselected in admin interface

### ISSUE THREAD

**Issue by fflorent** [Chocobozzz/PeerTube#4772] opened 2022-02-06 10:36 UTC
**Describe the current behavior**

A user uploaded a heavy video in a 2160p. A transcoding job was added to optimize the video (which somehow led to issues, which I will be report in another issue).

But, in my PeerTube instance, I configured transcoding as below:

![2022-02-06_11-17](https://user-images.githubusercontent.com/371705/152676389-a43efc46-f467-48b7-a6d1-914895b888dc.png)

**Steps to reproduce:** I can provide it upon request (I assumed it is straightforward using the above description, don't hesitate to ask me if you cannot reproduce it in a fresh instance)

**Actual behavior**: The video is attempted to be transcoded to 2160p.

**Additional information**
This was the job which has been created for transcoding:
```
Job: 140 Type: video-transcoding Processed on Feb 6, 2022, 10:56:02 AM Finished on Feb 6, 2022, 10:57:41 AM
--
{   "type": "new-resolution-to-hls",   "videoUUID": "<video-uuid>",   "resolution": 2160,   "isPortraitMode": false,   "copyCodecs": false,   "isMaxQuality": true,   "autoDeleteWebTorrentIfNeeded": true,   "isNewVideo": true }
Error: Missing lock for job 140 finished     at Object.finishedErrors (/var/www/peertube/node_modules/bull/lib/scripts.js:189:16)     at /var/www/peertube/node_modules/bull/lib/scripts.js:176:23     at runMicrotasks (<anonymous>)     at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

**Describe the expected behavior**: The video should be transcoded to the target resolutions: 240p, 360p, 480p, 720p, 1080p and audio-only.

* PeerTube instance:
  * URL:
  * version: 4.0.0
  * NodeJS version:
  * Ffmpeg version: 4.1.8-0+deb10u1

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by fflorent** [comment] 2022-02-06 10:41
Note that this might be related to this feature request: https://github.com/Chocobozzz/PeerTube/issues/3814

But my point is not about not being able to upload a video in a high resolution (I don't mind to allow it), it's about not transcoding and serving these high resolutions.

**Comment by Chocobozzz** [comment] 2022-02-07 08:24
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/1030

**Closed by Chocobozzz** 2022-02-07 08:24 UTC
