### ISSUE TITLE
Missing translation for window title overview

### ISSUE THREAD

**Issue by Jorropo** [Chocobozzz/PeerTube#1013] opened 2018-09-04 11:32 UTC
* **PeerTube version or URL:**
Development branch

* **What is the expected behaviour?**
Overview tab should change page title to overview but in right language.
* **What do you see instead?**
Title stay as I change the language.
I know that isn't a missing translation problem cause there is nothing in the code for change that.

PS: Why did you not do that ? (And can i do that to solve this issue ? (and other place if I found))
```typescript
    import { Component } from '@angular/core'
    import { Title }     from '@angular/platform-browser' //import here
     
    @Component({
    selector: 'app-root',
    template: "./template.html"
    })
    export class AppComponent {
      public constructor(private titleService: Title ) {// inject here
        this.titleService.setTitle(this.i18n("Page title")) // set page title here
      }
    }
```
This is more simpler.

**Comment by Chocobozzz** [comment] 2018-09-04 11:36
We did it before i18n, and it was simpler to put the titles in the route definitions. (duplicate of https://github.com/Chocobozzz/PeerTube/issues/793)

**Closed by Chocobozzz** 2018-09-04 11:36 UTC
