### ISSUE TITLE
Cannot access on Pale Moon

### ISSUE THREAD

**Issue by thepuzzledboy** [Chocobozzz/PeerTube#841] opened 2018-07-24 08:12 UTC
* **PeerTube version or URL:** Any instance that can be registered on currently.
* **Browser name/version:** Pale Moon 27.9.4

* **What is the expected behaviour?** Actually seeing the pages in question beyond the error.
* **What do you see instead?** "We are sorry but it seems that PeerTube is not compatible with your web browser."

**Comment by Chocobozzz** [comment] 2018-07-24 08:16
Thanks for reporting this issue, but this is a duplicate of Duplicate of https://github.com/Chocobozzz/PeerTube/issues/257

**Closed by Chocobozzz** 2018-07-24 08:16 UTC
