### ISSUE TITLE
Iphone iOS - I can't change the quality of video

### ISSUE THREAD

**Issue by Sir-Grizzly** [Chocobozzz/PeerTube#5290] opened 2022-09-23 23:49 UTC
### Describe the current behavior

on iPhone's , it is impossible to select the video quality on any browser (Safari, Chrome, Firefox)
Speed settings work fine , but menu of quality is empty.

![IMG_6894](https://user-images.githubusercontent.com/99275875/192070138-ee26a110-8903-437f-b85b-f5988d24c083.jpeg)

### Additional information

* PeerTube instance:
  * Version:4.3.0

**Comment by Chocobozzz** [comment] 2022-09-27 13:15
Unfortunately since iOS doesn't support mediasource on iphone, you can't change the resolution. We should hide the button for a better UX.

**Comment by Sir-Grizzly** [comment] 2022-09-27 18:13
Ok , I understand, thx for your answer

**Comment by warnerbryce** [comment] 2022-10-31 09:55
But does the iPhone auto-change the quality with the bandwidth it has ?

**Comment by jdaviescoates** [comment] 2023-01-22 21:44
> 



> Unfortunately since iOS doesn't support mediasource on iphone, you can't change the resolution. We should hide the button for a better UX.

I wonder if this has something to do with why multiple iPhone uses have now reported this short 9 second video not working for them (for some it doesn't play at all, for others they only hear the sound) https://bridport.tv/w/hCegSC1b9YGW5hAgbQbFcE :thinking: 

Seem iPhone and (my instance of) PeerTube aren't very compatible. I wonder what I could/ should do to improve that?

**Comment by Chocobozzz** [comment] 2023-01-23 08:11
@jdaviescoates What are the iOS versions involved?

**Comment by jdaviescoates** [comment] 2023-01-23 13:23
> @jdaviescoates Which iOS versions?

I'm not sure, I'm struggling to get people to even tell me what their iPhone model is, so haven't even asked about iOS version! But from what I know so far iPhone 11 and iPhone 12 having issues.

**Comment by warnerbryce** [comment] 2023-01-23 13:27
> > @jdaviescoates Which iOS versions?
> 
> I'm not sure, I'm struggling to get people to even tell me what their iPhone model is, so haven't even asked about iOS version! But from what I know so far iPhone 11 and iPhone 12 having issues.

I have an iPhone 5SE with iOS 15 and it’s normal that you can’t change the quality. I have the same behavior on other services. You click play you have a low quality during 5~10sec then it switch over on a better quality if your bandwidth allow it.

**Comment by Chocobozzz** [comment] 2023-01-23 13:31
Hum I wonder if the issue is that `0p` resolution contained in the master playlist is not the root cause of the issue, in coordination with a low bandwidth :thinking: 

@warnerbryce I think @jdaviescoates understands that point, we try to debug the "no sound"/"no video" bug :)

**Comment by jdaviescoates** [comment] 2023-01-23 13:33
> Hum I wonder if the `0p` resolution contained in the master playlist is not the root cause of the issue

Sorry, I'm very new to PeerTube, how/ where are you seeing that and is it something I can change?

**Comment by Chocobozzz** [comment] 2023-01-23 13:34
You can try to reupload the same video, after disabling the "Audio only" resolution in VOD transcoding configuration

**Comment by jdaviescoates** [comment] 2023-01-23 20:34
> You can try to reupload the same video, after disabling the "Audio only" resolution in VOD transcoding configuration

Thanks! :pray: that seems to have done the trick! So far heard back from two people who were having issues before but now they don't! :slightly_smiling_face:

**Comment by Chocobozzz** [comment] 2023-07-10 14:22
Hi,

This issue should be fixed by https://github.com/Chocobozzz/PeerTube/commit/63e2f087c3410206aa294df8099b005e615592e5

The other bug, where the built-in IOS player choose the audio quality would be fixed by this issue: https://github.com/Chocobozzz/PeerTube/issues/5797

**Closed by Chocobozzz** 2023-07-10 14:22 UTC
Labels: Type: Feature Request :sparkles:, UI, Component: Player :play_or_pause_button:, Component: Mobile
