### ISSUE TITLE
Suggestion: Add Timestamps to Player

### ISSUE THREAD

**Issue by TomatDividedBy0** [Chocobozzz/PeerTube#2670] opened 2020-04-21 23:46 UTC
One of the newer features on YouTube that actually seems really useful is the implementation of timestamps into the player itself as opposed to having to be worked into the description/comments.

I think having something like this (even if executed differently) would benefit PeerTube actually.

Context:
https://twitter.com/podcastage/status/1249486735345623041

**Comment by Chocobozzz** [comment] 2020-04-22 07:07
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/271

**Closed by Chocobozzz** 2020-04-22 07:07 UTC
