### ISSUE TITLE
Convert video time to links in comments

### ISSUE THREAD

**Issue by roipoussiere** [Chocobozzz/PeerTube#1728] opened 2019-03-22 17:44 UTC
It could be interesting to allow users to post a comment with a link to a specific time on the current video.

Something as simple as:

> [0:42]() nice

From a quick look, since PeerTube already allows to put a time on the url with `?t=<time_offset>`, it's mainly a regex on the comment system. Maybe something like `(\d?\d[:'])?\d?\d[:']\d\d"?` that parses 
`0:42`, `0'42"`, `00:42`, `00'42"`, `13:37`, `1:13:37` and `01:13:37`.

**Comment by Chocobozzz** [comment] 2019-03-23 08:02
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/1312

**Closed by Chocobozzz** 2019-03-23 08:02 UTC
Labels: Type: Duplicate :loop:
