### ISSUE TITLE
Filter admin table results

### ISSUE THREAD

**Issue by rigelk** [Chocobozzz/PeerTube#1197] opened 2018-10-05 08:36 UTC
As explained by @gled-rs, there is currently no way to search a specific user in the userlist in order to more efficiently take administrative action without going through the whole list of users. As instances grow, this is understandably burdensome.

Filters will probably look like this since it's the library we use for tables: https://www.primefaces.org/primeng/#/table/filter

**Comment by Nutomic** [comment] 2018-10-05 17:05
Duplicate of #1070 :P

**Comment by Chocobozzz** [comment] 2018-10-06 09:46
Oup's

![https://lutim.cpy.re/X51S4Ij5.jpg](https://lutim.cpy.re/X51S4Ij5.jpg)

**Closed by Chocobozzz** 2018-10-06 09:46 UTC
Labels: Component: Moderation :godmode:, Status: In Progress :soon:, Type: Enhancement :sparkles:
