### ISSUE TITLE
Floating video player

### ISSUE THREAD

**Issue by emansom** [Chocobozzz/PeerTube#5359] opened 2022-10-16 14:27 UTC
### Describe the problem to be solved

Currently when watching a video, clicking on a channel or on a button in the menu will cancel the currently playing video.

### Describe the solution you would like

The video player becoming a floating video player when clicking on a channel or on a button in the menu instead, allowing users to navigate around PeerTube while consuming content.

Similar to what Odysee does, watch [this](https://odysee.com/@FUTO:e/announcing-the-newest-member-of-futo:6) video and click on the channel to activate their floating video player.

**Comment by Chocobozzz** [comment] 2022-10-17 07:02
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/1211

**Closed by Chocobozzz** 2022-10-17 07:02 UTC

**Comment by emansom** [comment] 2022-10-17 11:53
PiP API != floating video.

PiP is a native browser API that integrates with the OS to create a new window, that can optionally be decoupled from the window.

Floating video is a styling centric change with some JavaScript atop to maintain and move the `<video>` element from and to a container.
