### ISSUE TITLE
Cannot publish stream archive that was incidentally ended by a streaming software crash

### ISSUE THREAD

**Issue by unfa** [Chocobozzz/PeerTube#3622] opened 2021-01-20 10:08 UTC
Yesterday I've done a first livestream on PeerTube.

One of the issues I have is I can't edit stream metadata after it's been started.
Because I had a streaming software crash (OBS) when streamign this one. The stream seems to be stuck in a limbo where it's still live but it's not, and I can't make it viewable.

Here's the stream archive:
https://tube.netzspielplatz.de/videos/watch/ea9989c7-dd62-44aa-a6ce-341b9d4e0b94

I've tried changing it's settings afterwards, but it says "can't edit a stream that's already started".

Maybe this one is related?
#3621

**Comment by Chocobozzz** [comment] 2021-01-20 11:03
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/3532

**Closed by Chocobozzz** 2021-01-20 11:03 UTC
