### ISSUE TITLE
Feature: Live-Streaming to De-Googlify from Youtube

### ISSUE THREAD

**Issue by McFlat** [Chocobozzz/PeerTube#2741] opened 2020-05-09 02:43 UTC
Would be awesome to have a page with a list of livestreams, it would require a database table for storing data about livestreams name, description, duration, status and uri path. It would use nginx rtmp and each person with an account on the site would be able to livestream their camera from OBS or many other apps like streamlabs or services like restream.io using a custom url pointing to their uri generated for them to livestream on and people will go to their channel uri/page to see a livestream happening to view it it would load the url for the livestream in the video player. Would also be nice to have a chat along side the video to be able to chat with the streamer. Much more can be said about this, but at the bare minimum if we could have a table in the database to stare some info for the livestream and a page to show the running livestreams that are happening would be sufficient to get people to de-googlify from youtube livestreaming. Here's a few links to some stuff I was looking at a while ago to tie livestreaming into peertube. I'm aware that people could livestream with jitsi-meet and save recording then import them into peertube(you'll find links below) but I think a specific page with live streams happening would be great and a way to actually livestream actually.

Maybe a way to use jitsi API to show video and chat on a page? idk whats a better way to do, I personally would like to use NGINX RTMP

http://nginx-rtmp.blogspot.com/

We would just create the nginx config which accounts for any users to livestream and giving a generated hash to each user or something where their livestream happens which is used for security and for watching the the stream in the video player.

Please give input and lets make this happen ASAP youtube shut down free speech a long time ago!

Links:

- https://github.com/cupcakearmy/livestream
- https://github.com/Marco01809/docker-livestreaming
- https://github.com/jitsi/docker-jitsi-meet#jitsi-meet-on-docker
- https://github.com/ikichigai/ptuploader

**Comment by Chocobozzz** [comment] 2020-05-09 06:21
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/151

**Closed by Chocobozzz** 2020-05-09 06:21 UTC
