### ISSUE TITLE
Display issue for multichannel account

### ISSUE THREAD

**Issue by raphgilles** [Chocobozzz/PeerTube#2082] opened 2019-08-26 14:27 UTC
Hello,

On all the multichannels account I have a display issue.

![Capture2](https://user-images.githubusercontent.com/49836486/63698003-442ec280-c81e-11e9-96c6-db280c3cd438.JPG)

I'm on the v1.4.0-rc1

Thank you !

**Comment by Chocobozzz** [comment] 2019-08-26 14:30
Hi,
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/2039 that should be fixed in 1.4

**Closed by Chocobozzz** 2019-08-26 14:30 UTC
