### ISSUE TITLE
Buttons in smartphone portrait fullscreen mode not visible

### ISSUE THREAD

**Issue by xundeenergie** [Chocobozzz/PeerTube#5558] opened 2023-01-26 06:44 UTC
### Describe the current behavior

When i go to fullscreen in portrait on my smartphone i see this

![Screenshot_20230126_073430](https://user-images.githubusercontent.com/5894829/214773192-9b49b3a1-5c38-4d72-8485-c05d68e8466d.jpg)

The arrow directs to the buttons on the bottom of the visible frame.
Can not use them

In landscape, its ok.
![Screenshot_20230126_073443_org mozilla firefox](https://user-images.githubusercontent.com/5894829/214773368-48326e91-d5fe-436f-9d2a-78d441526991.jpg)

### Steps to reproduce

1. Open a video in portraitmode
2. Tap to show it fullscreen

### Describe the expected behavior

See full buttons and progressbar

### Additional information

* PeerTube instance:
  * URL: https://kino.schuerz.at
  * Version: 5.0.1
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment] 2023-01-26 08:07
Hello,

What is your web browser?

**Comment by xundeenergie** [comment] 2023-01-26 21:49
Firefox on Android

**Comment by xundeenergie** [comment] 2023-01-26 21:51
But it's the same in Fennec

**Comment by Chocobozzz** [comment] 2023-01-27 07:15
I can't reproduce, can you paste the URL of the video?

**Comment by xundeenergie** [comment] 2023-01-27 16:54
All of my Videos on https://kino.schuerz.at
But... i think, i got now a bit of the problem.

When the video is not playing or paused, and it is a landscape-orientated video, and i change to fullscreen, then the buttons are shown cut as reported.
When the video is running, and i change to fullscreen, the orientation of the whole phone changes to landscape (even if i hold i "normal" in portrait-position), and the buttons are shown good.

It seems, it's a problem of landscape-orientated videos and firefox on huawei p30.

"Firefox klar" on my huawei turns orientation of the phone to landscape, even it the video is paused. The same on Samsung A53.

**Comment by xundeenergie** [comment] 2023-01-27 16:57
Changed to fullscreen, wen paused Video

![Screenshot_20230127_175513_org mozilla firefox](https://user-images.githubusercontent.com/5894829/215147112-db771418-2c56-4d75-a3dc-f4ab189df0b6.jpg)

Changed to fullscreen wen running Video
![Screenshot_20230127_175551_org mozilla firefox](https://user-images.githubusercontent.com/5894829/215147309-2eaec76f-582b-415a-a69a-75af48db50e0.jpg)


It is this Video https://kino.schuerz.at/w/f55QaQatL9KJgkbCoRihq2

**Comment by Chocobozzz** [comment] 2023-02-13 10:03
Do you reproduce the issue with your other device Samsung A53?

**Comment by Chocobozzz** [comment] 2023-02-27 09:52
Closing as it seems to be a bug of a particular Android platform/device, not related to peertube (we use classic HTML fullscreen API).

**Closed by Chocobozzz** 2023-02-27 09:52 UTC
Labels: Status: Waiting for answer
