### ISSUE TITLE
Implement W3C's ActivityPub in PeerTube

### ISSUE THREAD

**Issue by arthurlutz** [Chocobozzz/PeerTube#124] opened 2017-11-27 15:32 UTC
" The ActivityPub protocol is a decentralized social networking protocol based upon the ActivityStreams 2.0 data format. It provides a client to server API for creating, updating and deleting content, as well as a federated server to server API for delivering notifications and content. " https://www.w3.org/TR/activitypub/

This would be ultra nice and web standard for peertube. I haven't looking in detail on how this was implemented (or if at all) in https://mediagoblin.org/ but it seems to be the standard way forward. ActivityPub is used in mastodon by the way https://hackernoon.com/mastodon-and-the-w3c-f75f376f422

**Comment by Chocobozzz** [comment] 2017-11-27 15:33
Duplicate of https://github.com/Chocobozzz/PeerTube/issues/104

**Closed by Chocobozzz** 2017-11-27 15:33 UTC
