### ISSUE TITLE
Cannot see transcoded video even if you change the privacy

### ISSUE THREAD

**Issue by Zagur** [Chocobozzz/PeerTube#6005] opened 2023-10-13 12:16 UTC
### Describe the current behavior

When I publish a video if  I go to the "Go live" tab and I create a live video with public privacy on the selector then I go to the "live settings" tab automatically the selector has the **Privacy of the new replay** as **private**. So when the live ends and its transcoded and you change the privacy by **public** you cannot see the transcoded video.

### Steps to reproduce

1. Go to "Publish" button.
2. Select the "Go live" tab
3. Select normal or permanent option and "Go Live"
4. Initialize the live
5. Stop the live
6. After transcoding and after receiving the notification, change the privacy of the video.
7. The video now no longer loads :( 

### Describe the expected behavior

When I change the privacy of the transcoded video to public people must see the video.

### Additional information

  * PeerTube instance: FediverseTV
  * URL: https://fediverse.tv
  * Version: 5.2.1
  * NodeJS version: 16.x
  * Ffmpeg version: 

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

```
error[13/10/2023 13:38:10] Cannot move HLS file /www/storage/streaming-playlists/hls/private/79f4a1cb-f22d-41e1-bca8-6c97ef474e19 to /www/storage/streaming-playlists/hls/79f4a1cb-f22d-41e1-bca8-6c97ef474e19 after privacy change

{
  "err": {
    "stack": "Error: dest already exists.\n    at /app/node_modules/fs-extra/lib/move/move.js:51:31\n    at /app/node_modules/universalify/index.js:22:54",
    "message": "dest already exists."
  }
}
```

By deleting the /www/storage/streaming-playlists/hls/79f4a1cb-f22d-41e1-bca8-6c97ef474e19 directory manually, we were able to change the privacy and have the video play again.

**Comment by Chocobozzz** [comment] 2023-10-13 13:15
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/5936 that should already be fixed (will be released in next peertube version, v6)

**Closed by Chocobozzz** 2023-10-13 13:15 UTC
