### ISSUE TITLE
Add the ability for a channel to be used by multiple users

### ISSUE THREAD

**Issue by Kazer67** [Chocobozzz/PeerTube#2461] opened 2020-02-06 11:34 UTC
New feature for channel who work with multiple users. The idea is to allow different users to have access to the same channel so a group of remote people can work together on the same topic.

For that, I see multiple "rank" that can be used (need suggestion for better one?):
- Owner: all the right to the channel without restriction and can give rank
- Manager: can give specific rank that the owner allow.
- Uploader: can upload video to the channel (by default, upload on private to allow self-moderation of the channel)
- Editor: can edit the video from the Uploader rank if needed correction (Uploader may edit his own video only or not at all and ask Editor for fixing?)
- Validator: can pass a video from private to public or vice-versa
- Other ?

Maybe with check-box to allow multiple rank for an user if the owner want?

**Comment by Chocobozzz** [comment] 2020-02-06 14:20
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/699

**Closed by Chocobozzz** 2020-02-06 14:20 UTC
