### ISSUE TITLE
Cannot play more than 2 embedded video on mobile device

### ISSUE THREAD

**Issue by kirill2400** [Chocobozzz/PeerTube#5924] opened 2023-08-04 20:32 UTC
### Describe the current behavior

If there are more than 2 embedded videos on a page, I can't start watching the 3rd video after starting playback of the other two videos

### Steps to reproduce

1. open https://intypeinsense.ru/test.html on mobile device
2. play one random video
3. play second random video
4. play third random video
5. Get video stuck

### Describe the expected behavior

I need to be able to play 3 and further videos after watching others. Ideally several videos at once (if this does not contradict the browser developer's security goals). 

### Additional information

* PeerTube instance: https://spacecomfort.miracleinsense.ru
  * URL: https://spacecomfort.miracleinsense.ru/w/knt8of3PUURoGSXwSKZuxC
  * Version: 5.2.0
  * NodeJS version: v16.19.0
  * Ffmpeg version: 4.4.3-0ubuntu1~20.04.sav2

* Browser name, version and platforms on which you could reproduce the bug: Google Chrome on mobile device
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by kirill2400** [comment] 2023-08-05 13:08
Embedded youtube works perfectly
![image](https://github.com/Chocobozzz/PeerTube/assets/30482699/86718822-eeac-473b-bce7-58a5ab0465f0)

**Comment by Chocobozzz** [comment] 2023-08-05 13:39
I'm sorry but I can't reproduce: can you find web browser logs or server logs that show errors?

**Comment by kirill2400** [comment] 2023-08-05 14:24
> I'm sorry but I can't reproduce: can you find web browser logs or server logs that show errors?

![image](https://github.com/Chocobozzz/PeerTube/assets/30482699/63123ff8-855a-4037-95a7-670242a5cf8c)

**Comment by Chocobozzz** [comment] 2023-08-18 08:38
Can you also paste a screen of `Network` tab to see if some requests fail?

**Comment by kirill2400** [comment] 2023-08-21 12:03
[intypeinsense.ru.zip](https://github.com/Chocobozzz/PeerTube/files/12395693/intypeinsense.ru.zip)


> Can you also paste a screen of `Network` (in developer tools) tab to see if some requests fail?

**Comment by Chocobozzz** [comment] 2024-02-15 07:43
Do you still have the issue @kirill2400?

**Comment by Chocobozzz** [comment] 2024-02-15 10:02
Can you try to reproduce with embeds from another peertube instance like https://framatube.org/?

**Comment by kirill2400** [comment] 2024-02-15 10:17
> Can you try to reproduce with embeds from another peertube instance like https://framatube.org/?

Looks like no. I try this link and works perfect framatube.org/videos/embed/0af4f425-e301-49ad-a5e9-6134a8092900. But my instance is not

**Comment by Chocobozzz** [comment] 2024-02-15 10:24
Can you try with videos on your instance that are not stored in S3?

**Comment by kirill2400** [comment] 2024-02-15 10:36
> Can you try with videos on your instance that are not stored in S3?

Same bug for this video
![image](https://github.com/Chocobozzz/PeerTube/assets/30482699/5308a173-2f7b-43b2-a1fc-418600417bfb)
I think trouble in my instance

**Comment by Chocobozzz** [comment] 2024-02-15 13:56
Then I'm sorry but if you can't reproduce on framatube.org I don't think it's a PeerTube bug. Don't hesitate to comment if you have more information. In the meantime I'm closing this issue.

**Closed by Chocobozzz** 2024-02-15 13:56 UTC
Labels: Status: Waiting for answer

**Comment by kirill2400** [comment] 2024-02-15 14:38
> Then I'm sorry but if you can't reproduce on framatube.org I don't think it's a PeerTube bug. Don't hesitate to comment if you have more information. In the meantime I'm closing this issue.

Can this might be problem?
![image](https://github.com/Chocobozzz/PeerTube/assets/30482699/d3f57fbd-463c-4f40-81a6-3ab847c472cf)
