### ISSUE TITLE
Peertube not working in Chrome/Firefox on Debian

### ISSUE THREAD

**Issue by c0dev0id** [Chocobozzz/PeerTube#2051] opened 2019-08-19 07:20 UTC
**What happened?**
I can't use peertube.social, because:

We are sorry but it seems that PeerTube is not compatible with your web browser.
Please try with the latest version of Mozilla Firefox.
If you think this is a mistake, do not hesitate to report it.

This happens on Debian Linux with Chrome and Firefox.

**What do you expect to happen instead?**
Peertube should open. Or at least there should be a way to ignore the warning and open peertube.

**Steps to reproduce:**
Open peertube.social with Chrome or Firefox on Debian Buster

**Additional information**
* PeerTube version or URL: https://peertube.social/

* Browser name/version:

Firefox Quantum 60.8.0esr (64-bit)
Chrome Version 76.0.3809.100 (64-bit)
OS: Debian Buster

**Comment by tcitworld** [comment] 2019-08-19 07:41
Duplicate of #2040

**Closed by tcitworld** 2019-08-19 07:41 UTC
