### ISSUE TITLE
Automatic video redundancy not working

### ISSUE THREAD

**Issue by thorstenkirsch** [Chocobozzz/PeerTube#3775] opened 2021-02-24 21:34 UTC
**Describe the current behavior**
I have 2 instances that should automatically clone videos from a main instance.
Unfortunately, this does not work. According to the log, the redundancy scheduler runs without an error. But nothing happens, no new job and no video download.
Manual redundancy works, however.

**Steps to reproduce:**

1. Set up two new instances
2. Follow each other instance and configure redundancy
3. Upload a video and generate some views
4. Wait for the scheduler to run

**Describe the expected behavior**
It should clone the videos as defined by the strategies in the config.

**Additional information**
- The tracker is turned off right now. I tried to activate it, but it didn't do anything.
- I tried all 3 redundancy strategies
- Redundancy check interval 5 minutes
- I have enabled redundancy for the specific instances in the UI.
- Accepting redundancy from followings (I also tried anybody)
- No firewall blocking anything

* PeerTube instance:
  * URL: gegenstimme.tv, server1.gegenstimme.tv, server2.gegenstimme.tv
  * version: 3.0.1
  * NodeJS version: v12.20.2
  * Ffmpeg version: 4.2.4-1ubuntu0.1

* Browser name, version and platforms on which you could reproduce the bug: Ubuntu 20.04.2 LTS

**Comment by Chocobozzz** [comment] 2021-02-25 08:53
Thanks for the issue, but I think it's a duplicate of https://github.com/Chocobozzz/PeerTube/issues/3636#issuecomment-770748112 (that will be fixed in the next version).

**Closed by Chocobozzz** 2021-02-25 08:53 UTC
