### ISSUE TITLE
Statistics are invisible in dark theme

### ISSUE THREAD

**Issue by stemy2** [Chocobozzz/PeerTube#2285] opened 2019-11-25 15:18 UTC
**What happened?**
I activated black theme, and now, my statistics are nothing but empty white rectangles. I have to select all to be able to read the contents.

**Additional information**
* PeerTube version or URL: 2
* Browser name/version: Firefox 68.2 ESR
* NodeJS version: 10.17

**Comment by Chocobozzz** [comment] 2019-11-25 15:19
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/2237

**Closed by Chocobozzz** 2019-11-25 15:19 UTC
Labels: Type: Duplicate :loop:
