### ISSUE TITLE
Ability to have an audit log

### ISSUE THREAD

**Issue by McFlat** [Chocobozzz/PeerTube#1318] opened 2018-10-20 16:58 UTC
We could benefit from having an audit log that stores all changes made in the database models. An Admin could see the audit log once logged it.

Some current options of sequelize libraries we could use are on NPM, but am thinking they each one provides pros and cons. One logs views, while others don't and one has a nicer api while others are only ok. Maybe it's a side project to fit directly for the needs of PeerTube, a combination of all these libraries to make a solid api and a solid way of storing data and compressing it or storing only the differences instead of all the keys so to keep the space usage lower.

- https://www.npmjs.com/package/sequelize-version
- https://www.npmjs.com/package/sequelize-tracker
- https://www.npmjs.com/package/sequelize-logbook
- https://www.npmjs.com/package/sequelize-paper-trail
- https://github.com/bonaval/sequelize-temporal
- https://github.com/bkniffler/sequelize-revisions

**Comment by Chocobozzz** [comment] 2018-10-22 06:50
Duplicate of https://github.com/Chocobozzz/PeerTube/issues/826

The audit log is already implemented, but we have to create a page in the administration

**Closed by Chocobozzz** 2018-10-22 06:50 UTC
