### ISSUE TITLE
Incrustation activated when changing speed of video

### ISSUE THREAD

**Issue by Govi59** [Chocobozzz/PeerTube#4003] opened 2021-04-22 22:31 UTC
**Describe the current behavior**
When chosing setting "speed 1.25x", it is easy to misclick to "incrustation mode".

**Steps to reproduce:**

1. Open a video on Peertube (eg https://framatube.org/videos/watch/58933f82-ce83-4380-ae6a-17a03a2fe067)
2. Click on "Settings" gear
3. Click on "Speed"
4. Click on "1.25x" (at the right side of the button)
5. The "incrustation mode" button is clicked instead

**Describe the expected behavior**
The speed of the video should change, but the incrustation mode should not be activated.
Proposal : simply change the place or the z-index of the incrustation button.

**Additional information**
Actual behavior (the video incrustation is activated when clicking on speed 1.25) :
![Peek 23-04-2021 00-27](https://user-images.githubusercontent.com/22171202/115792534-c0e6bb00-a3ca-11eb-82ca-bfed6c10eaec.gif)

* PeerTube instance:
  * URL: https://framatube.org/
  * version: 3.1.0

**Comment by Chocobozzz** [comment] 2021-04-23 06:31
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/3275

**Closed by Chocobozzz** 2021-04-23 06:31 UTC
