### ISSUE TITLE
CLI tools fails to import video when cookies.txt is specified

### ISSUE THREAD

**Issue by achaiah** [Chocobozzz/PeerTube#3270] opened 2020-11-08 04:34 UTC
**Describe the current behavior**
I'm trying to use peertube CLI tools to download some videos from YT. However, youtube-dl needs a "cookies.txt" file to be able to download the videos successfully. When I supply this as an option via the peertube CLI, the script fails. The usage description for the CLI script is a bit terse `Usage: import-videos [global options] [ -- youtube-dl options]` but I believe i'm supplying the cookies parameter correctly (see below).

**Steps to reproduce:**

1. Download cookies file from browser into `cookies.txt` (e.g. Firefox has "Export Cookies" extension that can do this or you can export manually)
2. Execute: `peertube import-videos --target-url "https://www.youtube.com/watch?v=gZMPRymQsBw" -- "--cookies cookies.txt"`
3. Observe error: 
```youtube-dl: error: no such option: --cookies cookies.txt Command failed with exit code 2: /root/PeerTube/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best -j --flat-playlist --playlist-reverse --cookies cookies.txt http://www.youtube.com/watch?v=gZMPRymQsBw```

**Describe the expected behavior**
The expected behavior is that the file is successfully downloaded. In fact, if I simply copy the command from the error and run it manually...

```/root/PeerTube/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best -j --flat-playlist --playlist-reverse --cookies cookies.txt http://www.youtube.com/watch?v=gZMPRymQsBw```

...it works just fine.

I have also tried a few variations of the command (e.g. specifying the full path to cookies.txt in case it mattered, omitting the quotes around the youtube-dl options, using single vs. double quotes etc) and it definitely looks like the problem is with the PeerTube CLI.

**Additional information**

* PeerTube instance:
  * URL: private
  * version: 2.4
  * NodeJS version: 10
  * Ffmpeg version:

**Comment by rigelk** [comment] 2020-11-08 09:19
Hi @achaiah,

`"--cookies cookies.txt"` must be two arguments, and not one as you did with your use of quotes.

**Comment by achaiah** [comment] 2020-11-09 03:49
Hi @rigelk  Unfortunately that does not seem to be parsed correctly by the node script. Like I've mentioned, I tried many things. If I don't include the command in quotes I get this error:
```
info: Will download and upload 1 videos.

(node:40) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 1: /root/PeerTube/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best http://www.youtube.com/watch?v=gZMPRymQsBw
    at makeError (/root/PeerTube/node_modules/execa/lib/error.js:56:11)
    at handlePromise (/root/PeerTube/node_modules/execa/index.js:114:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:40) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:40) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Note that the node script tries to run is:
```
Command failed with exit code 1: /root/PeerTube/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best http://www.youtube.com/watch?v=gZMPRymQsBw
```
As you see, it does not pass along the custom parameters to youtube-dl.  Can you please re-open this issue?

Thanks

**Comment by Chocobozzz** [comment] 2020-11-10 14:36
Please try `peertube import-videos --target-url "https://www.youtube.com/watch?v=gZMPRymQsBw" -- --cookies cookies.txt`

**Comment by achaiah** [comment] 2020-11-10 14:41
Hi @Chocobozzz  Thanks for the suggestion but I have also tried that. It has the same effect as the previous message. The output is:
```
[root@1243f66e9b54 PeerTube]# peertube import-videos --target-url "https://www.youtube.com/watch?v=gZMPRymQsBw" -- --cookies cookies.txt
info: Will download and upload 1 videos.

(node:67) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 1: /root/PeerTube/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best http://www.youtube.com/watch?v=gZMPRymQsBw
    at makeError (/root/PeerTube/node_modules/execa/lib/error.js:56:11)
    at handlePromise (/root/PeerTube/node_modules/execa/index.js:114:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:67) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:67) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

As you can see, the command it tries to run is: ```Command failed with exit code 1: /root/PeerTube/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best http://www.youtube.com/watch?v=gZMPRymQsBw``` which is missing the cookies parameter.

**Comment by Chocobozzz** [comment] 2020-11-10 15:06
It's weird I can't reproduce :thinking: 

What about `node dist/server/tools/peertube.js import-videos --target-url "https://www.youtube.com/watch?v=gZMPRymQsBw" -- --cookies cookies.txt?`

**Comment by achaiah** [comment] 2020-11-10 15:33
Hmm I just pulled the latest from develop and am running into a different error now. I think something changed with the code
```
[root@1243f66e9b54 PeerTube]# node dist/server/tools/peertube.js import-videos --target-url "https://www.youtube.com/watch?v=gZMPRymQsBw" -- --cookies cookies.txt
/root/PeerTube/dist/server/initializers/constants.js:146
        cron: crypto_1.randomInt(1, 20) + ' * * * *'
                       ^

TypeError: crypto_1.randomInt is not a function
    at Object.<anonymous> (/root/PeerTube/dist/server/initializers/constants.js:146:24)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/PeerTube/dist/server/helpers/requests.js:8:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
```

Maybe I should roll back to a previous commit?

**Comment by achaiah** [comment] 2020-11-10 15:38
@Chocobozzz  I wonder if the difference might be in the shell that I'm using. I'm using `bash`. What are you running?

**Comment by rigelk** [comment] 2020-11-10 15:45
@achaiah if you pull code, you need to:
- synchronise dependencies (`yarn install`)
- recompile tools

**Comment by achaiah** [comment] 2020-11-10 15:50
@rigelk  I followed the setup in the [tools.md](https://framagit.org/framasoft/peertube/PeerTube/-/blob/develop/support/doc/tools.md) doc.

So I did:
```
git pull
git checkout develop
NOCLIENT=1 yarn install --pure-lockfile
npm run setup:cli
```
That didn't resolve the error but I simply edited the file and reverted it from [this commit](https://github.com/Chocobozzz/PeerTube/commit/0223291c45809d4a9dcc2be9ac4aa9406610a89c#diff-4fcad28b740bbd6e1fec121ab7cb021ad4c9fc1cb6656aaa044637a197239535) just to make it work.

I can now confirm that the latest develop branch does work!  Thanks for the help!

**Comment by Chocobozzz** [comment] 2020-11-10 16:04
Thanks @achaiah, the random int bug should also be fixed in https://github.com/Chocobozzz/PeerTube/commit/adbf1ed8c4094ab5e281f69f045dba607c1d14b6.

**Closed by Chocobozzz** 2020-11-10 16:04 UTC
Labels: Component: CLI, Status: To Reproduce, Status: Waiting answer
