### ISSUE TITLE
Video not playing in Brave browser

### ISSUE THREAD

**Issue by raisty** [Chocobozzz/PeerTube#1090] opened 2018-09-19 12:44 UTC
* **PeerTube version or URL:** https://peertube.cpy.re/videos/watch/da2b08d4-a242-4170-b32a-4ec8cbdca701
* **Browser name/version:** 
 Brave: 0.23.105 
V8: 6.8.275.24 
rev: 9a46f8f5cb22a9daf2af21989aed25911aa6f839 
Muon: 8.0.9 
OS Release: 17.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.84
* **NodeJS version:** 7.9.0

* **What is the expected behaviour?**
Playing video
* **What do you see instead?**
Video is downloading and produce blank peer page in Brave
![screen shot 2018-09-19 at 14 43 48](https://user-images.githubusercontent.com/537310/45753920-7dc47a00-bc1a-11e8-9ab0-92c065307d70.png)

**Comment by Chocobozzz** [comment] 2018-09-19 12:47
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/218

This is a Brave issue: https://github.com/brave/browser-laptop/issues/13060

We can't really do anything here

**Closed by Chocobozzz** 2018-09-19 12:47 UTC
