### ISSUE TITLE
Higher quality video options

### ISSUE THREAD

**Issue by tilllt** [Chocobozzz/PeerTube#2759] opened 2020-05-16 14:25 UTC
ATM, PeerTube has worse video quality compared to both YouTube and Vimeo. While for certain applications (maybe the average "Youtuber") that is fine, there are "fringe" applications where this makes PeerTube a no go.

As an example: i have been building a [DIY telecine](http://www.deniscarl.com/dokuwiki/doku.php?id=start) recently and i like to put these films online, on my peertube instance [pixelscope.de](https://pixelscope.de/video-channels/foss_feedback@www.pixelscope.de/videos) I will mainly be scanning Super8 home movies, these films tend to be very dusty and grainy, so worst case scenario for low bandwidth video.

The video looks very bad on [peertube](https://pixelscope.de/videos/watch/e0f0710e-19ef-4fd0-a6f4-13e402c38831), although the bitrate is higher than on [youtube](https://www.youtube.com/watch?v=frE0L8fF4ro), from the video streaming providers, [Vimeo looking best.
](https://vimeo.com/419295765)

To demonstrate the Bitrate / Encoding i would consider desirable, there is a version exported from the editing app, [uploaded to google drive.](https://drive.google.com/file/d/1t_db2FW3C6-UJkSWQxuJZkmBCARPdtXs/view) (download and watch in player to see the "real" quality)

**Peertube**
> /opt/docker/peertube/peertube_DATA/data/redundancy/hls/e0f0710e-19ef-4fd0-a6f4-13e402c38831# mediainfo  e0f0710e-19ef-4fd0-a6f4-13e402c38831-1080-fragmented.mp4
General
Complete name                            : e0f0710e-19ef-4fd0-a6f4-13e402c38831-1080-fragmented.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : iso5 (iso6/mp41)
File size                                : 108 MiB
Duration                                 : 5 min 28 s
Overall bit rate                         : 2 753 kb/s
Writing application                      : Lavf58.20.100

**Youtube**
> mediainfo Found\ Footage\ -\ Flug\ 1971\ \(Corona\ Roller\ Scan\ #5\)-frE0L8fF4ro.mp4
General
Complete name                            : Found Footage - Flug 1971 (Corona Roller Scan #5)-frE0L8fF4ro.mp4
Format                                   : MPEG-4
Format profile                           : Base Media / Version 2
Codec ID                                 : mp42 (isom/mp42)
File size                                : 57.9 MiB
Duration                                 : 5 min 28 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 1 479 kb/s
Encoded date                             : UTC 2020-05-16 14:08:13
Tagged date                              : UTC 2020-05-16 14:08:13
Writing application                      : Google
gsst                                     : 0
gstd                                     : 328260

**Vimeo**

>  mediainfo Found\ Footage\ -\ Flug\ 1971\ \(Corona\ Roller\ Scan\ #5\)-419295765.mp4
General
Complete name                            : Found Footage - Flug 1971 (Corona Roller Scan #5)-419295765.mp4
Format                                   : MPEG-4
Format profile                           : Base Media / Version 2
Codec ID                                 : mp42 (mp42/mp41/isom/avc1)
File size                                : 170 MiB
Duration                                 : 5 min 28 s
Overall bit rate                         : 4 333 kb/s
Encoded date                             : UTC 2020-05-16 14:38:56
Tagged date                              : UTC 2020-05-16 14:38:56

**h264 Export from Davinci Resolve**
> mediainfo 100516_Flug1971.mp4
General
Complete name                            : 100516_Flug1971.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/avc1/mp41)
File size                                : 385 MiB
Duration                                 : 5 min 28 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 9 848 kb/s
Writing application                      : Lavf57.25.100

I dont know what could be a strategy for Peertube because obviously Youtube is achieving a better quality at almost half the file size. So i guess there is room for improvement in terms of encoding options. The other option is to allow higher bitrate videos, or possibly: both.

Or is there already an option how to achieve higher quality uploads?

**Comment by tilllt** [comment] 2020-05-17 08:28
P.S. i am experimenting with 4k scans, the only option to "show" them somewhere is Youtube, since 4k is a paid feature on Vimeo and Peertube doesnt support it.

**Comment by Chocobozzz** [comment] 2020-05-18 07:25
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/2442

**Closed by Chocobozzz** 2020-05-18 07:25 UTC

**Comment by tilllt** [comment] 2020-05-18 07:38
Part of it is a duplicate, yes. But i do think of it as a more general discussion than adding ffmpeg parameters in the admin panel (like discussed in the other issue). Its about future proofing Peertube for higher bandwidth and user demands. This implies more encoding options, yes, but also higher Resolution etc. and how to deal with this in a federated environment. Actually 4k, which afaik Peertube does not offer, is a reality since a long time, at least several years. The Olympic Games were to be broadcast in 8k (if the hadnt been canceled that is).

**Comment by rigelk** [comment] 2020-05-18 07:52
@tilllt yyou Can enable 4k via the "2180p" resolution in the admin panel.

**Comment by tilllt** [comment] 2020-05-19 06:58
Yes! i had the 4k option enabled but it didnt work for a reason unknown to me. Now it did and the quaility and corresponding data rate is acceptable for my usecase. Higher bandwidth, lower resolution options would be great, but thats kind of optional. Generally the issue should be adressed though, since its a bit sad that videos on peertube look worse than elsewhere.

**Comment by lucacalcaterra** [comment] 2020-11-18 08:18
Similar issue (as opposite)
We have a server with an average of  350 nginx rev proxy connections . 

Users  complain the videos are too heavy and take up too much space, causing saturated bandwith (we have just upgraded to 500mb dedicated connection).

Ho we can reduce bitrate of transcoded video files ?

We already reduced nginx bitrate as suggested by someone on forum but is not a solution.

Thanks
