### ISSUE TITLE
Run transcoding from API

### ISSUE THREAD

**Issue by r6fans** [Chocobozzz/PeerTube#4456] opened 2021-10-10 15:18 UTC
I found that PeerTube was able to fetch the failed transcoding task via the REST API, but had to go into the machine to run the transcoding CLI script.

Will Remote Tools add the feature of performing transcoding tasks remotely in the future?

Or is there any way to run the transcoding CLI script from a remote machine?

**Comment by Chocobozzz** [comment] 2021-10-12 08:48
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/3723

**Closed as completed by Chocobozzz** 2021-10-12 08:48 UTC
Labels: Type: Feature Request :sparkles:, Type: Duplicate :loop:, Component: CLI
