### ISSUE TITLE
Update comments without page reload

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#3910] opened 2021-04-01 08:52 UTC
**Describe the problem to be solved**
Use cases:
A) When watching a newly published video it can be interesting to read other peoples comment during watching the video.
B) To add the user activity it would be great to be able to see comment replies during watching a video so that it can be an ongoing dialog.

**Describe the solution you would like:**
Some way to update the comments without interrupting the video.

**Describe alternatives you have considered**
A) An "update comments" button.
B) Auto update comments at a given interval.
C) Creating an overlay component that open up a minified comment box, so that when watching video A you're able to answer comments on video B without interrupting the video.

**Comment by Chocobozzz** [comment] 2021-04-01 08:58
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/212

**Closed by Chocobozzz** 2021-04-01 08:58 UTC
