### ISSUE TITLE
Gracefully handle metrics POST errors

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#5713] opened 2023-03-25 16:26 UTC
### Describe the problem to be solved

Probably this isn't an issue for users but our sentry is spammed with a lot of `Failed to fetch` due to error during posting metrics.

### Describe the solution you would like

It would be great if these can be logged as warnings instead.

**Comment by Chocobozzz** [comment] 2023-03-27 06:22
Hello,

What is the root cause of the HTTP errors?

**Comment by Chocobozzz** [comment] 2023-05-10 09:53
Fixed in https://github.com/Chocobozzz/PeerTube/commit/89fc0142625126b0a2923c9d625be5d201354bb7

**Closed by Chocobozzz** 2023-05-10 09:53 UTC
Labels: Type: Feature Request :sparkles:, good first issue
