### ISSUE TITLE
Any news about making Peertube complaint with LibreJS?

### ISSUE THREAD

**Issue by evilworld84** [Chocobozzz/PeerTube#6741] opened 2024-11-28 03:45 UTC
### Describe the problem to be solved

Sorry for my english.
I've just installed the LibreJS extension on my browsers and i noticed that there are a lot of javascripts not free in Peertube and i was wondering if you had any news about improving this situation.

these are all the JS that LibreJS blocks

`blocked scripts in https://peertube.uno/:

[<SCRIPT> at line 70 of https://peertube.uno/](view-source:https://peertube.uno/#line70):

NONTRIVIAL: nontrivial token: 'document'
https://peertube.uno/client/it-IT/chunk-4EDEHPUS.js:

External script with no known license
https://peertube.uno/client/it-IT/chunk-LU2XIJXA.js:

External script with no known license
https://peertube.uno/client/it-IT/chunk-VGWHSSUL.js:

External script with no known license
https://peertube.uno/client/it-IT/chunk-5NHDLC2L.js:

External script with no known license
https://peertube.uno/client/it-IT/chunk-CEOCBFKL.js:

External script with no known license
https://peertube.uno/client/it-IT/chunk-VBZACOPR.js:

External script with no known license
https://peertube.uno/client/it-IT/chunk-KATFD4V6.js:

External script with no known license
https://peertube.uno/client/it-IT/chunk-ZLGXC6W5.js:

External script with no known license
https://peertube.uno/client/it-IT/chunk-J36KBXON.js:

External script with no known license
https://peertube.uno/client/it-IT/chunk-PDDSSZE3.js:

External script with no known license
https://peertube.uno/client/it-IT/chunk-RQE5E7PH.js:

External script with no known license
https://peertube.uno/client/it-IT/chunk-SM4JS7ZF.js:

External script with no known license
https://peertube.uno/client/it-IT/chunk-UZBOK3PY.js:

External script with no known license
https://peertube.uno/client/it-IT/chunk-MBNJVH7B.js:

External script with no known license
https://peertube.uno/client/it-IT/chunk-ODKBFOSP.js:

External script with no known license
https://peertube.uno/plugins/akismet/0.1.2/client-scripts/dist/common-client-plugin.js:

External script with no known license
https://peertube.uno/client/it-IT/chunk-MRVUFXCI.js:

External script with no known license
https://peertube.uno/client/it-IT/chunk-EA6DNFAG.js:

External script with no known license
https://peertube.uno/client/it-IT/chunk-43HSLLKF.js:

External script with no known license
https://peertube.uno/client/it-IT/chunk-JWIX4ECY.js:

External script with no known license
https://peertube.uno/client/it-IT/chunk-Z3PWC2SQ.js:

External script with no known license`

**Comment by Chocobozzz** [comment] 2024-11-29 08:31
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/1254

**Closed by Chocobozzz** 2024-11-29 08:31 UTC
