### ISSUE TITLE
Multi Language Title and Description

### ISSUE THREAD

**Issue by StalinEXE** [Chocobozzz/PeerTube#1995] opened 2019-07-29 12:50 UTC
Can you add an abillity to translate titles and descriptions to another languages for multi language support? It will be great addition for [#939](https://github.com/Chocobozzz/PeerTube/issues/939)

[Feature on YouTube, En](https://support.google.com/youtube/answer/6289575?hl=en)

**Comment by robinkooli** [comment] 2019-07-29 17:16
YouTube has made it extremely easy to make subtitles for videos. 👍

**Comment by Chocobozzz** [comment] 2021-04-13 09:54
Duplicate of https://github.com/Chocobozzz/PeerTube/issues/2992

**Closed by Chocobozzz** 2021-04-13 09:54 UTC
Labels: Type: Enhancement :sparkles:
