### ISSUE TITLE
Allow auto-registration with admin approval

### ISSUE THREAD

**Issue by narcisgarcia** [Chocobozzz/PeerTube#3268] opened 2020-11-07 10:15 UTC
Feature request: On administration panel (configuration - New users) should be an option to require administrators approval of each new account.
This implies e-mail notification to administrators on each registration event.

**Comment by rigelk** [comment] 2020-11-07 10:52
Duplicate of #2242.

**Comment by narcisgarcia** [comment] 2020-11-07 11:22
I'm not talking about invitation nor CAPTCHA methods.
This is not an exact duplicate.

**Comment by rigelk** [comment] 2020-11-07 11:24
Please detail your difference more then

**Comment by narcisgarcia** [comment] 2020-11-07 11:27
I'm asking for administrators approval as step for new account to be usable; not depending on what way was used to register account.

**Comment by test2a** [comment] 2020-11-07 11:43
What I think the feature request means is  manual verification of all signups regardless of email verification.
So they can keep open signups but in the end the user is informed that accounts are activated only on manual verification.

**Closed** 2022-12-14 09:00 UTC
Labels: Type: Feature Request :sparkles:, Component: Moderation :godmode:
