### ISSUE TITLE
Custom Upload Quota

### ISSUE THREAD

**Issue by hexydes** [Chocobozzz/PeerTube#2998] opened 2020-07-23 21:30 UTC
[Enhancement Request]

It would be nice to have a custom quota amount for creators. For my instance, I am allowing certain users to have upload permissions. In my case, 1GB is way too small (many can barely fit 3-4 videos when I'm hoping they can have 5-10) but 5GB is way too large (a few users would overrun the present state of my server). It doesn't really make sense to add 100 different options in the drop-down, but some "custom" option and then a field to type a number in GB would be great.

**Comment by Chocobozzz** [comment] 2020-07-24 06:51
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/666

**Closed by Chocobozzz** 2020-07-24 06:51 UTC
