### ISSUE TITLE
Want to add to youtube-dl extractor to enable better 'Import with URL' results

### ISSUE THREAD

**Issue by bluecat999** [Chocobozzz/PeerTube#2385] opened 2020-01-06 22:48 UTC
**What happened?**
I imported a video from a youtube-dl-recognized PeerTube instance (peertube.co.uk) and there were some missing or unexpected results:

- Description is truncated
- Language missing (see https://github.com/Chocobozzz/PeerTube/issues/2252)
- License missing (see https://github.com/Chocobozzz/PeerTube/issues/2252)
- Captions are missing (see https://github.com/Chocobozzz/PeerTube/issues/1016)
- Original publish date is overwritten
(Support was untested, I don't know what that is for :/ )

**What do you expect to happen instead?**
I expect these to be properly extracted by youtube-dl and imported by PeerTube.

### I intend to help fix this by improving the youtube-dl extractor.
It already extracts the license properly. I can probably add fields to extract the language and (if we determine it to be expected behaviour) the original publish date if it exists. I am unsure about the captions but I believe that is possible. I will need feedback on the support section.

After this, is should be simple enough for someone to fix the PeerTube import script.

**Comment by BlueCatYellowCat** [comment] 2020-01-06 22:49
Note: I believe this is important to fix soon due to the news of peertube.video, a large instance, closing.

**Comment by Chocobozzz** [comment] 2020-01-07 07:46
You'll need to patch youtube-dl to support these new fields

**Comment by rigelk** [comment] 2020-01-07 07:49
hi @bluecat999 - please provide the example video that demonstrates your bugs.

Description is truncated by design (https://github.com/Chocobozzz/PeerTube/blob/develop/server/helpers/youtube-dl.ts#L221-L229), but within a limit of 10k chars (!). Is the description you refer to longer?

Same goes for original publish date (see same file).

**Comment by rigelk** [comment] 2020-01-07 09:07
@Chocobozzz @bluecat999 note that these new fields are being added in https://github.com/ytdl-org/youtube-dl/pull/23657. License is already present, though, so we might want to investigate why it failed so far.

**Comment by rigelk** [comment] 2020-03-02 20:21
with https://github.com/ytdl-org/youtube-dl/pull/23657 now merged, we should expect things to improve noticeably as soon as youtube-dl releases a new version.

**Closed** 2020-04-03 12:27 UTC
Labels: Component: Import
