### ISSUE TITLE
Dislikes count does not appear anymore in Beta.8

### ISSUE THREAD

**Issue by DavidLibeau** [Chocobozzz/PeerTube#653] opened 2018-06-12 12:47 UTC
* **PeerTube version or URL:** beta.8

* **What is the expected behaviour?**
See the dislikes count when hover the likes bar.
* **What do you see instead?**
`{{dislikesNumber}}`
<img width="240" alt="sans titre" src="https://user-images.githubusercontent.com/11574966/41291272-caecaa66-6e3e-11e8-9263-8603bf6be667.png">

**Comment by Chocobozzz** [comment] 2018-06-12 12:48
Duplicate of https://github.com/Chocobozzz/PeerTube/issues/648

**Closed by Chocobozzz** 2018-06-12 12:48 UTC
