### ISSUE TITLE
Video-Link via Embedding code is wrong

### ISSUE THREAD

**Issue by gloschtla** [Chocobozzz/PeerTube#4343] opened 2021-08-22 09:41 UTC
You can reproduce this by looking on any instance with the new version 3.3.0: https://instances.joinpeertube.org/instances?sort=-version&page=1

Open a recently uploaded video, click share button, copy the embedding iframe code, insert it into a html file then open it with a browser or just preview it online (html-css-js.com/). then hit the play button in the embedded video, then right click into the video frame, then "copy the video url"

the video id-code in this video url still is in old format, and there is /videos/ in the url which produces error 404. if you just remove this "/videos" from the url, you will be able to load the video

**Comment by gloschtla** [comment] 2021-08-22 09:49
screenshot with an example: 

[embedded video](https://i.snipboard.io/8xWMmU.jpg)

[error 404](https://i.snipboard.io/5z7thq.jpg)

**Comment by Chocobozzz** [comment] 2021-08-23 14:16
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/4267

**Closed by Chocobozzz** 2021-08-23 14:16 UTC
