### ISSUE TITLE
Video Duration Bug

### ISSUE THREAD

**Issue by kirill2400** [Chocobozzz/PeerTube#4595] opened 2021-12-01 19:34 UTC
### Describe the current behavior

There is a video with a duration of 4 minutes, the first 3 minutes is a video stream, from 3 to 4 minute contains only an audio stream. Peertube does not recognize this video correctly, as you can see in the screenshots. He thinks that video lenght is 3 min, but allow to watch more than 3:00 min, until video is over.

### Steps to reproduce:

1. Make a video with a video stream of 3 minutes duration and an audio stream of 4 minutes, as in the screenshot
![image](https://user-images.githubusercontent.com/30482699/144301329-12ceae3b-cf47-437a-90f2-521af3dcb13d.png)
2. Upload it to PeerTube your instance
3. It might be worth waiting for the encoding
4. Start video playback and wait until it ends completely, that is, wait about 4 minutes
![image](https://user-images.githubusercontent.com/30482699/144301353-6a5f2605-90b8-4bc1-9911-e031132f27ed.png)
![image](https://user-images.githubusercontent.com/30482699/144301415-f4be53e4-0fbc-43fc-b4fc-22c84961664c.png)

### Describe the expected behavior

Youtube in this case just fill last minute with blackscreen and show video duration right

### URL:

https://spacecomfort.miracleinsense.ru - Dont matter

### version:

3.4.1

### NodeJS version:

v12.22.7

### Ffmpeg version:

4.4.1-static

### Browser name, version and platforms on which you could reproduce the bug:

Opera GX LVL 3 (core: 81.0.4196.61) - Dont matter

**Comment by kontrollanten** [comment] 2021-12-01 20:10
It's hard to understand exactly what you mean, but I guess this is duplicate of https://github.com/Chocobozzz/PeerTube/issues/4130

**Comment by kirill2400** [comment] 2021-12-01 20:23
No. There is a video with a duration of 4 minutes, the first 3 minutes is a video stream, from 3 to 4 minute contains only an audio stream. Peertube does not recognize this video correctly, as you can see in the screenshots. He thinks that video lenght is 3 min, but allow to watch more than 3:00 min, until video is over.

**Comment by kirill2400** [comment] 2021-12-01 20:27
But youtube in this case just fill last minute with blackscreen and show video duration right

**Comment by Chocobozzz** [comment] 2021-12-02 07:55
Hello,

Please fill the [bug template](https://github.com/Chocobozzz/PeerTube/blob/develop/.github/ISSUE_TEMPLATE/00-bug-issue.md)

**Comment by kirill2400** [comment] 2021-12-02 08:13
> Hello,
> 
> Please fill the [bug template](https://github.com/Chocobozzz/PeerTube/blob/develop/.github/ISSUE_TEMPLATE/00-bug-issue.md)

Done

**Comment by Chocobozzz** [comment] 2021-12-02 09:02
Could you share this video so I can reproduce and see how to fix this bug?

**Comment by kirill2400** [comment] 2021-12-02 09:57
> Could you share this video so I can reproduce and see how to fix this bug?
https://docserver.miracleinsense.ru/s/as4Wmx7GBrp6nNE

**Comment by kirill2400** [comment] 2021-12-02 10:03
I remember that I merge this video stream from one file and audio stream from another file with ffmpeg without reencoding. So that file not show duration properly , for example, in VLC

**Comment by Chocobozzz** [comment] 2021-12-02 13:35
Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/9538ff139c8f0c0b00296e8a0bec7bcdd0838f8d

It's not perfect, but we now should correctly recover this inconsistency.

**Closed by Chocobozzz** 2021-12-02 13:35 UTC
Labels: Type: Bug :bug:, Component: Player :play_or_pause_button:
