### ISSUE TITLE
Ability to link to a certain time in video description

### ISSUE THREAD

**Issue by cdauth** [Chocobozzz/PeerTube#2007] opened 2019-08-07 08:17 UTC
I hope this hasn't been requested before, at least I couldn’t find anything related.

In YouTube, when you type in a timestamp (for example `5:12`) into the video description or a comment, it is transformed into a link. When clicking the link, the player jumps to that time stamp and starts playing from there. This is commonly used to create a table of contents in the video description, or to comment about a certain moment in the video.

It would be nice if PeerTube would support this as well. Currently, the only way that I could find is to manually create a link to the video at the given start time (for example `[0:20](/videos/watch/abcdef?start=20)`). This is less than ideal, because:
* The video ID has to be specified (simply using `?start=20` as the URL does not work, the base URL seems to be that of the instance, not of the video)
* The link will open in a new tab, causing the video to play in two different tabs at the same time

**Comment by Chocobozzz** [comment] 2019-08-07 08:18
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/1312  :)

**Closed by Chocobozzz** 2019-08-07 08:18 UTC
