### ISSUE TITLE
Open Telemetry metrics slows down the server

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#5531] opened 2023-01-12 22:38 UTC
### Describe the current behavior

<img width="709" alt="image" src="https://user-images.githubusercontent.com/6680299/212194314-86d1b1cf-b546-4751-94e8-1500f33efcf3.png">

Between 23:00 and 23:20 in the above graph Prometheus where calling the metrics endpoint once in a minute, then PeerTube was removed as Prometheus target.

### Steps to reproduce

1. Enable open_telemetry metrics.
2. Start prometheus with default interval (1 minute)

**Comment by Chocobozzz** [comment] 2023-01-13 07:57
Hi,

Can you provide more information?
  * Does the metric endpoint it slow down other HTTP responses?
  * What are the slow HTTP responses?
  * If it's only the metric endpoint that is slow, what are the SQL queries involved?

We did not optimize the metric endpoint (some complex SQL requests, we process sequentially since we don't want to overload the server + we don't need to answer quickly).

**Comment by Chocobozzz** [comment] 2023-01-13 09:03
> I haven't found a good way to find out this yet, neither in Grafana nor Nginx Amplify.

You can find detailed response time in nginx log

> Where can I find this information?

In PostgreSQL slow logs

**Comment by Chocobozzz** [comment] 2023-01-13 10:16
It's difficult to help without more information. What you can try:
 * Enable tracing
 * Profile the application using `--inspect` nodejs option
 * Check grafana opentelemetry dashboard to see if there is an overload on PostgreSQL, Redis, high CPU usage etc
 * Change Prometheus scraping to 30s and see if you still have 40-50 seconds of small latency (we have an internal cache of 1 minutes when getting internal stats, so if you still have the same latency the cache invalidation could be the issue)

**Comment by Chocobozzz** [comment] 2023-01-16 09:16
Thanks, so it seems the issue is PostgreSQL/Redis is overloaded when Prometheus scraping is enabled. To check what is the root cause, can you:
 * Disable Redis and PostgreSQL scraping from Prometheus? (`postgresql` and `redis` job names in prometheus configuration)
 * Can you disable prometheus scrapping and call the opentelemtry endpoint of peertube to check if it's the cause of the issue? And if it is, I you can check on the redis/postgresql server what kind of data is transferred

**Comment by Chocobozzz** [comment] 2023-02-09 07:23
So maybe peertube has difficulties to display all the metrics. Could be related to HTTP requests stats?
You can try to disable some metrics to find which one is problematic (for example https://github.com/Chocobozzz/PeerTube/blob/develop/server/lib/opentelemetry/metrics.ts#L65)

**Comment by Chocobozzz** [comment] 2023-02-27 13:07
Thanks, I added the ability to disable HTTP duration metrics in https://github.com/Chocobozzz/PeerTube/commit/8d1f78044ca6eb9995001d3ab83be62460e043a6

**Closed by Chocobozzz** 2023-02-27 13:07 UTC
Labels: Status: Waiting for answer

**Comment by aeharding** [comment] 2023-04-01 14:50
<img width="527" alt="image" src="https://user-images.githubusercontent.com/2166114/229296255-a953c767-5c8f-41bc-9f90-0b03aa5583f2.png">

Disabling the duration metric has worked really well for our instance! 😊 Network traffic has dropped, and CPU load has also improved.

It would be nice if this boolean would keep the metrics (raw number of requests & status code) while dropping only the duration in ms, but not a huge deal!
