### ISSUE TITLE
Video Studio seems to cause out-of-sync audio in some browsers

### ISSUE THREAD

**Issue by Mike35538** [Chocobozzz/PeerTube#5561] opened 2023-01-28 07:31 UTC
### Describe the current behavior

When watching a video after trimming the front and end in video studio it seems to have out-of-sync audio depending on what browser you watch it in.

After editing the video, the audio is off by about 1 second compared to the original video before the editing but it is browser specific. On the newly edited video, the audio is perfectly in-sync in Firefox but in Chrome and Edge the audio is 1 second off.

### Steps to reproduce

1. Use a video where you can clearly see someone talking if possible and give it a new start time by editing off 30+ seconds from the beginning, and also give it a new end time by editing off 30+ seconds from the end.
2. Run video edition and then let the video transcode fully.
3. Watch the video in Firefox, then watch it in Chrome, Edge. See that the audio from the person talking is out-of-sync with the video in the latter two browsers.

### Describe the expected behavior

No audio/video sync changes after editing.

### Additional information

  * Version: 5.0.1
  * Ffmpeg version: I've seen it in 4.3.5 and 4.1.9

**Comment by Chocobozzz** [comment] 2023-02-13 14:44
Hi,

Can you share the input file? It seems I can't reproduce but it can depend on the codec, video length etc

**Comment by Chocobozzz** [comment] 2023-02-14 10:52
Thanks, I think it will be fixed by https://github.com/Chocobozzz/PeerTube/commit/4ea827076df39935375d66fffb5e1e27e667111e

**Closed by Chocobozzz** 2023-02-14 10:52 UTC
Labels: Type: Bug :bug:, Component: Studio
