### ISSUE TITLE
Censor banned accounts

### ISSUE THREAD

**Issue by dausruddin** [Chocobozzz/PeerTube#5830] opened 2023-06-10 05:00 UTC
### Describe the problem to be solved

When a user is banned, their profile picture and bio are still visible.
Some of these spam accounts have explicit and inappropriate profile picture and bio, they sometimes putting link of weird stuff.

### Describe the solution you would like

My suggestion is to censor their peofile picture and bio when banned. 
A better idea is to make them optional when banning, and editable afterwards in-case mods changed their minds regarding the censoring.

**Comment by vid-bin** [comment] 2023-06-11 13:22
I'd like to suggest the profile picture and bio is fully deleted on a ban. No reason to keep the content on our servers.

**Comment by vid-bin** [comment] 2023-06-11 21:51
> That would be great too, but I still suggest to make it optional when an admin is banning, like "tick this box to delete profile picture and bio". Some people might want those info to stay.

Should be the other way around. The checkmark box should be if you want to keep the bio/profile because it would involve less clicks when deleting spam accounts.

**Comment by Chocobozzz** [comment] 2023-06-18 15:48
Hi,

I think this issue is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/5127

**Closed by Chocobozzz** 2023-06-18 15:48 UTC
