### ISSUE TITLE
Youutbe - Sign in to confirm you’re not a bot. This helps protect our community

### ISSUE THREAD

**Issue by tio-trom** [Chocobozzz/PeerTube#6525] opened 2024-07-31 14:15 UTC
### Describe the current behavior

Cannot import videos from Youtube anymore. We rarely used our instance for that but maybe something changed on youtube's side. 

Logs:

```
error[7/31/2024, 4:12:03 PM] An error occurred while importing the video https://youtu.be/c7Z4DRhy9pI.

{
  "err": {
    "stack": "ExecaError: Command failed with exit code 1: /usr/bin/python3 /home/yunohost.app/peertube/storage/bin/yt-dlp --dump-json -f 'bestvideo[vcodec^=avc1][height=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=1080]+bestaudio/bestvideo[vcodec^=avc1][height<=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best' 'https://youtu.be/c7Z4DRhy9pI'\n\nERROR: [youtube] c7Z4DRhy9pI: Sign in to confirm you’re not a bot. This helps protect our community. Learn more\n    at getFinalError (file:///var/www/peertube/node_modules/execa/lib/return/final-error.js:6:9)\n    at makeError (file:///var/www/peertube/node_modules/execa/lib/return/result.js:108:16)\n    at getAsyncResult (file:///var/www/peertube/node_modules/execa/lib/methods/main-async.js:167:4)\n    at handlePromise (file:///var/www/peertube/node_modules/execa/lib/methods/main-async.js:150:17)\n    at async YoutubeDLCLI.run (file:///var/www/peertube/dist/core/helpers/youtube-dl/youtube-dl-cli.js:141:24)\n    at async YoutubeDLCLI.getInfo (file:///var/www/peertube/dist/core/helpers/youtube-dl/youtube-dl-cli.js:89:22)\n    at async YoutubeDLWrapper.getInfoForDownload (file:///var/www/peertube/dist/core/helpers/youtube-dl/youtube-dl-wrapper.js:23:22)\n    at async buildYoutubeDLImport (file:///var/www/peertube/dist/core/lib/video-pre-import.js:104:25)\n    at async handleYoutubeDlImport (file:///var/www/peertube/dist/core/controllers/api/videos/import.js:114:38)",
    "message": "Cannot fetch information from import for URL https://youtu.be/c7Z4DRhy9pI",
    "code": 0,
    "cause": {
      "stack": "ExecaError: Command failed with exit code 1: /usr/bin/python3 /home/yunohost.app/peertube/storage/bin/yt-dlp --dump-json -f 'bestvideo[vcodec^=avc1][height=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=1080]+bestaudio/bestvideo[vcodec^=avc1][height<=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best' 'https://youtu.be/c7Z4DRhy9pI'\n\nERROR: [youtube] c7Z4DRhy9pI: Sign in to confirm you’re not a bot. This helps protect our community. Learn more\n    at getFinalError (file:///var/www/peertube/node_modules/execa/lib/return/final-error.js:6:9)\n    at makeError (file:///var/www/peertube/node_modules/execa/lib/return/result.js:108:16)\n    at getAsyncResult (file:///var/www/peertube/node_modules/execa/lib/methods/main-async.js:167:4)\n    at handlePromise (file:///var/www/peertube/node_modules/execa/lib/methods/main-async.js:150:17)\n    at async YoutubeDLCLI.run (file:///var/www/peertube/dist/core/helpers/youtube-dl/youtube-dl-cli.js:141:24)\n    at async YoutubeDLCLI.getInfo (file:///var/www/peertube/dist/core/helpers/youtube-dl/youtube-dl-cli.js:89:22)\n    at async YoutubeDLWrapper.getInfoForDownload (file:///var/www/peertube/dist/core/helpers/youtube-dl/youtube-dl-wrapper.js:23:22)\n    at async buildYoutubeDLImport (file:///var/www/peertube/dist/core/lib/video-pre-import.js:104:25)\n    at async handleYoutubeDlImport (file:///var/www/peertube/dist/core/controllers/api/videos/import.js:114:38)",
      "message": "Command failed with exit code 1: /usr/bin/python3 /home/yunohost.app/peertube/storage/bin/yt-dlp --dump-json -f 'bestvideo[vcodec^=avc1][height=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=1080]+bestaudio/bestvideo[vcodec^=avc1][height<=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best' 'https://youtu.be/c7Z4DRhy9pI'\n\nERROR: [youtube] c7Z4DRhy9pI: Sign in to confirm you’re not a bot. This helps protect our community. Learn more",
      "shortMessage": "Command failed with exit code 1: /usr/bin/python3 /home/yunohost.app/peertube/storage/bin/yt-dlp --dump-json -f 'bestvideo[vcodec^=avc1][height=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=1080]+bestaudio/bestvideo[vcodec^=avc1][height<=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best' 'https://youtu.be/c7Z4DRhy9pI'",
      "command": "/usr/bin/python3 /home/yunohost.app/peertube/storage/bin/yt-dlp --dump-json -f bestvideo[vcodec^=avc1][height=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=1080]+bestaudio/bestvideo[vcodec^=avc1][height<=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best https://youtu.be/c7Z4DRhy9pI",
      "escapedCommand": "/usr/bin/python3 /home/yunohost.app/peertube/storage/bin/yt-dlp --dump-json -f 'bestvideo[vcodec^=avc1][height=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=1080]+bestaudio/bestvideo[vcodec^=avc1][height<=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best' 'https://youtu.be/c7Z4DRhy9pI'",
      "cwd": "/var/www/peertube",
      "durationMs": 2338.603966,
      "failed": true,
      "timedOut": false,
      "isCanceled": false,
      "isGracefullyCanceled": false,
      "isTerminated": false,
      "isMaxBuffer": false,
      "isForcefullyTerminated": false,
      "exitCode": 1,
      "stdout": "",
      "stderr": "ERROR: [youtube] c7Z4DRhy9pI: Sign in to confirm you’re not a bot. This helps protect our community. Learn more",
      "stdio": [
        null,
        "",
        "ERROR: [youtube] c7Z4DRhy9pI: Sign in to confirm you’re not a bot. This helps protect our community. Learn more"
      ],
      "ipcOutput": [],
      "pipedFrom": []
    }
  }
}

error[7/31/2024, 4:12:03 PM] Client log: Backend returned code 400, errorMessage is: Cannot fetch information from import for URL https://youtu.be/c7Z4DRhy9pI

{
  "tags": [
    "client"
  ],
  "username": "tio",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0",
  "meta": "{\"url\":\"https://videos.trom.tf/api/v1/videos/imports/\"}",
  "url": "https://videos.trom.tf/videos/upload#import-url"
}

error[7/31/2024, 4:12:03 PM] Client log: Error: Cannot fetch information from import for URL https://youtu.be/c7Z4DRhy9pI

{
  "tags": [
    "client"
  ],
  "username": "tio",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0",
  "url": "https://videos.trom.tf/videos/upload#import-url"
}
```

### Additional information

Version 6.2.0

**Comment by Chocobozzz** [comment] 2024-07-31 14:23
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/6522

**Closed by Chocobozzz** 2024-07-31 14:23 UTC
Labels: Type: Duplicate :loop:
