### ISSUE TITLE
Peertube Sharing has undesirable behaviour

### ISSUE THREAD

**Issue by LPS-github** [Chocobozzz/PeerTube#3103] opened 2020-08-18 20:26 UTC
When attempting to share a video of a creator I subscribe to, I am given the URL of the instance I am a user of instead of the original Public URL. In this case it is invalid (requires login?) and only available to someone on my instance.

![image](https://user-images.githubusercontent.com/69872464/90561679-13524680-e16f-11ea-8dab-3efee8ad9342.png)

The expected behaviour would be a direct link to the original.

![image](https://user-images.githubusercontent.com/69872464/90561628-ff0e4980-e16e-11ea-91ce-3dbc21c898b6.png)

![image](https://user-images.githubusercontent.com/69872464/90561744-2ebd5180-e16f-11ea-99f3-5a245122cfcf.png)

This would be the preferred behaviour from the original instance. It’s now available to anyone without login.

Thanks!

**Comment by Chocobozzz** [comment] 2020-08-19 06:27
I think users expect to share their current page, not another one. Moreover we try to avoid redirecting people to the origin instance to not overload it (sharing the video using your instance helps to share the load). We could add a checkbox in the more customization though.

**Comment by HuGo-Y** [comment] 2020-08-19 18:06
> I think users expect to share their current page, not another one. Moreover we try to avoid redirecting people to the origin instance to not overload it (sharing the video using your instance helps to share the load). 

Not only that, but redirecting people to unknown instances may be dangerous, we don't know what else is on that instance, maybe NSFW or something illegal?

**Comment by LPS-github** [comment] 2020-08-20 21:08
Maybe this is a larger issue.  Should we not be sharing the link only not the entire instance?

Something like how it works on Nextcloud, rather like an embedded page, access is given to only the shared content.

![image](https://user-images.githubusercontent.com/69872464/90825519-09634b80-e307-11ea-9c04-18790629d4dd.png)

![image](https://user-images.githubusercontent.com/69872464/90825603-27c94700-e307-11ea-9a46-005af6738c99.png)

Also, my understanding is that unless the video is actually hosted/mirrored on "my site" it is still streaming from the original is it not?

By linking to a quasi embed page we get rid of the potentially offensive site and only show the intended content.

**Comment by LPS-github** [comment] 2020-08-20 22:17
I've continued to test and it appears that sharing a video that I subscribe to as a USER will not work since it's only usable to me.

The scenario goes like this:

I subscribe to a remote Channel, via Global search, from my home instance which then aggregates videos to my Subscription tab.

New videos arrive and if I think it should be seen by a larger audience I attempt to share it.

So either sharing links are available to anyone other than the user or the link should point to the source.

**Comment by LPS-github** [comment] 2020-08-20 22:24
Just a comment to add.

The ability to Subscribe to channels with Global search from a single-user instance is really powerful and desirable.  This removes, as you suggested, offensive or illegal content that is often visible on larger instances.

I now have a perfectly curated timeline/subscription tab with only the content I want.

This can make Peertube truly federatee with smaller instances being desirable.  The ability to mirror select videos is also a great feature to add redundancy for things that are important as to not lose them.

**Comment by Chocobozzz** [comment] 2020-08-25 15:15
Closing this issue since it's a duplicate of https://github.com/Chocobozzz/PeerTube/issues/2972

For bugs please create a dedicated issue

**Closed by Chocobozzz** 2020-08-25 15:15 UTC
Labels: Type: Discussion :thought_balloon:
