### ISSUE TITLE
Home page cannot contain internal named anchor links

### ISSUE THREAD

**Issue by DalekDave** [Chocobozzz/PeerTube#5530] opened 2023-01-12 21:55 UTC
### Describe the problem to be solved

In the markup currently permitted for the home page, you cannot define named anchor links that link to a section within the home page. See the screenshot below:

![Dalek Zone home page - cannot have internal page anchor links](https://user-images.githubusercontent.com/64964084/212188508-7485c2eb-2b29-4d04-8370-8e86de29a60e.png)

My home page is long, and there is a "Sections in this page" menu that should consist of named anchor links that link to an associated name link in the same page. But I can't make that work in the markup, and so visitors have scroll down and down until they get to the section they're interested in.

### Describe the solution you would like

Can we extend the permitted markup to include named anchor links that go to a section title in the page being contained in a named anchor link?

Or am I not doing it night? You can see my home page markup in bug report #5527

And thanks again for all your work on PeerTube! :)

**Comment by Chocobozzz** [comment] 2023-03-08 14:12
Duplicate of https://github.com/Chocobozzz/PeerTube/issues/4298

**Closed by Chocobozzz** 2023-03-08 14:12 UTC
Labels: Type: Feature Request :sparkles:, Component: Custom Markdown
