### ISSUE TITLE
Whimsical videos seconds durations

### ISSUE THREAD

**Issue by pprw** [Chocobozzz/PeerTube#2666] opened 2020-04-20 18:44 UTC
For some reason, a lot of videos in my instance are displaying whimsical seconds durations. Hours and minutes are correct.

![image](https://user-images.githubusercontent.com/5262986/79787250-fb94be00-8346-11ea-8ca0-e01f51e1db7c.png)
![image](https://user-images.githubusercontent.com/5262986/79787304-11a27e80-8347-11ea-87d3-25d8cff79937.png)

Peertube instance: https://videos.ahp-numerique.fr

**Comment by rigelk** [comment] 2020-04-20 23:35
This was fixed in https://github.com/Chocobozzz/PeerTube/commit/03db5c3f979928419fb3ead8c65f0bce12d07f5c. Also duplicate of #2560.

**Closed** 2020-04-20 23:36 UTC
Labels: Type: Duplicate :loop:
