### ISSUE TITLE
record mode for permanent live

### ISSUE THREAD

**Issue by test2a** [Chocobozzz/PeerTube#3495] opened 2020-12-20 18:01 UTC
**Describe the problem to be solved**

how about we have a record mode for permanent lives too, say i start a permanent live today and i want to record the days events. i click on record and it keeps on saving. once i close the stream for the day, it asks if i want to save or not. if i click yes, it is saved or not.
this would also have the same size limitation like normal lives

the only reason for asking this feature is because a non permanent live changes the url and permanent does not but doesnt save.

a record mode for permanent live would be the perfect middle ground

**Describe the solution you would like:**
a record mode for permanent live videos

**Comment by Booteille** [comment] 2020-12-20 23:18
I thinki this is a duplicate of #3396

**Closed** 2020-12-21 00:33 UTC
Labels: Component: Live, Type: Duplicate :loop:
