### ISSUE TITLE
Blurr is not enought for NSFW or not safe for work videos

### ISSUE THREAD

**Issue by Zig-03** [Chocobozzz/PeerTube#515] opened 2018-04-17 16:21 UTC
You can still see what the NSFW or not safe for work videos are about from the video's thumbnail. 
Even blurring to 100% might eventually scare people away, simply because it'll spark curiosity. So parents for example, for sure will not suggest peertube to their kids or teachers to their students and so on. 

Why not make them **unlisted**, and if someone gets the link then they'd have to confirm they are 18+ by clicking a button or if they have an account, they should toggle the option that would allow viewing such content.

If someone doesn't have an account and has confirmed that he/she is 18+, the cookie containing this data should expire in a smart way, preventing maybe some other members of the family from viewing NSFW or not safe for work videos later.

Thank you.

**Comment by Chocobozzz** [comment] 2018-04-17 16:25
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/506 :)

**Closed by Chocobozzz** 2018-04-17 16:25 UTC

**Comment by Zig-03** [comment] 2018-06-20 22:44
@Chocobozzz the issue #506 has the status "implemented" yet I'm confused because I don't understand how that solves this issue.

If a child goes on Joinpeertube.org > [Instances](https://instances.joinpeertube.org/instances) (top right corner) > peertube.social > scroll through the videos and see a lot of NSFW blurred thumbnails.

**Comment by Chocobozzz** [comment] 2018-06-21 06:13
It is the administrator's choice to display NSFW videos or not. peertube.video administrator decided to blur these kind of videos.
