### ISSUE TITLE
Provide feed discovery in meta tags to make subscription simple

### ISSUE THREAD

**Issue by rptb1** [Chocobozzz/PeerTube#6719] opened 2024-11-11 16:42 UTC
### Describe the problem to be solved

If you try to pass a video channel such as https://framatube.org/c/framablog.audio/videos to a feed reader, it will complain that there is no feed there.

### Describe the solution you would like

This page, and quite a few others, *can* provide RSS and similar feeds, but they are hidden in a drop-down menu, like this:
![image](https://github.com/user-attachments/assets/22620e28-c139-4c38-83f0-6caa70423c9a)

However, the page HTML lacks any META tags that would provide feed discovery.  For example, in this case:
```
<link rel="alternate" type="application/rss+xml" 
  title="Lectures du Framablog" 
  href="/feeds/videos.xml?videoChannelId=332" />
```

Anyone who *does* choose from the drop down in their browser gets page full of RSS, instead of subscribing to the feed.

I suggest that everywhere that RSS (or other) feeds are available, they are provided in META tags, so that they can be easily discovered and subscribed.

This would help to promote PeerTube watching by making it easy to subscribe using e.g. podcast software.

[How to add RSS Autodiscovery to your site](https://www.petefreitag.com/blog/rss-autodiscovery/) is a short article about this topic, in case that helps.

Thanks!

**Comment by Chocobozzz** [comment] 2024-11-12 07:59
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/541

**Closed as completed by Chocobozzz** 2024-11-12 07:59 UTC
Labels: Type: Duplicate :loop:
