### ISSUE TITLE
[Plugin] When the plugin installation failed, the plugin still appears in the list of installed plugins

### ISSUE THREAD

**Issue by lutangar** [Chocobozzz/PeerTube#4217] opened 2021-06-30 08:12 UTC
**Describe the current behavior**

When the plugin installation failed, the plugin still appears in the list of installed plugins.
It leaves the plugin in an undetermined state with non-functional settings pages, etc...

**Steps to reproduce:**

If I recall correctly, one use-case where this happens was, referencing a non existent asset file in the `package.json` 
> maybe this case shouldn't fail the installation at all tho, but it happens in other cases as well...

**Describe the expected behavior**

In case of a failed plugin installation (meaning the user saw the installation failed toaster), a/the cleanup function should be called.
The plugin should to not appears in the list of installed plugin anymore.
Ideally this behavior should only happens for an install but not for a failed update.
> I'm not sure, but I think the behavior is fine on update.

**Comment by Chocobozzz** [comment] 2021-06-30 09:23
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/4140

**Closed by Chocobozzz** 2021-06-30 09:23 UTC
