### ISSUE TITLE
Can't launch PeerTube with PureBrowser

### ISSUE THREAD

**Issue by Tvax** [Chocobozzz/PeerTube#2074] opened 2019-08-22 20:42 UTC
I try to access [peertube.social](https://peertube.social) I get this message:

> We are sorry but it seems that PeerTube is not compatible with your web browser.
> 
> Please try with the latest version of Mozilla Firefox.
> 
> If you think this is a mistake, do not hesitate to report it.

I'm using PureBrowser 60.8.0esr (64-bit) on PureOS

It worked well before do I absolutely have to use PeerTube with Firefox from now on?

**Comment by realityfabric** [comment] 2019-08-22 22:20
This sounds like a duplicate of #2040

**Closed** 2019-08-23 07:05 UTC
Labels: Type: Duplicate :loop:
