### ISSUE TITLE
video buffer based on internet speed

### ISSUE THREAD

**Issue by Zig-03** [Chocobozzz/PeerTube#1109] opened 2018-09-23 10:10 UTC
Often times I click on a video, watch a few seconds (or pause it right at the beginning) and then close that tab and watch something else. The thing is that I have a good internet speed and in a matter of seconds I get the entire video buffered for no reason since I won't watch the whole video. I don't have a problem with that, but I think I'm wasting the server's resources this way.

**My suggestion:**

Buffer only the next **n** minutes from the point where the user is at. For example, if I'm at 1:35 then the video should buffer until 4:35 (3 min) or 6:35 (5 min) and continue buffering as we continue watching that video, but never surpass that 3 or 5 minutes of extra buffer that guarantees a smooth experience.

Now these timings (3 and 5 minutes) are just examples and they may not work for everyone because we all have a different internet speed. So we could either come up with a smart formula or just set some fixed values, for example:

if internet speed is =< 0.5 MB/s then do a 7 minutes buffer
if internet speed is between 0.5MB/s - 1 MB/s then do a 6 minutes buffer
if internet speed is between 1MB/s - 6 MB/s then do a 4 minutes buffer
if internet speed is => 6.1 MB/s then do a 3 minutes buffer

IMO, we'd be better if we had a formula for that. The formula should check if the internet speed can handle 1s buffer in 1s time then add extra buffer duration, just to be safe, for example 3 minutes. 

So if the internet speed can handle 1s buffer in 1s time then buffer 3 minutes more of video. 
If the internet speed can't handle 1s buffer in 1s time then determine how much can it buffer in 1s time and then depending on that gap add a few more extra minutes to buffer.

**Comment by rigelk** [comment] 2018-09-23 14:04
On the one hand you might be wasting the server's bandwidth, but on the other hand you quickly become a seeder for all chunks of the video. But I guess being a full seeder is only a goal for long term seeders (like seedboxes or replication servers).

**Comment by BO41** [comment] 2018-09-23 14:59
this is an duplicate to https://github.com/Chocobozzz/PeerTube/issues/75 or not?

I think @Zig-03 is right, but as @rigelk mentioned, sooner or later the project should be able to share peer connections.

**Comment by rigelk** [comment] 2018-09-23 15:10
Good catch! This is indeed a duplicate of #75, to the point we have exactly had the same arguments :sweat_smile: 

Closing in favor of #75's precedence.

**Closed by rigelk** 2018-09-23 15:10 UTC
Labels: Component: Player :play_or_pause_button:, Type: Enhancement :sparkles:

**Comment by rigelk** [comment] 2018-09-25 09:28
@Zig-03 please contribute on #75
