### ISSUE TITLE
My imports list trash icon shows wrongly on "processing" imports after a deletion

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#6265] opened 2024-03-12 14:13 UTC
### Describe the current behavior

if I delete an import stated "failed" or flagged as "video deleted" and if the next video is in "processing" status then I can see
a trash icon in front of the "processing" video which must be without any delete icon nor edit icon.

### Steps to reproduce

1. delete a video from My imports where the next video is in processing status and from the next page, appearing when the previous import on the list has been deleted.
2. check after deleted the delete icon is on the processing video

### Describe the expected behavior

processing video must have not any delete icon.

### Additional information

out of the issue subject but related to my imports, it would be very nice to have a filter like the "videos" section where we can show only failed,success,pending or processing imports, and also a global actions like delete as for now we can delete one by one.

**Comment by Chocobozzz** [comment] 2024-03-15 15:29
Hi,

I'm sorry but I can't reproduce. Can you try to reproduce this bug with peertube 6.0.3?

**Comment by ROBERT-MCDOWELL** [comment] 2024-03-15 16:30
yes it's already version 6.0.3. it's a minor glitch anyhow. for now I have no failed imports and no processing one to the next import which is to the next page increment and among more than 1000 increments it's hard to find it when I cannot order from state or date.

**Comment by Chocobozzz** [comment] 2024-05-29 13:39
Closing as I could not reproduce but don't hesitate to comment if you get more information on this bug :)

**Closed by Chocobozzz** 2024-05-29 13:39 UTC
Labels: Status: Waiting for answer
