### ISSUE TITLE
YouTube Bridge

### ISSUE THREAD

**Issue by PopeRigby** [Chocobozzz/PeerTube#1860] opened 2019-05-31 22:06 UTC
To have a way to view YouTube videos using your PeerTube account and PeerTube interface, you could try implementing something similar to what [Invidious](https://github.com/omarroth/invidious) or [NewPipe](https://github.com/TeamNewPipe/NewPipe) does. They allow you to watch YouTube videos through their interface, and in Invidious' case, using a seperate account. You could try to use one of their scrapers, and keep the YouTube subscriptions stored in PeerTube accounts. If this were integrated into PeerTube, it would be much easier to gradually move away from YouTube, because you aren't technically using their service.

**Comment by Chocobozzz** [comment] 2019-06-02 08:14
I think it is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/1045

**Comment by PopeRigby** [comment] 2019-06-02 23:31
It is? I didn't get that impression when I read through that issue. Well, how could this be implemented in a plugin? Do you mean browser plugin or PeerTube plugin?

**Comment by Chocobozzz** [comment] 2020-04-17 12:07
This issue is out of the scope of PeerTube. I think a third party service would be the way to do such thing (like NewPipe already does).

**Closed by Chocobozzz** 2020-04-17 12:07 UTC
Labels: Component: PeerTube Plugin :package:, Type: Enhancement :sparkles:
