### ISSUE TITLE
Channel display name and avatar in miniatures

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#4405] opened 2021-09-14 14:18 UTC
**Describe the problem to be solved**
Currently the video channel showed at the first page is the channel unique name, that name isn't always human friendly.

**Describe the solution you would like:**
We'd like to show the display name. Aside from that we'd also like to show the avatar to make some graphical distinction between channels.

**Describe alternatives you have considered**  
Make it configurable via the yaml config (maybe `instance.always_show_channel_display_name`).

**Comment by Chocobozzz** [comment] 2021-09-15 07:42
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/4040

**Comment by kontrollanten** [comment] 2021-11-20 06:14
I'd like to reopen this since my proposal of displaying avatar in video miniatures didn't get accepted. I can't find a good way to solve that with a plugin. Can we add the avatar to video miniatures and let the admins hide it with CSS if they don't like it? We could add a CSS snippet to the release notes if it's a common request to not display it.

**Comment by Chocobozzz** [comment] 2021-11-22 07:45
@kontrollanten open a new issue, this one had 2 features

> Can we add the avatar to video miniatures and let the admins hide it with CSS if they don't like it?

No sorry, we don't want to display avatars by default since they are not resized to be displayed efficiently in a small size.

**Closed by Chocobozzz** 2021-11-22 07:45 UTC
Labels: Type: Duplicate :loop:
