### ISSUE TITLE
Ephemeral video

### ISSUE THREAD

**Issue by markvdb** [Chocobozzz/PeerTube#3243] opened 2020-11-01 15:33 UTC
Some videos might be ephemeral. It would be great if they could expiry in some way. See also #3242 .

Maybe a minimalistic implementation could be based upon an expiry bit? If the bit is set on a video, and storage limits get reached (disk full/s3 quote/preset quota...), the oldest file with the expiry bit set gets pruned.

Would something along these lines fit the PeerTube philosophy and roadmap?

**Comment by rigelk** [comment] 2020-11-01 15:51
Duplicate of #1289, see https://github.com/Chocobozzz/PeerTube/issues/1289#issuecomment-680021457

**Closed by rigelk** 2020-11-01 15:51 UTC
Labels: Type: Duplicate :loop:
