### ISSUE TITLE
Multiple audio tracks in a video would be brilliant

### ISSUE THREAD

**Issue by LucaPranay** [Chocobozzz/PeerTube#3570] opened 2021-01-09 20:31 UTC
Imagine being able to choose if you want a (tutorial) video to have, or to not have background music… some people love videos without the background music, because they are listening to their own music - and many good videos on youtube suffer from this 'comercial' bullsh. …

Or imagine multiple languages in a video…

And this should probably be quite simple to implement imho

**Comment by Chocobozzz** [comment] 2021-01-11 10:11
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/939

**Closed by Chocobozzz** 2021-01-11 10:11 UTC
