### ISSUE TITLE
localized invitation/verification email

### ISSUE THREAD

**Issue by test2a** [Chocobozzz/PeerTube#3286] opened 2020-11-11 04:20 UTC
**Describe the problem to be solved**
as observed by @jeena in https://tube.jeena.net/videos/watch/6367bdb5-d9e1-4a8f-b04d-0105c927cc04?start=1m37s
the password email is sent in the default language of the server. this user describes how he is unable to send the invitation in any other language other than english in his case.

**Describe the solution you would like:**
allow the admin to customize the language of the invitation email so that a localized version can be sent if the admin so chooses

**Describe alternatives you have considered**

**Comment by Chocobozzz** [comment] 2020-11-11 07:28
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/912

**Closed by Chocobozzz** 2020-11-11 07:28 UTC
