### ISSUE TITLE
Video bitrate too high - transcoding needs a maxrate

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#997] opened 2018-08-31 22:28 UTC
I might be wrong about my assessment of the situation so far, but it looks like the transcode process isn't specifying a bitrate, so ffmpeg defaults to a particular quality level with no bitrate cap. This means that video which suddenly gets complicated (snow, textures, etc) will look great but the player will struggle to keep up.

Here's a sample video. (Play in 1080p) It starts off playing smoothly for me, but the complexity gradually increases until the player can't keep up any longer:

https://diode.zone/videos/watch/7d428b63-8694-4cb9-9707-856a255f4b94

I mentioned this briefly in #938, but it seems like as part of the future options we allow for customizing ffmpeg, it would be really useful to set the specific bitrate caps according to either the available bandwidth we expect to have per-stream, and the available client CPU power on the client side.

**Comment by rigelk** [comment] 2018-08-31 22:49
@scanlime there is definitely something to be done there, setting a `-maxbuffer` and `-maxrate`. Since we already know a maximum rate of 3Mbit/s is more or less what we target, that could be a nice limit. There is a nice explanation of how to set the rate limits dynamically on [this article](https://videoblerg.wordpress.com/2017/11/10/ffmpeg-and-how-to-use-it-wrong/) too, if you want to add dynamicity to these parameters.

If you can make tests with it, the code is sitting in [server/helpers/ffmpeg-utils.ts](https://github.com/Chocobozzz/PeerTube/blob/develop/server/helpers/ffmpeg-utils.ts).

**Comment by Nutomic** [comment] 2018-09-28 07:35
Duplicate of #638.

**Comment by Chocobozzz** [comment] 2018-09-28 08:38
Thanks @Nutomic

**Closed by Chocobozzz** 2018-09-28 08:38 UTC
Labels: Component: Transcoding, Type: Enhancement :sparkles:
