### ISSUE TITLE
Unable to create live in version 4.0.0-RC-1

### ISSUE THREAD

**Issue by Zagur** [Chocobozzz/PeerTube#4610] opened 2021-12-06 14:17 UTC
**Describe the current behavior**
when we update to version 4.0.0 when we initiate a live from OBS or jitsi meet it crashes.

**Steps to reproduce:**

Example in OBS
1. Create Live in Peertube 
2. Add url live in OBS
3. Initial transmission

OBS error: It's disconnects and connects all time

**Additional information**
We where upgrading from version 3.30 straight forward to 4.0.0
* PeerTube instance:
  * URL: https://fediverse.tv
  * version: 4.0-RC-1
  * NodeJS version: v14.18.2
  * Ffmpeg version: 4.1.8-0+deb10u1

* Browser name, version and platforms on which you could reproduce the bug: Firefox 94, Kubuntu 21.10 and Jitsi Meet Latest version
* Link to browser console log if relevant:

In our case we log here the output of storage log:

```
{"err":{"stack":"Error: ffmpeg exited with code 1: v:2,a:2: Invalid argument\n\n    at ChildProcess.<anonymous> (/var/www/vhosts/fediverse.tv/www/versions/peertube-v4.0.0-rc.1/node_modules/fluent-ffmpeg/lib/processor.js:182:22)\n    at ChildProcess.emit (events.js:400:28)\n    at ChildProcess.emit (domain.js:475:12)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)","message":"ffmpeg exited with code 1: v:2,a:2: Invalid argument\n"},"stdout":"","stderr":"ffmpeg version 4.1.8-0+deb10u1 Copyright (c) 2000-2021 the FFmpeg developers\n  built with gcc 8 (Debian 8.3.0-6)\n  configuration: --prefix=/usr --extra-version=0+deb10u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared\n  libavutil      56. 22.100 / 56. 22.100\n  libavcodec     58. 35.100 / 58. 35.100\n  libavformat    58. 20.100 / 58. 20.100\n  libavdevice    58.  5.100 / 58.  5.100\n  libavfilter     7. 40.101 /  7. 40.101\n  libavresample   4.  0.  0 /  4.  0.  0\n  libswscale      5.  3.100 /  5.  3.100\n  libswresample   3.  3.100 /  3.  3.100\n  libpostproc    55.  3.100 / 55.  3.100\nInput #0, flv, from 'rtmp://127.0.0.1:1935/live/6b1a7445-e7f8-4415-96af-bad90c5fb5ab':\n  Metadata:\n    fileSize        : 0\n    audiochannels   : 2\n    2.1             : false\n    3.1             : false\n    4.0             : false\n    4.1             : false\n    5.1             : false\n    7.1             : false\n    encoder         : obs-output module (libobs version 27.0.1+dfsg1-1)\n  Duration: 00:00:00.00, start: 0.066000, bitrate: N/A\n    Stream #0:0: Audio: aac (LC), 48000 Hz, stereo, fltp, 163 kb/s\n    Stream #0:1: Video: h264 (High), yuv420p(tv, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], 2560 kb/s, 30 fps, 30 tbr, 1k tbn, 60 tbc\n[NULL @ 0x55cd204c8a40] Unable to find a suitable output format for 'v:2,a:2'\nv:2,a:2: Invalid argument\n","level":"error","message":"Live transcoding error.","label":"fediverse.tv:443","timestamp":"2021-12-06T13:52:36.690Z"}
{"sessionId":"GUK38CPY","tags":["live","GUK38CPY"],"level":"info","message":"Live session ended.","label":"fediverse.tv:443","timestamp":"2021-12-06T13:52:36.690Z"}
{"level":"info","message":"Creating job to update video https://fediverse.tv/videos/watch/c04437d8-b23c-40a9-a7c1-dc30ba868ccd.","label":"fediverse.tv:443","timestamp":"2021-12-06T13:52:37.700Z"}
{"level":"info","message":"Processing ActivityPub broadcast in job 33404.","label":"fediverse.tv:443","timestamp":"2021-12-06T13:52:37.708Z"}
```

* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment] 2021-12-06 15:13
Hello,

What do you stream using OBS? Do you have the same error if you stream using `ffmpeg`? Could you try to check what ffmpeg command peertube is running? (using `ps` for example)

**Comment by Zagur** [comment] 2021-12-06 16:26
Hi @Chocobozzz 

When I try to stream with `ffmpeg` I have this output (bear in mind that this instruction we replicate it in another peertube instance and it runs OK): 

```
$ ffmpeg -f x11grab -s 1920x1200 -framerate 15 -i :0.0+1920,0 -f pulse -ac 2 -i default -c:v libx264 -preset fast -pix_fmt yuv420p -s 1280x800 -c:a aac -b:a 160k -ar 44100 -threads 0 -f flv "rtmp://fediverse.tv:1935/live/0981a365-b0f3-4714-9ad5-ea6c3693ad20"
ffmpeg version 4.4-6ubuntu5 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-7ubuntu1)
  configuration: --prefix=/usr --extra-version=6ubuntu5 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[x11grab @ 0x55a8d53e6740] Stream #0: not enough frames to estimate rate; consider increasing probesize
Input #0, x11grab, from ':0.0+1920,0':
  Duration: N/A, start: 1638807262.674152, bitrate: 1105920 kb/s
  Stream #0:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 1920x1200, 1105920 kb/s, 15 fps, 1000k tbr, 1000k tbn, 1000k tbc
Guessed Channel Layout for Input Stream #1.0 : stereo
Input #1, pulse, from 'default':
  Duration: N/A, start: 1638807262.683903, bitrate: 1536 kb/s
  Stream #1:0: Audio: pcm_s16le, 48000 Hz, stereo, s16, 1536 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264))
  Stream #1:0 -> #0:1 (pcm_s16le (native) -> aac (native))
Press [q] to stop, [?] for help
[libx264 @ 0x55a8d53ff9c0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x55a8d53ff9c0] profile High, level 3.2, 4:2:0, 8-bit
[libx264 @ 0x55a8d53ff9c0] 264 - core 160 r3011 cde9a93 - H.264/MPEG-4 AVC codec - Copyleft 2003-2020 - http://www.videolan.org/x264.html - options: cabac=1 ref=2 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=6 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=24 lookahead_threads=4 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=1 keyint=250 keyint_min=15 scenecut=40 intra_refresh=0 rc_lookahead=30 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, flv, to 'rtmp://fediverse.tv:1935/live/0981a365-b0f3-4714-9ad5-ea6c3693ad20':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 ([7][0][0][0] / 0x0007), yuv420p(tv, progressive), 1280x800, q=2-31, 15 fps, 1k tbn
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
  Stream #0:1: Audio: aac (LC) ([10][0][0][0] / 0x000A), 44100 Hz, stereo, fltp, 160 kb/s
    Metadata:
      encoder         : Lavc58.134.100 aac
[x11grab @ 0x55a8d53e6740] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
av_interleaved_write_frame(): Broken pipeB time=00:00:07.91 bitrate= 512.7kbits/s dup=0 drop=35 speed=0.972x    
    Last message repeated 1 times
[flv @ 0x55a8d53fde00] Failed to update header with correct duration.
[flv @ 0x55a8d53fde00] Failed to update header with correct filesize.
Error writing trailer of rtmp://fediverse.tv:1935/live/0981a365-b0f3-4714-9ad5-ea6c3693ad20: Broken pipe
frame=  128 fps= 13 q=27.0 Lsize=     531kB time=00:00:07.94 bitrate= 548.1kbits/s dup=0 drop=35 speed=0.826x    
video:392kB audio:156kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[libx264 @ 0x55a8d53ff9c0] frame I:1     Avg QP:12.48  size:131126
[libx264 @ 0x55a8d53ff9c0] frame P:41    Avg QP:19.68  size:  8780
[libx264 @ 0x55a8d53ff9c0] frame B:86    Avg QP:23.64  size:   517
[libx264 @ 0x55a8d53ff9c0] consecutive B-frames:  8.6%  3.1%  7.0% 81.2%
[libx264 @ 0x55a8d53ff9c0] mb I  I16..4: 50.9%  8.0% 41.1%
[libx264 @ 0x55a8d53ff9c0] mb P  I16..4:  3.1%  5.5%  2.2%  P16..4:  2.0%  0.5%  0.2%  0.0%  0.0%    skip:86.5%
[libx264 @ 0x55a8d53ff9c0] mb B  I16..4:  0.2%  0.0%  0.1%  B16..8:  1.0%  0.1%  0.1%  direct: 0.1%  skip:98.4%  L0:40.8% L1:57.0% BI: 2.2%
[libx264 @ 0x55a8d53ff9c0] 8x8 transform intra:41.2% inter:37.4%
[libx264 @ 0x55a8d53ff9c0] coded y,uvDC,uvAC intra: 27.0% 22.8% 18.0% inter: 0.5% 0.4% 0.1%
[libx264 @ 0x55a8d53ff9c0] i16 v,h,dc,p: 51% 48%  1%  0%
[libx264 @ 0x55a8d53ff9c0] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 21% 18% 51%  2%  1%  1%  2%  1%  3%
[libx264 @ 0x55a8d53ff9c0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 25% 36% 13%  3%  4%  4%  6%  3%  7%
[libx264 @ 0x55a8d53ff9c0] i8c dc,h,v,p: 69% 24%  6%  2%
[libx264 @ 0x55a8d53ff9c0] Weighted P-Frames: Y:0.0% UV:0.0%
[libx264 @ 0x55a8d53ff9c0] ref P L0: 74.6% 25.4%
[libx264 @ 0x55a8d53ff9c0] ref B L0: 94.2%  5.8%
[libx264 @ 0x55a8d53ff9c0] ref B L1: 95.0%  5.0%
[libx264 @ 0x55a8d53ff9c0] kb/s:391.87
[aac @ 0x55a8d5401480] Qavg: 168.828
Conversion failed!
```

When we execute the command at the same time we have this in top:

```
PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                            
24877 peertube  20   0 1030292 206716  38984 S   2.7   0.3   2:27.85 peertube                                                                                                                                           
27748 peertube  20   0  256000  37144  29736 S   1.3   0.1   0:00.04 /usr/bin/ffprobe -show_streams -show_format rtmp://127.0.0.1:1935/live/7137b414-f3cd-4b7f-b286-aa66b3d1267a                                        
30878 www-data  20   0  349824  15156   6352 S   0.3   0.0   0:50.90 nginx: worker process
```

Best regards,
Zagur.

**Comment by rnek0** [comment] 2021-12-07 06:43
I couldn't connect with OBS but with Jitsi Meet it works.

**Comment by Chocobozzz** [comment] 2021-12-07 12:43
I can't reproduce. Please replace `dist/server/lib/live/shared/muxing-session.js` by attached file, restart peertube and retry to run a live session. PeerTube should log the ffmpeg command it tries to run.
[Uploading muxing-session.js.zip…]()

**Comment by Zagur** [comment] 2021-12-07 13:13
Hi @Chocobozzz 

This is the ffmpeg command:

```bash
error[7/12/2021, 14:06:11] Live transcoding error.

{
  "err": {
    "stack": "Error: ffmpeg exited with code 1: v:2,a:2: Invalid argument\n\n    at ChildProcess.<anonymous> (/var/www/vhosts/fediverse.tv/www/versions/peertube-v4.0.0-rc.1/node_modules/fluent-ffmpeg/lib/processor.js:182:22)\n    at ChildProcess.emit (events.js:400:28)\n    at ChildProcess.emit (domain.js:475:12)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)",
    "message": "ffmpeg exited with code 1: v:2,a:2: Invalid argument\n"
  },
  "stdout": "",
  "stderr": "ffmpeg version 4.4.1-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2021 the FFmpeg developers\n  built with gcc 8 (Debian 8.3.0-6)\n  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg\n  libavutil      56. 70.100 / 56. 70.100\n  libavcodec     58.134.100 / 58.134.100\n  libavformat    58. 76.100 / 58. 76.100\n  libavdevice    58. 13.100 / 58. 13.100\n  libavfilter     7.110.100 /  7.110.100\n  libswscale      5.  9.100 /  5.  9.100\n  libswresample   3.  9.100 /  3.  9.100\n  libpostproc    55.  9.100 / 55.  9.100\nInput #0, flv, from 'rtmp://127.0.0.1:1935/live/f1930bfa-bc62-4e5a-8ea4-7d46084975fd':\n  Metadata:\n    |RtmpSampleAccess: false\n    fileSize        : 0\n    audiochannels   : 2\n    2.1             : false\n    3.1             : false\n    4.0             : false\n    4.1             : false\n    5.1             : false\n    7.1             : false\n    encoder         : obs-output module (libobs version 27.0.1+dfsg1-1)\n  Duration: 00:00:00.00, start: 0.066000, bitrate: N/A\n  Stream #0:0: Audio: aac (LC), 48000 Hz, stereo, fltp, 163 kb/s\n  Stream #0:1: Video: h264 (High), yuv420p(tv, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], 2560 kb/s, 30 fps, 30 tbr, 1k tbn, 60 tbc\n[NULL @ 0x739be80] Unable to find a suitable output format for 'v:2,a:2'\nv:2,a:2: Invalid argument\n",
  "ffmpegShellCommand": "ffmpeg -n 5 /usr/local/bin/ffmpeg -i rtmp://127.0.0.1:1935/live/f1930bfa-bc62-4e5a-8ea4-7d46084975fd -y -filter_complex [v:0]split=4[vtemp480][vtemp360][vtemp240][vtemp720];[vtemp480]scale=w=-2:h=480[vout480];[vtemp360]scale=w=-2:h=360[vout360];[vtemp240]scale=w=-2:h=240[vout240];[vtemp720]scale=w=-2:h=720[vout720] -threads 4 -sc_threshold 0 -max_muxing_queue_size 1024 -map_metadata -1 -b_strategy 1 -bf 16 -pix_fmt yuv420p -map [vout480] -level:v:0 3.1 -g:v:0 60 -c:v:0 libx264 -preset veryfast -r:v:0 30 -b:v:0 1474560 -maxrate 1474560 -bufsize 2949120 -map a:0 -c:a:0 copy -map [vout360] -level:v:1 3.1 -g:v:1 60 -c:v:1 libx264 -preset veryfast -r:v:1 30 -b:v:1 1036800 -maxrate 1036800 -bufsize 2073600 -map a:0 -c:a:1 copy -map [vout240] -level:v:2 3.1 -g:v:2 60 -c:v:2 libx264 -preset veryfast -r:v:2 30 -b:v:2 522240 -maxrate 522240 -bufsize 1044480 -map a:0 -c:a:2 copy -map [vout720] -level:v:3 3.1 -g:v:3 60 -c:v:3 libx264 -preset veryfast -r:v:3 30 -b:v:3 3041280 -maxrate 3041280 -bufsize 6082560 -map a:0 -c:a:3 copy -hls_time 4 -hls_list_size 15 -hls_flags delete_segments+independent_segments -hls_segment_filename /var/www/vhosts/fediverse.tv/www/storage/streaming-playlists/hls/7c148faa-9767-4feb-91fa-36b6b3fd1b72/%v-%06d.ts -master_pl_name master.m3u8 -f hls -var_stream_map v:0,a:0 v:1,a:1 v:2,a:2 v:3,a:3 /var/www/vhosts/fediverse.tv/www/storage/streaming-playlists/hls/7c148faa-9767-4feb-91fa-36b6b3fd1b72/%v.m3u8",
  "tags": [
    "live",
    "A69U3EYO",
    "7c148faa-9767-4feb-91fa-36b6b3fd1b72"
  ]
}
```

Regards,
zagur

**Comment by Chocobozzz** [comment] 2021-12-07 14:13
What OS do you use?

**Comment by drym3r** [comment] 2021-12-07 14:21
@Chocobozzz Debian buster

**Comment by drym3r** [comment] 2021-12-07 14:33
Also, we've tried launching on the server manually the same order that peertube seems to have trouble launching.  The next command is the same as Zagur copied on the error above (we've only added the quotes on every part that has [] so bash could execute it):

```bash
ffmpeg -n 5 /usr/local/bin/ffmpeg -i rtmp://127.0.0.1:1935/live/f1930bfa-bc62-4e5a-8ea4-7d46084975fd -y -filter_complex "[v:0]split=4[vtemp480][vtemp360][vtemp240][vtemp720];[vtemp480]scale=w=-2:h=480[vout480];[vtemp360]scale=w=-2:h=360[vout360];[vtemp240]scale=w=-2:h=240[vout240];[vtemp720]scale=w=-2:h=720[vout720]" -threads 4 -sc_threshold 0 -max_muxing_queue_size 1024 -map_metadata -1 -b_strategy 1 -bf 16 -pix_fmt yuv420p -map "[vout480"] -level:v:0 3.1 -g:v:0 60 -c:v:0 libx264 -preset veryfast -r:v:0 30 -b:v:0 1474560 -maxrate 1474560 -bufsize 2949120 -map a:0 -c:a:0 copy -map "[vout360"] -level:v:1 3.1 -g:v:1 60 -c:v:1 libx264 -preset veryfast -r:v:1 30 -b:v:1 1036800 -maxrate 1036800 -bufsize 2073600 -map a:0 -c:a:1 copy -map "[vout240"] -level:v:2 3.1 -g:v:2 60 -c:v:2 libx264 -preset veryfast -r:v:2 30 -b:v:2 522240 -maxrate 522240 -bufsize 1044480 -map a:0 -c:a:2 copy -map "[vout720"] -level:v:3 3.1 -g:v:3 60 -c:v:3 libx264 -preset veryfast -r:v:3 30 -b:v:3 3041280 -maxrate 3041280 -bufsize 6082560 -map a:0 -c:a:3 copy -hls_time 4 -hls_list_size 15 -hls_flags delete_segments+independent_segments -hls_segment_filename /var/www/vhosts/fediverse.tv/www/storage/streaming-playlists/hls/6758ea62-1965-451a-a063-41645d74b1aa/%v-%06d.ts -master_pl_name master.m3u8 -f hls -var_stream_map v:0,a:0 v:1,a:1 v:2,a:2 v:3,a:3 /var/www/vhosts/fediverse.tv/www/storage/streaming-playlists/hls/6758ea62-1965-451a-a063-41645d74b1aa/%v.m3u8```

And it's launched correctly. There's no invalid argument whatsoever.

Still, we can't stream there, but that may have other explanations, regarding on how peertube works internally.

**Comment by Chocobozzz** [comment] 2021-12-07 15:29
I confirm the ffmpeg command is valid. I think the problem is the space in `-var_stream_map` arg (`v:0,a:0 v:1,a:1 v:2,a:2 v:3,a:3`).
The lib we use run [spawn](https://nodejs.org/api/child_process.html#child_processspawncommand-args-options) under the hood, without shell invocation so it should correctly handle this argument.

It's weird that this bug came after v4 upgrade since we did not change ffmpeg command utils. Could it be a nodejs bug?

You could try to check the args sent to `spawn` using `console.log(require('util').inspect(args, { maxArrayLength: 200 }))` line `150` in `node_modules/fluent-ffmpeg/lib/processor.js`

**Comment by rnek0** [comment] 2021-12-07 15:35
> I can't reproduce. Please replace `dist/server/lib/live/shared/muxing-session.js` by [this file](https://github.com/Chocobozzz/PeerTube/files/7668348/muxing-session.js.zip), restart peertube and retry to run a live session. PeerTube should log the ffmpeg command it tries to run.

Thanks @Chocobozzz for me it works with your zip and OBS  : )
```bash
❯ obs --version
OBS Studio - 27.1.3-1 (linux)
#
❯ lsb_release -a
LSB Version: 1.4
Distributor ID: Arch
Description: Arch Linux
Release: rolling
Codename: n/a
#
ffmpeg version 4.3.3-0+deb11u1
#
cat /etc/debian_version
11.1
```

**Comment by drym3r** [comment] 2021-12-07 18:05
> I confirm the ffmpeg command is valid. I think the problem is the space in `-var_stream_map` arg (`v:0,a:0 v:1,a:1 v:2,a:2 v:3,a:3`). The lib we use run [spawn](https://nodejs.org/api/child_process.html#child_processspawncommand-args-options) under the hood, without shell invocation so it should correctly handle this argument.
> 
> It's weird that this bug came after v4 upgrade since we did not change ffmpeg command utils. Could it be a nodejs bug?
> 
> You could try to check the args sent to `spawn` using `console.log(require('util').inspect(args, { maxArrayLength: 200 }))` line `150` in `node_modules/fluent-ffmpeg/lib/processor.js`

I've done and it prints the next in the logs:
```text
{"ffmpegShellCommand":"ffmpeg -n 5 /usr/local/bin/ffmpeg -i rtmp://127.0.0.1:1935/live/6022e06f-7719-43f4-bb08-02a3369d352f -y -filter_complex [v:0]split=2[vtemp240][vtemp360];[vtemp240]scale=w=-2:h=240[vout240];[vtemp360]scale=w=-2:h=360[vout360] -threads 4 -sc_threshold 0 -max_muxing_queue_size 1024 -map_metadata -1 -b_strategy 1 -bf 16 -pix_fmt yuv420p -map [vout240] -level:v:03.1 -g:v:0 60 -c:v:0 libx264 -preset veryfast -r:v:0 30 -b:v:0 260000 -maxrate 260000 -bufsize 520000 -map a:0 -c:a:0 aac -b:a:0 128k -map [vout360] -level:v:1 3.1 -g:v:1 60 -c:v:1 libx264 -preset veryfast -r:v:1 30 -b:v:1 260000 -maxrate 260000 -bufsize 520000 -map a:0 -c:a:1 aac -b:a:1 128k -hls_time 4 -hls_list_size 15 -hls_flags delete_segments+independent_segments -hls_segment_filename /var/www/vhosts/fediverse.tv/www/storage/streaming-playlists/hls/53b228bf-e62e-44e3-98cb-85a10827d999/%v-%06d.ts -master_pl_name master.m3u8 -f hls -var_stream_map v:0,a:0 v:1,a:1 /var/www/vhosts/fediverse.tv/www/storage/streaming-playlists/hls/53b228bf-e62e-44e3-98cb-85a10827d999/%v.m3u8","tags":["live","EYKGG9C6","53b228bf-e62e-44e3-98cb-85a10827d999"],"level":"debug","message":"Running ffmpeg command for live","label":"fediverse.tv:443","timestamp":"2021-12-07T17:59:00.063Z"}

```

And again, when running it like a bash command, it works:
```bash
ffmpeg -n 5 /usr/local/bin/ffmpeg -i rtmp://127.0.0.1:1935/live/6022e06f-7719-43f4-bb08-02a3369d352f -y -filter_complex "[v:0]split=2[vtemp240][vtemp360];[vtemp240]scale=w=-2:h=240[vout240];[vtemp360]scale=w=-2:h=360[vout360]" -threads 4 -sc_threshold 0 -max_muxing_queue_size 1024 -map_metadata -1 -b_strategy 1 -bf 16 -pix_fmt yuv420p -map "[vout240]" -level:v:03.1 -g:v:0 60 -c:v:0 libx264 -preset veryfast -r:v:0 30 -b:v:0 260000 -maxrate 260000 -bufsize 520000 -map a:0 -c:a:0 aac -b:a:0 128k -map "[vout360]" -level:v:1 3.1 -g:v:1 60 -c:v:1 libx264 -preset veryfast -r:v:1 30 -b:v:1 260000 -maxrate 260000 -bufsize 520000 -map a:0 -c:a:1 aac -b:a:1 128k -hls_time 4 -hls_list_size 15 -hls_flags delete_segments+independent_segments -hls_segment_filename /var/www/vhosts/fediverse.tv/www/storage/streaming-playlists/hls/53b228bf-e62e-44e3-98cb-85a10827d999/%v-%06d.ts -master_pl_name master.m3u8 -f hls -var_stream_map v:0,a:0 v:1,a:1 /var/www/vhosts/fediverse.tv/www/storage/streaming-playlists/hls/53b228bf-e62e-44e3-98cb-85a10827d999/%v.m3u8
```

**Comment by drym3r** [comment] 2021-12-09 03:05
I've seen the problem. The command executed is `ffmpeg -n 5 /usr/local/bin/ffmpeg ...` when it should be `nice -n 5 /usr/local/bin/ffmpeg ...`
I'm trying to debug the problem, any idea on where to look?

**Comment by Chocobozzz** [comment] 2021-12-09 08:14
> I've seen the problem. The command executed is ffmpeg -n 5 /usr/local/bin/ffmpeg ... when it should be nice -n 5 /usr/local/bin/ffmpeg ...

This is a bug in the debug print, but the command is `nice -n 5 ...` (https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/blob/master/lib/processor.js#L446 vs https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/blob/master/lib/processor.js#L140)

Could you try with another version of nodejs? (`14.18.1` for example)

> I've done and it prints the next in the logs:

The line you pasted is not related to the debug log you have put in `node_modules/fluent-ffmpeg/lib/processor.js`. Since it's a `console.log` it won't be printed in file logs, but in stdout (so you can see it from `journalctl` for example). Once you have the `args` argument, you could try to run it manually from `node` interactive shell:

```
const args = ... // What is printed in journalctl
const p = require('child_process').spawn('ffmpeg', args)
p.stdout.on('data', (data) => {
  console.log(`stdout: ${data}`)
})
p.stderr.on('data', (data) => {
  console.error(`stderr: ${data}`);
});
p.on('close', (code) => {
  console.log(`child process exited with code ${code}`);
})
```

**Comment by drym3r** [comment] 2021-12-09 13:22
> > I've seen the problem. The command executed is ffmpeg -n 5 /usr/local/bin/ffmpeg ... when it should be nice -n 5 /usr/local/bin/ffmpeg ...
> 
> This is a bug in the debug print, but the command is `nice -n 5 ...` ([fluent-ffmpeg/node-fluent-ffmpeg@`master`/lib/processor.js#L446](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/blob/master/lib/processor.js?rgh-link-date=2021-12-09T08%3A14%3A15Z#L446) vs [fluent-ffmpeg/node-fluent-ffmpeg@`master`/lib/processor.js#L140](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/blob/master/lib/processor.js?rgh-link-date=2021-12-09T08%3A14%3A15Z#L140))
> 
> Could you try with another version of nodejs? (`14.18.1` for example)
I've tried and it still reproduces the same problem.

> > I've done and it prints the next in the logs:
> 
> The line you pasted is not related to the debug log you have put in `node_modules/fluent-ffmpeg/lib/processor.js`. Since it's a `console.log` it won't be printed in file logs, but in stdout (so you can see it from `journalctl` for example). Once you have the `args` argument, you could try to run it manually from `node` interactive shell:
You're wright, confused the console.log with your muxing-server file. I used the inspector, but id it should show in journalctl I search there, thanks.

**Comment by drym3r** [comment] 2021-12-10 12:12
We couldn't fix it, we don't know what happens but we we're able to make it work using the docker image. We've discarded ffmpeg, peertube itself, the library fluent-ffmpeg, ... We've all directly in another server, copied the peertube directory to the main server and still had the error. So we'll close it without knowing what happened.

**Closed** 2022-01-14 14:12 UTC
Labels: Status: To Reproduce, Component: Live
