### ISSUE TITLE
Add interface translation support.

### ISSUE THREAD

**Issue by s8321414** [Chocobozzz/PeerTube#157] opened 2017-12-17 13:12 UTC
Please add localization support so we can translate and spread it to more and more users 😄

**Comment by rigelk** [comment] 2017-12-17 15:36
related to #148 − please contribute on that issue.

**Comment by Chocobozzz** [comment] 2017-12-17 17:54
As @rigelk said, duplicate of https://github.com/Chocobozzz/PeerTube/issues/148

**Closed by Chocobozzz** 2017-12-17 17:54 UTC
