### ISSUE TITLE
Unable to subscribe to Peertube channel from Mastodon when mastodon's decription contains smiley

### ISSUE THREAD

**Issue by LecygneNoir** [Chocobozzz/PeerTube#2177] opened 2019-10-16 09:42 UTC
Hello,

**What happened?**
We have a problem with a user trying to follow account on the Peertube instance from mastodon.  
His profile description contains smiley (country flags) and it crash Peertube with "incorrect description" in logs:

```
  "err": {
    "stack": "SequelizeValidationError: Validation error: \"<p>🇫🇷 <a href=\"https://diaspodon.fr/tags/Bidouilleur\" class=\"mention hashtag\" rel=\"tag\">#<span>Bidouilleur</span></a> <a href=\"https://diaspodon.f
r/tags/routard\" class=\"mention hashtag\" rel=\"tag\">#<span>routard</span></a> <br />🇬🇧 <a href=\"https://diaspodon.fr/tags/hacker\" class=\"mention hashtag\" rel=\"tag\">#<span>hacker</span></a> <a href=\"https
://diaspodon.fr/tags/hitchhiker\" class=\"mention hashtag\" rel=\"tag\">#<span>hitchhiker</span></a></p><p><a href=\"https://diaspodon.fr/tags/Kubernetes\" class=\"mention hashtag\" rel=\"tag\">#<span>Kubernetes</
span></a> <a href=\"https://diaspodon.fr/tags/k8s\" class=\"mention hashtag\" rel=\"tag\">#<span>k8s</span></a> <a href=\"https://diaspodon.fr/tags/docker\" class=\"mention hashtag\" rel=\"tag\">#<span>docker</spa
n></a> <a href=\"https://diaspodon.fr/tags/devops\" class=\"mention hashtag\" rel=\"tag\">#<span>devops</span></a> <a href=\"https://diaspodon.fr/tags/admin\" class=\"mention hashtag\" rel=\"tag\">#<span>admin</sp
an></a> <a href=\"https://diaspodon.fr/tags/Ranch...\" is not a valid description.\n    at Promise.all.then (/app/node_modules/sequelize/lib/instance-validator.js:74:15)\n    at tryCatcher (/app/node_modules/blueb
ird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:517:31)\n    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:57
4:18)\n    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:619:10)\n    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:699:18)\n    at Promise._fulfill (/
app/node_modules/bluebird/js/release/promise.js:643:18)\n    at PromiseArray._resolve (/app/node_modules/bluebird/js/release/promise_array.js:126:19)\n    at PromiseArray._promiseFulfilled (/app/node_modules/blueb
ird/js/release/promise_array.js:144:14)\n    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:579:26)\n    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:61
9:10)\n    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:699:18)\n    at Promise._fulfill (/app/node_modules/bluebird/js/release/promise.js:643:18)\n    at Promise._resolveCallback (
/app/node_modules/bluebird/js/release/promise.js:437:57)\n    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:529:17)\n    at Promise._settlePromise (/app/node_modules/bluebi
rd/js/release/promise.js:574:18)\n    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:619:10)\n    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:699:18)\
n    at Promise._fulfill (/app/node_modules/bluebird/js/release/promise.js:643:18)\n    at PromiseArray._resolve (/app/node_modules/bluebird/js/release/promise_array.js:126:19)\n    at PromiseArray._promiseFulfill
ed (/app/node_modules/bluebird/js/release/promise_array.js:144:14)\n    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:579:26)\n    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:619:10)\n    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:699:18)\n    at Promise._fulfill (/app/node_modules/bluebird/js/release/promise.js:643:18)\n    at Promise._resolveCallback (/app/node_modules/bluebird/js/release/promise.js:437:57)\n    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:529:17)\n    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:574:18)\n    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:619:10)\n    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:699:18)\n    at Promise._fulfill (/app/node_modules/bluebird/js/release/promise.js:643:18)\n    at Promise._resolveCallback (/app/node_modules/bluebird/js/release/promise.js:437:57)\n    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:529:17)\n    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:574:18)\n    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:619:10)\n    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:699:18)\n    at Promise._fulfill (/app/node_modules/bluebird/js/release/promise.js:643:18)\n    at PromiseArray._resolve (/app/node_modules/bluebird/js/release/promise_array.js:126:19)\n    at PromiseArray._promiseFulfilled (/app/node_modules/bluebird/js/release/promise_array.js:144:14)\n    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:579:26)",
    "message": "Validation error: \"<p>🇫🇷 <a href=\"https://diaspodon.fr/tags/Bidouilleur\" class=\"mention hashtag\" rel=\"tag\">#<span>Bidouilleur</span></a> <a href=\"https://diaspodon.fr/tags/routard\" class=\"mention hashtag\" rel=\"tag\">#<span>routard</span></a> <br />🇬🇧 <a href=\"https://diaspodon.fr/tags/hacker\" class=\"mention hashtag\" rel=\"tag\">#<span>hacker</span></a> <a href=\"https://diaspodon.fr/tags/hitchhiker\" class=\"mention hashtag\" rel=\"tag\">#<span>hitchhiker</span></a></p><p><a href=\"https://diaspodon.fr/tags/Kubernetes\" class=\"mention hashtag\" rel=\"tag\">#<span>Kubernetes</span></a> <a href=\"https://diaspodon.fr/tags/k8s\" class=\"mention hashtag\" rel=\"tag\">#<span>k8s</span></a> <a href=\"https://diaspodon.fr/tags/docker\" class=\"mention hashtag\" rel=\"tag\">#<span>docker</span></a> <a href=\"https://diaspodon.fr/tags/devops\" class=\"mention hashtag\" rel=\"tag\">#<span>devops</span></a> <a href=\"https://diaspodon.fr/tags/admin\" class=\"mention hashtag\" rel=\"tag\">#<span>admin</span></a> <a href=\"https://diaspodon.fr/tags/Ranch...\" is not a valid description.",
```

Note that github interprets smiley, but in logs it appears with big **FR** and **GB**:
![Capture d’écran de 2019-10-16 10-41-20](https://user-images.githubusercontent.com/7755000/66907279-61effb00-f009-11e9-84a2-e1a8cc42c0fa.png)

After that, the invitation stay pending on mastodon, and on the peertube instance there is nothing that indicates that someone is trying to subscribe.

**What do you expect to happen instead?**
User with smiley in description should be able to subscribe to Peertube

**Steps to reproduce:**

1. Create an account on mastodon using smiley in description (or add smiley in your description)

2. Try to follow an account on Peertube (which you does not already follow) with your mastodon account

3. Bam :-)

**Additional information**
* PeerTube version or URL: Peetube 1.4.1
* Browser name/version: Firefox
* NodeJS version: node 10

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

Full Peertube logs on instance:

```
[videos.pair2jeux.tube:443] 2019-10-16 07:59:56.454 error: Error in ActivityPub signature checker.Validation error: "<p>🇫🇷 <a href="https://diaspodon.fr/tags/Bidouilleur" class="mention hashtag" rel="tag">#<span>Bidouilleur</span></a> <a href="https://diaspodon.fr/tags/routard" class="mention hashtag" rel="tag">#<span>routard</span></a> <br />🇬🇧 <a href="https://diaspodon.fr/tags/hacker" class="mention hashtag" rel="tag">#<span>hacker</span></a> <a href="https://diaspodon.fr/tags/hitchhiker" class="mention hashtag" rel="tag">#<span>hitchhiker</span></a></p><p><a href="https://diaspodon.fr/tags/Kubernetes" class="mention hashtag" rel="tag">#<span>Kubernetes</span></a> <a href="https://diaspodon.fr/tags/k8s" class="mention hashtag" rel="tag">#<span>k8s</span></a> <a href="https://diaspodon.fr/tags/docker" class="mention hashtag" rel="tag">#<span>docker</span></a> <a href="https://diaspodon.fr/tags/devops" class="mention hashtag" rel="tag">#<span>devops</span></a> <a href="https://diaspodon.fr/tags/admin" class="mention hashtag" rel="tag">#<span>admin</span></a> <a href="https://diaspodon.fr/tags/Ranch..." is not a valid description. {
      "message": "\"<p>🇫🇷 <a href=\"https://diaspodon.fr/tags/Bidouilleur\" class=\"mention hashtag\" rel=\"tag\">#<span>Bidouilleur</span></a> <a href=\"https://diaspodon.fr/tags/routard\" class=\"mention hashtag\" rel=\"tag\">#<span>routard</span></a> <br />🇬🇧 <a href=\"https://diaspodon.fr/tags/hacker\" class=\"mention hashtag\" rel=\"tag\">#<span>hacker</span></a> <a href=\"https://diaspodon.fr/tags/hitchhiker\" class=\"mention hashtag\" rel=\"tag\">#<span>hitchhiker</span></a></p><p><a href=\"https://diaspodon.fr/tags/Kubernetes\" class=\"mention hashtag\" rel=\"tag\">#<span>Kubernetes</span></a> <a href=\"https://diaspodon.fr/tags/k8s\" class=\"mention hashtag\" rel=\"tag\">#<span>k8s</span></a> <a href=\"https://diaspodon.fr/tags/docker\" class=\"mention hashtag\" rel=\"tag\">#<span>docker</span></a> <a href=\"https://diaspodon.fr/tags/devops\" class=\"mention hashtag\" rel=\"tag\">#<span>devops</span></a> <a href=\"https://diaspodon.fr/tags/admin\" class=\"mention hashtag\" rel=\"tag\">#<span>admin</span></a> <a href=\"https://diaspodon.fr/tags/Ranch...\" is not a valid description.",
      "value": "<p>🇫🇷 <a href=\"https://diaspodon.fr/tags/Bidouilleur\" class=\"mention hashtag\" rel=\"tag\">#<span>Bidouilleur</span></a> <a href=\"https://diaspodon.fr/tags/routard\" class=\"mention hashtag\" rel=\"tag\">#<span>routard</span></a> <br />🇬🇧 <a href=\"https://diaspodon.fr/tags/hacker\" class=\"mention hashtag\" rel=\"tag\">#<span>hacker</span></a> <a href=\"https://diaspodon.fr/tags/hitchhiker\" class=\"mention hashtag\" rel=\"tag\">#<span>hitchhiker</span></a></p><p><a href=\"https://diaspodon.fr/tags/Kubernetes\" class=\"mention hashtag\" rel=\"tag\">#<span>Kubernetes</span></a> <a href=\"https://diaspodon.fr/tags/k8s\" class=\"mention hashtag\" rel=\"tag\">#<span>k8s</span></a> <a href=\"https://diaspodon.fr/tags/docker\" class=\"mention hashtag\" rel=\"tag\">#<span>docker</span></a> <a href=\"https://diaspodon.fr/tags/devops\" class=\"mention hashtag\" rel=\"tag\">#<span>devops</span></a> <a href=\"https://diaspodon.fr/tags/admin\" class=\"mention hashtag\" rel=\"tag\">#<span>admin</span></a> <a href=\"https://diaspodon.fr/tags/Ranch...",
        "description": "<p>🇫🇷 <a href=\"https://diaspodon.fr/tags/Bidouilleur\" class=\"mention hashtag\" rel=\"tag\">#<span>Bidouilleur</span></a> <a href=\"https://diaspodon.fr/tags/routard\" class=\"mention hashtag\" rel=\"tag\">#<span>routard</span></a> <br />🇬🇧 <a href=\"https://diaspodon.fr/tags/hacker\" class=\"mention hashtag\" rel=\"tag\">#<span>hacker</span></a> <a href=\"https://diaspodon.fr/tags/hitchhiker\" class=\"mention hashtag\" rel=\"tag\">#<span>hitchhiker</span></a></p><p><a href=\"https://diaspodon.fr/tags/Kubernetes\" class=\"mention hashtag\" rel=\"tag\">#<span>Kubernetes</span></a> <a href=\"https://diaspodon.fr/tags/k8s\" class=\"mention hashtag\" rel=\"tag\">#<span>k8s</span></a> <a href=\"https://diaspodon.fr/tags/docker\" class=\"mention hashtag\" rel=\"tag\">#<span>docker</span></a> <a href=\"https://diaspodon.fr/tags/devops\" class=\"mention hashtag\" rel=\"tag\">#<span>devops</span></a> <a href=\"https://diaspodon.fr/tags/admin\" class=\"mention hashtag\" rel=\"tag\">#<span>admin</span></a> <a href=\"https://diaspodon.fr/tags/Ranch...",
        "stack": "Error: \"<p>🇫🇷 <a href=\"https://diaspodon.fr/tags/Bidouilleur\" class=\"mention hashtag\" rel=\"tag\">#<span>Bidouilleur</span></a> <a href=\"https://diaspodon.fr/tags/routard\" class=\"mention hashtag\" rel=\"tag\">#<span>routard</span></a> <br />🇬🇧 <a href=\"https://diaspodon.fr/tags/hacker\" class=\"mention hashtag\" rel=\"tag\">#<span>hacker</span></a> <a href=\"https://diaspodon.fr/tags/hitchhiker\" class=\"mention hashtag\" rel=\"tag\">#<span>hitchhiker</span></a></p><p><a href=\"https://diaspodon.fr/tags/Kubernetes\" class=\"mention hashtag\" rel=\"tag\">#<span>Kubernetes</span></a> <a href=\"https://diaspodon.fr/tags/k8s\" class=\"mention hashtag\" rel=\"tag\">#<span>k8s</span></a> <a href=\"https://diaspodon.fr/tags/docker\" class=\"mention hashtag\" rel=\"tag\">#<span>docker</span></a> <a href=\"https://diaspodon.fr/tags/devops\" class=\"mention hashtag\" rel=\"tag\">#<span>devops</span></a> <a href=\"https://diaspodon.fr/tags/admin\" class=\"mention hashtag\" rel=\"tag\">#<span>admin</span></a> <a href=\"https://diaspodon.fr/tags/Ranch...\" is not a valid description.\n    at Object.throwIfNotValid (/app/dist/server/models/utils.js:61:15)\n    at self.sequelize_typescript_1.Is.value (/app/dist/server/models/account/account.js:213:70)\n    at Promise.try (/app/node_modules/sequelize/lib/instance-validator.js:269:28)\n    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)\n    at Function.Promise.attempt.Promise.try (/app/node_modules/bluebird/js/release/method.js:39:29)\n    at InstanceValidator._invokeCustomValidator (/app/node_modules/sequelize/lib/instance-validator.js:269:11)\n    at _.forIn (/app/node_modules/sequelize/lib/instance-validator.js:208:30)\n    at /app/node_modules/lodash/lodash.js:4905:15\n    at Function.forIn (/app/node_modules/lodash/lodash.js:12950:11)\n    at InstanceValidator._singleAttrValidate (/app/node_modules/sequelize/lib/instance-validator.js:193:7)\n    at _.forIn (/app/node_modules/sequelize/lib/instance-validator.js:142:30)\n    at /app/node_modules/lodash/lodash.js:4905:15\n    at Function.forIn (/app/node_modules/lodash/lodash.js:12950:11)\n    at InstanceValidator._perAttributeValidators (/app/node_modules/sequelize/lib/instance-validator.js:125:7)\n    at InstanceValidator._validate (/app/node_modules/sequelize/lib/instance-validator.js:70:12)\n    at runHooks.then (/app/node_modules/sequelize/lib/instance-validator.js:107:14)\n    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:517:31)\n    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:574:18)\n    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:619:10)\n    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:699:18)\n    at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:138:12)\n    at _drainQueue (/app/node_modules/bluebird/js/release/async.js:131:9)\n    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:147:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)",
        "message": "\"<p>🇫🇷 <a href=\"https://diaspodon.fr/tags/Bidouilleur\" class=\"mention hashtag\" rel=\"tag\">#<span>Bidouilleur</span></a> <a href=\"https://diaspodon.fr/tags/routard\" class=\"mention hashtag\" rel=\"tag\">#<span>routard</span></a> <br />🇬🇧 <a href=\"https://diaspodon.fr/tags/hacker\" class=\"mention hashtag\" rel=\"tag\">#<span>hacker</span></a> <a href=\"https://diaspodon.fr/tags/hitchhiker\" class=\"mention hashtag\" rel=\"tag\">#<span>hitchhiker</span></a></p><p><a href=\"https://diaspodon.fr/tags/Kubernetes\" class=\"mention hashtag\" rel=\"tag\">#<span>Kubernetes</span></a> <a href=\"https://diaspodon.fr/tags/k8s\" class=\"mention hashtag\" rel=\"tag\">#<span>k8s</span></a> <a href=\"https://diaspodon.fr/tags/docker\" class=\"mention hashtag\" rel=\"tag\">#<span>docker</span></a> <a href=\"https://diaspodon.fr/tags/devops\" class=\"mention hashtag\" rel=\"tag\">#<span>devops</span></a> <a href=\"https://diaspodon.fr/tags/admin\" class=\"mention hashtag\" rel=\"tag\">#<span>admin</span></a> <a href=\"https://diaspodon.fr/tags/Ranch...\" is not a valid description."
  "stack": "SequelizeValidationError: Validation error: \"<p>🇫🇷 <a href=\"https://diaspodon.fr/tags/Bidouilleur\" class=\"mention hashtag\" rel=\"tag\">#<span>Bidouilleur</span></a> <a href=\"https://diaspodon.fr/tags/routard\" class=\"mention hashtag\" rel=\"tag\">#<span>routard</span></a> <br />🇬🇧 <a href=\"https://diaspodon.fr/tags/hacker\" class=\"mention hashtag\" rel=\"tag\">#<span>hacker</span></a> <a href=\"https://diaspodon.fr/tags/hitchhiker\" class=\"mention hashtag\" rel=\"tag\">#<span>hitchhiker</span></a></p><p><a href=\"https://diaspodon.fr/tags/Kubernetes\" class=\"mention hashtag\" rel=\"tag\">#<span>Kubernetes</span></a> <a href=\"https://diaspodon.fr/tags/k8s\" class=\"mention hashtag\" rel=\"tag\">#<span>k8s</span></a> <a href=\"https://diaspodon.fr/tags/docker\" class=\"mention hashtag\" rel=\"tag\">#<span>docker</span></a> <a href=\"https://diaspodon.fr/tags/devops\" class=\"mention hashtag\" rel=\"tag\">#<span>devops</span></a> <a href=\"https://diaspodon.fr/tags/admin\" class=\"mention hashtag\" rel=\"tag\">#<span>admin</span></a> <a href=\"https://diaspodon.fr/tags/Ranch...\" is not a valid description.\n    at Promise.all.then (/app/node_modules/sequelize/lib/instance-validator.js:74:15)\n    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:517:31)\n    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:574:18)\n    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:619:10)\n    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:699:18)\n    at Promise._fulfill (/app/node_modules/bluebird/js/release/promise.js:643:18)\n    at PromiseArray._resolve (/app/node_modules/bluebird/js/release/promise_array.js:126:19)\n    at PromiseArray._promiseFulfilled (/app/node_modules/bluebird/js/release/promise_array.js:144:14)\n    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:579:26)\n    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:619:10)\n    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:699:18)\n    at Promise._fulfill (/app/node_modules/bluebird/js/release/promise.js:643:18)\n    at Promise._resolveCallback (/app/node_modules/bluebird/js/release/promise.js:437:57)\n    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:529:17)\n    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:574:18)\n    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:619:10)\n    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:699:18)\n    at Promise._fulfill (/app/node_modules/bluebird/js/release/promise.js:643:18)\n    at PromiseArray._resolve (/app/node_modules/bluebird/js/release/promise_array.js:126:19)\n    at PromiseArray._promiseFulfilled (/app/node_modules/bluebird/js/release/promise_array.js:144:14)\n    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:579:26)\n    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:619:10)\n    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:699:18)\n    at Promise._fulfill (/app/node_modules/bluebird/js/release/promise.js:643:18)\n    at Promise._resolveCallback (/app/node_modules/bluebird/js/release/promise.js:437:57)\n    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:529:17)\n    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:574:18)\n    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:619:10)\n    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:699:18)\n    at Promise._fulfill (/app/node_modules/bluebird/js/release/promise.js:643:18)\n    at Promise._resolveCallback (/app/node_modules/bluebird/js/release/promise.js:437:57)\n    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:529:17)\n    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:574:18)\n    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:619:10)\n    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:699:18)\n    at Promise._fulfill (/app/node_modules/bluebird/js/release/promise.js:643:18)\n    at PromiseArray._resolve (/app/node_modules/bluebird/js/release/promise_array.js:126:19)\n    at PromiseArray._promiseFulfilled (/app/node_modules/bluebird/js/release/promise_array.js:144:14)\n    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:579:26)"
```

Thanks for the help!

**Comment by dadall** [comment] 2019-10-16 09:43
Thanks @LecygneNoir !

**Comment by Umiooo** [comment] 2019-10-17 19:56
Could not reproduce on Mastodon v2.9.3 with @rigelk
We tried to follow from https://mastodont.cat/@umio on mastodon to chocobozzz@peertube.cpy.re on peertube.

**Comment by LecygneNoir** [comment] 2019-10-18 06:05
Mmmh, I thought it was the smiley because they appears oddly in the logs, but perhaps it was something else :thinking: 

Perhaps hashtag, the description size or combination of three. 
@dadall have you still your old description somewhere (or are able to rewrite it) to reproduce? If I do not mistake, you are also using mastodon 3.1?

Thanks!

**Comment by Chocobozzz** [comment] 2019-10-21 07:54
Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/687c6180bc5f48b9159bbb229ec5404cc205919e

I could not test the fix because it seems @dadall that you changed your mastodon description :)

**Closed by Chocobozzz** 2019-10-21 07:54 UTC
Labels: Status: In Progress :soon:, Type: Bug :bug:
