### ISSUE TITLE
"Your video file was too large (max. size: 8G)" error when uploading 400mb video

### ISSUE THREAD

**Issue by RalphORama** [Chocobozzz/PeerTube#4119] opened 2021-05-23 17:14 UTC
**Describe the current behavior**

When attempting to upload a video to my peertube instance, small videos (~20mb) upload fine, but when I try to upload a larger video (~400mb), I get the error "Your video file was too large (max. size: 8G)"

**Steps to reproduce:**

1. Install via Docker
2. Download [this video](https://www.youtube.com/watch?v=4KGsgpFiswQ) with `youtube-dl`
3. Attempt to upload video to instance
4. Error happens

**Describe the expected behavior**

Peertube shouldn't think 400mb videos are ~8gb

**Additional information**

* PeerTube instance:
  * URL: https://videos.valiumsadfemme.mom
  * version: latest provided by `docker-compose pull`
  * NodeJS version: provided by Docker
  * Ffmpeg version: provided by Docker

* Browser name, version and platforms on which you could reproduce the bug: Firefox Developer 89.0b15 (64-bit) Windows 10 Pro 21H1
* Link to browser console log if relevant: n/a
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): https://paste.ubuntu.com/p/h8bYPTMgVv/

**Comment by kgnfth** [comment] 2021-05-24 13:17
Same here

**Comment by kontrollanten** [comment] 2021-05-25 05:21
It may be caused by network disruptions which can explain why multiple retries can solve it, but then the error message is wrong. I think this may be solved by #324 which will be included in the next release.

**Comment by Chocobozzz** [comment] 2021-05-25 09:24
Please paste your nginx configuration

**Comment by kgnfth** [comment] 2021-05-25 14:24
@Chocobozzz i am running it in docker with proxy forwarding

```
<%
if (s.forceSsl) {
%>
    server {

        listen       80;

        server_name  <%-s.publicDomain%>;

        # Used by Lets Encrypt
        location /.well-known/acme-challenge/ {
            root <%-s.staticWebRoot%>;
        }

        # Used by CapRover for health check
        location /.well-known/captain-identifier {
            root <%-s.staticWebRoot%>;
        }

        location / {
            return 302 https://$http_host$request_uri;
        }
    }
<%
}
%>


server {

    <%
    if (!s.forceSsl) {
    %>
        listen       80;
    <%
    }
    if (s.hasSsl) {
    %>
        listen              443 ssl http2;
        ssl_certificate     <%-s.crtPath%>;
        ssl_certificate_key <%-s.keyPath%>;
    <%
    }
    %>

        client_max_body_size 500m;

        server_name  <%-s.publicDomain%>;

        # 127.0.0.11 is DNS set up by Docker, see:
        # https://docs.docker.com/engine/userguide/networking/configure-dns/
        # https://github.com/moby/moby/issues/20026
        resolver 127.0.0.11 valid=10s;
        # IMPORTANT!! If you are here from an old thread to set a custom port, you do not need to modify this port manually here!!
        # Simply change the Container HTTP Port from the dashboard HTTP panel
        set $upstream http://<%-s.localDomain%>:<%-s.containerHttpPort%>;

        location / {

    <%
    if (s.httpBasicAuthPath) {
    %>
            auth_basic           "Restricted Access";
            auth_basic_user_file <%-s.httpBasicAuthPath%>; 
    <%
    }
    %>

            proxy_pass $upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

    <%
    if (s.websocketSupport) {
    %>
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_http_version 1.1;
    <%
    }
    %>
        }

        # Used by Lets Encrypt
        location /.well-known/acme-challenge/ {
            root <%-s.staticWebRoot%>;
        }
        
        # Used by CapRover for health check
        location /.well-known/captain-identifier {
            root <%-s.staticWebRoot%>;
        }

        error_page 502 /captain_502_custom_error_page.html;
        location = /captain_502_custom_error_page.html {
                root <%-s.customErrorPagesDirectory%>;
                internal;
        }
}
```

**Comment by Chocobozzz** [comment] 2021-05-25 14:28
I'm sorry but we only support our docker/nginx templates.

` client_max_body_size 500m;` directive seems to be the issue

**Closed by Chocobozzz** 2021-05-25 14:28 UTC
Labels: Component: Docker :whale:, Status: Waiting for answer

**Comment by popindavibe** [comment] 2021-06-03 17:31
Getting same issue here, after upgrading to 3.2.1. Turned out my nginx configuration needed alignment with latest `/var/www/peertube/versions/peertube-v3.2.1/support/nginx/peertube `
