### ISSUE TITLE
Sync video between two instances

### ISSUE THREAD

**Issue by tomamplius** [Chocobozzz/PeerTube#1440] opened 2018-12-01 12:04 UTC
One video is not sync on other instance. How i can analyse why?

You find 2 links with my instance and another instance. URL is the same but the video Episode 10 on my instance is not sync on all the 21 instances who are subscribe on my instance.

my instance : https://videos.side-ways.net/video-channels/episodes@videos.side-ways.net/videos
Other instance : https://peertube.jorropo.ovh/video-channels/episodes@videos.side-ways.net/videos

**Comment by zestyr** [comment] 2018-12-01 23:33
Maybe duplicate of #815. I've encountered the same issue a few times across multiple instances, but troubleshooting it is difficult due to the complete lack of log messages related to the issue.

**Comment by tomamplius** [comment] 2018-12-02 02:14
I think that if we create a new instance and follow an instance with this issue, it can be possible to check if the video is in the stream? But i don't knwon where i can find this stream?
There is 2 case, the video is not send or the follower can't add the video

**Comment by Chocobozzz** [comment] 2018-12-13 15:48
@tomamplius Please display the result of the following psql command:

`select "videoShare".* from "videoShare" inner join video ON video.id = "videoShare"."videoId" WHERE "video"."uuid" = '2e5557ff-4e3d-4721-bd35-74f5aab65de4'`

What did you do with this video? (ie did you update it after upload? changed the channel? change the privacy?)

**Comment by tomamplius** [comment] 2018-12-13 15:59
thanks, you can find the query result below

```
 id |                                            url                                             | actorId | videoId |         createdAt         |         updatedAt         
----+--------------------------------------------------------------------------------------------+---------+---------+---------------------------+---------------------------
  1 | https://videos.side-ways.net/videos/watch/2e5557ff-4e3d-4721-bd35-74f5aab65de4/announces/8 |       8 |       1 | 2018-11-01 16:37:08.68+01 | 2018-11-01 16:37:08.68+01
```
I discovered the problem a month later. I have probably made some update but I do not really remember

**Comment by Chocobozzz** [comment] 2018-12-19 12:42
Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/56b13bd193b076d32925f0ad14b755b250b803a8

Thanks for your help @tomamplius and rjkmelb on IRC

**Closed by Chocobozzz** 2018-12-19 12:42 UTC
Labels: Component: Federation :ferris_wheel:, Type: Bug :bug:

**Comment by tomamplius** [comment] 2018-12-19 12:57
Thanks a lot for your help and about your good work on PeerTube.

After update peerTube with the fix le video will be push on the fediverse?
