### ISSUE TITLE
Seperate uploaded videos from the transcoding videos

### ISSUE THREAD

**Issue by andreaspeters** [Chocobozzz/PeerTube#989] opened 2018-08-30 21:39 UTC
Hi,

is it possible that if a user is uploading a video, it will stored first into a temp directory until the video is transcoded? Let me tell u why I'm asking. Well, all the videos on my peertube instance are on a huge (200TB), secure but very very slowly storage. Its so slowly that every time if peertube start to transcode the video, and after that rename it, it happen sth and the video is deleted. I imagine its because of my very slowly storage. So... with a separated temporary upload directory, I can change it to a small but fast storage and after the transcoding and rename peertube will move the video into his persistent destination.
 
Actually, I had a look into your code to create a PR, but I got headache from it. :-)

Kind Regards,
Andreas

**Comment by Chocobozzz** [comment] 2018-08-31 07:12
Hi @andreaspeters,

Thanks for this issue but it's a duplicate of https://github.com/Chocobozzz/PeerTube/issues/765 :)

**Closed by Chocobozzz** 2018-08-31 07:12 UTC
