### ISSUE TITLE
UI error when successfully updating a live stream metadata

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#3562] opened 2021-01-08 21:42 UTC
![image](https://user-images.githubusercontent.com/923812/104066911-09c98980-51b7-11eb-93c8-0bbb1a9b2819.png)

**Describe the current behavior**

When changing metadata (tags, description, image) for an ongoing live stream, the change seems to succeed but the UI reports an error.

**Steps to reproduce:**

1. Start a stream
2. Use 'update' to make changes
3. Apply

**Describe the expected behavior**

I would expect that most parameters could be changed after the stream is live, and no error would result. If there are reasons some parameters must not be changed after the stream starts, I would expect that reason to be clear and for the error to be localized to those particular settings.

**Additional information**

* PeerTube instance:
  * URL: diode.zone
  * version: v3.0.0
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment] 2021-01-11 09:17
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/3532

**Closed by Chocobozzz** 2021-01-11 09:17 UTC
Labels: Component: Live
