### ISSUE TITLE
Not showing the right text when hoover over the video age

### ISSUE THREAD

**Issue by alejandrocobo** [Chocobozzz/PeerTube#6203] opened 2024-02-03 21:43 UTC
### Describe the current behavior

When you hover on the video age (ex. "4 hours ago"), it should appear the date of the video. Instead, it shows "Toggle this date format to 'date'". It is reproducicle when the interface is in English and Spanish (I didn't try other languages).

### Steps to reproduce

1. Go to any instance with 6.0.3.
2. Put the mouse pointer over the video age to check the date.

### Describe the expected behavior

It should show just the date.

### Additional information

* PeerTube instance:
  * Version: 6.0.3

**Comment by Chocobozzz** [comment] 2024-02-15 13:09
Hello,

The label explains what happens when you click on the date so I'm not sure what the problem is?

**Comment by alejandrocobo** [comment] 2024-02-16 18:55
Ohh, I got it. So the problem then is that the tag appears in English despite the interface is in Spanish. In Italian, French and French shows in English too btw.

**Comment by Chocobozzz** [comment] 2024-02-19 10:01
> Ohh, I got it. So the problem then is that the tag appears in English despite the interface is in Spanish. In Italian, French and Portuguese shows in English too btw.

Then it will be fixed progressively when contributors will translate the sentence on weblate :)

**Closed by Chocobozzz** 2024-02-19 10:01 UTC
Labels: Status: Waiting for answer

**Comment by lucacalcaterra** [comment] 2024-03-05 16:08
@Chocobozzz i've updated italian sentence in peertube weblate portal; when sould be released new version with fix ? There is a wa to manualy fix it until next ? Thanks !

**Comment by Chocobozzz** [comment] 2024-03-08 09:07
You can check latest pulled translations on https://peertube2.cpy.re

**Comment by lucacalcaterra** [comment] 2024-03-08 09:13
> You can check latest pulled translations on https://peertube2.cpy.re

@Chocobozzz I cannot understand your link... need to bring the translation on my own instance running with docker. Pulling latest image doesn't update translations i made in the italian language

**Comment by Chocobozzz** [comment] 2024-03-08 10:30
> @Chocobozzz I cannot understand your link... need to bring the translation on my own instance running with docker. Pulling latest image doesn't update translations i made in the italian language

Sorry I thought you wanted to check your translations directly in the UI.

I merged the latest translations in https://github.com/Chocobozzz/PeerTube/commit/3a53d442466d371ee41f35e2cb4c8bfa0bf0646c

The docker image `develop-bookworm` containing these changes should be available in ~24 hours

**Comment by lucacalcaterra** [comment] 2024-03-08 10:52
> > @Chocobozzz I cannot understand your link... need to bring the translation on my own instance running with docker. Pulling latest image doesn't update translations i made in the italian language
> 
> Sorry I thought you wanted to check your translations directly in the UI.
> 
> I merged the latest translations in [3a53d44](https://github.com/Chocobozzz/PeerTube/commit/3a53d442466d371ee41f35e2cb4c8bfa0bf0646c)
> 
> The docker image `develop-bookworm` containing these changes should be available in ~24 hours

Thanks !! so i should use the dev image ? Can i trust the dev branch on a production server in your opinion ? ThankS
