### ISSUE TITLE
Landing page bug

### ISSUE THREAD

**Issue by tiotrom** [Chocobozzz/PeerTube#3827] opened 2021-03-04 13:41 UTC
**Describe the current behavior**
If admin selects the landing page to be (say) Local (the local videos), then it only changes for logged in users.

**Steps to reproduce:**

1. Change landing page to Local in the Admin
2. Visit the instance in incognito mode
3. The landing page will be Trending

**Describe the expected behavior**
The landing page for users that are logged in or not, should be the one selected in the Admin.

**Additional information**

* PeerTube instance: videos.trom.tf
  * URL: videos.trom.tf
  * version: 3.0.1

* Browser name, version and platforms on which you could reproduce the bug: Firefox and Chromium

**Comment by Chocobozzz** [comment] 2021-03-04 14:02
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/504

**Closed by Chocobozzz** 2021-03-04 14:02 UTC
