### ISSUE TITLE
MP3 files failing when importing or uploading

### ISSUE THREAD

**Issue by dhk2** [Chocobozzz/PeerTube#4686] opened 2022-01-03 05:08 UTC
**Describe the current behavior**
Mp3 file uploads failing apparently due to fps being 0
**Steps to reproduce:**

1. Enable Audio file upload
2. Attempt to publish with an uploaded mp3 file
3. fails with error

**Describe the expected behavior**
import and transcode mp3 file to hls and play
**Additional information**
PeerTube 4.0 Using youtube-dl
ffmpeg version 4.3.2-0york0~18.04 Copyright (c) 2000-2021 the FFmpeg developers

Job: 60964 Type: video-transcoding Processed on Jan 2, 2022, 8:16:28 PM Finished on Jan 2, 2022, 8:16:30 PM
--
{   "type": "optimize-to-webtorrent",   "videoUUID": "b7a0e47c-3535-459f-80fe-7c23ed89aa08",   "isNewVideo": true }
Error: Cannot compute FPS because 0 is lower than our minimum value 1     at computeFPS (/var/www/peertube/versions/peertube-v4.0.0/dist/server/helpers/ffprobe-utils.js:286:15)     at Object.<anonymous> (/var/www/peertube/versions/peertube-v4.0.0/dist/server/helpers/ffmpeg-utils.js:222:46)     at Generator.next (<anonymous>)     at fulfilled (/var/www/peertube/versions/peertube-v4.0.0/node_modules/tslib/tslib.js:114:62)     at runMicrotasks (<anonymous>)     at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by dhk2** [comment] 2022-01-03 05:24
On further testing it appears the failures aren't from normal uploading, but from importing using the PeerTube Rest API.

**Comment by dhk2** [comment] 2022-01-03 06:03
To reproduce
1. click publish
2. Select Import with URL tab
3. Put in path to mp3 such as https://file-examples-com.github.io/uploads/2017/11/file_example_MP3_2MG.mp3
4. After importing, the transcoding job fails due to FPS being 0

**Comment by Chocobozzz** [comment] 2022-01-03 08:12
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/4657

**Closed by Chocobozzz** 2022-01-03 08:12 UTC

**Comment by dhk2** [comment] 2022-01-03 10:17
That's what I get for searching for mp3, sorry
