### ISSUE TITLE
It would be more effective and Monserrat only video in your language.

### ISSUE THREAD

**Issue by discapacidad5** [Chocobozzz/PeerTube#2789] opened 2020-05-26 19:55 UTC
Hello again, I appreciate this great program
But there is one detail that I would like you to be able to solve And it is that it shows videos in other languages
I for example only speak Spanish
 i'm talking to you using google translate
I would like that when I open my application it will only show me videos in Spanish but it shows me a lot of trending videos in any language
I believe that if it could be filtered by language and that for example in my instance only videos will be shown in the language that I configure
 It would help a lot to make people understand each other better with the system and
that people expect to see videos trending that they understand are in their language

Yes I know that in search of a filter that allows Search video only in the language that one chooses
but it is that if the application is configured to be in a language it should show the most viewed trends and the videos only in that language
And if someone wants to Search for video in another language then let them go to the search with the custom search options

**Comment by Chocobozzz** [comment] 2020-05-27 06:55
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/2642

**Closed by Chocobozzz** 2020-05-27 06:55 UTC

**Comment by discapacidad5** [comment] 2020-05-29 18:21
> Thanks for reporting this issue, but this is a duplicate of #2642


Excuse me but I don't see it as a duplicate
  since that one talks about anonymous users

  I speak generally not of anonymous users
But of all the users if your page is in a language the videos should be viewed preferably in that language

if a channel is configured to display by default in a language
it should show by default the videos that you have that language
when loading a video one choose what language that video is in
  that would serve to make the filter to know what video to show in the language of the channel

perhaps my suggestion is not being very clear Remember that I do not speak English and used the Google translator that often makes what you mean a little difficult
