### ISSUE TITLE
transcoding-profile-debug: unable to select transcoding profile in settings via browser

### ISSUE THREAD

**Issue by Izorkin** [Chocobozzz/PeerTube#4008] opened 2021-04-23 14:22 UTC
**Describe the current behavior**
Unable to select transcoding profile in settings via browser.
A custom profile is displayed in the "Transcoding profile" list, but it cannot be selected.

**Steps to reproduce:**

1. Create custom transcoding profile.
2. Open setting https://custom_peertube/admin/config/edit-custom#transcoding

**Additional information**

* PeerTube instance:
  * version: 3.0.1
  * NodeJS version: 14.16.1
  * Ffmpeg version: 4.3.2
  * transcoding-profile-debug version: 0.0.2
* Browser:
  * Vivaldi version: 3.8.2259.16

**Comment by SimplyCorbett** [comment] 2021-04-23 14:24
Hello!

I had the same issue. You can get around this by stopping peertube and editing the local-production.json in the config folder.

Under "transcoding" change the profile from default to your custom profile. Then restart peertube.

Hopefully this workaround helps you for the time being!

**Comment by Chocobozzz** [comment] 2021-04-26 07:13
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/3912

**Closed by Chocobozzz** 2021-04-26 07:13 UTC
