### ISSUE TITLE
No more than 5 videos on own library page are shown

### ISSUE THREAD

**Issue by alexdetsch** [Chocobozzz/PeerTube#2035] opened 2019-08-15 22:12 UTC
**What happened?**
When your screen is big enough to fit 5 videos without scrolling bars on the <instance>/my-account/videos page, then there are only 5 videos shown and no possibility to get the others. When you resize the window to a smaller size - so you have to scroll to see all 5 videos, the other videos are loaded and shown.

**What do you expect to happen instead?**
load as much videos as fit on the page and load the others when needed/scrolled.

**Steps to reproduce:**

1. Visit the <instance>/my-account/videos page of an account with more than 5 videos in nearly fullscreen mode at a high resolution monitor.

2. Only 5 videos are shown and there is plenty space left below the last.

3. Try to get the other ones with scrolling or reloading (it won't work)

**Additional information**
* PeerTube version or URL: 1.3.1 (build directly from git on 24.08.2019)
* Browser name/version: Firefox 68
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment] 2019-08-16 06:18
Hi,

Thanks for the issue but it's a duplicate of https://github.com/Chocobozzz/PeerTube/issues/1912 that should be fixed in 1.4-rc.1

**Closed by Chocobozzz** 2019-08-16 06:18 UTC
