### ISSUE TITLE
Embeds and video playback don't work with Brave browser

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#1374] opened 2018-11-04 21:29 UTC
Visitors to my instance have reported two variants of this bug:

- In the default configuration, there's a Webtorrent plugin which will intercept *any* fetch() or XHR of a .torrent file and redirect the page to a torrent client. This means that as soon as a video playback page loads, it redirects to a plain torrent client page. Even if the user wants to use this for video playback, it's missing the rest of the PeerTube UI, such as the comments and navigation.

- In embedded videos, the player displays an error message on an otherwise black screen, claiming the remote PeerTube instance can't be reached. If you click the embed, it redirects to the torrent client.

So, this clearly seems like unwelcome behavior on the part of Brave, but after having several visitors report this to me as broken behavior, I'm wondering if there's something we can do on our side to mitigate it. 

One straw-man approach may be to simply disable P2P selectively when the client is running on Brave, or even by detecting the Webtorrent plugin. Maybe we can do better though. Perhaps we could offer a varient of the .torrent file under a different mime type.

**Comment by Nutomic** [comment] 2018-11-04 21:50
The Brave issue for this is reported fixed: https://github.com/brave/browser-laptop/issues/10672

Also see #218.

**Comment by scanlime** [comment] 2018-11-04 22:00
I'm running Brave 0.25.2 (8ea2a9c) which claims to be the latest, and the bug is still reproducible. But if there's a fix upstream that just needs to come out in a release, that's good. If there's no upstream fix on the way, I'd argue that this might be worth a mitigation in PeerTube, which is why I filed the bug here.

**Comment by Nutomic** [comment] 2018-11-04 22:39
First of all you should comment on the Brave issue, or contact them because the issue is on their side. It should be really easy to fix for them.

**Comment by kontrollanten** [comment] 2019-12-06 00:20
This seems to be fixed by Brave now? At least I can't reproduce this as described in #1564 anymore.

**Closed** 2019-12-06 07:40 UTC
Labels: Status: Blocked
