### ISSUE TITLE
Docker environment-variables template out of sync: no way to mitigate infohash-logs in deploy

### ISSUE THREAD

**Issue by Arnd-At-Blender** [Chocobozzz/PeerTube#6742] opened 2024-11-28 10:16 UTC
### Describe the current behavior

Current docker-compose.yaml pulls in the 'stable' peertube image that seems to not have support for overriding (at least) the 'log->log_tracker_unknown_infohash' setting.
There might be other settings that are similarly not possible to set via the env-vars yet

### Steps to reproduce

1.
2.
3.

### Describe the expected behavior

New config-settings in peertube should, ultimately, have an environment-var equivalent to set them for use from docker .env

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment] 2024-11-29 08:31
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/6591

**Closed by Chocobozzz** 2024-11-29 08:31 UTC
