### ISSUE TITLE
[Feature Request] Import captions

### ISSUE THREAD

**Issue by LoveIsGrief** [Chocobozzz/PeerTube#2003] opened 2019-08-03 21:25 UTC
**What happened?**

Imported a video from youtube that had captions, but the captions weren't imported with the other information.

**What do you expect to happen instead?**

Captions to be proposed during the creation of the video or to be there once the video has been imported

**Steps to reproduce:**

1. Import a video with captions e.g [this](https://www.youtube.com/watch?v=23H8IdaS3tk)

2. Play the video

3. Observe that there are no captions

**Additional information**
* PeerTube version or URL: PeerTube v1.3.0...1f20622f
* Browser name/version: Firefox 68

**Comment by Chocobozzz** [comment] 2019-08-05 07:20
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/1016

**Closed by Chocobozzz** 2019-08-05 07:20 UTC

**Comment by LoveIsGrief** [comment] 2019-08-05 08:43
Ah, didn't think to search for "subtitles" instead of captions. Thank you.
