### ISSUE TITLE
Internal error when trying to accept registration request with duplicate email

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#5717] opened 2023-03-27 16:15 UTC
### Describe the current behavior

I had a registration request from a user who already had an account that they forgot about. When I tried to approve this request, the server experienced an internal SQL validation error, and the UI gives me an unhelpful generic validation error.

The server logs give the real reason for the failure, `error: duplicate key value violates unique constraint "user_email"`

Searching the user list confirms that the email is in fact duplicate.

### Steps to reproduce

1. Register an account
2. Request another account, using the same email address
3. Using the admin interface, try to approve the request

### Describe the expected behavior

Either the registration request should not be allowed in the first place, or the admin interface should not allow approving the request.

### Additional information

* PeerTube instance:
  * URL: diode.zone
  * Version: 5.1.0
  * NodeJS version: v16.19.1
  * Ffmpeg version: 4.4.2-0ubuntu0.22.04.1

* Browser name, version and platforms on which you could reproduce the bug: firefox, chrome
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment] 2023-05-10 09:52
Hi,

I can't reproduce with your steps. In my tests peertube correctly detects another user or registration request exist for the same username.

Is it possible that the user has been manually created by an admin with this email, after the registration request of this user?

**Comment by Chocobozzz** [comment] 2023-05-30 08:59
Ping @scanlime

**Comment by Chocobozzz** [comment] 2023-07-12 07:25
Closing as we can't reproduce. Of course, don't hesitate to comment this issue if you encounter the same bug

**Closed by Chocobozzz** 2023-07-12 07:25 UTC
Labels: Type: Bug :bug:, Status: Waiting for answer, Component: Registration
