### ISSUE TITLE
The media could not be loaded, either because the server or network failed or because the format is not supported.

### ISSUE THREAD

**Issue by ReK2Fernandez** [Chocobozzz/PeerTube#268] opened 2018-02-02 06:35 UTC
Im getting that for the lasted video I uploaded, is the same type and format than all the other 20 I uploaded last week.. only difference is that I updated the server...
Any reason why will this happen? file to big? torrent/browser issue?
![peertubeerror](https://user-images.githubusercontent.com/5316229/35719926-682dde36-07a0-11e8-97ac-5b2755459ad7.png)

Thanks.

**Comment by ReK2Fernandez** [comment] 2018-02-02 06:56
This may help.
```
eb 02 06:47:05 video peertube[6224]: Error: Can't set headers after they are sent.
Feb 02 06:47:05 video peertube[6224]:     at validateHeader (_http_outgoing.js:494:11)
Feb 02 06:47:05 video peertube[6224]:     at ServerResponse.setHeader (_http_outgoing.js:501:3)
Feb 02 06:47:05 video peertube[6224]:     at ServerResponse.header (/var/www/PeerTube/versions/peertube-v0.0.20-alpha/node_modules/express/lib/response.js:767:10)
Feb 02 06:47:05 video peertube[6224]:     at ServerResponse.contentType (/var/www/PeerTube/versions/peertube-v0.0.20-alpha/node_modules/express/lib/response.js:595:15)
Feb 02 06:47:05 video peertube[6224]:     at ServerResponse.sendStatus (/var/www/PeerTube/versions/peertube-v0.0.20-alpha/node_modules/express/lib/response.js:357:8)
Feb 02 06:47:05 video peertube[6224]:     at /var/www/PeerTube/versions/peertube-v0.0.20-alpha/dist/server.js:127:9
Feb 02 06:47:05 video peertube[6224]:     at Layer.handle_error (/var/www/PeerTube/versions/peertube-v0.0.20-alpha/node_modules/express/lib/router/layer.js:71:5)
Feb 02 06:47:05 video peertube[6224]:     at trim_prefix (/var/www/PeerTube/versions/peertube-v0.0.20-alpha/node_modules/express/lib/router/index.js:315:13)
Feb 02 06:47:05 video peertube[6224]:     at /var/www/PeerTube/versions/peertube-v0.0.20-alpha/node_modules/express/lib/router/index.js:284:7
Feb 02 06:47:05 video peertube[6224]:     at Function.process_params (/var/www/PeerTube/versions/peertube-v0.0.20-alpha/node_modules/express/lib/router/index.js:335:12)
Feb 02 06:47:05 video peertube[6224]:     at next (/var/www/PeerTube/versions/peertube-v0.0.20-alpha/node_modules/express/lib/router/index.js:275:10)
Feb 02 06:47:05 video peertube[6224]:     at Layer.handle_error (/var/www/PeerTube/versions/peertube-v0.0.20-alpha/node_modules/express/lib/router/layer.js:67:12)
Feb 02 06:47:05 video peertube[6224]:     at trim_prefix (/var/www/PeerTube/versions/peertube-v0.0.20-alpha/node_modules/express/lib/router/index.js:315:13)
Feb 02 06:47:05 video peertube[6224]:     at /var/www/PeerTube/versions/peertube-v0.0.20-alpha/node_modules/express/lib/router/index.js:284:7
Feb 02 06:47:05 video peertube[6224]:     at Function.process_params (/var/www/PeerTube/versions/peertube-v0.0.20-alpha/node_modules/express/lib/router/index.js:335:12)
Feb 02 06:47:05 video peertube[6224]:     at next (/var/www/PeerTube/versions/peertube-v0.0.20-alpha/node_modules/express/lib/router/index.js:275:10)
Feb 02 06:47:05 video peertube[6224]:     at Layer.handle_error (/var/www/PeerTube/versions/peertube-v0.0.20-alpha/node_modules/express/lib/router/layer.js:67:12)
Feb 02 06:47:05 video peertube[6224]:     at trim_prefix (/var/www/PeerTube/versions/peertube-v0.0.20-alpha/node_modules/express/lib/router/index.js:315:13)
Feb 02 06:47:05 video peertube[6224]:     at /var/www/PeerTube/versions/peertube-v0.0.20-alpha/node_modules/express/lib/router/index.js:284:7
Feb 02 06:47:05 video peertube[6224]:     at param (/var/www/PeerTube/versions/peertube-v0.0.20-alpha/node_modules/express/lib/router/index.js:354:14)
Feb 02 06:47:05 video peertube[6224]:     at param (/var/www/PeerTube/versions/peertube-v0.0.20-alpha/node_modules/express/lib/router/index.js:365:14)
Feb 02 06:47:05 video peertube[6224]:     at Function.process_params (/var/www/PeerTube/versions/peertube-v0.0.20-alpha/node_modules/express/lib/router/index.js:410:3)
Feb 02 06:47:05 video peertube[6224]:     at next (/var/www/PeerTube/versions/peertube-v0.0.20-alpha/node_modules/express/lib/router/index.js:275:10)
Feb 02 06:47:05 video peertube[6224]:     at Layer.handle_error (/var/www/PeerTube/versions/peertube-v0.0.20-alpha/node_modules/express/lib/router/layer.js:67:12)
Feb 02 06:47:05 video peertube[6224]:     at trim_prefix (/var/www/PeerTube/versions/peertube-v0.0.20-alpha/node_modules/express/lib/router/index.js:315:13)
Feb 02 06:47:05 video peertube[6224]:     at /var/www/PeerTube/versions/peertube-v0.0.20-alpha/node_modules/express/lib/router/index.js:284:7
Feb 02 06:47:05 video peertube[6224]:     at Function.process_params (/var/www/PeerTube/versions/peertube-v0.0.20-alpha/node_modules/express/lib/router/index.js:335:12)
Feb 02 06:47:05 video peertube[6224]:     at next (/var/www/PeerTube/versions/peertube-v0.0.20-alpha/node_modules/express/lib/router/index.js:275:10)
Feb 02 06:47:05 video peertube[6224]:     at Layer.handle_error (/var/www/PeerTube/versions/peertube-v0.0.20-alpha/node_modules/express/lib/router/layer.js:67:12)
Feb 02 06:47:05 video peertube[6224]:     at trim_prefix (/var/www/PeerTube/versions/peertube-v0.0.20-alpha/node_modules/express/lib/router/index.js:315:13)
Feb 02 06:47:05 video peertube[6224]:     at /var/www/PeerTube/versions/peertube-v0.0.20-alpha/node_modules/express/lib/router/index.js:284:7
Feb 02 06:47:05 video peertube[6224]:     at Function.process_params (/var/www/PeerTube/versions/peertube-v0.0.20-alpha/node_modules/express/lib/router/index.js:335:12)
Feb 02 06:47:05 video peertube[6224]:     at next (/var/www/PeerTube/versions/peertube-v0.0.20-alpha/node_modules/express/lib/router/index.js:275:10)
Feb 02 06:47:05 video peertube[6224]:     at Layer.handle_error (/var/www/PeerTube/versions/peertube-v0.0.20-alpha/node_modules/express/lib/router/layer.js:67:12)
Feb 02 06:47:05 video peertube[6224]:     at trim_prefix (/var/www/PeerTube/versions/peertube-v0.0.20-alpha/node_modules/express/lib/router/index.js:315:13)
Feb 02 06:47:05 video peertube[6224]:     at /var/www/PeerTube/versions/peertube-v0.0.20-alpha/node_modules/express/lib/router/index.js:284:7
Feb 02 06:47:05 video peertube[6224]:     at Function.process_params (/var/www/PeerTube/versions/peertube-v0.0.20-alpha/node_modules/express/lib/router/index.js:335:12)
Feb 02 06:47:05 video peertube[6224]:     at next (/var/www/PeerTube/versions/peertube-v0.0.20-alpha/node_modules/express/lib/router/index.js:275:10)
Feb 02 06:47:05 video peertube[6224]:     at Layer.handle_error (/var/www/PeerTube/versions/peertube-v0.0.20-alpha/node_modules/express/lib/router/layer.js:67:12)
Feb 02 06:47:05 video peertube[6224]:     at trim_prefix (/var/www/PeerTube/versions/peertube-v0.0.20-alpha/node_modules/express/lib/router/index.js:315:13)
```

**Comment by ReK2Fernandez** [comment] 2018-02-03 00:12
I downgraded to .19 and I dont get that.
But now it wont show any video, nor the ones on my node or the other ones linked/following
```
Feb 03 00:02:37 video peertube[12303]: > peertube@0.0.19-alpha start /var/www/PeerTube/versions/peertube-v0.0.19-alpha
Feb 03 00:02:37 video peertube[12303]: > node dist/server

```

**Comment by ReK2Fernandez** [comment] 2018-02-03 01:06
ok so got home and I get the same video output but I dont get that msg on the log.. so it may not be related.. also if I go to another node that follows me and try to see the video from there I also get the same error screen as the first post screenshot.
https://tubes.libox.fr/videos/watch/4f68b57b-7aa0-4116-95e0-995ef91106f7
check for yourself..

**Comment by ReK2Fernandez** [comment] 2018-02-03 02:06
Another note, people can download via torrent or direct download from the "download" option that works fine is only the streaming part.

**Comment by bnjbvr** [comment] 2018-02-03 11:11
Interesting. There are a few errors showing up in the developer console, the first two being:

```
Media resource blob:https://tubes.libox.fr/bd222bc7-dad1-4a2c-8864-b24380f95738 could not be decoded.
```

Second one:

```
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported.
```

But what's weird is that the client keeps on requesting media bytes from the server, although an error happened; so this is hammering the server's bandwidth despite the client error preventing from playing the video.

**Comment by ReK2Fernandez** [comment] 2018-02-03 20:34
@bnjbvr maybe is because is to big? it is a .mp4 file, I am converting as I write this to .webm and will upload that to test.

**Comment by ReK2Fernandez** [comment] 2018-02-04 03:19
so I uploaded it again, a lower resolution instead of 18G is 6G and same issue https://video.hispagatos.org/videos/watch/6b198426-579c-41da-9c08-df9b0268800a
is odd I had only 5-6G video uploaded and they work just fine... :(

**Comment by ReK2Fernandez** [comment] 2018-02-04 03:24
@bnjbvr @Chocobozzz more logs.
```
Feb 03 07:04:07 video peertube[14409]: [video.hispagatos.org:443] 2018-02-06 07:04:07.320 error: TypeError: req.query.url.startsWith is not a function
Feb 03 07:04:07 video peertube[14409]:     at Object.<anonymous> (/var/www/PeerTube/versions/peertube-v0.0.19-alpha/dist/server/middlewares/validators/oembed.js:43:41)
Feb 03 07:04:07 video peertube[14409]:     at Generator.next (<anonymous>)
Feb 03 07:04:07 video peertube[14409]:     at /var/www/PeerTube/versions/peertube-v0.0.19-alpha/dist/server/middlewares/validators/oembed.js:7:71
Feb 03 07:04:07 video peertube[14409]:     at new Promise (<anonymous>)
Feb 03 07:04:07 video peertube[14409]:     at __awaiter (/var/www/PeerTube/versions/peertube-v0.0.19-alpha/dist/server/middlewares/validators/oembed.js:3:12)
Feb 03 07:04:07 video peertube[14409]:     at oembedValidator (/var/www/PeerTube/versions/peertube-v0.0.19-alpha/dist/server/middlewares/validators/oembed.js:34:25)
Feb 03 07:04:07 video peertube[14409]:     at async_1.eachSeries (/var/www/PeerTube/versions/peertube-v0.0.19-alpha/dist/server/middlewares/async.js:8:33)
Feb 03 07:04:07 video peertube[14409]:     at /var/www/PeerTube/versions/peertube-v0.0.19-alpha/node_modules/async/dist/async.js:3096:16
Feb 03 07:04:07 video peertube[14409]:     at replenish (/var/www/PeerTube/versions/peertube-v0.0.19-alpha/node_modules/async/dist/async.js:998:17)
Feb 03 07:04:07 video peertube[14409]:     at iterateeCallback (/var/www/PeerTube/versions/peertube-v0.0.19-alpha/node_modules/async/dist/async.js:983:17)
Feb 03 07:04:07 video peertube[14409]:     at /var/www/PeerTube/versions/peertube-v0.0.19-alpha/node_modules/async/dist/async.js:958:16
Feb 03 07:04:07 video peertube[14409]:     at runner.then.errors (/var/www/PeerTube/versions/peertube-v0.0.19-alpha/node_modules/express-validator/check/check.js:16:7)
Feb 03 07:04:07 video peertube[14409]:     at <anonymous>
Feb 03 07:04:07 video peertube[14409]:     at process._tickCallback (internal/process/next_tick.js:188:7)
Feb 03 07:04:08 video peertube[14409]: [video.hispagatos.org:443] 2018-02-06 07:04:08.124 error: TypeError: req.query.url.startsWith is not a function
Feb 03 07:04:08 video peertube[14409]:     at Object.<anonymous> (/var/www/PeerTube/versions/peertube-v0.0.19-alpha/dist/server/middlewares/validators/oembed.js:43:41)
Feb 03 07:04:08 video peertube[14409]:     at Generator.next (<anonymous>)
Feb 03 07:04:08 video peertube[14409]:     at /var/www/PeerTube/versions/peertube-v0.0.19-alpha/dist/server/middlewares/validators/oembed.js:7:71
Feb 03 07:04:08 video peertube[14409]:     at new Promise (<anonymous>)
Feb 03 07:04:08 video peertube[14409]:     at __awaiter (/var/www/PeerTube/versions/peertube-v0.0.19-alpha/dist/server/middlewares/validators/oembed.js:3:12)
Feb 03 07:04:08 video peertube[14409]:     at oembedValidator (/var/www/PeerTube/versions/peertube-v0.0.19-alpha/dist/server/middlewares/validators/oembed.js:34:25)
Feb 03 07:04:08 video peertube[14409]:     at async_1.eachSeries (/var/www/PeerTube/versions/peertube-v0.0.19-alpha/dist/server/middlewares/async.js:8:33)
Feb 03 07:04:08 video peertube[14409]:     at /var/www/PeerTube/versions/peertube-v0.0.19-alpha/node_modules/async/dist/async.js:3096:16
Feb 03 07:04:08 video peertube[14409]:     at replenish (/var/www/PeerTube/versions/peertube-v0.0.19-alpha/node_modules/async/dist/async.js:998:17)
Feb 03 07:04:08 video peertube[14409]:     at iterateeCallback (/var/www/PeerTube/versions/peertube-v0.0.19-alpha/node_modules/async/dist/async.js:983:17)
Feb 03 07:04:08 video peertube[14409]:     at /var/www/PeerTube/versions/peertube-v0.0.19-alpha/node_modules/async/dist/async.js:958:16
Feb 03 07:04:08 video peertube[14409]:     at runner.then.errors (/var/www/PeerTube/versions/peertube-v0.0.19-alpha/node_modules/express-validator/check/check.js:16:7)
Feb 03 07:04:08 video peertube[14409]:     at <anonymous>
Feb 03 07:04:08 video peertube[14409]:     at process._tickCallback (internal/process/next_tick.js:188:7)
Feb 03 07:04:09 video peertube[14409]: [video.hispagatos.org:443] 2018-02-06 07:04:09.019 error: TypeError: req.query.url.startsWith is not a function
Feb 03 07:04:09 video peertube[14409]:     at Object.<anonymous> (/var/www/PeerTube/versions/peertube-v0.0.19-alpha/dist/server/middlewares/validators/oembed.js:43:41)
Feb 03 07:04:09 video peertube[14409]:     at Generator.next (<anonymous>)
Feb 03 07:04:09 video peertube[14409]:     at /var/www/PeerTube/versions/peertube-v0.0.19-alpha/dist/server/middlewares/validators/oembed.js:7:71
Feb 03 07:04:09 video peertube[14409]:     at new Promise (<anonymous>)
Feb 03 07:04:09 video peertube[14409]:     at __awaiter (/var/www/PeerTube/versions/peertube-v0.0.19-alpha/dist/server/middlewares/validators/oembed.js:3:12)
Feb 03 07:04:09 video peertube[14409]:     at oembedValidator (/var/www/PeerTube/versions/peertube-v0.0.19-alpha/dist/server/middlewares/validators/oembed.js:34:25)
Feb 03 07:04:09 video peertube[14409]:     at async_1.eachSeries (/var/www/PeerTube/versions/peertube-v0.0.19-alpha/dist/server/middlewares/async.js:8:33)
Feb 03 07:04:09 video peertube[14409]:     at /var/www/PeerTube/versions/peertube-v0.0.19-alpha/node_modules/async/dist/async.js:3096:16
Feb 03 07:04:09 video peertube[14409]:     at replenish (/var/www/PeerTube/versions/peertube-v0.0.19-alpha/node_modules/async/dist/async.js:998:17)
Feb 03 07:04:09 video peertube[14409]:     at iterateeCallback (/var/www/PeerTube/versions/peertube-v0.0.19-alpha/node_modules/async/dist/async.js:983:17)
Feb 03 07:04:09 video peertube[14409]:     at /var/www/PeerTube/versions/peertube-v0.0.19-alpha/node_modules/async/dist/async.js:958:16
Feb 03 07:04:09 video peertube[14409]:     at runner.then.errors (/var/www/PeerTube/versions/peertube-v0.0.19-alpha/node_modules/express-validator/check/check.js:16:7)
Feb 03 07:04:09 video peertube[14409]:     at <anonymous>
Feb 03 07:04:09 video peertube[14409]:     at process._tickCallback (internal/process/next_tick.js:188:7)
Feb 03 07:04:09 video peertube[14409]: [video.hispagatos.org:443] 2018-02-06 07:04:09.090 error: TypeError: req.query.url.startsWith is not a function
Feb 03 07:04:09 video peertube[14409]:     at Object.<anonymous> (/var/www/PeerTube/versions/peertube-v0.0.19-alpha/dist/server/middlewares/validators/oembed.js:43:41)
Feb 03 07:04:09 video peertube[14409]:     at Generator.next (<anonymous>)
Feb 03 07:04:09 video peertube[14409]:     at /var/www/PeerTube/versions/peertube-v0.0.19-alpha/dist/server/middlewares/validators/oembed.js:7:71
Feb 03 07:04:09 video peertube[14409]:     at new Promise (<anonymous>)
Feb 03 07:04:09 video peertube[14409]:     at __awaiter (/var/www/PeerTube/versions/peertube-v0.0.19-alpha/dist/server/middlewares/validators/oembed.js:3:12)
Feb 03 07:04:09 video peertube[14409]:     at oembedValidator (/var/www/PeerTube/versions/peertube-v0.0.19-alpha/dist/server/middlewares/validators/oembed.js:34:25)
Feb 03 07:04:09 video peertube[14409]:     at async_1.eachSeries (/var/www/PeerTube/versions/peertube-v0.0.19-alpha/dist/server/middlewares/async.js:8:33)
Feb 03 07:04:09 video peertube[14409]:     at /var/www/PeerTube/versions/peertube-v0.0.19-alpha/node_modules/async/dist/async.js:3096:16
Feb 03 07:04:09 video peertube[14409]:     at replenish (/var/www/PeerTube/versions/peertube-v0.0.19-alpha/node_modules/async/dist/async.js:998:17)
Feb 03 07:04:09 video peertube[14409]:     at iterateeCallback (/var/www/PeerTube/versions/peertube-v0.0.19-alpha/node_modules/async/dist/async.js:983:17)
Feb 03 07:04:09 video peertube[14409]:     at /var/www/PeerTube/versions/peertube-v0.0.19-alpha/node_modules/async/dist/async.js:958:16
Feb 03 07:04:09 video peertube[14409]:     at runner.then.errors (/var/www/PeerTube/versions/peertube-v0.0.19-alpha/node_modules/express-validator/check/check.js:16:7)
Feb 03 07:04:09 video peertube[14409]:     at <anonymous>
Feb 03 07:04:09 video peertube[14409]:     at process._tickCallback (internal/process/next_tick.js:188:7)
Feb 03 07:04:09 video peertube[14409]: [video.hispagatos.org:443] 2018-02-06 07:04:09.457 error: TypeError: req.query.url.startsWith is not a function
Feb 03 07:04:09 video peertube[14409]:     at Object.<anonymous> (/var/www/PeerTube/versions/peertube-v0.0.19-alpha/dist/server/middlewares/validators/oembed.js:43:41)
Feb 03 07:04:09 video peertube[14409]:     at Generator.next (<anonymous>)
Feb 03 07:04:09 video peertube[14409]:     at /var/www/PeerTube/versions/peertube-v0.0.19-alpha/dist/server/middlewares/validators/oembed.js:7:71
Feb 03 07:04:09 video peertube[14409]:     at new Promise (<anonymous>)
Feb 03 07:04:09 video peertube[14409]:     at __awaiter (/var/www/PeerTube/versions/peertube-v0.0.19-alpha/dist/server/middlewares/validators/oembed.js:3:12)
Feb 03 07:04:09 video peertube[14409]:     at oembedValidator (/var/www/PeerTube/versions/peertube-v0.0.19-alpha/dist/server/middlewares/validators/oembed.js:34:25)
Feb 03 07:04:09 video peertube[14409]:     at async_1.eachSeries (/var/www/PeerTube/versions/peertube-v0.0.19-alpha/dist/server/middlewares/async.js:8:33)
Feb 03 07:04:09 video peertube[14409]:     at /var/www/PeerTube/versions/peertube-v0.0.19-alpha/node_modules/async/dist/async.js:3096:16
Feb 03 07:04:09 video peertube[14409]:     at replenish (/var/www/PeerTube/versions/peertube-v0.0.19-alpha/node_modules/async/dist/async.js:998:17)
Feb 03 07:04:09 video peertube[14409]:     at iterateeCallback (/var/www/PeerTube/versions/peertube-v0.0.19-alpha/node_modules/async/dist/async.js:983:17)
Feb 03 07:04:09 video peertube[14409]:     at /var/www/PeerTube/versions/peertube-v0.0.19-alpha/node_modules/async/dist/async.js:958:16
Feb 03 07:04:09 video peertube[14409]:     at runner.then.errors (/var/www/PeerTube/versions/peertube-v0.0.19-alpha/node_modules/express-validator/check/check.js:16:7)
Feb 03 07:04:09 video peertube[14409]:     at <anonymous>
Feb 03 07:04:09 video peertube[14409]:     at process._tickCallback (internal/process/next_tick.js:188:7)
Feb 03 07:04:30 video peertube[14409]: [video.hispagatos.org:443] 2018-02-06 07:04:30.084 error: TypeError: req.query.url.startsWith is not a function
Feb 03 07:04:30 video peertube[14409]:     at Object.<anonymous> (/var/www/PeerTube/versions/peertube-v0.0.19-alpha/dist/server/middlewares/validators/oembed.js:43:41)
Feb 03 07:04:30 video peertube[14409]:     at Generator.next (<anonymous>)
Feb 03 07:04:30 video peertube[14409]:     at /var/www/PeerTube/versions/peertube-v0.0.19-alpha/dist/server/middlewares/validators/oembed.js:7:71
Feb 03 07:04:30 video peertube[14409]:     at new Promise (<anonymous>)
Feb 03 07:04:30 video peertube[14409]:     at __awaiter (/var/www/PeerTube/versions/peertube-v0.0.19-alpha/dist/server/middlewares/validators/oembed.js:3:12)
Feb 03 07:04:30 video peertube[14409]:     at oembedValidator (/var/www/PeerTube/versions/peertube-v0.0.19-alpha/dist/server/middlewares/validators/oembed.js:34:25)
Feb 03 07:04:30 video peertube[14409]:     at async_1.eachSeries (/var/www/PeerTube/versions/peertube-v0.0.19-alpha/dist/server/middlewares/async.js:8:33)
Feb 03 07:04:30 video peertube[14409]:     at /var/www/PeerTube/versions/peertube-v0.0.19-alpha/node_modules/async/dist/async.js:3096:16
Feb 03 07:04:30 video peertube[14409]:     at replenish (/var/www/PeerTube/versions/peertube-v0.0.19-alpha/node_modules/async/dist/async.js:998:17)
Feb 03 07:04:30 video peertube[14409]:     at iterateeCallback (/var/www/PeerTube/versions/peertube-v0.0.19-alpha/node_modules/async/dist/async.js:983:17)
Feb 03 07:04:30 video peertube[14409]:     at /var/www/PeerTube/versions/peertube-v0.0.19-alpha/node_modules/async/dist/async.js:958:16
Feb 03 07:04:30 video peertube[14409]:     at runner.then.errors (/var/www/PeerTube/versions/peertube-v0.0.19-alpha/node_modules/express-validator/check/check.js:16:7)
Feb 03 07:04:30 video peertube[14409]:     at <anonymous>
Feb 03 07:04:30 video peertube[14409]:     at process._tickCallback (internal/process/next_tick.js:188:7)
Feb 03 22:09:06 video peertube[14409]: npm ERR! code ELIFECYCLE
Feb 03 22:09:06 video peertube[14409]: npm ERR! errno 1
Feb 03 22:09:06 video peertube[14409]: npm ERR! peertube@0.0.19-alpha start: `node dist/server`
Feb 03 22:09:06 video peertube[14409]: npm ERR! Exit status 1
Feb 03 22:09:06 video peertube[14409]: npm ERR!
Feb 03 22:09:06 video peertube[14409]: npm ERR! Failed at the peertube@0.0.19-alpha start script.
Feb 03 22:09:06 video peertube[14409]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Feb 03 22:09:06 video peertube[14409]: npm ERR! A complete log of this run can be found in:
Feb 03 22:09:06 video peertube[14409]: npm ERR!     /home/peertube/.npm/_logs/2018-02-03T22_09_06_376Z-debug.log
Feb 03 22:09:06 video systemd[1]: peertube.service: Main process exited, code=exited, status=1/FAILURE
Feb 03 22:09:06 video systemd[1]: peertube.service: Unit entered failed state.
Feb 03 22:09:06 video systemd[1]: peertube.service: Failed with result 'exit-code'.
```

**Comment by bnjbvr** [comment] 2018-02-04 17:14
Can you try the following:

- check that the Express version you're using is the one specified in the yarn.lock file? (it might be that `req.query.url` is empty) One way to make sure of this is to remove node_modules and reuse `yarn install --pure-lockfile`.
- check that you're running a `nodejs` server recent enough? `String.prototype.startsWith` has been added to ES6, which should be implemented in node 4 according to kangaxx compatibility tables.
- if none of the above works, can you add debugging in `server/middlewares/validators/oembed.js` (either in the dist/ built file, or in the source and then recompile): `console.log('HELLO THERE', req.query.url);`

**Comment by ReK2Fernandez** [comment] 2018-02-04 19:57
@bnjbvr thanks a lot for helping, I just woke up, im on PST time, will have some lunch and check into all this since nobody can watch the video now only download :/

**Comment by ReK2Fernandez** [comment] 2018-02-06 00:42
@bnjbvr Hey, sorry but where exactly and how to I enable debug so I can paste it here? I am a C/GO/QT/Ruby(not rails) person so anything webapp dev I am clueless, no JS...etc :)
Thanks.

**Comment by bnjbvr** [comment] 2018-02-06 21:20
- if you're using Docker, first get into the container with `docker exec -ti $container_id /bin/bash`
- go to the PeerTube installation directory
- then edit the file `dist/server/middlewares/validators/oembed.js` with the following changes:

```patch
diff --git a/dist/server/middlewares/validators/oembed.js b/dist/server/middlewares/validators/oembed.js
index ddf4b33..3621046 100644
--- a/dist/server/middlewares/validators/oembed.js
+++ b/dist/server/middlewares/validators/oembed.js
@@ -40,6 +40,11 @@ const oembedValidator = [
                 .json({ error: 'Requested format is not implemented on server.' })
                 .end();
         }
+        console.log('DEBUGGING: typeof String.prototype.startsWith =', typeof String.prototype.startsWith);
+        console.log('DEBUGGING: url =', req.query.url);
+        console.log('DEBUGGING: typeof url =', typeof req.query.url);
+        console.log('DEBUGGING: typeof url.startsWith =', typeof req.query.url.startsWith);
+        console.log('DEBUGGING: typeof "url".startsWith =', typeof ('' + req.query.url).startsWith);
         const startIsOk = req.query.url.startsWith(urlShouldStartWith);
         const matches = videoWatchRegex.exec(req.query.url);
         if (startIsOk === false || matches === null) {
```
- then restart PeerTube, reproduce the issue and include logs in this issue please :)

**Comment by ReK2Fernandez** [comment] 2018-02-06 23:15
@bnjbvr thanks! not using docker but should be in the same place I suppose.

**Comment by Chocobozzz** [comment] 2018-02-07 11:04
Hi, thanks for the investigation!

I think it is related to this issue: https://github.com/feross/render-media/issues/28

@ReK2Fernandez could you try to reduce the video file size to < 4GB and reupload it?

**Comment by bnjbvr** [comment] 2018-02-07 13:12
Potential nice find! But I still think there is/was also a different error happening here.

@ReK2Fernandez, could you replace all the occurrences of `console.log` by `logger_1.logger.warn` and restart peertube, please? (grep "DEBUGGING" which should be printed at some point?...)

**Comment by ReK2Fernandez** [comment] 2018-02-08 16:41
@Chocobozzz is there a way to reduce the file with out loosing quality? I am afraid that if this is not possible, this is still a mayor bug, since lot of people that we do video podcast the videos are 1-2 hours for special events like this one that has interview from the 34c3 hacker conference...
@bnjbvr Thanks! hopefully I can do that after work today after work, and post the logs. thanks again.

**Comment by Chocobozzz** [comment] 2018-02-09 07:20
Solutions:
 * Encode the original video in 720p
 * Split the video in two parts

Remember that Dailymotion has a maximum duration of 60 minutes per video or Vimeo has a quota of 500MB per week so I don't think it's really a major bug.

**Comment by ReK2Fernandez** [comment] 2018-02-10 02:24
@Chocobozzz you are right.. the video shows under 720p  is there a way to remove the 1080 so I dont have to re-upload?

**Comment by skid9000** [comment] 2018-02-11 23:08
Hmm, i have this bug on my instance :s

Same crap as @ReK2Fernandez in the logs ...

[https://peertube.nsa.ovh/videos/watch/0bdea558-8a92-4d63-96e1-f547bcc4d757](https://peertube.nsa.ovh/videos/watch/0bdea558-8a92-4d63-96e1-f547bcc4d757)

I just updated to the last version 10 minutes ago but it changed nothing :/

**Comment by Chocobozzz** [comment] 2018-02-12 07:08
@skid9000 I think your issue is different: your file is broken https://peertube.nsa.ovh/static/webseed/0bdea558-8a92-4d63-96e1-f547bcc4d757-240.mp4

**Comment by ReK2Fernandez** [comment] 2018-02-12 22:47
@Chocobozzz yes that is what I meant, from the database/disk..  so just a sql DELETE from that table and delete the files? ok good to know. Thanks.

**Comment by ReK2Fernandez** [comment] 2018-02-17 03:32
@Chocobozzz someone uploaded a new video that is under 1g and is not working, same error msg
video is .mp4 and size 701M https://video.hispagatos.org/videos/watch/6a506a16-5fc4-47f8-880e-868299a1394a

**Comment by Chocobozzz** [comment] 2018-02-17 07:55
It works on my side.

**Comment by Tekprog-fr** [comment] 2018-02-17 21:38
I have just uploaded around 2 videos with username mlsuyt1 on https://video.tedomum.net instance.
I uploaded the video by using youtube-dl, flexget and peeror.
All videos format are webm. Normally this format is supposed to be a valid format. 
The size of the both videos is respectively 13M and 15M
when I try to watch the video, I have the same error : 
The media could not be loaded, either because the server or network failed or because the format is not supported

The browser used is Chromium Version 57.0.2987.98 Built on 8.7, running on Debian buster/sid

Maybe this issue is only for me, anyone can confirm the same issue ?

The links to the both videos are : 
https://video.tedomum.net/videos/watch/03734e88-83bd-47d5-8fdc-fc62d9ccdfea
https://video.tedomum.net/videos/watch/9ff75a18-40c3-4bd8-ba3a-ad8f787fbfae

The conversion of the format video from webm to mp4 is necessary maybe ?

I don't know for the moment how gaining more debugging information as regarding this issue since it is not my instance.

**Comment by Tekprog-fr** [comment] 2018-02-17 21:45
I don't know if it can help but for information as regarding the previous comment, VLC manage to open the both videos, so files are not malformed on my computer.

**Comment by Tekprog-fr** [comment] 2018-02-17 22:07
the instance  https://video.tedomum.net  has for version : PeerTube v0.0.20-alpha - CopyLeft 2015-2017

**Comment by ReK2Fernandez** [comment] 2018-02-18 00:58
@Chocobozzz you are right, it works now, maybe it was rendering?

**Comment by Tekprog-fr** [comment] 2018-02-18 07:39
Ok. I have juste tested the both videos in firefox and it works:). So there is issue linked to Chromium.
Ok. Je viens donc de testé les 2 vidéos sur fireforx and cela fonctionne. Donc le problème viendrait de chromium qui n'est pas content.

**Comment by Chocobozzz** [comment] 2018-02-18 08:55
@Tekprog-fr I fixed your issue: https://github.com/Chocobozzz/PeerTube/commit/16f16570978bc57bbe14524e6d0cc27260191bfd

@ReK2Fernandez Sometimes videos are not suitable for the web, transcoding resolve most of the issues.

**Comment by Chocobozzz** [comment] 2018-02-22 15:54
Closing this issue. I added an error message if a user try to upload a big video: https://github.com/Chocobozzz/PeerTube/commit/81c263c86fe2a030f09e942e118551727f145b6d

**Closed by Chocobozzz** 2018-02-22 15:54 UTC
Labels: Type: Bug
