### ISSUE TITLE
More discreet "Incompatible browser" message

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#6284] opened 2024-03-22 09:41 UTC
### Describe the problem to be solved

A lot of smart TV's has old browsers installed and no easy way to update the browser. Today the "Incompatible browser" message takes a huge amount of area of the site which gives the user the feeling that's something is broken.

![image](https://github.com/Chocobozzz/PeerTube/assets/6680299/702e30e3-2128-48cf-b7a7-c50d0380f3b6)
![image](https://github.com/Chocobozzz/PeerTube/assets/6680299/0947ed1a-e551-4ab7-9606-6721b0c7e0fe)

### Describe the solution you would like

Even though the browser is old and it's not supported by Peertube it may still be working. Therefore I'd propose to have a clear message that explains that this browser is not supported, but you can continue on your own risk. A simple solution could be the one below, but it could be even more discreet.

![image](https://github.com/Chocobozzz/PeerTube/assets/6680299/f5822467-8300-40c3-aaab-35a5390f6471)

**Comment by Chocobozzz** [comment] 2024-03-25 09:06
Do you know what is the JS error that leads to this message?

I think we should hide the angular application in such a scenario because we're not sure how the application will behave.

**Comment by kontrollanten** [comment] 2024-03-26 08:56
> Do you know what is the JS error that leads to this message?

No, unfortunately I'm not able to reproduce this.

> I think we should hide the angular application in such a scenario because we're not sure how the application will behave.

Is the "Incompatible browser" message only shown when there's actually an error or does it only check the browser version? If it's the latter, isn't it better to just show a clear message that says something like "enter at your own risk" since it may work even though it's unsupported?

**Comment by Chocobozzz** [comment] 2024-03-26 15:18
> Is the "Incompatible browser" message only shown when there's actually an error 

Yes it's when there is an error (except to detect internet explorer). You can see the logic here: https://github.com/Chocobozzz/PeerTube/blob/develop/client/src/index.html#L70

**Comment by Chocobozzz** [comment] 2024-05-29 13:45
Hi,

Are you able to know which web browser and version has this kind of error?

**Comment by kontrollanten** [comment] 2024-05-29 18:40
Hi, unfortunately I don't know in this specific case. I looked in Google Analytics to see which browser versions our TV users has been using for the last 90 days and found the following:

| Browser | Version |
| ---            | ---- |
| Opera | 28.0.1754.0 |
| Chrome | 87.0.4280.144 |
| Amazon Silk | 118.7.1 |
| Amazon Silk | 120.5.10 |
| Amazon Silk | 122.1.60 |

For the issue https://github.com/Chocobozzz/PeerTube/issues/3736 I know the user had Chrome 38 on a LG TV bought 2020.

**Comment by Chocobozzz** [comment] 2024-09-13 08:14
Closing because we were not able to reproduce the issue.

**Closed by Chocobozzz** 2024-09-13 08:14 UTC
Labels: Status: Waiting for answer
