### ISSUE TITLE
"Other Videos" sidebar suggests you videos you already watched

### ISSUE THREAD

**Issue by ghost** [Chocobozzz/PeerTube#1985] opened 2019-07-24 14:25 UTC
As of right now on PeerTube v1.3.1 the "Other Videos" sidebar suggests you videos you already watched - so you end up in a loop and you stop using the sidebar recommendations at some point.
What we can do to make sure people see great, non-duplicated content in the sidebar?

**Comment by frankstrater** [comment] 2019-07-30 12:24
Maybe we could extend the functionality from the [video history](https://docs.joinpeertube.org/#/use-video-history) to filter the list of sidebar recommendations, but then you might end up with zero recommendations after watching them all.

**Comment by realityfabric** [comment] 2019-07-30 14:35
If you do that (filter based on view history) you may want to add a user setting to toggle that filter on and off.

**Comment by frankstrater** [comment] 2019-08-01 10:21
I would prefer just randomized 5 recommendations picked from a metedata matched (or otherwise) set of at least 20, but that's because I don't like 'personalisation' / user tracking built in by design.

**Comment by LoveIsGrief** [comment] 2021-05-29 17:51
It looks like the recommendations are built by the client in a query

https://github.com/Chocobozzz/PeerTube/blob/db5814c0472d2b9e8f0ca6bdd1175ff1cd99ed7c/client/src/app/%2Bvideos/%2Bvideo-watch/recommendations/recent-videos-recommendation.service.ts#L56

The autoplay then uses the first video from that list (originally it was a random video, not sure why that was changed :thinking: )

https://github.com/Chocobozzz/PeerTube/blob/9e2e51dc0bee5dc065a61c927e787ae021e8aa73/client/src/app/%2Bvideos/%2Bvideo-watch/video-watch.component.ts#L325

In any case, either a new API endpoint is required to return better recommendations or the client will have to make multiple queries depending on the settings we choose to introduce. I believe an API endpoint would be better, then the user-settings can be used to forge the query and only a list of videos will be returned.

My preference would be : 
 - either have the option to filter out videos I've already watched
 - or use the current API [`searchVideos`](https://docs.joinpeertube.org/api-rest-reference.html#operation/searchVideos) to make multiple queries that are then merged, filtered (to remove the current video) and finally shuffled
   1. Make a bigger query (current size is 5 so maybe multiply the result size). This would maybe even allow filtering out watched videos.
   2. Query using the category of the current video
   3. Query using title of video while removing short words (e.g <3 or <4)
   4. (Optional) If nothing really comes up then make simple query for the newest videos

Regardless of which solution is chosen, I think it would be good for users to have the option for pseudo sorting that modifies the search query. Atm the moment it's just "Newest related videos" (`-publishedAt`). We could introduce "sorting" for related videos that are:

 - Oldest
 - Lowest/Highest rated
 - Lowest/Highest views
 - Least/Most popular
 
Thoughts?

**Comment by kontrollanten** [comment] 2021-05-31 08:15
Interesting. Could this be done by allowing plugins to altering _related videos_? I can see other use cases where this could be helpful, i.e. weighting videos in current channel or instance higher than other videos.

**Closed** 2023-04-12 07:32 UTC
Labels: Type: Feature Request :sparkles:, Component: Recommendation
