### ISSUE TITLE
Show video with sponsored content

### ISSUE THREAD

**Issue by davlgd** [Chocobozzz/PeerTube#810] opened 2018-07-14 07:03 UTC
If a user upload a video containing sponsored content, he needs a checkbox to tell if it contains sponsored content. Such a video should show a warning to viewers to follow the law in France (but certainly in many countries)

**Comment by Chocobozzz** [comment] 2018-07-14 07:41
Hello @davlgd, thanks for the issue but it's a duplicate of https://github.com/Chocobozzz/PeerTube/issues/473 :)

**Closed by Chocobozzz** 2018-07-14 07:41 UTC
