### ISSUE TITLE
My Notifications errors if imported video deleted 

### ISSUE THREAD

**Issue by joshmorel** [Chocobozzz/PeerTube#1632] opened 2019-02-13 20:33 UTC
**What happened?**

Deleted imported video and get `"Error TypeError: Cannot read property 'uuid' of undefined"` 

**What do you expect to happen instead?**

No error - either notification deleted if video deleted OR logic in front-end with empty `buildVideoUrl` if `video` missing on `videoImport` object. 

**Steps to reproduce:**

1. Import with URL from https://youtu.be/msX3jv1XdvM

2. Delete video that was just imported

3. Click on Avatar

**Additional information**
* PeerTube version or URL: Develop at 7f40ce53243be994a3cf093e07eb1d460f696b10
* Browser name/version: Chrome Version 72.0.3626.96 (Official Build) (64-bit)
* NodeJS version: 8.15.0

* Browser console log:

```
main.js:11991 TypeError: Cannot read property 'uuid' of undefined
    at UserNotification.push../src/app/shared/users/user-notification.model.ts.UserNotification.buildVideoUrl (main.js:13010)
    at new UserNotification (main.js:12995)
    at UserNotificationService.push../src/app/shared/users/user-notification.service.ts.UserNotificationService.formatNotification (main.js:13112)
    at main.js:11934
    at Array.forEach (<anonymous>)
    at RestExtractor.push../src/app/shared/rest/rest-extractor.service.ts.RestExtractor.applyToResultListData (main.js:11934)
    at MapSubscriber.project (main.js:13084)
    at MapSubscriber.push../node_modules/rxjs/_esm5/internal/operators/map.js.MapSubscriber._next (vendor.js:155813)
    at MapSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (vendor.js:150527)
    at MapSubscriber.push../node_modules/rxjs/_esm5/internal/operators/map.js.MapSubscriber._next (vendor.js:155819)
```

**Comment by Chocobozzz** [comment] 2019-02-14 09:00
Thanks @joshmorel 

It's a duplicate of https://github.com/Chocobozzz/PeerTube/issues/1599 but your stack trace helped me a lot. I'll fix it

**Closed by Chocobozzz** 2019-02-14 09:00 UTC
