### ISSUE TITLE
A missing translation on alert when you want to modify a live (4.0.0-rc.1)

### ISSUE THREAD

**Issue by rnek0** [Chocobozzz/PeerTube#4617] opened 2021-12-08 12:16 UTC
**Describe the current behavior**

The sentence below is in English, see the image.

**Steps to reproduce:**

1. Launch a live
2. Try to modifie it
3. Alert appears

**Describe the expected behavior**

The **two sentences** must be in the same language

**Additional information**

![live-i18n](https://user-images.githubusercontent.com/52655832/145206066-8b879ba0-19d6-4c3f-b54a-74920e27f10f.png)

* PeerTube instance:
* URL: ptb.lunarviews.net
* version: 4.0.0-rc.1
* NodeJS version: v14.18.1
* Ffmpeg version: 4.3.3-0+deb11u1
* Video : [see here](https://ptb.lunarviews.net/w/tJeZKEGoJpJMWUnk7pwpkt?start=49s)

**Comment by Chocobozzz** [comment] 2021-12-09 12:55
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/1122

**Closed by Chocobozzz** 2021-12-09 12:55 UTC
