### ISSUE TITLE
Mobile UI Bug when adding Clips Playlists 

### ISSUE THREAD

**Issue by tilllt** [Chocobozzz/PeerTube#6567] opened 2024-09-02 17:51 UTC
### Describe the current behavior

When trying to add a clip to a playlist on mobile view, the dialog opens partly off-screen making it hard to select the correct playlist.

### Steps to reproduce

1. Modify Clip Metadata
2. Try to add to playlist 
3.

### Describe the expected behavior

The dialog should probably be centered and honor mobile screen width.

### Additional information

* PeerTube instance: 6.2 / docker
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
Android Firefox and Chrome 
![Screenshot_2024-09-02-19-45-09-065_com android chrome-edit](https://github.com/user-attachments/assets/9dd7dc98-245b-4533-bc3e-0a3c47e6b098)

* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment] 2024-09-05 13:25
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/6519

**Closed by Chocobozzz** 2024-09-05 13:25 UTC
Labels: Type: Duplicate :loop:, Component: Mobile
