### ISSUE TITLE
Verifying PeerTube instance ownership on Mastodon

### ISSUE THREAD

**Issue by bristow** [Chocobozzz/PeerTube#5429] opened 2022-11-24 09:06 UTC
### Describe the problem to be solved

On Mastodon, you can verify your ownership of a website by inserting a link to your Mastodon account with the rel=« me » option included.

Is there any way to insert this code on the front page of a PeerTube instance without a custom homepage and only with an admin account ?

I have a link to my PeerTube instance on my Mastodon profile, and it would be nice to make it turn green by using this code.

Thanks a lot :+1: 

### Describe the solution you would like

A simply way to verify an Peertube instance :)

**Comment by evoLucidity** [comment] 2022-11-25 13:51
If you're the admin you can add the link to `<peertube-latest>/client/dist/$your_locale/index.html`.

**Comment by bristow** [comment] 2022-11-25 15:45
admin but not adminsys.

And we use Docker...

**Comment by Chocobozzz** [comment] 2022-11-28 08:23
Hi,

Our custom markdown is able to correctly parse `<a rel="me" href=""></a>` links. So can add this link in the description of your instance for example, and put `/about/instance` as path for mastodon if it can parse JS to render the page.

**Comment by fflorent** [comment] 2023-02-26 11:09
AFAIK, it does not render the verification mechanism does not parse JS:
https://github.com/mastodon/mastodon/issues/16322#issuecomment-849746060

This issue will probably allow to solve the issue of PeerTube instance verification Mastodon-side:
https://github.com/mastodon/mastodon/issues/20030

**Comment by Chocobozzz** [comment] 2024-12-27 08:36
Fixed in https://github.com/Chocobozzz/PeerTube/commit/cf921354a9f07c004650e4bce0d2ba0d20d70049 

(will be included in v7.1)

**Closed by Chocobozzz** 2024-12-27 08:36 UTC
Labels: Type: Feature Request :sparkles:, Component: Federation :ferris_wheel:

**Comment by rrgeorge** [comment] 2025-03-19 22:00
I think this issue should be reopened as this does not appear to be fully implemented. While the interface does support adding rel=me links to the description fields, the pages still require JavaScript to be rendered. Mastodon requires the rel=me link to be present in the raw html. See the comment above: https://github.com/Chocobozzz/PeerTube/issues/5429#issuecomment-1445331983

**Comment by Chocobozzz** [comment] 2025-03-20 05:17
With the commit above descriptions are parsed by the server and rel=me links should be included in the rendered page. It doesn't work on your instance?

**Comment by CodingOtaku** [comment] 2025-03-20 21:47
@rrgeorge, this is because peertube takes the _first_ rel-me link and ignores the others.
If you do `curl -s https://rrgeorge.video | grep rrgeorge.live` you will see the link `<link href="https://rrgeorge.live" rel="me">` in the header.

I will soon create a feature request to increase the amount of rel-me links to be picked up.

**Comment by rrgeorge** [comment] 2025-03-20 22:04
Thank you @CodingOtaku 
I knew I *had* to be missing something. I didn’t even think to check the other link.
Might be worth updating the release notes to indicate that it’s only the first rel=me link.

**Comment by CodingOtaku** [comment] 2025-03-20 22:06
Yeah, I also thought that the JS was the issue when I couldn't verify my links, then I spent a considerable amount of time thinking I did something wrong after finding one link appear in the header.
I should've just looked at the commit Chocobozzz linked here.

**Comment by frankstrater** [comment] 2025-03-24 13:12
> With the commit above descriptions are parsed by the server and rel=me links should be included in the rendered page. It doesn't work on your instance?

It doesn't work for the description field on the About page. See: https://peertube.beeldengeluid.nl/about/instance/home

**Comment by frankstrater** [comment] 2025-03-28 10:04
> [@frankstrater](https://github.com/frankstrater) Can you create a dedicated issue? I can't reproduce and I don't understand why it doesn't work on your instance 🤔

If you can't reproduce it, then it's a 'me' (lol) issue. I'll fix it myself.

**Comment by bristow** [comment] 2025-03-28 10:18
@frankstrater for me it's ok : 

![Image](https://github.com/user-attachments/assets/982e264b-d60b-45c6-b0c3-13e01664da46)

Mastodon needs to refresh the profile for this to be taken into account

**Comment by frankstrater** [comment] 2025-03-31 10:33
@bristow For me as well, but I was talking about a different URL, as the description field for the About page mentions in should now support link-rel-me generation, but I'm not seeing it https://peertube.beeldengeluid.nl/about/instance/home

I'm fine with the verification for the main URL as it is.
