### ISSUE TITLE
Low CPU usage when transcoding lower resolutions

### ISSUE THREAD

**Issue by vid-bin** [Chocobozzz/PeerTube#5249] opened 2022-09-12 07:52 UTC
Peertube uses 100% of the CPU when transcoding the original resolution but only 30%-50% of the CPU when it starts to transcode lower resolutions.

This is not version specific like I originally thought.

### Additional information

* PeerTube instance:
  * URL: vidbin.org
  * Version: 4.3.0-rc.1
  * NodeJS version: 18
  * Ffmpeg version: master

**Comment by vid-bin** [comment] 2022-09-12 08:43
I think what's going on here is the original video is only used for the first transcode. Then it uses the peertube produced HLS file for lower resolution transcodes. And for some reason it's just slower with the fragmented/HLS video.

**Comment by emansom** [comment] 2022-09-12 14:15
I observed similar behavior in my instance of PeerTube. Anything but highest resolution only maxes out at 60% CPU utilization, possibly leading to slower transcode times.

**Comment by vid-bin** [comment] 2022-09-12 19:41
https://www.youtube.com/watch?v=bR8De0woh0s

https://vidbin.org/w/4MsoK5aQdTxVkdqNFJDgfo

Using the below as the test:

https://vidbin.org/download/streaming-playlists/hls/videos/1ea4267d-37e3-4d40-bb92-124dd8faf1a6-1440-fragmented.mp4

Command: 

`ffmpeg -i /root/1ea4267d-37e3-4d40-bb92-124dd8faf1a6-1440-fragmented.mp4 -y -acodec aac -vcodec libsvtav1 -threads 24 -f mp4 -movflags faststart -max_muxing_queue_size 1024 -map_metadata -1 -pix_fmt yuv420p -b:a 192k -ac 2 -vf scale=w=-2:h=1080 -crf 42 -preset 7 -g 999 -hls_time 4 -hls_list_size 0 -hls_playlist_type vod -hls_segment_filename /root/1080-fragmented.mp4 -hls_segment_type fmp4 -f hls -hls_flags single_file /root/1080.m3u8`

The resulting FPS is only 28!!!! This is BAD.

![28fps](https://user-images.githubusercontent.com/112714131/189740840-b97d9982-1567-45c9-9420-73607213fa27.png)

Downloading https://www.youtube.com/watch?v=bR8De0woh0s 299+251 (1080p avc1+opus)

command:

`ffmpeg -i /root/input-1080p.mkv -y -acodec aac -vcodec libsvtav1 -threads 24 -f mp4 -movflags faststart -max_muxing_queue_size 1024 -map_metadata -1 -pix_fmt yuv420p -b:a 192k -ac 2 -vf scale=w=-2:h=1080 -crf 42 -preset 7 -g 999 /root/output-1080p-fragmented.mp4`

Resulting FPS is 55-60. This is GOOD!

![50fps](https://user-images.githubusercontent.com/112714131/189741454-7bce6a9c-c1a7-4511-a3de-72217fe4b991.png)

**Comment by vid-bin** [comment] 2022-09-12 19:46
Using 308+251 (1440p+opus)

`ffmpeg -i /root/1440p.mkv -y -acodec aac -vcodec libsvtav1 -threads 24 -f mp4 -movflags faststart -max_muxing_queue_size 1024 -map_metadata -1 -pix_fmt yuv420p -b:a 192k -ac 2 -vf scale=w=-2:h=1080 -crf 42 -preset 7 -g 999 /root/output-1080p-fragmented.mp4`

Resulting FPS is still 50.

This command slows down the entire transcoding process significantly:

`ffmpeg -i /root/1ea4267d-37e3-4d40-bb92-124dd8faf1a6-1440-fragmented.mp4 -y -acodec aac -vcodec libsvtav1 -threads 24 -f mp4 -movflags faststart -max_muxing_queue_size 1024 -map_metadata -1 -pix_fmt yuv420p -b:a 192k -ac 2 -vf scale=w=-2:h=1080 -crf 42 -preset 7 -g 999 -hls_time 4 -hls_list_size 0 -hls_playlist_type vod -hls_segment_filename /root/1080-fragmented.mp4 -hls_segment_type fmp4 -f hls -hls_flags single_file /root/1080.m3u8`

**Comment by emansom** [comment] 2022-09-12 20:02
Recently discovered ffmpeg also supports [transcoding to multiple resolutions at once](https://stackoverflow.com/a/71985380), this would possibly yield the lowest and most effective CPU utilization possible.

**Comment by JacksonChen666** [comment] 2022-09-12 20:55
ffmpeg's "trasncode to multiple resolutions at once" is actually just [multiple outputs](https://trac.ffmpeg.org/wiki/Creating%20multiple%20outputs) (i've encountered it before). however, it is not guaranteed to reduce transcoding time and could be potentially worse with it (see "Parallel Encoding" in the link page).

**Comment by Chocobozzz** [comment] 2022-09-13 07:39
Hello,

Is it a peertube bug? I think we always specify the appropriate thread option. Can you check the ffmpeg command ran by peertube?

**Comment by vid-bin** [comment] 2022-09-13 10:05
> Hello,
> 
> Is it a peertube bug? I think we always specify the appropriate thread option. Can you check the ffmpeg command ran by peertube?

These are the commands run by peertube. I just don't understand why the first transcode doesn't have the hls options and subsequent transcodes with the lower resolutions do.

**Comment by vid-bin** [comment] 2022-09-13 20:44
After further testing the CPU usage is only limited to 700% when using the peertube-created 1440-fragmented.mp4 to encode lower resolutions.

**Purposed solution:** Use the original video for all resolutions. Currently peertube does the following:

original resolution (1440p) -> encoded resolution  (1440p) -> lower resolution

**Change to:**

original resolution (1440p) -> encoded resolution (1440p) && original resolution (1440p) -> lower resolution (1080p, 720p, etc)

It's not limited to 1440p. It does the same thing if 1080p is the max resolution. It always encodes the highest first, then uses the encoded resolution for lower resolutions.

**Comment by Chocobozzz** [comment] 2022-09-14 07:20
Isn't related to your encoder? Why ffmpeg consumes less CPU depending on the input file?

**Comment by vid-bin** [comment] 2022-09-14 14:54
> Isn't related to your encoder? Why ffmpeg consumes less CPU depending on the input file?

@emansom Are you seeing the same thing on your end? You don't use svtav1 right?

**Comment by Chocobozzz** [comment] 2022-09-20 07:28
@vid-bin Why don't you consider that transcoding from fragmented mp4 file with a scale filter resulting in low CPU usage is not a bug? https://trac.ffmpeg.org/ticket/9923

**Comment by Chocobozzz** [comment] 2022-10-10 13:09
Closing as it seems to be a ffmpeg bug rather a peertube one

**Closed by Chocobozzz** 2022-10-10 13:09 UTC
Labels: Status: Waiting for answer
