### ISSUE TITLE
Custom landing page not working

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#4156] opened 2021-06-04 04:40 UTC
**Describe the current behavior**
Setting a custom landing page won't have any effect.

**Steps to reproduce:**

1. Visit https://peertube.heraut.eu/
2. See that the landing page is trending instead of recently added (which you can see in the config).

**Describe the expected behavior**
Landing page config should be respected.

* PeerTube instance:
  * URL: https://peertube.heraut.eu/
  * version: 3.2.1

* Browser name, version and platforms on which you could reproduce the bug:
Chrome, latest

**Comment by Chocobozzz** [comment] 2021-06-04 06:28
This is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/504 fixed by https://github.com/Chocobozzz/PeerTube/commit/aea0b0e7cde7495e60fe07b4444067f53d35ce3f

**Closed by Chocobozzz** 2021-06-04 06:28 UTC
