### ISSUE TITLE
Playlists should ignore/give the possibility to reset remembered positions in videos

### ISSUE THREAD

**Issue by 6543** [Chocobozzz/PeerTube#2167] opened 2019-10-05 18:53 UTC
PeerTube version: 1.4.1
Client OS: Linux
Client Browser: Firefox 69.0.1

## Description
The Videoplayer remeber the position the player had stoped last - wich is nice -
but in combination with a plaxlist this can end in a bad play experience

## Reproduce
 1. create a Playlist
 2. add 3 Videos
 3. play the second video until it has some secounds (10-20) to the end left
 4. play the first video until the end
 -> now the secound video is played next but only for 10-20sec and then the third video starts - there is no reset :(

I would say priorety is low but it should be fixed in some time  ...

**Comment by robinkooli** [comment] 2019-10-06 17:13
Remembered position for music is also bad experience imo. YouTube doesn't save position on music videos.

**Comment by 6543** [comment] 2019-10-06 17:46
Sometimes it is usefull

**Comment by 6543** [comment] 2019-10-06 17:47
-> enable/disable in settings?

But THIS is a other issue .. @robinkooli

**Comment by JohnXLivingston** [comment] 2019-10-07 09:03
I think this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/1889

**Comment by rigelk** [comment] 2019-10-07 11:48
@JohnXLivingston indeed! Thanks for spotting it.

**Closed by rigelk** 2019-10-07 11:48 UTC
Labels: Component: Playlist, Type: Enhancement :sparkles:
