### ISSUE TITLE
Why is PeerTube never born?

### ISSUE THREAD

**Issue by kiridu1988** [Chocobozzz/PeerTube#1846] opened 2019-05-25 08:47 UTC
You killed the project by stupid total decentralization.
It was necessary to make one big single service, like on YouTube.
A waste of time.

Why do you call this an alternative for Youtube?
This is not an alternative to Youtube!

**Comment by Aluriak** [comment] 2019-05-25 09:13
> stupid total decentralization

What is the alternative ? You are speaking to peoples interested by ideas.

> It was necessary to make one big single service, like on YouTube.

So… To solve the youtube problems, we should reproduce a copy of youtube suffering from the same problems ? Bold move.

> A waste of time.

The single fact that peoples are using PeerTube is telling the opposite.

> Why do you call this an alternative for Youtube?

Because it is. At least according to [this dictionnary](https://en.wiktionary.org/wiki/alternative#Adjective), [this one](https://dictionary.cambridge.org/dictionary/english/alternative), or [this thesaurus](https://www.thesaurus.com/browse/alternative).

> This is not an alternative to Youtube!

I wonder what are you trying to achieve here ? To only assert that last claim without evidence, or to convinced everyone involved here by your aggressive comment ?

Also, we're not on a social media here. Please don't bother working peoples with low-effort facebook-like posting. Thank you.

**Comment by Aluriak** [comment] 2019-05-25 09:16
Whoever working here should probably close this issue (and label it with something like «low-effort facebook post», that would be joyous).

**Comment by Zig-03** [comment] 2019-05-25 09:38
You should probably look into bitchute. It is centralized (and proprietary) - just like you want it to be.

**Closed** 2019-05-25 10:11 UTC
