### ISSUE TITLE
Issue with comments / answers to comments tree when interacting with mastodon 

### ISSUE THREAD

**Issue by PhieF** [Chocobozzz/PeerTube#367] opened 2018-03-20 17:03 UTC
* **PeerTube version or commit:** v1.0.0-beta.1
* **Browser name/version:**  firefox 59
* **NodeJS version:** v8.10.0
* **PostgreSQL version:** 9.5.12

two bugs that seem to be linked : 
user A on peertube
user B and C on Mastodon

1 st:
User B comments User A's video
C comments B

A answers to B
C also receive the answer on mastodon
So here is what we have on peertube

|A
     |B
          |C
          |A

on mastodon

|A
     |B
          |C
              |A

if user C answers to A, peertube's tree is modified and becomes like mastodon's tree 

before answering : 
https://framapic.org/MUUJmQNNg6nx/z51qrcvR0wsH.png

after answering: 
https://framapic.org/vgDIcLRCIjQn/TPm156qCtBqa.png

thanks Marsxyz 🇧🇪@marsxyz@maly.io for noticing the issue

**Comment by Chocobozzz** [comment] 2018-03-21 10:32
You first bug concerning the order of the answers is an intended behaviour: we want your answer just at the bottom of the comment you respond to.

For your second bug nice catch! It should be fixed: https://github.com/Chocobozzz/PeerTube/commit/a3cffab42d78560a7db8ad1df14680be5b55277f

**Closed by Chocobozzz** 2018-03-21 10:32 UTC
Labels: Status: In Progress, Type: Bug
