### ISSUE TITLE
Feature - change mail for user root

### ISSUE THREAD

**Issue by EricThi** [Chocobozzz/PeerTube#1782] opened 2019-04-24 12:28 UTC
**What happened?**
Change mail adresse for user root

**Additional information**
* PeerTube version or URL:
Version 1.2.1
https://peertube.eric.ovh
* Browser name/version:
Firefox 67
* NodeJS version:
node -v
v11.13.0

npm -v
6.9.0

Thank you, Eric

**Comment by Chocobozzz** [comment] 2019-04-24 12:29
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/1393

**Closed by Chocobozzz** 2019-04-24 12:29 UTC

**Comment by EricThi** [comment] 2019-04-24 12:31
Hum sorry, i miss to check for simple user... my bad
