### ISSUE TITLE
Delete User Causing error on Moderation Reports Page.

### ISSUE THREAD

**Issue by siberkolosis** [Chocobozzz/PeerTube#4729] opened 2022-01-20 00:17 UTC
**Describe the current behavior**
on moderation reports page, crashed and table row stop, action button not showing if any deleted reporter account.

**Steps to reproduce:**

1. setup peertube
2. create report, and delete reporter account from admin
3. open moderation reports page. 

**Describe the expected behavior**

**Additional information**
deleting report manualy from database,
* PeerTube instance:
  * URL:
  * version: 4.0.0
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
This error log error looping forever. to reproduce just delete reporter account. yes its happen when delete reporter account.

ERROR TypeError: c.reporterAccount is null
isLocalAbuse abuse-list-table.component.ts:173
x abuse-list-table.component.html:124
Angular 46
RxJS 6
Angular 19
addEventListeners websocket.js:76
doOpen websocket.js:61
open transport.js:44
probe socket.js:270
onOpen socket.js:290
onHandshake socket.js:344
onPacket socket.js:308
emit index.js:143
onPacket transport.js:100
onData polling.js:83
onData polling.js:86
emit index.js:143
onData polling-xhr.js:188
onLoad polling-xhr.js:229
onreadystatechange polling-xhr.js:147
Angular 16
create polling-xhr.js:143
Ge polling-xhr.js:101
request polling-xhr.js:53
doPoll polling-xhr.js:78
poll polling.js:63
doOpen polling.js:23
open transport.js:44
open socket.js:159
Ge socket.js:100
open manager.js:108
Yt manager.js:39
fn index.js:29
initNotificationSocket peertube-socket.service.ts:55
rt tslib.es6.js:73
Angular 4
core.mjs:6495:12
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment] 2022-01-20 07:40
Hi,

I'm sorry but I can't reproduce. Could you paste web browser console logs please?

**Comment by siberkolosis** [comment] 2022-01-20 08:26
this error log error looping forever.  to reproduce just delete reporter account.

ERROR TypeError: c.reporterAccount is null
    isLocalAbuse abuse-list-table.component.ts:173
    x abuse-list-table.component.html:124
    Angular 46
    RxJS 6
    Angular 19
    addEventListeners websocket.js:76
    doOpen websocket.js:61
    open transport.js:44
    probe socket.js:270
    onOpen socket.js:290
    onHandshake socket.js:344
    onPacket socket.js:308
    emit index.js:143
    onPacket transport.js:100
    onData polling.js:83
    onData polling.js:86
    emit index.js:143
    onData polling-xhr.js:188
    onLoad polling-xhr.js:229
    onreadystatechange polling-xhr.js:147
    Angular 16
    create polling-xhr.js:143
    Ge polling-xhr.js:101
    request polling-xhr.js:53
    doPoll polling-xhr.js:78
    poll polling.js:63
    doOpen polling.js:23
    open transport.js:44
    open socket.js:159
    Ge socket.js:100
    open manager.js:108
    Yt manager.js:39
    fn index.js:29
    initNotificationSocket peertube-socket.service.ts:55
    rt tslib.es6.js:73
    Angular 4
core.mjs:6495:12

**Comment by Chocobozzz** [comment] 2022-01-20 09:55
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/82b9a1005cd5f5d3c338270839a24f217594b35d

**Closed by Chocobozzz** 2022-01-20 09:55 UTC
Labels: Type: Bug :bug:, Component: Moderation :godmode:
