### ISSUE TITLE
Data loss when a transcode completes incorrectly

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#3666] opened 2021-01-29 17:56 UTC
**Describe the current behavior**

The original media files are always deleted, which can cause data loss if a transcode returns successfully but produces incorrect or truncated output.

**Steps to reproduce:**

1. Update ffmpeg to latest from git
2. Upload video
3. Notice broken HLS
4. Try to re-transcode
5. Re-transcode fails for some reason and leaves truncated files
6. Video is now deleted, and sysadmin has to restore from zfs snapshots.

**Describe the expected behavior**

I really would expect to have a way to re-run transcodes losslessly, by keeping the original master media files around.

**Additional information**

* PeerTube instance:
  * URL: diode.zone
  * version: 3.0.1
  * NodeJS version:
  * Ffmpeg version: git 

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment] 2021-02-01 07:43
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/733

**Closed by Chocobozzz** 2021-02-01 07:43 UTC

**Comment by scanlime** [comment] 2021-02-01 15:33
Is it a duplicate though? I'm talking about data loss during the initial transcode.

**Comment by Chocobozzz** [comment] 2021-02-02 10:42
>  I'm talking about data loss during the initial transcode.

It will be fixed by https://github.com/Chocobozzz/PeerTube/issues/3668
