### ISSUE TITLE
peertube still transcodes to 1080p and publishes the 1080p version to activitypub even when only the 480p box is checked

### ISSUE THREAD

**Issue by goatmeal01** [Chocobozzz/PeerTube#4025] opened 2021-04-30 01:47 UTC
**Describe the current behavior**

I have my instance set to transcode HLS P2P with only the 480p box checked. When I upload or import and the resolution is higher than that, it will transcode scaled to 480p but it will keep the higher resolution as well. Then it's going to publish only the higher resolution video to activitypub.

**Steps to reproduce:**

1. go to VOD Transcoding page and ensure that under Output formats only HLS P2P and 480p boxes are checked, and that transcoding is enabled
2. upload a video in 1080p resolution
3. observe the video that got sent out to the fediverse

**Describe the expected behavior**

Instead I want to upload something in say 1080p, then I want it to transcode to HLS P2P 480p, delete the 1080p version because the 1080p box was not checked, and when all of that is finished just publish the 480p version to activitypub. Until this is implemented I am stuck with running ffmpeg on my local machine to scale the video before uploading to peertube, and I have to download the video on my local machine as well.

**Additional information**

* PeerTube instance:
  * version: 3.1.0

**Comment by kimsible** [comment] 2021-04-30 15:58
I think it's because PeerTube keeps the source file if no transcoding is done in the resolution source.

**Comment by SimplyCorbett** [comment] 2021-04-30 16:54
> 
> 
> I think it's because PeerTube keeps the source file if no transcoding is done in the resolution source.

No, it does transcode the original resolution source even if 480p is selected. OP is correct on the problem.

**Comment by Chocobozzz** [comment] 2021-05-03 06:42
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/1030

**Closed by Chocobozzz** 2021-05-03 06:42 UTC
