### ISSUE TITLE
Improve video uploading reliability

### ISSUE THREAD

**Issue by AbakumovAlexandr** [Chocobozzz/PeerTube#3739] opened 2021-02-15 05:25 UTC
Video uploading is a nightmare at the moment.

I have average Internet connection able to handle upload speeds at 1-2Mbps and tried around 5 various PeerTube instances and was unable to upload a 90Mb video on any of them including top ones like PeerTube UK. My best result after like 15 attempts was 90% ended up with either 'Unknown error' or 'Server error. Try later'.

I can't even think of how to upload a video with a size of a few Gbytes with the current JS uploader.

It should at least allow uploading in chunks to be able to continue keeping progress between retries.

Let me know if you need some debugging info to track down the issue.

**Comment by Chocobozzz** [comment] 2021-02-15 09:09
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/324

**Closed by Chocobozzz** 2021-02-15 09:09 UTC
