### ISSUE TITLE
Co-author video channel

### ISSUE THREAD

**Issue by kimsible** [Chocobozzz/PeerTube#3335] opened 2020-11-20 13:17 UTC
Adding co-author to a video channel would be a great feature.
This co-author could be able to upload on the owner channel.

I don't think how it is technically possible but we need to think about : 

- Owner's video channel rights on videos published by co-authors ;
- Co-authors rights on other videos of the common channel ;
- Displaying co-authors on every view.

Do you have any idea ?

**Comment by test2a** [comment] 2020-11-20 13:44
We should implement permissions logic. This would be beneficial for all sorts of cases like this.

In moderation, you could have dozens of comment janitors who could moderate comments only. Same as many other roles that are present in various services. Some users could moderate video reports. Some would get permission to ban users. Some could be allowed to modify the federation.. there is a lot of things that a moderator can do today but because this power is sudo all, many administrators fear abuse. Giving certain permissions only would be helpful in this case. 

In the present case, a channel owner could give "edit" permission or "upload" or "delete"  to someone and this issue would be solved. This way if I give "full" permissions to someone and have them delete me, that should do the trick.  The display part would be easily solvable later.

Just my two cents.

**Comment by Chocobozzz** [comment] 2020-11-20 13:49
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/699

**Closed by Chocobozzz** 2020-11-20 13:49 UTC
Labels: Type: Duplicate :loop:

**Comment by kimsible** [comment] 2020-11-20 15:04
Ok my bad !
