### ISSUE TITLE
Since 6.3.0 release, settings menu on viewer is broken on mobile

### ISSUE THREAD

**Issue by Agorise** [Chocobozzz/PeerTube#6614] opened 2024-09-23 21:50 UTC
### Describe the current behavior

Since the 6.3.0 update, the video settings have stopped working on mobile.  The settings menu will pop up for a fraction of a second and then it disappears. 
 
You can't adjust resolution, video speed, etc. anymore.  I tested multiple browsers and it's definitely broken now. 

### Steps to reproduce

1. go to the watch page of any video and click on the settings icon in the viewer 

### Describe the expected behavior

The settings menu will pop up for a fraction of a second and then it disappears.

### Additional information

* PeerTube instance: 
  * URL: https://vigilante.tv 
  * Version: 6.3.0 
  * NodeJS version: node 18.20.4  npm 10.7.0 
  * Ffmpeg version: 5.1.6 

* Browser name, version and platforms on which you could reproduce the bug: android with both chrome and brave browsers. also tested on latest version of GrapheneOS and tested both Vanadium & Firefox.

**Comment by Chocobozzz** [comment] 2024-09-24 06:30
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/6593

**Closed by Chocobozzz** 2024-09-24 06:30 UTC
