### ISSUE TITLE
Auto Deleting a video after it expires

### ISSUE THREAD

**Issue by maxdrash** [Chocobozzz/PeerTube#1723] opened 2019-03-19 21:52 UTC
Users request.
To have the possibility to set an expiration on a video through either user interface and the API.

Example: auto deleting after hours, days or date.

Thank you for this project :+1: 

**Additional information**
* PeerTube version or URL: v1.2.1

**Comment by Chocobozzz** [comment] 2019-03-20 07:38
Thanks for this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/1289

**Closed by Chocobozzz** 2019-03-20 07:38 UTC
