### ISSUE TITLE
Add embedded videos and YouTube channels without uploading to the server

### ISSUE THREAD

**Issue by volanar** [Chocobozzz/PeerTube#4325] opened 2021-08-14 21:15 UTC
To upload a lot of videos to your server, you need to have unlimited disk space. Not all website owners are millionaires. I suggest giving the owners of the platform on peertube a choice: upload embedded videos without uploading to their server or upload to their server. Youtube encourages embedding videos and according to its policy, you do not need to ask permission to embed such videos. This way we save server resources and disk space and have the opportunity to create thematic sites with an unlimited number of videos. For example, d.tube (https://github.com/dtube/dtube) allows you to do this. Here's what they write: 
"Add a video from a third party url
Third party video providers is a great way to ensure that your video is watchable at highest qualities. It's never a bad thing to add a third party video source.
If you want to share a non-original video on DTube, this is the recommended way, as it will reward the original creator registered on these third party websites.
If you create original content, these solutions should not be your first choice as these platforms will most often force you to give them your personal data and/or put ads on top of your videos. Censorship or country restriction can also hurt the availability of your videos."

**Comment by Chocobozzz** [comment] 2021-08-18 09:26
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/1045

**Closed by Chocobozzz** 2021-08-18 09:26 UTC

**Comment by volanar** [comment] 2021-08-18 10:28
Unfortunately, the problem has not been solved in 3 years. For the initial promotion of your platform, this is the only way out. Otherwise, 99 % of peertube instances will remain with 100-1000 videos until the owners get tired of paying for disk space
