### ISSUE TITLE
activitypub-refresher SequelizeDatabaseError: value too long for type character varying(255)

### ISSUE THREAD

**Issue by Tr4sK** [Chocobozzz/PeerTube#1796] opened 2019-05-02 15:16 UTC
Hi
On my instance, I’m having a lot of failed job from 'activitypub-refresher'
Here is some failing account:
```
{
  "type": "actor",
  "url": "https://video.tedomum.net/accounts/nofear75"
}
```
```
{
  "type": "actor",
  "url": "https://peertube.social/accounts/fribbledom"
}
```
```
{
  "type": "actor",
  "url": "https://www.yiny.org/accounts/shore"
}
```

The full message here:

```
SequelizeDatabaseError: value too long for type character varying(255)
    at Query.formatError (/var/www/peertube/versions/peertube-v1.2.1/node_modules/sequelize/lib/dialects/postgres/query.js:363:16)
    at query.catch.err (/var/www/peertube/versions/peertube-v1.2.1/node_modules/sequelize/lib/dialects/postgres/query.js:86:18)
    at tryCatcher (/var/www/peertube/versions/peertube-v1.2.1/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/peertube/versions/peertube-v1.2.1/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/www/peertube/versions/peertube-v1.2.1/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/www/peertube/versions/peertube-v1.2.1/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/www/peertube/versions/peertube-v1.2.1/node_modules/bluebird/js/release/promise.js:690:18)
    at _drainQueueStep (/var/www/peertube/versions/peertube-v1.2.1/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/var/www/peertube/versions/peertube-v1.2.1/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/var/www/peertube/versions/peertube-v1.2.1/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/var/www/peertube/versions/peertube-v1.2.1/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
```

**Additional information**
* PeerTube version or URL: https://tube.tr4sk.me
* NodeJS version: v8.15.1

My guess is that the description field is not properly managed on my instance:

Original: https://video.tedomum.net/accounts/nofear75/about
What I see from my instance: https://tube.tr4sk.me/accounts/nofear75@video.tedomum.net/about

**Comment by tcitworld** [comment] 2019-05-02 15:24
Closed as duplicate of #1792

**Closed by tcitworld** 2019-05-02 15:24 UTC
