### ISSUE TITLE
Change text to "remote susbcribe with a federated account", not just Mastodon.

### ISSUE THREAD

**Issue by tiotrom** [Chocobozzz/PeerTube#3752] opened 2021-02-18 13:30 UTC
I think it is a bit confusing to say "Subscribe with a Mastodon account" when in fact it works as well with a Friendica or Pleroma account, and perhaps other too. Should change the description into "Subscribe with a federated account (ex: Mastodon, Friendica, etc.)." I know that when you click the little question mare you get more of an explanation, but the main text should be more general and not specific to mastodon. 

When I first saw it, I was like "bummer...I would like to subscribe with the awesome Friendica" :D - only to give it a shot and it worked perfectly fine.

So, my suggestion is to change the text from "Subscribe with a Mastodon account" to "Subscribe with a federated account" and when users click the little question mark, to provide examples of such accounts.

Cheers!

**Comment by Chocobozzz** [comment] 2021-02-18 13:47
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/2888

**Closed by Chocobozzz** 2021-02-18 13:47 UTC
