### ISSUE TITLE
RSS Media Feed

### ISSUE THREAD

**Issue by mmmccain** [Chocobozzz/PeerTube#4743] opened 2022-01-23 00:10 UTC
I have attempted to use many RSS aggregators and players with the RSS feed from a channel. It will find and display the feed, it will not play the video (or audio form the video). Below is an example. It actually acts exactly the same as with [Presto Player](https://github.com/Chocobozzz/PeerTube/issues/4739), if that helps. 

![image](https://user-images.githubusercontent.com/97072059/150659543-289467e6-b0ba-42ed-af30-3cacc9157c42.png)

**Additional information**

* PeerTube instance:
  * URL: ap.okyrios.org
  * version: 4.0

**Comment by Chocobozzz** [comment] 2022-01-31 09:10
Hello,

Could you contact them to see what peertube should provide so the video can be played?

**Comment by Chocobozzz** [comment] 2022-02-07 08:45
I think this issue is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/4052

**Closed by Chocobozzz** 2022-02-07 08:45 UTC
Labels: Type: Enhancement :sparkles:, Component: Subscriptions, Status: Waiting for answer
