### ISSUE TITLE
Upload speed always stay to 0

### ISSUE THREAD

**Issue by Jorropo** [Chocobozzz/PeerTube#738] opened 2018-06-27 21:50 UTC
* **PeerTube version or URL:**
[peertube.video](https://peertube.video/)
[peertube.xyz](https://peertube.xyz/)
And surely all node
* **Browser name/version:**
Ubuntu 17.10 Firefox 60.0.2 (64 bits)

* **What is the expected behaviour?**
The speed of upload printed in the video is the total of speed used be seeding.
* **What do you see instead?**
It stay to 0.

I'm totaly sure that isn't working, cause I'm on old wifi G (limited to 2MB/s), I start viewing a video, then I pause the video and go make an other think, then 30 min later when I come back the video was fully downloaded in firefox and I choose to download it, for download I use WebTorrent desktop cause it is an hybrid node of webtorrent and bittorrent, and my download speed up to 16 MB/s, but in firefox upload stay to 0.
This is impossible that this speed came from outside (2MB/s max) so it came from my browser but in the browser the upload speed stay to 0MB/s.

**Comment by Chocobozzz** [comment] 2018-07-09 14:30
I'm sorry I can't reproduce. I tested and it worked well on my side.

Is there anyone who reproduced this issue?

**Comment by Chocobozzz** [comment] 2018-07-16 14:42
Closing, feel free to comment if somebody can reproduce this bug.

**Closed by Chocobozzz** 2018-07-16 14:42 UTC
Labels: Status: To Reproduce
