### ISSUE TITLE
Rumble channel syncs failing now after upgrade to v6.0.3

### ISSUE THREAD

**Issue by Mike35538** [Chocobozzz/PeerTube#6194] opened 2024-01-26 17:31 UTC
### Describe the current behavior

It seems like video channel syncs are failing for Rumble channels since I upgraded to v6.0.3. All YouTube channel syncs work fine still, but every Rumble channel sync fails and can no longer sync and import new videos from the Rumble channels. You can add a Rumble video import manually through "Import with URL" and it works great, but Rumble channel sync imports fail every time.

Here is an example of the error from one of the failed syncs (I changed the channel name for privacy).

error[1/26/2024, 9:39:06 AM] Failed to import https://rumble.com/user/channelname in channel PeerTube Channel
{
  "err": {
    "stack": "Error: YoutubeDL could not get list info from https://rumble.com/user/channelname: undefined\n    at YoutubeDLWrapper.getInfoForListImport (file:///var/www/peertube/versions/peertube-v6.0.3/dist/core/helpers/youtube-dl/youtube-dl-wrapper.js:44:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async synchronizeChannel (file:///var/www/peertube/versions/peertube-v6.0.3/dist/core/lib/sync-channel.js:20:28)\n    at async VideoChannelSyncLatestScheduler.internalExecute (file:///var/www/peertube/versions/peertube-v6.0.3/dist/core/lib/schedulers/video-channel-sync-latest-scheduler.js:24:13)\n    at async VideoChannelSyncLatestScheduler.execute (file:///var/www/peertube/versions/peertube-v6.0.3/dist/core/lib/schedulers/abstract-scheduler.js:19:13)",
    "message": "YoutubeDL could not get list info from https://rumble.com/user/channelname: undefined"
  }

### Steps to reproduce

1. Add a rumble.com channel to My synchronizations. Wait for it to attempt syncing.
2. Sync fails

### Additional information

* PeerTube instance:
  * Version: 6.0.3
  * NodeJS version: v18.11.0
  * Ffmpeg version: 4.3.6-0+debllul

**Comment by ROBERT-MCDOWELL** [comment] 2024-01-27 01:51
yup, I just noticed the same here ;(

**Comment by Chocobozzz** [comment] 2024-02-05 10:51
Hello,

Please check on your server `yt-dlp` correctly works using the rumble URL (binary should be in `var/www/peertube/storage/bin/yt-dlp`)

**Comment by ROBERT-MCDOWELL** [comment] 2024-02-05 12:32
I have a server in France, maybe that's why :-\
RumbleChannel] Extracting URL: https://rumble.com/user/AmazingPolly
[download] Downloading playlist: AmazingPolly
[RumbleChannel] AmazingPolly: Downloading page 1
ERROR: Unable to download webpage: HTTP Error 451: Unavailable For Legal Reasons (caused by <HTTPError 451: Unavailable For Legal Reasons>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling 

my other server in finland gives
./yt-dlp https://rumble.com/user/AmazingPolly
[RumbleChannel] Extracting URL: https://rumble.com/user/AmazingPolly
[download] Downloading playlist: AmazingPolly
[RumbleChannel] AmazingPolly: Downloading page 1
[RumbleChannel] AmazingPolly: Downloading page 2
[RumbleChannel] AmazingPolly: Downloading page 3
[RumbleChannel] AmazingPolly: Downloading page 4
[RumbleChannel] AmazingPolly: Downloading page 5
[RumbleChannel] AmazingPolly: Downloading page 6
[RumbleChannel] AmazingPolly: Downloading page 7
[RumbleChannel] AmazingPolly: Downloading page 8
[RumbleChannel] Playlist AmazingPolly: Downloading 0 items
[download] Finished downloading playlist: AmazingPolly

**Comment by Chocobozzz** [comment] 2024-02-05 13:03
Unfortunately we can't do anything on peertube side, as Rumble blocks french IPs.

**Comment by ROBERT-MCDOWELL** [comment] 2024-02-05 13:05
@Chocobozzz 
wait before to close the issue, @Mike35538 issue is something else....

**Comment by Mike35538** [comment] 2024-02-06 06:56
Hi,
I'm not sure what you mean "Please check on your server yt-dlp correctly works using the rumble URL" or how to do that. But my server is in the USA and I have always been able to sync Rumble channels until recent. I can import a video URL such as https://rumble.com/v4amyju-vision-offering-2024-sunday-march-3rd.html without any issues (Publish button > Import with URL). But syncing a channel such as https://rumble.com/user/VerityBaptistChurch always produces an error now (Videos > My Imports > My synchronizations > Add synchronization). Does PeerTube use a new version of yt-dlp? I saw this over at yt-dlp but don't know if it is the related https://github.com/yt-dlp/yt-dlp/issues/8782.
Thanks

**Comment by ROBERT-MCDOWELL** [comment] 2024-02-06 15:19
@Chocobozzz I confirm that the issue comes from the semi-colon ":" in the URL, 
I have some channel sync from odysee not containing ":" and it works. Rather, the other containing ":" does not sync and shows "error"

**Comment by ROBERT-MCDOWELL** [comment] 2024-02-09 00:07
@Umplo no I talk about a colon in the URI like https://www.rumble.com/xxxxxxx_:4

**Comment by Chocobozzz** [comment] 2024-02-15 08:12
Hi,

I can confirm it is a `yt-dlp` issue that is already fixed in nightly builds but not yet released. PeerTube automatically update yt-dlp so when you'll get the new version when it will be released.

**Closed by Chocobozzz** 2024-02-15 08:12 UTC
Labels: Status: Waiting for answer
