### ISSUE TITLE
searching for video URL fails if it has ?start=Xs in the end

### ISSUE THREAD

**Issue by deckname** [Chocobozzz/PeerTube#4019] opened 2021-04-27 23:16 UTC
**Describe the current behavior**
When I search for a link of a video, that is hosted on another instance, with the ?start=Xs in the end, then it says "No results found", if I search for the same link without the ?start=Xs part the same instance does give a result. 
**Steps to reproduce:**

1.take a video
2.search for the URL on an instance
3.remove everything after ?

**Describe the expected behavior**
I would expect to either not have any results for both or give a result for both

* PeerTube instance: 
  * URL: https://peertube.social
  * version: 3.0.1

* Browser name, version and platforms on which you could reproduce the bug: Firefox

**Comment by Chocobozzz** [comment] 2021-04-28 06:46
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/1768

**Closed by Chocobozzz** 2021-04-28 06:46 UTC
