### ISSUE TITLE
Allow video uploaders to see all features of a given video.

### ISSUE THREAD

**Issue by therahedwig** [Chocobozzz/PeerTube#1718] opened 2019-03-14 13:14 UTC
It would be great if a video uploader could see all the available features on a video they uploaded. For example:

* at which resolutions it is available
* what formats/codecs
* audio
* subtitles, chapter selection
* whatever other features a given video can have.

This was inspired by me uploading a HDR 'video' yesterday to youtube, and having no ability to see whether youtube was considering it a 'HDR video' as my device isn't HDR enabled. (Youtube does allow showing which version is being streamed to your device, but, you know, youtube wasn't serving HDR to me, so...)

I think this would help a lot, not just with my specific usecase, but also for cases like video creators to understand peertube is still transcoding(it'd be super cool if peertube could give also some feedback on this), or to double check whether a feature was or was not enabled.

**Comment by Jorropo** [comment] 2019-03-19 17:54
All these data are pulic, I think that a good idea but we may can make it accessible to everyone like stats for nerd (allready proposed in an other issue but I don't find it).

**Comment by Chocobozzz** [comment] 2019-04-01 13:27
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/479

**Closed by Chocobozzz** 2019-04-01 13:27 UTC
Labels: Type: Duplicate :loop:
