### ISSUE TITLE
Add thumbnails for scrubbing through video

### ISSUE THREAD

**Issue by Findus23** [Chocobozzz/PeerTube#2190] opened 2019-10-21 09:56 UTC
This definitely is a larger project and won't be tackled soon, but no one suggested it yet and I think it would be really cool, so here it is:

On media.ccc.de ([example video](https://media.ccc.de/v/ds19-10456-qubes_os_-_eine_einfuhrung)) I can quickly look through a video and find a specific second by hovering over the timebar and looking through the thumbnails at that time. (Most video platforms have such a feature)

It would be amazing if Peertube would also get such a feature as it would make searching in a long video much easier.

About the implementation:

It seems like media.ccc.de generates a list of images than themselves have 11x6 small thumbnails with a total size of around 1000x1000px.
https://static.media.ccc.de/media/events/datenspuren/2019/10456-hd.thumbnails-09.jpg

In addition (which I don't know any other video site that does this) the timeline itself consists of a list of 1px wide frames for every part of the video:
https://static.media.ccc.de/media/events/datenspuren/2019/10456-hd.timeline.jpg

media.ccc.de is open source (https://github.com/voc/voctoweb), so maybe the implementation can be compare with them

**Comment by Chocobozzz** [comment] 2019-10-21 09:57
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/537

**Closed by Chocobozzz** 2019-10-21 09:57 UTC

**Comment by Findus23** [comment] 2019-10-21 10:00
Ah, I knew I was using the wrong keywords to search for it.
Thanks for finding it.
