### ISSUE TITLE
Picture-in-Picture support

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#3961] opened 2021-04-13 19:36 UTC
**Describe the problem to be solved**
Add Picture-in-Picture button to videojs player. See demo of PiP here https://developer.mozilla.org/en-US/docs/Web/API/Picture-in-Picture_API#examples

**Describe the solution you would like:**
Set [pictureInPictureToggle: true](https://docs.videojs.com/tutorial-components.html). Currently the video stops playing when leaving the page, but that may be caused by the p2p-media-loader?

**Comment by Chocobozzz** [comment] 2021-04-14 07:05
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/1211

**Closed by Chocobozzz** 2021-04-14 07:05 UTC
Labels: Component: Player :play_or_pause_button:, Type: Enhancement :sparkles:
