### ISSUE TITLE
Subscribe my instance to a user/channel on another instance, rather than the whole instance itself

### ISSUE THREAD

**Issue by TILvids** [Chocobozzz/PeerTube#3364] opened 2020-11-26 02:07 UTC
**Describe the problem to be solved**

As an instance admin, I would like to be able to follow _channels_ on other instance, not just whole instances or nothing. There are oftentimes instances that have content I don't want to show up on my own instance, but I would like an individual channel(s) from that instance to show up on my own instance.

**Describe the solution you would like:**

In the "Federation >> Instance you follow" section, I should be able to add a user from another instance, not just the domain. Or subscribe via their RSS or something.

**Describe alternatives you have considered**  

I'm an admin for tilvids.com and I've chatted with users on other instances that are happy with having their home-base account on another instance, but would like their content to show up on mine as well. We cannot figure out how to do this, at present.

**Comment by test2a** [comment] 2020-11-26 04:24
So federate a single channel from a remote instance instead of the entire remote instance.

**Comment by test2a** [comment] 2020-11-26 06:28
In the same vein, can I as a user in an instance, like ABC follow an entire instance without having to have to federate and all that? Like I am on ABC and want to follow "all" channels of tilvids, like the public ones. Manually doing this would be time consuming and  new channels manually added.

**Comment by Chocobozzz** [comment] 2020-11-26 07:25
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/1604

**Closed by Chocobozzz** 2020-11-26 07:25 UTC
