### ISSUE TITLE
Html title is not localized

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#2032] opened 2019-08-15 13:05 UTC
**What happened?**
The html title content is in english, but my account is in french.
For example, if I am on the «Récemment ajoutées» page, the title in my browser tabs is «Recently added videos - ...»

**What do you expect to happen instead?**
The page title should be in the user's language.

**Additional information**
* PeerTube version or URL: 1.4.0-rc1
* Browser name/version: Firefox

**Comment by JohnXLivingston** [comment] 2019-08-15 13:06
And, another point : in 1.4.0-rc1, the «overview» page was renamed «discover». But the page title is still «Videos overview».

**Comment by robinkooli** [comment] 2019-08-15 13:07
Also it says overview on keyboard shortcuts list.

**Comment by AutomCoding** [comment] 2019-08-16 17:34
This is a duplicate of #793.

**Closed** 2019-08-22 07:50 UTC
