### ISSUE TITLE
Share seeding load between servers

### ISSUE THREAD

**Issue by LeoTindall** [Chocobozzz/PeerTube#459] opened 2018-04-02 16:53 UTC
I would really like to be able to allocate a portion of my disk space and bandwidth to help seed via Webseed videos from other instances.

For instance, I would like to have a ~10GB "cache" where videos from other instances watched by people on vid.leotindall.com would get downloaded by my and then seeded to everyone watching it.

I feel like this would really improve the usability and diversity in the Fediverse; for instance it would (partially) solve the problem of slow PeerTube instances slowing down the network, because their work could be shared by other servers.

In addition, it would make setting up a CDN trivial, since you could just make a number of instances with no local videos and a huge cache.

**Comment by rigelk** [comment] 2018-04-02 18:32
Indeed :) but it's a duplicate of #123. Please contribute on that issue.

**Closed by rigelk** 2018-04-02 18:32 UTC
