### ISSUE TITLE
MKV and .ass subtitles.

### ISSUE THREAD

**Issue by fufik** [Chocobozzz/PeerTube#2284] opened 2019-11-24 14:06 UTC
I upload a MKV container with a video subtitled in multiple languages on a PeerTube 2.0 instance and I can't turn them on. Ones I use are in .ass format, what should I do to enable them for audience? They also include different fonts and positioning, is this all implemented in the current version?

**Comment by Nutomic** [comment] 2019-11-25 00:24
I dont think Peertube can extract subtitles from the video container. You probably have to upload them seperately.

**Comment by Chocobozzz** [comment] 2019-11-25 08:52
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/1226

**Closed by Chocobozzz** 2019-11-25 08:52 UTC
Labels: Type: Duplicate :loop:
