### ISSUE TITLE
Upvote comments

### ISSUE THREAD

**Issue by stemy2** [Chocobozzz/PeerTube#2449] opened 2020-02-03 14:04 UTC
Hello,

I'd like to let know to some comments authors that i like their comment, but there's no upvote feature.

**Comment by onlyjob** [comment] 2020-02-07 10:38
Upvote should be equally balanced by _downvote_. Implementing just one would be meaningless and unbalanced.

**Comment by DontUseGithub** [comment] 2020-02-07 10:46
I think we should have 3 possible options for these:

- upvote/downvote
- upvote only
- no voting

**Comment by onlyjob** [comment] 2020-02-07 11:58
No it should be either "no voting" or "upvote/downvote". Just upvote is annoying and outright wrong.

**Comment by rigelk** [comment] 2020-02-07 12:16
@onlyjob why? It works well enough on Mastodon and other social platforms.

**Comment by Aluriak** [comment] 2020-02-07 13:31
From my experience, many places allows only to «upvote». This replace the downvoting-to-hell hysteria by a sainer ignorance, and enables multiple viewpoints in the discussions despite the existence of a more popular one. And limits greatly the interest of using bots to ensure preponderance of a viewpoint.

The fact that social networks such as twitter don't have a negative feedback for tweets seems to indicate that i'm wrong.

________

Anyway, if upvote and downvote are allowed, i would also indicate *explicitly* the number of each, or a ratio. Having a comment with 10 upvotes is not the same thing as having a comment with a total score of 1, for 100 upvote and 99 downvotes.

Finally, because i don't like making choices for others, i would in fine advocate letting the video uploader to choose whether or not (1) comments are allowed and (2) if so, which voting system proposed by @DontUseGithub to apply.

**Comment by onlyjob** [comment] 2020-02-07 23:52
> why? It works well enough on Mastodon and other social platforms.

Because we should not limit range of emotions. Right/wrong, approve/disapprove, like/dislike, _True/False_ they are different sides of the same thing. Encouraging the good behavior is equally important to discouraging wrongdoing. If people can express appreciation then they should be able to express the opposite as well or we reduce conversation to kindergarten level where "everyone gets a participation award and nobody loses".
I strongly dislike that Mastodon and others made this mistake. IMHO it does not work well at all.

Also see what happens here in this very issue -- someone downvoted my earlier reply and it is beautiful because you can instantly see that they disagreed. What would our conversation be like if you only allow agreeing with expressed views? 

I want to see downvotes when someone is rude because merely upvoting nice comments somehow make it "OK" to write something terrible and receive no negative feedback whatsoever.

Frankly all of it should be obvious. Imagine a survey where for every question or statement the only allowed answer is "Yes" -- you will only ever see replies of those who's "in favour" when the opposite view is completely discarded because there is no way to express it.

**Comment by onlyjob** [comment] 2020-02-08 03:34
I've thought of another example: imagine post like "Let's make T-shirts illegal" and only upvotes under it (no dislikes). And some misguided soul thinking "Maybe it is not such a bad idea since so many people liked it."...

**Comment by onlyjob** [comment] 2020-02-08 04:31
Also note how the very guy who said that there should be no downvotes, disliked my comment.  
Isn't that hilarious? Whether he realises it or not, is seems that even he who spoke against dislikes/downvotes, actually appreciates the usefulness of downvoting. :)

**Comment by DontUseGithub** [comment] 2020-02-08 09:37
You're making some good points, especially this one:

> If people can express appreciation then they should be able to express the opposite as well or we reduce conversation to kindergarten level where "everyone gets a participation award and nobody loses".

Tactics like these created the snowflakes (aka people) we have today on 2020. I also dislike the fact that PeerTube has gone CoC way, which is another political tactic of teaching people to think in a certain way. 
In any case, I didn't say that

> Also note how the very guy who **said that there should be no downvotes**, disliked my comment.
> Isn't that hilarious?

Please read my comment again. I'll just add that I like @Aluriak's suggestion very much i.e. let the Peertubers decide which of these 3 options:
- upvote/downvote
- upvote only
- no voting
he'd prefer to have for a certain video of his or for all of them. Additionally instance admins should be able to decide on which of the 3 options should be available for Peertubers.

**Comment by Aluriak** [comment] 2020-02-08 12:34
@onlyjob i think i'm now convinced that the «upvote only» system is not desirable.

However, iif the choice is left per-video to the uploader, I would advocate for letting that option in the possible voting systems. Other peoples may not be convinced, and special needs may arise.


> Also note how the very guy who said that there should be no downvotes, disliked my comment.

To be honest, it was probably because your comment was just an assertion. Someone else had to explicitly ask «why» to transform that belief-battle initiation into a discussion, and only then you answered what should have been wrote in your first comment.

While i totally agree with @DontUseGithub concerning snowflakes (i didn't know that expression), we do not have to let bland assertions pollute a space dedicated to discussion.

**Comment by onlyjob** [comment] 2020-02-08 15:13
Yes, @DontUseGithub, valid correction. Thanks. Everything I wrote is regarding "upvote only" option which, I insist, should not exist. How about "downvote only"? That would be stupid, right? But how the opposite is not?

Imaging a question which you can answer by "Yes" or "No". Would answer make any sense if you you couldn't answer "No" because such option don't exist?
How about you answer all my questions with "Yes" (or staying quiet) because disagreements are not allowed?

Having one-sided option will encourage people to use it manipulatively. And how would you even justify existence of such option in first place? Just because Mastodon have it? They've made a mistake. Upvote-only anti-feature is one reason why I do not want to use Mastodon...

My first comment was not merely an assertion. I used the word "balance" to briefly explain my position but frankly even assertion should be enough. It is a very obvious matter to me.

**Comment by 3risian** [comment] 2020-02-13 23:56
Some thoughs on some of the arguments here (on both sides):

>why? It works well enough on Mastodon and other social platforms.

No voting works well enough on imageboards, where messages are judged by their contents. Up+Down works well enough on YouTube and is even used on PeerTube for the videos themselves! Surely that's as relevant.

>This replace the downvoting-to-hell hysteria by a sainer ignorance, and enables multiple viewpoints in the discussions despite the existence of a more popular one. And limits greatly the interest of using bots to ensure preponderance of a viewpoint.

This is a good point. While upvoting-to-heaven is still an issue, it would prevent burying from raids/bots/hiveminds. I also agree with their point about up/down transparency. I don't think it would limit the interest of bots though...

I think it is important to note how comments are ordered. If comments are ordered by score, a buried opinion gets partially censored. If comments are ordered by time, useful comments are likely to be buried.

Apart from this point, I believe an up/down system is preferable to an up only system. That said, the only reasons I would currently support comment voting at all is that:
* It allows helpful/important comments and critiques to rise while lowering low-effort comments.
* For a popular video, it is cleaner than 100 redundant replies saying 'lol' and 'yes!' and is easier to give (mild) feedback to comment. Maybe that is more of a YouTube cultural issue.

I suppose that outside of political content, this is less likely to be abused.

**Comment by 3risian** [comment] 2020-02-14 00:55
I had a think about this and I would like feedback on this idea:

 * Up and Down can be used. All comments display their up/down values
 * Instance owner chooses how comments are ranked (including `Up:Down ratio`, `Total Upvotes` and `Recent`), user preferences can override.

The reason I want the instance owner to choose is because default settings are going to apply to almost all its viewers.

The reason I think `Total Upvotes` is good to have is that for videos/instances likely to provoke competing opinions (e.g. partially political videos, neutral journalism), a controversial opinion is not buried but a low-effort/unappreciated comment is. It will still be clear that it is controversial by the number of downvotes, so the social critique is still easy.

**Comment by onlyjob** [comment] 2020-02-14 01:32
Good ideas except that I see no reasons for instance admin to push their preferences as users' defaults. Just a PeerTube default should be enough as long as users can override as they wish.

"Total Upvotes" appears to be meaningless to me.

Let's just use both _ratio_ and numbers of _up_ and _down_ votes, always.  

The only options for channel owners to choose would be "no voting" and "show voting" where the latter shows numbers for up/down votes (and maybe ratio as well). Simple and straightforward (this issue shows some signs of overthinking).

**Comment by 3risian** [comment] 2020-02-14 03:17
>"Total Upvotes" appears to be meaningless to me

Consider the following comments on a video mentioning a controversial political topic:

 * comment 1 gives an opinion that has factual merit, appealing to conservative political values, 183 up, 103 down
 * comment 2 gives an opinion that has as much factual merit, appealing to more progressive political values, 118 up, 131 down
 * comment 3 is low effort, it just says 'good video', 0 up 0 down
 * comment 4 says 'fuk u dumbass', 0 up, 5 down

I think it's fair to infer that, due to the amount of approval each of 1 and 2 has gained, they are both acceptable comments with merit. Due to subjective factors, both have high approval and high disapproval. Despite comment 2 having a score of -13, I think it should still be placed highly to support balanced discussion. I think it should certainly be placed higher than 3 (score 0) and 4 (score -5).

This voting system, to me, seems fairer for subjective topics to prevent legitimate but controversial opinions being drowned. However, for other communities, this voting system is probably not ideal.

>I see no reasons for instance admin to push their preferences as users' defaults.

The reason I proposed that was because I don't think this is a 'one-size-fits-all' option. Maybe I am wrong and honestly these aren't issues yet at PeerTube's current popularity, but I think it matters. Overthinking? I probably am overthinking for this stage, but these become proper social issues if videos start getting hundreds of comments and votes. I'd rather think about it now than later.

**Comment by onlyjob** [comment] 2020-02-14 07:32
The scope of this issue is just scores for up _and_ down votes. Sorting comments is a different issue (IMHO comments should be presented only by time without any arbitrary ordering). Anyway how to use voting system is beyond the scope of this issue. Let's not digress please.

**Comment by 3risian** [comment] 2020-02-14 08:12
You're right. We can discuss sorting after votes are implemented.

It did help me decide that I'm in favor of up/down, not only up.

**Comment by trymeouteh** [comment] 2020-05-03 02:52
Would like to see a upvote and downvotes on comments

**Comment by Chocobozzz** [comment] 2020-05-05 13:57
Duplicate of https://github.com/Chocobozzz/PeerTube/issues/1644

**Closed by Chocobozzz** 2020-05-05 13:57 UTC
Labels: Component: Comments, Priority: Low, Type: Enhancement :sparkles:
