### ISSUE TITLE
Notification and information on change of ownership

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#5346] opened 2022-10-11 08:30 UTC
### Describe the problem to be solved

When I transfer a video to another account (changing the owner of the video), the user does not see any information. He needs to periodically go to the "My ownership change" section to see the video that was given to him.

### Describe the solution you would like

It would be nice to show a notification, and also in the "My videos" section to display information that there are videos on your account waiting to be accepted.

**Comment by Chocobozzz** [comment] 2022-10-11 11:46
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/3639

**Closed by Chocobozzz** 2022-10-11 11:46 UTC
