### ISSUE TITLE
Regenerate thumbnails

### ISSUE THREAD

**Issue by TROMsite** [Chocobozzz/PeerTube#3855] opened 2021-03-13 13:37 UTC
**Describe the problem to be solved**
Add the ability to auto regenerate the thumbnails. 

**Describe the solution you would like:**
Like on all major video platforms, you can either choose between multiple thumbnails, or click a button to regenerate and create new ones.

**Comment by Chocobozzz** [comment] 2021-03-22 07:13
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/1322

**Closed by Chocobozzz** 2021-03-22 07:13 UTC
Labels: Type: Duplicate :loop:
