### ISSUE TITLE
Auto instances cleanup

### ISSUE THREAD

**Issue by Jorropo** [Chocobozzz/PeerTube#1003] opened 2018-09-02 11:58 UTC
That could be good if instances that no more run can be clean (remove) automatically (like if don't have any contact since last week, auto remove video, channel, instances, ...).

Cause if you go on [peertube.jorropo.ovh/videos/watch/b37a5b9f-e6b5-415c-b700-04a5cd6ec205](https://peertube.jorropo.ovh/videos/watch/b37a5b9f-e6b5-415c-b700-04a5cd6ec205) (the most viewed video) you have an error message cause [peertube.nsa.ovh](https://peertube.nsa.ovh/) is no more running.

**Comment by rigelk** [comment] 2018-09-02 12:34
This is already in place, but peertube.nsa.ovh is not answering a 404. We should make a more thorough check.

**Comment by Jorropo** [comment] 2018-09-02 12:39
Ok, but lot of die instances stay in list.
And if it require 404 that a problem cause lot of die instances don't response 404.

**Comment by Chocobozzz** [comment] 2018-09-03 06:41
I don't know how we could detect a dead instance if it answers 200. 

Anyway, this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/987

**Closed by Chocobozzz** 2018-09-03 06:41 UTC
Labels: Type: Duplicate :loop:
