### ISSUE TITLE
Add filter "without transcription" in admin->overview->videos

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#6636] opened 2024-09-27 23:34 UTC
### Describe the problem to be solved

no filter "without transcription" :(?

### Describe the solution you would like

It would be nice to add the filter option in the selectbox "without transcription" so we can have an overview of which videos have transcription or not...

**Comment by alejandrocobo** [comment] 2024-09-28 09:00
I think this is a duplicate of #6605.

**Closed** 2024-09-28 12:15 UTC
