### ISSUE TITLE
Save video speed and resolution like current time

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#5274] opened 2022-09-17 12:11 UTC
### Describe the current behavior

It would be nice that PT saves like current video time the speed and resolution globally for other video watching and when leave browser and go back

**Comment by Chocobozzz** [comment] 2022-09-19 07:00
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/1909

**Closed by Chocobozzz** 2022-09-19 07:00 UTC
