### ISSUE TITLE
Followers / followed instances page broken on v3.0.0~rc1

### ISSUE THREAD

**Issue by vincib** [Chocobozzz/PeerTube#3510] opened 2020-12-23 06:23 UTC
I recently upgraded my dev instance of peertube to 3.0.0~rc1 and now I have a 404 on 2 pages : 

* https://dev.indymotion.fr/admin/follows/following-list
* https://dev.indymotion.fr/admin/follows/followers-list

these pages are doing the following API calls : 

* https://dev.indymotion.fr/client/fr-FR/true/api/v1/server/following?start=0&count=10&sort=-createdAt
* https://dev.indymotion.fr/client/fr-FR/true/api/v1/server/followers?start=0&count=10&sort=-createdAt

looks like there is a /client/[locale]/true/  in the url that other api calls are not using.

I don't know how to fix that though, sorry.

**Comment by Chocobozzz** [comment] 2020-12-23 07:02
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/3473

**Closed by Chocobozzz** 2020-12-23 07:02 UTC
