### ISSUE TITLE
"Play All" feature for video channels

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#2109] opened 2019-09-04 22:14 UTC
It would be handy to have a single click way to play all the videos on a channel as if they're a playlist.

For example, there's a musician uploading some things, they don't have a playlist but they have several new tracks I'd like to check out:

https://diode.zone/accounts/housesquatt/video-channels

It would be nice to have a "Play All" button perhaps near the "Subscribe" or below the row of videos, in order to navigate to a playlist view of the channel.

**Comment by Chocobozzz** [comment] 2019-12-05 09:59
Duplicate of https://github.com/Chocobozzz/PeerTube/issues/1645

**Closed by Chocobozzz** 2019-12-05 09:59 UTC
Labels: Component: Playlist, Type: Enhancement :sparkles:, UI
