### ISSUE TITLE
Add the ability to make alternate audio tracks for a video.

### ISSUE THREAD

**Issue by rkingett** [Chocobozzz/PeerTube#2809] opened 2020-05-30 13:34 UTC
Would it be possible to allow creators to upload different audio tracks for one video? This way, a creator could dub their video, or provide other accessibility features like Audio Description tracks that can be switched.

**Comment by Chocobozzz** [comment] 2020-06-04 12:35
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/939

**Closed by Chocobozzz** 2020-06-04 12:35 UTC
Labels: Type: Duplicate :loop:
