### ISSUE TITLE
Possibility to upload multiple files

### ISSUE THREAD

**Issue by aflamrip** [Chocobozzz/PeerTube#5742] opened 2023-04-09 20:04 UTC
### Describe the solution you would like

It is possible to allow more than one file to be uploaded at the same time on the channel, so that the content is added to an instance faster

**Comment by Chocobozzz** [comment] 2023-04-11 07:39
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/5466

**Closed by Chocobozzz** 2023-04-11 07:39 UTC
