### ISSUE TITLE
Add an option for multiple languages

### ISSUE THREAD

**Issue by r4dh4l** [Chocobozzz/PeerTube#2299] opened 2019-12-03 00:02 UTC
In addtion to https://github.com/Chocobozzz/PeerTube/issues/1489 it would be great to tag a video with multiple languages which would be useful for multilingual videos of conferences.

First option could be: "Multiple languages"
Then it would be great to have additional options to specify this a little:
- Main language: (dropdown)
- With contributions in following languages:
(dropdown)
+ (dropdown)
+ (dropdown)
...

However: Thank you so much for PeerTube!

**Comment by Chocobozzz** [comment] 2019-12-03 07:39
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/347

**Closed by Chocobozzz** 2019-12-03 07:39 UTC
