### ISSUE TITLE
[Feature request] Live streaming

### ISSUE THREAD

**Issue by stemy2** [Chocobozzz/PeerTube#1894] opened 2019-06-11 21:41 UTC
Hello,

It would be cool to add a live streaming feature. Is it technically possible/not too difficult ?

**Comment by Zig-03** [comment] 2019-06-11 21:47
https://github.com/Chocobozzz/PeerTube/issues/151

**Comment by Chocobozzz** [comment] 2019-06-12 06:43
Thanks for the issue but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/151 :)

**Closed by Chocobozzz** 2019-06-12 06:43 UTC
