### ISSUE TITLE
Content Rating System

### ISSUE THREAD

**Issue by kidmock** [Chocobozzz/PeerTube#3712] opened 2021-02-07 13:22 UTC
**Describe the problem to be solved**
I would like to be able to rate content loosely based on the MPAA or ESRB

**Describe the solution you would like:**
I would like to enforce a rating system and by extension force moderation of videos based on content. The NSFW is nice but I  don't think it adequately covers content rating

I'm thinking something like:

* Everyone - Safe for all ages 
* Teen 13+ - May contain crude humor, mild violence and content not suitable for younger audiences
* Mature 17+ - May contain strong language,  violence, gore, and sexual topics.
* Adult 18+ (current NSFW?)- May contain topics that are sexually explicit, prolong violence, and that may be otherwise disturbing to viewers.

Content creator would be required to "rate" their content based upon this criteria.

Viewers would be able to flag and/or report content that doesn't meet the criteria for moderators to re-classify.

Federated sites could choose what content ratings to replicate.

**Comment by test2a** [comment] 2021-02-07 14:27
While I understand the kids and teens rating, the adult rating itself is too big in itself.

How do you differentiate between nsfw, conspiracy, and other subgroups?

Do we specify each one separately? Wouldnt that confuse the users because they would need to "choose"?

**Comment by kidmock** [comment] 2021-02-07 15:42
I've always subscribed to keeping things as flat as possible and as deep as necessary. 

I'm merely talking about content rating not content categorization. Over categorizing creates the paradox of choice. Going into subgroups kind of deviates into the genre realm which is already existing functionality. 

Simple choices makes compliance easier to follow, review and enforce. 

I'm not sure what all the "Offensive" categories are but I think it comes down to Language, Violence, Nudity, and Sex With degrees that range from Mild to Graphic.

So if we have:

* Mild Language
* Mild Violence
* Mild Nudity
* Mild Sex

* Graphic Language
* Graphic Violence
* Graphic Nudity
* Graphic Sex

Perhaps we could have the basic rating system as follows with the option to set advanced options above.

Whereas: 
Everyone = has no mildly or graphically offensive content
Teen = May have mild language and mild violence and no nudity or sex
Mature = May have graphic language and graphic violence but no graphic nudity or sex
Adult = May have graphic nudity or sex

**Comment by test2a** [comment] 2021-02-07 18:33
Quick question, what does lbry or vimeo or dailymotion or YouTube use? I have no accounts in any service so I dont have any idea of these

**Comment by kidmock** [comment] 2021-02-07 19:02
I don't think they use anything and that's part of their problem. 

Traditional media use either an embedded tag like Apple's Atom 
(https://developer.apple.com/documentation/corespotlight/cssearchableitemattributeset/1616027-contentrating?language=occ) 

While others use the MPAA/US-TV Ratings in .nfo files with tags like:
(https://kodi.wiki/view/NFO_files/TV_shows)

Here's a couple of examples of Apple media files:

mediainfo Blue\ Bloods\ -\ S01E01\ -\ Pilot.mp4 | grep Content
ContentType                              : TV Show
ContentRating                            : us-tv|TV-14|500|

mediainfo Star Wars - Episode IV - A New Hope (1977)]$ mediainfo Star\ Wars\ -\ Episode\ IV\ -\ A\ New\ Hope\ \(1977\).mp4 | grep Content
ContentType                              : Short Film
ContentRating                            : mpaa|PG|200|

They use the US-MPAA and US-TV rating embedded in their metadata. 

I'm kind of getting my cue from the content distributors with my suggestions. I know it's a little US centric. But other countries  do similar things

https://en.wikipedia.org/wiki/Television_content_rating_system

**Comment by Chocobozzz** [comment] 2021-02-08 08:49
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/1588

**Closed by Chocobozzz** 2021-02-08 08:49 UTC
Labels: Template not filled
