### ISSUE TITLE
Recognize subtitles already present in video files

### ISSUE THREAD

**Issue by wioxjk** [Chocobozzz/PeerTube#1948] opened 2019-06-27 19:31 UTC
Currently, if you upload a .mkv file for example, with subtitles present - they will not be imported into peertube automatically.
Instead, I have to export them (if it is possible) and upload them manually - which often does not really work that well.

Would be great if Peertube could to it automatically.

Here is the output of ffprobe on a .mkv file with several subtitles:

```ffprobe version 3.4.2-2+8.0trisquel1 Copyright (c) 2007-2018 the FFmpeg developers

  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 20160609
  configuration: --prefix=/usr --extra-version=2+8.0trisquel1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Input #0, matroska,webm, from 'One-Punch Man - S02E01 - The Hero's Return.mkv':
  Metadata:
    COMPATIBLE_BRANDS: isomiso2avc1mp41
    MAJOR_BRAND     : isom
    MINOR_VERSION   : 512
    ENCODER         : Lavf58.20.100
  Duration: 00:23:51.91, start: 0.000000, bitrate: 1648 kb/s
    Stream #0:0: Video: h264 (High), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
    Metadata:
      HANDLER_NAME    : VideoHandler
      DURATION        : 00:23:50.137000000
    Stream #0:1(jpn): Audio: aac (LC), 44100 Hz, stereo, fltp (default)
    Metadata:
      HANDLER_NAME    : SoundHandler
      DURATION        : 00:23:50.117000000
    Stream #0:2(eng): Subtitle: ass (default)
    Metadata:
      title           : English(US)
      BPS-eng         : 167
      DURATION-eng    : 00:23:46.860000000
      NUMBER_OF_FRAMES-eng: 430
      NUMBER_OF_BYTES-eng: 29877
      _STATISTICS_WRITING_APP-eng: mkvmerge v26.0.0 ('In The Game') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2019-04-09 17:37:27
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      DURATION        : 00:23:51.150000000
    Stream #0:3(spa): Subtitle: ass
    Metadata:
      title           : Espanol(Espana)
      BPS-eng         : 133
      DURATION-eng    : 00:23:47.700000000
      NUMBER_OF_FRAMES-eng: 362
      NUMBER_OF_BYTES-eng: 23858
      _STATISTICS_WRITING_APP-eng: mkvmerge v26.0.0 ('In The Game') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2019-04-09 17:37:27
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      DURATION        : 00:23:51.910000000
    Stream #0:4(rus): Subtitle: ass
    Metadata:
      title           : Russian
      BPS-eng         : 244
      DURATION-eng    : 00:23:45.740000000
      NUMBER_OF_FRAMES-eng: 415
      NUMBER_OF_BYTES-eng: 43494
      _STATISTICS_WRITING_APP-eng: mkvmerge v26.0.0 ('In The Game') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2019-04-09 17:37:27
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      DURATION        : 00:23:50.100000000```

**Comment by Chocobozzz** [comment] 2019-07-02 16:03
Hi,

Thanks for the issue but I think it's a duplicate of https://github.com/Chocobozzz/PeerTube/issues/1226

**Closed** 2019-07-03 13:50 UTC
