### ISSUE TITLE
How do I increase the number of tags and the tag length?

### ISSUE THREAD

**Issue by quicktrick** [Chocobozzz/PeerTube#4911] opened 2022-04-11 16:56 UTC
My video server is dedicated to art auctions. Each video contains a review of the top auction lots, with 6–12 lots of different artists. Accordingly, I need at least 12 tags with artists' names.  And I also need to increase the tag length to 40 characters.

I found in the source code in `/var/www/peertube/peertube-latest/dist/server/initializers/constants.js` the tag settings. [I increased the limits](https://github.com/Chocobozzz/PeerTube/issues/704#issuecomment-1094687259), but that didn't help.

Please tell me where else I need to change something to increase the tag limits?

**Comment by Chocobozzz** [comment] 2022-04-15 08:24
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/1815

**Closed by Chocobozzz** 2022-04-15 08:24 UTC
Labels: Type: Question
