### ISSUE TITLE
Backend returned code 0, errorMessage is: Unknown error.

### ISSUE THREAD

**Issue by think222** [Chocobozzz/PeerTube#2273] opened 2019-11-19 18:53 UTC
**What happened?**
When uploading files, particularly large ones, I will sometimes get the error "Unknown error", with the following browser console logs:
```
Backend returned code 0, errorMessage is: Unknown error. main-es2015.7c0f808f1ecdb81fa0dd.js:1:564209
    handleError https://nona.li/client/en_US/main-es2015.7c0f808f1ecdb81fa0dd.js:1
    uploadVideo https://nona.li/client/en_US/main-es2015.7c0f808f1ecdb81fa0dd.js:1
    error https://nona.li/client/en_US/main-es2015.7c0f808f1ecdb81fa0dd.js:1
    notifyError https://nona.li/client/en_US/main-es2015.7c0f808f1ecdb81fa0dd.js:1
    _error https://nona.li/client/en_US/main-es2015.7c0f808f1ecdb81fa0dd.js:1
    error https://nona.li/client/en_US/main-es2015.7c0f808f1ecdb81fa0dd.js:1
    notifyError https://nona.li/client/en_US/main-es2015.7c0f808f1ecdb81fa0dd.js:1
    _error https://nona.li/client/en_US/main-es2015.7c0f808f1ecdb81fa0dd.js:1
    error https://nona.li/client/en_US/main-es2015.7c0f808f1ecdb81fa0dd.js:1
    r https://nona.li/client/en_US/main-es2015.7c0f808f1ecdb81fa0dd.js:1
    _trySubscribe https://nona.li/client/en_US/main-es2015.7c0f808f1ecdb81fa0dd.js:1
    subscribe https://nona.li/client/en_US/main-es2015.7c0f808f1ecdb81fa0dd.js:1
    s https://nona.li/client/en_US/main-es2015.7c0f808f1ecdb81fa0dd.js:1
    error https://nona.li/client/en_US/main-es2015.7c0f808f1ecdb81fa0dd.js:1
    l https://nona.li/client/en_US/main-es2015.7c0f808f1ecdb81fa0dd.js:1
    invokeTask https://nona.li/client/en_US/polyfills-es2015.65ea6e6f4e37ff0c4ef4.js:1
    onInvokeTask https://nona.li/client/en_US/main-es2015.7c0f808f1ecdb81fa0dd.js:1
    invokeTask https://nona.li/client/en_US/polyfills-es2015.65ea6e6f4e37ff0c4ef4.js:1
    runTask https://nona.li/client/en_US/polyfills-es2015.65ea6e6f4e37ff0c4ef4.js:1
    invokeTask https://nona.li/client/en_US/polyfills-es2015.65ea6e6f4e37ff0c4ef4.js:1
    b https://nona.li/client/en_US/polyfills-es2015.65ea6e6f4e37ff0c4ef4.js:1
    m https://nona.li/client/en_US/polyfills-es2015.65ea6e6f4e37ff0c4ef4.js:1
```

It appears this is the same bug as #2114.

**Steps to reproduce:**

1. Upload a very big file to https://nona.li (I can reproduce consistently if it's 1-2gb).

**Additional information**
* PeerTube version or URL: https://nona.li 
* Browser name/version: Firefox
* NodeJS version: 10.

I've thoroughly checked `/var/www/peertube/storage/logs/` and I can't seem to find anything that explicitly references this error. Greps for `error` or `Unknown` don't turn up anything useful.

I am not sure if there is somewhere else I should be looking? The log file appears to be the same thing as `sudo journalctl -feu peertube`. Also @Chocobozzz, if you would like to try and reproduce, I can create an account for you on my instance.

**Comment by JohnXLivingston** [comment] 2019-11-21 10:04
What is the status code of the request in your nginx access logs ? 499 ?
I had similar issues. At that time, I had a very slow server (only one CPU). Since I upgraded it, it works. We never found the problem (see https://github.com/Chocobozzz/PeerTube/issues/1359)

**Comment by think222** [comment] 2019-11-29 02:49
Nginx logs do have 499 errors. This does indeed appear to be the same issue. Looks like I need beefier servers. I would have expected 2 cores + 4gb of ram to be enough though.

**Comment by JohnXLivingston** [comment] 2019-11-29 09:45
I think there is a real bug underneath. That should not happen.

**Comment by Chocobozzz** [comment] 2019-11-29 09:54
How long it takes to get this 499 error code? Do you use a CDN or another proxy in front of NGINX? Also, do you use a VPN or another thing between your web browser and PeerTube?

**Comment by think222** [comment] 2019-12-02 00:00
In this case, I'll reopen. I am using a VPN. There is no proxy other than nginx itself. The full network stack would be: `Wifi>VPN>My server>Nginx proxy>PeerTube`.

As for how long it takes, it depends. Sometimes it happens only after 5 minutes, sometimes it's after 10-20 minutes. Usually the latter. I've never been able to successfully upload very large files (3gb+), and if I get lucky a 1gb file may succeed. This sometimes will happen even on smaller files that are maybe 300mb and 20 minutes long.

I am not entirely sure if it's a performance issue either, as when reproducing this with `top` open, the CPU usage never gets maxed out and is almost always below 10%.

**Comment by Chocobozzz** [comment] 2019-12-02 07:43
Do you have the same issue if you disable your VPN?

**Comment by think222** [comment] 2019-12-02 16:18
@Chocobozzz I am unable to test this due to security reasons.

**Comment by Chocobozzz** [comment] 2019-12-03 13:18
Then I'm closing this issue until someone else reproduces this error so we can find what closes the connection.

**Closed by Chocobozzz** 2019-12-03 13:18 UTC
Labels: Status: Waiting answer
