### ISSUE TITLE
AUTOPLAY button disables authomathically

### ISSUE THREAD

**Issue by paymanzafar1** [Chocobozzz/PeerTube#5549] opened 2023-01-23 11:51 UTC
### Describe the current behavior

I am using PeerTube version 5.0.1. When I am not logged in, and set the AUTOPLAY button, or check the "Automatically start playing the next video" checkbox in My settings, it does not save.

When I play another video, or open the My settings tab again, they are unchecked. 

### Steps to reproduce

1.
2.
3.

### Describe the expected behavior

I hope these settings to be saved in my session.

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment] 2023-01-23 12:42
Hello,

What is your PeerTube website URL?

**Comment by paymanzafar1** [comment] 2023-01-23 13:08
I saw this problem on all instances like:

https://myvideos.facb69.com.br/

**Comment by Chocobozzz** [comment] 2023-01-23 13:16
Can you paste a screen of the page where you update the settings?

**Comment by paymanzafar1** [comment] 2023-01-23 13:36
![error1](https://user-images.githubusercontent.com/91053236/214053027-f5aaa9bf-b055-473a-84b2-f0776f21d155.jpg)
![error2](https://user-images.githubusercontent.com/91053236/214053092-10e66369-deb1-4e09-bd39-c7c6736a8c19.jpg)

**Comment by Chocobozzz** [comment] 2023-01-23 14:26
You said "When I am not logged in", it's the reason why I could not reproduce: you're not logged in ;)

It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/b1d8261c458f5c9a800539d0aebc749e53dfcdbe

**Closed by Chocobozzz** 2023-01-23 14:26 UTC
Labels: Status: Waiting for answer

**Comment by paymanzafar1** [comment] 2023-01-23 15:35
Thank you very much to resolve this problem. Should I wait for the next minor release?

Is it possible to enable these options by default?

**Comment by paymanzafar1** [comment] 2023-02-01 11:31
@Chocobozzz I compiled & built your new code. It saves this setting for anonymous user, but if you update it in one place, it does not update the other one (I mean in My settings & next to Other videos)

**Comment by Chocobozzz** [comment] 2023-02-13 13:48
Can you create a dedicated issue with the steps to reproduce this new issue please? (some screenshots a video can help a lot!)

**Comment by paymanzafar1** [comment] 2023-02-14 07:22
1) Open a video page
2) Disable the autoplay button under the video player
3) Open My settings & set the "Automatically start playing the next video" check box
4) Close My settings
5) You see the autoplay button under the video player is still disabled
6) But if you disable/enable the autoplay button under the player, it will update "My settings"

In other words this change, will go from autoplay button to my settings, but not vise versa.

**Comment by paymanzafar1** [comment] 2023-02-14 08:06
I am sorry. I created another issue as per your message.
