### ISSUE TITLE
Show transcoding status to users

### ISSUE THREAD

**Issue by busshimoe** [Chocobozzz/PeerTube#2477] opened 2020-02-11 18:46 UTC
When a video is being transcoded, PeerTube could show
* If the video is currently being transcoded or in a queue
* If in a queue, how many videos are ahead of it and approximately how long they will take
* If currently transcoded, the progress on each resolution (and estimated time remaining)

**Comment by Chocobozzz** [comment] 2020-02-12 07:39
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/799

**Closed by Chocobozzz** 2020-02-12 07:39 UTC
