### ISSUE TITLE
Playlist (Watch Later) starts at 0, and won't play first item.

### ISSUE THREAD

**Issue by JigmeDatse** [Chocobozzz/PeerTube#4544] opened 2021-11-15 21:44 UTC
**Describe the current behavior**

Currently my main account has a Watch Later playlist that is starting at 0 (it usually starts at 1) and it won't play first item.

**Steps to reproduce:**

Not sure entirely how to reproduce, but it *might* be related to a period where updates had been made, which caused breakages with the Postgresql connection.  

1.
2.
3.

**Describe the expected behavior**

Playlist to have the same behaviour as expected (it usually starts at 1, but I have no preference myself).

**Additional information**

This happened at some point along when I was doing updates, and shortly after updating I added some new follows for instances, but it was showing as delayed with a PostgreSQL library error.  This may or may not be related.  

It looks like it could be an issue that database corruption has happened, and I've not yet tried to look to see if there's something that makes sense as that being the cause, and I really don't want to do anything beyond a `select` or similar to look at what the data is currently.  

* PeerTube instance:
  * URL: https://video.jigmedatse.com/
  * version: 3.4.0
  * NodeJS version: 14.17.6
  * Ffmpeg version: 4.4-r1

* Browser name, version and platforms on which you could reproduce the bug: Firefox 94.0.1 on Gentoo Linux
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

There is one playlist element that has a `position` of 0.  This seems to be the cause of this.  Deleting the element from the database may fix it, but I'm not certain that would not cause further issues.

**Comment by Chocobozzz** [comment] 2022-01-14 14:11
Hello,

Unfortunately without reproducing steps, and since nobody seems to have been able to reproduce this bug I'm going to close this issue. Of course if someone has new information don't hesitate to comment.

**Closed by Chocobozzz** 2022-01-14 14:11 UTC
Labels: Status: To Reproduce, Component: Playlist

**Comment by JigmeDatse** [comment] 2022-01-14 22:32
The thing is...  You want "steps to reproduce" for something that comes up at most 1 a month for a user.  We don't *really* have much idea what *causes* it.  Perhaps trying to find ways to reproduce it, by poking at the playlist.  In normal usage, it is pretty rare, but since it ends up breaking the playlist, and isn't really trivial to fix (especially for a user who doesn't know what to do, let alone a server admin).  

It feels like some sort of testing of it would be useful, as this has been a "can't reproduce, won't fix" for several years.
