### ISSUE TITLE
Request : Maintenance mode

### ISSUE THREAD

**Issue by 22decembre** [Chocobozzz/PeerTube#2901] opened 2020-06-25 21:18 UTC
I wish one could place their instance(s) on a maintenance mode of some kind. Meaning, at least still functional, but not being able to upload videos. So, read-only.

**Comment by Chocobozzz** [comment] 2020-06-26 06:38
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/1230

**Closed by Chocobozzz** 2020-06-26 06:38 UTC
