### ISSUE TITLE
Languages filter for videos overview

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#4309] opened 2021-08-06 05:36 UTC
**Describe the current behavior**
For my account, the video is displayed only in Russian. If you go to the Trending page, all videos are displayed in my native language, but if you go to the Overview page, I see all videos in all languages.

![Screenshot_1](https://user-images.githubusercontent.com/11453567/128461683-82665848-7b5a-408b-90b6-95e985f8f1c1.png)

**Steps to reproduce:**
1. Go to the "Overview" page
2. Videos are displayed in different languages.

**Describe the expected behavior**
The Overview page should display videos in the language I selected in my profile settings.

* PeerTube instance:
  * URL: https://peervideo.ru
  * version: 3.3.0
  * NodeJS version: 12.22.2
  * Ffmpeg version: 4.1.6-1~deb10u1

**Comment by Axeltherabbit** [comment] 2022-05-02 13:13
I'm facing the same issue.

**Comment by merlin1608** [comment] 2023-02-11 10:34
Hello,
Agree with this demand because it rebuts a lot of people to have many vidéos in languages they can't understand in the overview (discover) 
The Overview page should display videos in the language I selected in my profile settings.
Thanks and keep the good work !

**Comment by Chocobozzz** [comment] 2023-03-08 13:43
Duplicate of https://github.com/Chocobozzz/PeerTube/issues/3152

**Closed by Chocobozzz** 2023-03-08 13:43 UTC
Labels: Type: Feature Request :sparkles:
