### ISSUE TITLE
Audio only option doesn't show under Quality in video player

### ISSUE THREAD

**Issue by Mike35538** [Chocobozzz/PeerTube#5368] opened 2022-10-19 23:03 UTC
### Describe the current behavior

When watching a video and going to the gear icon and selecting Quality, it shows all of the resolution options except Audio.

See image.

I have Audio-only enabled in the admin sections under file resolution.
In Administration > Overview > Videos, I can see that the video has Audio transcoded for WebTorrent and HLS
When you go to watch the video and select the Quality, there is no option for Audio
On that same video you can go to Download and see that there is an Audio-only download option for that video.

![peertube-audio](https://user-images.githubusercontent.com/104943871/196819911-5fc94ab5-0ff9-40d4-b560-8b5d88c18289.jpg)

### Steps to reproduce

1. Setup PeerTube initially without Audio-only transcoding
2. later on, enable audio-only
3. Upload videos
4. Audio-only is transcoded but not shown as a Quality option

### Describe the expected behavior

Show Audio-only option under Quality in video player

### Additional information

* PeerTube instance:
  * URL:
  * Version: 4.3.0
  * NodeJS version: 18
  * Ffmpeg version: 4.3.4

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment] 2022-10-21 06:43
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/3281

**Closed by Chocobozzz** 2022-10-21 06:43 UTC

**Comment by Mike35538** [comment] 2022-10-21 20:12
Ok, thanks Chocobozzz. Sorry I should of done a better job at searching for the existing issue!

Maybe consider updating the help text next to Audio-only, from:
A .mp4 that keeps the original audio track, with no video
and include also a note that says:
Audio-only resolution option does not show in the video player when the video has HLS format resolutions. Audio-only option will show in the video player if the video has only WebTorrent format resolutions and no HLS.
