### ISSUE TITLE
Add additional previews

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#3716] opened 2021-02-08 09:22 UTC
**Describe the problem to be solved**
After adding and processing the video, only 1 preview appears in the "Advanced" section. Sometimes this preview is very ugly, and it's not very convenient to upload your images.

**Describe the solution you would like:**
You can add 2 more previews so that I can choose any of them. If I don't like any of them, then I'll upload my image.

**Describe alternatives you have considered**
On Youtube, after processing the file, several preview options appear, where I can choose any of them. It is very convenient.

---

I would like to suggest some more ideas to improve the Peertube functionality a little:

* I think to autocomplete the "Date added" field after adding and processing the video. If desired, the user can then select a different date.
* The video download function is always activated. This is very inconvenient for me! For large videos, I have to manually disable this feature. I don't want my videos to be downloaded to my computer. I want them to be viewed only on a copy. It seems to me that this will not affect the work of the tracker.

I suggest adding the option to disable this feature by default in your account settings.

In the screenshot, I have highlighted these improvements.
![Screenshot_1](https://user-images.githubusercontent.com/11453567/107199896-0ae51500-6a08-11eb-8b6c-be036e5cfa67.png)

**Comment by rigelk** [comment] 2021-02-08 09:31
hi @Alterak,

Please fill a proper feature request template for 1, and edit the issue title accordingly 🙂 

As for 2 and 3, I see some issues with your solution:

- the original publication date cannot be inferred
- the "enable download" can be saved as an individual setting, but a better solution would be to have "video setting templates" which ensures not only this property can be memorized for later uploads

**Comment by Alterak** [comment] 2021-02-08 10:23
> Please fill a proper feature request template for 1, and edit the issue title accordingly

Исправлено. 

> * the original publication date cannot be inferred

It's a pity, I was hoping that the date of addition can be taken from the database, or the current time of the operating system can be indicated.


> * the "enable download" can be saved as an individual setting, but a better solution would be to have "video setting templates" which ensures not only this property can be memorized for later uploads

"video setting templates" - that's a great idea! It would be great! Are you already developing such functionality?

**Comment by rigelk** [comment] 2021-02-08 10:35
No, not yet. I'm just saying that's a probably better solution in the future.

**Comment by rigelk** [comment] 2021-02-08 10:37
@Alterak you are not filling the template correctly, i.e. explaining what the problem is. You are just providing a solution without any explanation why it is needed in the first place.

**Comment by Alterak** [comment] 2021-02-08 13:22
> you are not filling the template correctly, i.e. explaining what the problem is. You are just providing a solution without any explanation why it is needed in the first place.

-) Excuse me. It should now be properly formatted.

**Comment by Chocobozzz** [comment] 2021-02-12 08:26
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/1322

**Closed by Chocobozzz** 2021-02-12 08:26 UTC
Labels: Template not filled
