### ISSUE TITLE
Autoplay when in fullscreen mode looses fullscreen when changing video

### ISSUE THREAD

**Issue by jeremies** [Chocobozzz/PeerTube#6032] opened 2023-11-15 15:39 UTC
### Describe the problem to be solved

How to persist fullscreen mode in browser like youtube.com playlist does?

In youtube.com, when you play a playlist in fullscreen mode, the fullscreen persists when switching from one video to another in the playlist. I am trying to do the same in my website, where there is a playlist of videos, and user can watch in fullscreen mode, but a new video starts to play, the fullscreen doesn't persist.

I understand from Fullscreen API, there needs a user interaction to make the video fullscreen. But, then how the heck youtube.com is doing it?

Any help would be appreciated! Thanks.

**Comment by Chocobozzz** [comment] 2023-11-17 10:18
Hi,

Thanks for the issue but it's a duplicate of https://github.com/Chocobozzz/PeerTube/issues/3159

And so it should be fixed in PeerTube v6, planned for the end of the month :)

**Closed by Chocobozzz** 2023-11-17 10:18 UTC
