### ISSUE TITLE
 video visibility descriptions incorrect

### ISSUE THREAD

**Issue by rscmbbng** [Chocobozzz/PeerTube#4384] opened 2021-09-08 09:10 UTC
**Describe the current behavior**

The descriptions in the drop down menu for video visibility settings show 'Only I can see this video' for every option. Since the recent upgrade to 3.3

See screenshot:

![](https://i.ibb.co/MNzjrNK/Screenshot-from-2021-09-08-07-51-54.png) 

**Steps to reproduce:**

1. Edit the visibility settings on an existing video
2. Set the visibility settings when uploading a new video
3.

**Describe the expected behavior**

The original accurate visibility descriptions are used.
 
**Additional information**

* PeerTube instance:
  * URL: https://tv.lumbung.space
  * version: 3.3.0
  * NodeJS version: unknown, using https://git.coopcloud.tech/coop-cloud/peertube
  * Ffmpeg version: unknown, using https://git.coopcloud.tech/coop-cloud/peertube

* Browser name, version and platforms on which you could reproduce the bug: Firefox, Brave

**Comment by Chocobozzz** [comment] 2021-09-09 13:06
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/4273

**Closed by Chocobozzz** 2021-09-09 13:06 UTC

**Comment by rscmbbng** [comment] 2021-09-09 13:41
Thanks for the fix!
