### ISSUE TITLE
Allow multiple users to manage a channel

### ISSUE THREAD

**Issue by ranjithrajv** [Chocobozzz/PeerTube#4590] opened 2021-12-01 07:12 UTC
**Describe the problem to be solved**
We have opened our orgnaisation account in a peertube instance. This channel needs to be managed by multiple users in the organisation.

**Describe the solution you would like:**
Add a feature to allow multiple users to manage a channel. 

**Describe alternatives you have considered**

**Comment by kontrollanten** [comment] 2021-12-01 07:34
Hi! This is a duplicate of #699

**Closed** 2021-12-01 07:55 UTC
Labels: Type: Duplicate :loop:
