### ISSUE TITLE
[Feature] Add instance language

### ISSUE THREAD

**Issue by ncorder** [Chocobozzz/PeerTube#4524] opened 2021-11-07 19:57 UTC
**Describe the problem to be solved:**

Language moderation can be very difficult for instances that aren't focused towards the more popular languages on Peertube.

Most instances trending pages show English, French or Russian and may turn users to believe there aren't large video selections in other languages. 

**Describe the solution you would like:**

- Allow instances to set a default or language focus

Peertube does have a `Only display videos in the following languages/subtitles` setting for users, but not for what the default should be for users that are not logged in.

I would also like to note, Peertube currently does allow you to set what language your moderators speak but as far as I am aware it doesn't allow you to set the default or individual user preference.

It might be helpful for moderated instances that only have moderation in a few languages, to understand and properly block potentially illegal content. 

**Describe alternatives you have considered:** 

- Language detection via a free/libre translation tool such as [Apertium](https://www.wikipedia.org/wiki/Apertium) 

_________________________________________________

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=103194484)](https://www.bountysource.com/issues/103194484-feature-add-instance-language)

**Comment by Chocobozzz** [comment] 2021-11-08 09:59
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/2642

**Closed by Chocobozzz** 2021-11-08 09:59 UTC

**Comment by ncorder** [comment] 2021-11-08 21:15
> Thanks for reporting this issue, but this is a duplicate of #2642

oh shoot, thanks for pointing that out!

And thank you for your response and time. :)
