### ISSUE TITLE
Editing profile requires a description

### ISSUE THREAD

**Issue by tcitworld** [Chocobozzz/PeerTube#565] opened 2018-05-13 13:13 UTC
Edit your profile:

![peertube_edit_profile](https://user-images.githubusercontent.com/2197836/39967667-f8c4395e-56bf-11e8-94fc-ae2f8c4f553b.png)

* The form can't be validated if the description filled isn't valid (empty or less than 3 characters)
* The error message is incorrect

Configuration : 

* Peertube 1.0.0-beta.4
* Firefox 61

**Comment by Chocobozzz** [comment] 2018-05-13 15:00
Hi @tcitworld,

I think it's a duplicate of https://github.com/Chocobozzz/PeerTube/issues/546, and thus it's fixed in develop.

**Closed by Chocobozzz** 2018-05-13 15:00 UTC

**Comment by tcitworld** [comment] 2018-05-13 15:17
Damn you Github search !
