### ISSUE TITLE
Allow users to request an archive of their data (and easily move to other services/instances)

### ISSUE THREAD

**Issue by ppnplus** [Chocobozzz/PeerTube#3764] opened 2021-02-22 05:11 UTC
**Describe the problem to be solved**
At the moment, I haven't found a way for users to download an archive of their data easily (e.g. videos, video description and metadata, comments, likes, subscriptions). Therefore, it can be hard for users to keep a backup or "move" their data when necessary.

**Describe the solution you would like:**
I would like my users to be able to get an archive of their data so that they can either view the data directly from the archive (if possible) or easily move them to other services or instances.

**Comment by S7venLights** [comment] 2023-02-03 22:03
Duplicate of #[549](https://github.com/Chocobozzz/PeerTube/issues/549)
Any form of local backup would be great to avoid loosing a channel

**Comment by Chocobozzz** [comment] 2023-02-13 09:58
Hi,

We prefer to keep this issue opened even if it's related to https://github.com/Chocobozzz/PeerTube/issues/549 because requesting an archive of its data can also be a dedicated feature, that could be implement as a first step of account migration.

**Closed** 2024-08-02 12:08 UTC
Labels: Type: Feature Request :sparkles:

**Comment by S7venLights** [comment] 2024-08-20 21:05
Thanks so much for this feature, unfortunately one instance I've put a lot of time into is offline the same days I'm seeing this. I'm hoping they're just doing updates.

One question when I request an export and check 'including videos' on an instance should I expect the whole video files? Because i just got a 400kb zip file...

**Comment by Chocobozzz** [comment] 2024-08-21 07:51
> One question when I request an export and check 'including videos' on an instance should I expect the whole video files? Because i just got a 400kb zip file...

Yes, you can expect that the video file (original video file or max quality file) is included in the ZIP.

> New question then, can i even use my export to move instances?

I'm sorry but I don't understand. Please use the forum for PeerTube related questions: https://framacolibri.org/c/peertube/38

**Comment by S7venLights** [comment] 2024-08-21 13:16
The problem is that even when I request an export including videos, it isn't including the videos.
So I'm wondering if it's not working because those videos were uploaded before PeerTube V6.1

So now, if I wanted a full export, would I have to download my videos off the peertube instance one by one?
Then when it came to importing would importing even work?
