### ISSUE TITLE
Custom Profile Pages (Like Old YouTube)

### ISSUE THREAD

**Issue by seniorm0ment** [Chocobozzz/PeerTube#4015] opened 2021-04-25 11:39 UTC
Requesting the ability to allow users to customize their profile and account pages, similar to that of old YouTube.

Example: https://web.archive.org/web/20111004165235/https://www.youtube.com/user/Nyanners

This could be added with an option for users to toggle off custom profile themes client side (and use the default PeerTube theme) for consistency, and if felt needed the ability for the instance host to disable editing profiles on that instance. 

A feature like this really lets users be creative, and stand out to express their content, and show off what their content is about.
If they don't have interest in it, that's all good they don't need to touch it. But for users who want it, it would be amazing.

**Comment by Chocobozzz** [comment] 2021-04-26 09:47
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/3997

**Closed by Chocobozzz** 2021-04-26 09:47 UTC
