### ISSUE TITLE
Move multiple videos to a channel

### ISSUE THREAD

**Issue by Vertux** [Chocobozzz/PeerTube#1505] opened 2018-12-26 07:46 UTC
My enhancement suggestion is related to #349 and #1361

I think it would be very handy to have the possibility to move multiple videos to a channel (or more, #1361) e.g. I had the situation, that I wanted to move all videos with a special tag to a newly created channel. Maybe this feature could be added to the my videos page (https://example.com/my-account/videos)
An additional option could be to automatically add/move selected videos to a newly created channel, which would save a manual work steps (e.g. Adobe Lightroom offers to move selected photos to a newly created collection)

**Comment by Chocobozzz** [comment] 2018-12-26 10:09
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/827

**Closed by Chocobozzz** 2018-12-26 10:09 UTC

**Comment by Vertux** [comment] 2018-12-27 08:55
I am sorry, I overlooked it, searching for known issues is tricky sometimes.
