### ISSUE TITLE
developer can you make when plugin don't work 100 % to report developer.

### ISSUE THREAD

**Issue by bgman111111** [Chocobozzz/PeerTube#5106] opened 2022-07-07 01:02 UTC
### Describe the desired information/correction

This is other message report about transcript report. In new 4.2.2 now to start work but stop work  because of missing path. I newbie don't know how to solve this:

Gecko/102.0 Firefox/102.0"
Jul  7 00:46:31 a peertube[17285]: [Worker n°8] 2022-07-07 0
0:46:31.568 #033[32minfo#033[39m: Processing transcription r
equest for video "7b59b44d-3410-4d8f-a9f6-b924227cbf91" in "
de".
Jul  7 00:46:31 a peertube[17285]: [Worker n°8] 2022-07-07 0
0:46:31.812 #033[32minfo#033[39m: From /var/www/peertube/sto
rage/streaming-playlists/hls/7b59b44d-3410-4d8f-a9f6-b924227
cbf91/9288a845-6219-42a6-974d-87fa57f1e201-0-fragmented.mp4
to /var/www/peertube/storage/plugins/data/peertube-plugin-tr
anscription/captions/7b59b44d-3410-4d8f-a9f6-b924227cbf91-de
.vtt
Jul  7 00:46:32 a peertube[17285]: ERROR (VoskAPI:Model():mo
del.cc:122) Folder '/var/www/peertube/storage/plugins/data/p
eertube-plugin-transcription/models/de' does not contain mod
el files. Make sure you specified the model path properly in
 Model constructor. If you are not sure about relative path,
 use absolute path specification.
^

Choco hou are great making this program so everybody has server can host it. Question is can you make when plugin don't work 100 % to refuse install or some diagnostic and automatically repair the issue. In older version 4.2.0 transcript didn't work but now it seam to work only it miss the path can someone help me I don't want speak . I don't know developer and he maybe is bad person. This plugin is great if it work. It will automatically make subtitles of video and if he can make multiply languages. For examples. If this is German and Russian then make subtitles when he ran speak and when Russian speak show subtitles.

**Comment by toby3d** [comment] 2022-07-07 10:57
Duplicate of #4742. Report your issue on [GitLab repository of transcription plugin](https://gitlab.com/apps_education/peertube/plugin-transcription/-/issues) instead.

**Closed** 2022-07-08 08:59 UTC
Labels: Component: Documentation :books:
