### ISSUE TITLE
Video timeline images

### ISSUE THREAD

**Issue by hellomotow** [Chocobozzz/PeerTube#736] opened 2018-06-27 19:53 UTC
It would be great to see this sort of thing implemented https://i.gyazo.com/b2de025f1c39e68661e925786c1e4536.mp4 (scroll on video bar to see multiple images across different video timeline)

Also for videos posted on the home page/trending etc https://i.gyazo.com/626d7e054f0f542688e567f79fb06ef4.png nice if these where gifs

**Comment by Chocobozzz** [comment] 2018-06-28 12:33
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/537 :)

**Closed by Chocobozzz** 2018-06-28 12:33 UTC
